### ISSUE TITLE
现在支持Latex吗

### ISSUE THREAD

**Issue by therehello** [fluid-dev/hexo-theme-fluid#100]
latex用的比较多，在网上搜寻了许多办法也搞不成

**Comment by zkqiang** [comment]
下个版本会支持

**Comment by zkqiang** [comment]
develop 分支已更新，感兴趣可以尝鲜体验

**Comment by zkqiang** [comment]
[v1.6.0](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.6.0) 已支持
