### ISSUE TITLE
文章封面图如何显示

### ISSUE THREAD

**Issue by hyy34** [fluid-dev/hexo-theme-fluid#1004]
根据配置指南，在文章首页添加

---
title: 文章标题
tags: [Hexo, Fluid]
index_img: /pic/微信截图_20230912095633.jpg
date: 2019-10-10 10:00:00
---

但是首页会显示内容，但是不会显示图片。是什么地方设置的问题吗？？

![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/26433019/db8e226e-9901-4877-bdb0-3d5159d4b2fd)

**Comment by hyy34** [comment]
而且，不支持 JSON Front-matter 格式吗？

**Comment by Code-Newborn** [comment]
你尝试采用图床链接

**Comment by hyy34** [comment]
> 你尝试采用图床链接

额。本地图片不可以吗？？

**Comment by zkqiang** [comment]
本地图片可以，但是要放在相当路径下，具体可以看文档
