### ISSUE TITLE
如何调整文章内容的段内行间距或者段间距

### ISSUE THREAD

**Issue by Code-Newborn** [fluid-dev/hexo-theme-fluid#1005]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

Hexo-Fluid主题能否调整内容的行间距，该如何实现？

**Comment by Code-Newborn** [comment]
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/47051839/ccccf576-02e5-48df-be31-901aae82618f)
行间距不一致，看着不美观

**Comment by zkqiang** [comment]
自定义 CSS

**Comment by Code-Newborn** [comment]
在文件夹`.\themes\fluid\source\css`里创建custom.css文件写入如下内容，并在fluid主题的配置文件里启用
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/47051839/d4c72997-174b-42a7-b7ac-88cb3404041e)
