### ISSUE TITLE
#字符优化

### ISSUE THREAD

**Issue by JackeyLea** [fluid-dev/hexo-theme-fluid#1010]
#### 如是功能需求，请确定符合以下情况
- [ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [ ] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

网址、cata、tags等等中出现`c#`就会显示异常，网址中出现`c#/intro-of-c#`就会404，tags中出现`c#`点击后会跳转至c，应该是`#`在解析时被删除了

#### 请描述您认为可行的解决方案

`c#`替换为csharp就正常了

**Comment by zkqiang** [comment]
能提供个示例吗，我这边测试没复现出来

<img width="178" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/32983588/83839063-a60a-44df-9256-7943f482a77d">

<img width="175" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/32983588/3538aa9a-9435-49b9-9c8e-ceacea27c009">

**Comment by JackeyLea** [comment]
> 能提供个示例吗，我这边测试没复现出来
> 
> <img alt="image" width="178" src="https://private-user-images.githubusercontent.com/32983588/286831964-83839063-a60a-44df-9256-7943f482a77d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjg1MjQsIm5iZiI6MTcxOTIyODIyNCwicGF0aCI6Ii8zMjk4MzU4OC8yODY4MzE5NjQtODM4MzkwNjMtYTYwYS00NGRmLTkyNTYtNzk0M2Y0ODJhNzdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDExMjM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZjIxNzU4OWI3MjVjZjAzZTBhMDZiYmFjNDNlNTcxNDVkM2RlMTBmMjJhYmM4YTRkNzdjZGQ3YzMzMDgyMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fvSL4r5YqmKGD3d6K3y7IM2it555UVoRce31W9bIatE"> <img alt="image" width="175" src="https://private-user-images.githubusercontent.com/32983588/286832065-3538aa9a-9435-49b9-9c8e-ceacea27c009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjg1MjQsIm5iZiI6MTcxOTIyODIyNCwicGF0aCI6Ii8zMjk4MzU4OC8yODY4MzIwNjUtMzUzOGFhOWEtOTQzNS00OWI5LTljOGUtY2VhY2VhMjdjMDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDExMjM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYmQ5ZjliY2IxMzA4ODBiMTY0YjU1MzQyNWU1NjM1NzVhYzIyMDQwZGU0Nzg1NGU5MWY2NThmODZhYjQ4NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ElibvDgGRvraex6BCn8bUX1lT36S16HwertgV3IFWrY">

如果链接中有C#会报错
![捕获](https://github.com/fluid-dev/hexo-theme-fluid/assets/22772053/36a69a67-94d7-4a2a-bb74-22e41934ab87)
如果是标签，就会跳转到C
![2](https://github.com/fluid-dev/hexo-theme-fluid/assets/22772053/b0bed4b9-78cd-479d-9778-b0755b0787c8)

**Comment by zkqiang** [comment]
因为链接里 # 号是特殊字符啊（[URL的井号](https://ruanyifeng.com/blog/2011/03/url_hash.html)）

是故意过滤掉特殊字符，可以用 [tag_map](https://hexo.io/zh-cn/docs/configuration#%E5%88%86%E7%B1%BB-%E6%A0%87%E7%AD%BE) 改成你想要的 url
