### ISSUE TITLE
随机文章图片

### ISSUE THREAD

**Issue by huajien** [fluid-dev/hexo-theme-fluid#1012]
文章图片随机例如调用
https://img.xjh.me/random_img.php?type=bg&ctype=nature&return=302
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/75553778/c0fc9005-f1cb-4d45-9897-afc4e33defc9)
调用的api图片不同的文章拥有不同的图片不要一样的图片

**Comment by LingkKang** [comment]
看看这个？[配置指南 | Hexo Fluid 用户手册 # 文章页顶部大图](https://hexo.fluid-dev.com/docs/guide/#%E6%96%87%E7%AB%A0%E9%A1%B5%E9%A1%B6%E9%83%A8%E5%A4%A7%E5%9B%BE)

相对路径改成随机图片的网址就好了。

**Comment by huajien** [comment]
> 看看这个？[配置指南 |Hexo Fluid 用户手册 # 文章页顶部大图](https://hexo.fluid-dev.com/docs/guide/#%E6%96%87%E7%AB%A0%E9%A1%B5%E9%A1%B6%E9%83%A8%E5%A4%A7%E5%9B%BE)
> 
> 相对路径改成随机图片的网址就好了。

尝试了还是一样的随机图片都是加载的一个随机图片

**Comment by LingkKang** [comment]
> 尝试了还是一样的随机图片都是加载的一个随机图片

https://picsum.photos/200 试试这个网站？我本地是可以的

**Comment by huajien** [comment]
> > 尝试了还是一样的随机图片都是加载的一个随机图片
> 
> https://picsum.photos/200 试试这个网站？我本地是可以的
还是这样师傅
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/75553778/ec4f9065-750f-45c4-ba63-65a288536165)
代码我是这样配置我在本地跑的
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/75553778/812a0d6e-46b8-444e-94ae-6b84f8d3fc80)
