### ISSUE TITLE
请求在首页给文章添加分割线功能

### ISSUE THREAD

**Issue by vicar5235** [fluid-dev/hexo-theme-fluid#1013]
作者们好，能否在首页给文章之间添加分割线，或者让文章在首页以“块”的形式展示？现在的样式在电脑上看是不错的，但到了手机上就体验不佳了，很容易分不清文章的信息是属于上面的还是下面的。

**Comment by xiyuvi** [comment]
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/38217058/dbdc4500-1f6a-462d-8d08-d0251bc7f558)

移动端确实第一次访问页面会不明确，你可以在主题样式中加入
```
.index-card.row.mx-auto {
    border-bottom: 1px dashed #eee;
}
```
来达到上述效果，只有移动端会有分割线

**Comment by xiyuvi** [comment]
@zkqiang  后续是否修改主题的移动端样式得看强哥
