### ISSUE TITLE
文章 “更新时间” 选择 “相对时间” 后无法变化

### ISSUE THREAD

**Issue by Sovy0** [fluid-dev/hexo-theme-fluid#1014]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

文章更新时间选择 “相对时间” 后，生成的 HTML 文件的更新时间是静态的，导致更新时间无法随着时间流逝而变化，比如永远显示 5 小时前。

#### 截图

![设置为相对时间](https://github.com/fluid-dev/hexo-theme-fluid/assets/120722648/9cb7914d-d127-4d20-8e84-e15d720be1af)

![更新时间永远是 5 小时前](https://github.com/fluid-dev/hexo-theme-fluid/assets/120722648/12590bec-fdf5-46cb-90f2-e5ca80fd1777)

希望可以解决一下这个问题，非常感谢！

**Comment by f88083** [comment]
@Sovy0 hexo clean && hexo g重新生成文件能解決這個問題嗎?如果可以的話可能得寫個Github Action每天固定時間重新生成網頁

**Comment by zkqiang** [comment]
@Sovy0 @f88083 dev分支已更新，可以体验下

**Comment by zkqiang** [comment]
[v1.9.7](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.9.7) 已修复
