### ISSUE TITLE
页面完全空白,什么都不显示，并且F12报错

### ISSUE THREAD

**Issue by ysc2** [fluid-dev/hexo-theme-fluid#1016]

**Comment by ysc2** [comment]
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/89937434/7f266812-fbbb-4e2b-a5fa-ca6e58b41961)

**Comment by ysc2** [comment]
我的浏览器：Chrome (118.0.0.0)
OS：Windows10

**Comment by ysc2** [comment]
预期效果：
![Uploading image.png…]()

**Comment by ysc2** [comment]
预期效果：
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/89937434/dc7a6df5-68c3-4d41-b555-85049daebf6e)

**Comment by xiyuvi** [comment]
404是没找到文件，你部署的不对，和主题没有关系的

**Comment by ysc2** [comment]
解决：注意检查在_config.yml文件中url:https://username.github.io/project，其中的project名字应该为你的github名字+.+github.io
