### ISSUE TITLE
代码块不能显示title

### ISSUE THREAD

**Issue by ZhangIvan1** [fluid-dev/hexo-theme-fluid#1018]
我想在代码块中加入title等信息
根据hexo的[文档](https://hexo.io/zh-cn/docs/syntax-highlight)
我是这样写的
<img width="360" alt="截屏2023-11-15 20 10 07" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/49400113/ab670a4a-a37b-438b-a8b6-0fa5411be497">

但是在网站上依然只显示语言
![截屏2023-11-15 20 09 18](https://github.com/fluid-dev/hexo-theme-fluid/assets/49400113/1c2c0e10-9a55-40a9-92f1-e0edbeb88628)

**Comment by ZhangIvan1** [comment]
f12看了一下，发现这个tile实际上是有的
```
<figcaption><span>src/main.rs</span></figcaption>
```
但是样式`display: none;`在`.markdown-body figcaption:not(.image-caption)`中

目前我通过`custom_css`改了一下，现在是能用的一个状态
```
.highlight figcaption
      display: block !important
      background: #21252b
      padding-left: 20px
      color: #ffffff
      font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace
      font-size: 0.75rem;
      font-weight: bold;
```

<img width="553" alt="截屏2023-11-15 23 02 45" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/49400113/052edb5f-c287-4584-aa4d-8c10351348f9">

**Comment by zkqiang** [comment]
没有这个 feature，考虑下个版本加上
