### ISSUE TITLE
使用Tag中的折叠功能报错

### ISSUE THREAD

**Issue by MMoYu** [fluid-dev/hexo-theme-fluid#1019]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

**Comment by MMoYu** [comment]
使用折叠功能,hexo g报错： unknown block tag: fold
{% fold info @title %}

xxxxx
{% endfold %}
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/103867316/7c0a6405-a653-4c92-a47c-4fa3637e20c7)

**Comment by MMoYu** [comment]
已更新至最新版本，hexo s 本地也是同样错误

**Comment by f88083** [comment]
@MMoYu 最近這邊都沒人回覆，我剛好也遇到了這個問題，研究了一下，發現不知道為什麼他們沒有把這個功能包進7月份的更新，卻在文檔中說有這個功能。翻閱了pull request發現有大老三個月前實作了這個功能: [請參見](https://github.com/fluid-dev/hexo-theme-fluid/pull/993)。照著這個PR修改自己的本地fluid文件就可以實現了!希望有幫助到你~😆

**Comment by MMoYu** [comment]
> @MMoYu 最近這邊都沒人回覆，我剛好也遇到了這個問題，研究了一下，發現不知道為什麼他們沒有把這個功能包進7月份的更新，卻在文檔中說有這個功能。翻閱了pull request發現有大老三個月前實作了這個功能: [請參見](https://github.com/fluid-dev/hexo-theme-fluid/pull/993)。照著這個PR修改自己的本地fluid文件就可以實現了!希望有幫助到你~😆有任何問題直接問不用客氣:D

非常感谢！！！

**Comment by MMoYu** [comment]
实测这个功能在最新版本没有；
我这边本地hexo version为7.0.0，Fluid未找到查询版本方式，已按照npm install --save hexo-theme-fluid更新本地fluid版本；

参照https://github.com/fluid-dev/hexo-theme-fluid/pull/993 修改成功解决该问题

**Comment by MMoYu** [comment]
实测这个功能在最新版本没有；
我这边本地hexo version为7.0.0，Fluid未找到查询版本方式，已按照npm install --save hexo-theme-fluid更新本地fluid版本；

参照https://github.com/fluid-dev/hexo-theme-fluid/pull/993 修改，本地hexo s 渲染成功：

**Comment by MMoYu** [comment]
实测这个功能在最新版本没有；
我这边本地hexo version为7.0.0，Fluid未找到查询版本方式，已按照npm install --save hexo-theme-fluid更新本地fluid版本；

参照https://github.com/fluid-dev/hexo-theme-fluid/pull/993 修改，本地hexo s 渲染成功：
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/103867316/2e7dbda7-7f5d-4f52-a02e-1d5d58b6e507)

但是在网站上的实际效果并没有渲染成功：
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/103867316/10e7b5c9-2c35-438d-80da-2828f611aff7)

已清除缓冲过

**Comment by MMoYu** [comment]
实测这个功能在最新版本没有；
我这边本地hexo version为7.0.0，Fluid未找到查询版本方式，已按照npm install --save hexo-theme-fluid更新本地fluid版本；

参照https://github.com/fluid-dev/hexo-theme-fluid/pull/993 修改成功

**Comment by zkqiang** [comment]
@MMoYu @f88083 
抱歉，该功能和未正式发布，可以暂时使用 develop 分支

**Comment by f88083** [comment]
> @MMoYu @f88083 抱歉，该功能和未正式发布，可以暂时使用 develop 分支

好的感謝回覆!不過我比較好奇怎麼文檔裡寫說有這功能，是否需要移除避免其他人遇到同樣問題
