### ISSUE TITLE
安卓平台中文字体加粗无效

### ISSUE THREAD

**Issue by jupitersh** [fluid-dev/hexo-theme-fluid#102]
安卓平台中文字体加粗无效，英文及数字加粗没问题，PC及iOS平台都正常

**Comment by HarborZeng** [comment]
应该是安卓上面的字体问题

**Comment by zkqiang** [comment]
已定位修复 https://github.com/fluid-dev/hexo-theme-fluid/commit/d46589e035a67c1faef33edd2006bb50b06412ab
