### ISSUE TITLE
無法啟用prismjs，高亮失效

### ISSUE THREAD

**Issue by f88083** [fluid-dev/hexo-theme-fluid#1020]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

無法切換成prismjs

#### 复现步骤
该 Bug 复现步骤如下：

1. 使用最新版hexo
2. 使用純淨fluid
3. _config.fluid.yml底下配置`lib: "prismjs"`

***這樣子無法切換成prismjs高亮程式碼***

#### 解決方法

原因是hexo v7.0.0更新了切換highlighter的方式，[請見](https://github.com/hexojs/hexo/releases/tag/v7.0.0)
現在需在`_config.yml`使用`syntax_highlighter:`來切換高亮工具
```yml
syntax_highlighter: prismjs  # highlight.js | prismjs | <empty>
```

**Comment by zkqiang** [comment]
已在 1.9.6 版本修复
