### ISSUE TITLE
在_config.fluid.yml新增banner

### ISSUE THREAD

**Issue by AndyLicion** [fluid-dev/hexo-theme-fluid#1021]
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/108504824/9cf25a3f-0cc6-453d-82ec-103ad8361909)
页面没有显示生效

**Comment by zkqiang** [comment]
是在 front-matter 里配置，再看看文档

**Comment by AndyLicion** [comment]
感谢您的解答，我再详细看看文档🤝
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月04日 14:05 |
| 收件人 | fluid-dev/hexo-theme-fluid ***@***.***> |
| 抄送人 | Jiacheng ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [fluid-dev/hexo-theme-fluid] 在_config.fluid.yml新增banner (Issue #1021) |

是在 front-matter 里配置，再看看文档
