### ISSUE TITLE
Suggestion: supply option to change other page's slogan

### ISSUE THREAD

**Issue by chen-huaneng** [fluid-dev/hexo-theme-fluid#1022]
#### 尝试修改其他页面的slogan中显示的文字
出于自定义的需求，我尝试修改slogan中的文字，但是文档中只写了如何修改主页面的slogan，但是我同时想要修改其他页面的slogan，所以我就在文档中找能否在不改变主题的文件配置的情况下修改其他页面的slogan，但是没有找到。

#### 通过更改_data/languages中的文件来达到目的
最后我在国际化中的语言文件中找到了更改的方法，能够实现在不更改主题的文件下，覆盖掉原有的配置。具体步骤如下：
- 在文档中的[语言配置](https://fluid-dev.github.io/hexo-fluid-docs/guide/#%E8%AF%AD%E8%A8%80%E9%85%8D%E7%BD%AE)中根据描述操作
- 在想要修改的语言的文件下，比如我想要修改的就是zh-CN.yml文件，修改相对应的subtitle的值然后重新生成页面就行

#### 建议
在文档中增加相关的描述来提供修改其他页面的slogan的说明，可以按照我上面描述的方法，或者像更改主页一样增加接口来修改。

**Comment by zkqiang** [comment]
因为这种修改方式并不是设计初衷，所以没有特别说明了
