### ISSUE TITLE
黑暗模式下，折叠块 title 显示模糊

### ISSUE THREAD

**Issue by woshixiaoguo** [fluid-dev/hexo-theme-fluid#1023]
### 明亮模式
<img width="786" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/42127895/d4659fc5-9d6f-4e25-a940-db1928fccdfc">

### 黑暗模式
<img width="794" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/42127895/910548ed-3f41-439d-85bd-4a164d1c2f1f">

**Comment by zkqiang** [comment]
[v1.9.7](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.9.7) 已修复
