### ISSUE TITLE
折叠块的三个 bug：行间距、颜色与同时展开折叠

### ISSUE THREAD

**Issue by xyfJASON** [fluid-dev/hexo-theme-fluid#1026]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述
1. 折叠块内行间距比正文大；
2. 使用 `secondary` 的时候没有颜色（其他颜色正常）；
3. 如果两个折叠块内容相同，它们会被同时展开或折叠。

浏览器：Chrome / Safari

#### 复现步骤
新建一篇文章，输入以下内容并 `hexo s`：

```markdown
---
title: fold测试
date: 2023-12-07 20:48:21
tags:
categories:
banner_img:
index_img:
---

### Bug 1: 折叠块行间距过大

正文第一行

正文第二行

{% fold primary @折叠块测试 %}

折叠块第一行

折叠块第二行

{% endfold %}



### Bug 2: secondary 没有颜色

{% fold secondary @折叠块测试 %}

secondary 没有颜色（其他颜色正常）

{% endfold %}



### Bug 3: 相同内容的折叠块会被同时展开和折叠

{% fold success @折叠块测试 %}

aaa

{% endfold %}

{% fold danger @折叠块测试 %}

aaa

{% endfold %}

{% fold warning @折叠块测试 %}

bbb

{% endfold %}

{% fold info @折叠块测试 %}

bbb

{% endfold %}

{% fold light @折叠块测试 %}

bbb

{% endfold %}

```

#### 截图

<img width="600" alt="Xnip2023-12-07_21-19-14" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/59991810/d9ac0687-0e27-4e6c-ab13-97d6f9a2850d">

#### 版本信息

<img width="404" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/59991810/006d30d2-6426-4d62-9796-988b63843926">

**Comment by zkqiang** [comment]
1 和 2 已在 dev 分支修复

3 的原理是根据折叠内容作为折叠的编号，所以只要内容不同就没有这个情况，不然没有其他识别唯一性的好办法

**Comment by xyfJASON** [comment]
好的，谢谢 😃

**Comment by mobeicanyue** [comment]
@zkqiang 您好，看到您的博客的折叠块代码效果是这样的（折叠logo）
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/81098819/cc324b0f-4800-45aa-a016-7d8d35f23d89)

但是我照着您的源码写 logo效果却如下
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/81098819/b5ebf393-87a4-4945-b64f-e31609c40719)
请问是我有哪里没写到位？是目前最新的主题版本

**Comment by zkqiang** [comment]
@mobeicanyue 是你浏览器的问题吧，实际就是下一个

<img width="462" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/32983588/62338bdf-ac5d-4729-b2fa-d8ec8a4d11fe">

**Comment by mobeicanyue** [comment]
> @mobeicanyue 是你浏览器的问题吧，实际就是下一个
> 
> <img alt="image" width="462" src="https://private-user-images.githubusercontent.com/32983588/297606382-62338bdf-ac5d-4729-b2fa-d8ec8a4d11fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTAwNzQsIm5iZiI6MTcwNTU0OTc3NCwicGF0aCI6Ii8zMjk4MzU4OC8yOTc2MDYzODItNjIzMzhiZGYtYWM1ZC00NzI5LWIyZmEtZDhlYzhhNGQxMWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDAzNDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNzg2ODgxZDVlOTkyZDZkYWFkMTc5MTIzNWMzZDQzYzAzYTlmZTc1N2EzMjFjYmZmY2VhY2Q2YWEyNGM4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uS8GIPjS8Uv6VCsGoY_OOGhBLP69qKZon1r-FmNX6kc">

确实好奇怪，和浏览器也有关系
我用手机访问你的blog 就是你发的图片的效果，但是如果电脑使用 chrome
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/81098819/ee451236-0c3f-4dfb-9bc1-e9ba98595264)
而同样是chrome 我打开我的网页就是
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/81098819/da35dc49-2ff1-45e0-809b-236fde890c51)

**Comment by zkqiang** [comment]
@mobeicanyue 应该是你系统字体的关系

**Comment by mobeicanyue** [comment]
应该是我博客字体的关系
