### ISSUE TITLE
CDN配置是否可以覆盖文章正文内图片资源？

### ISSUE THREAD

**Issue by DubheHub** [fluid-dev/hexo-theme-fluid#1027]
#### 请确认
- [ ✅] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ✅] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

我对站内内部使用资源进行了cdn配置，加速效果很好。
但是写文章引用img时需要手动给每个img添加cdn地址，感觉很繁琐。
是否有什么配置可以让文章内通过 （/img/XXX）即本地引用的图片url也可以走到全局cdn上去呢？

**Comment by zkqiang** [comment]
这个应该是插件做的事，可以找下有没有类似功能的插件
