### ISSUE TITLE
如何调高隐藏空白边栏的阈值？

### ISSUE THREAD

**Issue by zh0ngtian** [fluid-dev/hexo-theme-fluid#1028]
#### Make sure
- [x] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] No solution found in [documentations](https://hexo.fluid-dev.com/docs/en/)

#### Describe the question
当浏览器页面比较窄的时候，主题会自动去掉两边的空白，请问如何调高这个自动去掉空白的阈值呢？

**Comment by zkqiang** [comment]
通过自定义 CSS 修改如下几处地方

https://github.com/fluid-dev/hexo-theme-fluid/blob/55df7c03eb98f0ba9aefbb0ecc8f1bb4665ee109/source/css/_pages/_post/post-page.styl#L6-L14
