### ISSUE TITLE
添加百度统计问题

### ISSUE THREAD

**Issue by luoyuanxiang** [fluid-dev/hexo-theme-fluid#103]
根据提示我添加了百度统计的代码，但是不起作用，如图
![image](https://user-images.githubusercontent.com/29119330/68353528-d4558600-0144-11ea-8ead-c8d41800713e.png)

显示如下：
![image](https://user-images.githubusercontent.com/29119330/68353571-fcdd8000-0144-11ea-9223-385d5957e261.png)

源代码：
![image](https://user-images.githubusercontent.com/29119330/68353597-0f57b980-0145-11ea-8fc5-edc0a519ec4b.png)

我修改为:
![image](https://user-images.githubusercontent.com/29119330/68353622-24344d00-0145-11ea-8fa4-5d61d6f984de.png)

但是报错：
![image](https://user-images.githubusercontent.com/29119330/68353680-45953900-0145-11ea-892b-b20bed6da5cd.png)

希望能解决，谢谢

**Comment by zkqiang** [comment]
我的错误，需要改成 `theme.web_analytics.baidu`，Fix 版本会修复

**Comment by luoyuanxiang** [comment]
好的，谢谢，修复后直接更新就可以了吧

**Comment by zkqiang** [comment]
是的，感谢提供BUG

**Comment by luoyuanxiang** [comment]
好的，不客气，我正在使用这个主题感觉非常不错

**Comment by zkqiang** [comment]
master 分支已更新修复代码，感兴趣可以加入我们的[微信群交流](https://github.com/fluid-dev/hexo-theme-fluid/issues/96)
