### ISSUE TITLE
markdown文件中公式编辑报错：missing or unrecognized delimiter for left

### ISSUE THREAD

**Issue by whlok** [fluid-dev/hexo-theme-fluid#1030]
#### Bug 描述
文件中编辑公，typora打开显示正常，hexo s 显示 missing or unrecognized delimiter for left。

#### 复现步骤
该 Bug 复现步骤如下：
1. 编辑公式：
$$
F(i,j)=\begin{cases}
max\left\{ F(i-1,j),F(i-1,j-w_i)\right\},{j-w_i>=0} \\
F(i-1,j), {j-w_i}<0
\end{cases}
$$
2. hexo g -d
3. 公式部分显示为：missing or unrecognized delimiter for left

https://whlok.github.io/2023/10/24/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E6%B5%85%E5%AD%A6/#%E8%83%8C%E5%8C%85%E9%97%AE%E9%A2%98%E5%92%8C%E8%AE%B0%E5%BF%86%E5%8A%9F%E8%83%BD

#### 截图
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/52624849/6018a5fd-6091-4872-af79-1922a49281ea)

**Comment by zkqiang** [comment]
这个要看你使用的 renderer，主题只是做引入并不进行二次处理
