### ISSUE TITLE
插入的图片路径带有空格不会渲染图片

### ISSUE THREAD

**Issue by lililib** [fluid-dev/hexo-theme-fluid#1036]
1. 是当前最新的 [Release 版本]
2. 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
3. 已经排除是其他 Hexo 插件影响
#### Bug 描述
如果文章内部插入的图片路径带有**空格**不会渲染图片

#### 复现步骤

```
不带空格：
![](./没有空格的测试/没有空格的测试-1703919498363.png)  可以正常渲染


带有空格：
![](./hexo fluid 一个生成模板图片测试/hexo fluid 一个生成模板图片测试-1703919324943.png)  不能正常渲染

```

#### 截图
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/46933726/d118abcf-97a4-4b00-a1f2-29f43ad74494)

**Comment by zkqiang** [comment]
这个和你使用的 renderer 有关，主题不会做这类事

另外 url 规范本身不允许有空格，不应该有带空格的路径
