### ISSUE TITLE
Giscus评论插件错误的CSS样式

### ISSUE THREAD

**Issue by H2Sxxa** [fluid-dev/hexo-theme-fluid#1039]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

Fluid更新到1.9.7后，评论插件出现了错误的样式

![6220a1800b40b2adc9366137b2737b82](https://github.com/fluid-dev/hexo-theme-fluid/assets/88923783/01bbfb74-c6db-4005-a514-3168f2982f27)
![2d118812d463b5a3404f5700c0dc7503](https://github.com/fluid-dev/hexo-theme-fluid/assets/88923783/0e2f438a-e7fb-427b-9649-b435911142f0)

将`giscus.style.cssText += 'color-scheme: normal;';`注释后恢复正常，控制台不再抛出错误

```js
    // 设置 giscus 评论主题
    var giscus = document.querySelector('iframe.giscus-frame');
    if (giscus) {
      var giscusTheme = schema === 'dark' ? window.GiscusThemeDark : window.GiscusThemeLight;
      const message = {
        setConfig: {
          theme: giscusTheme,
        }
      };
      // giscus.style.cssText += 'color-scheme: normal;';
      giscus.contentWindow.postMessage({ 'giscus': message }, 'https://giscus.app'); 
    }
```

![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/88923783/4469339e-27f8-4f9e-9464-e33c6730ae76)

~~我不确定是不是我的问题，~~ 与 #978 有关，由于我不熟悉 JavaScript，所以将此问题进行汇报

Giscus也有相关错误汇报 **https://github.com/giscus/giscus/issues/675#issuecomment-1304908689**

up: 在他人博客中得到复现，大概能确认是这个问题，具体原理不清楚

#### 复现步骤

1. 配置 Giscus 评论插件
2. 访问

**Comment by EastMonster** [comment]
same problem

**Comment by mobeicanyue** [comment]
您好，您的giscus评论，在白色背景下会出现边框不完整吗？
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/81098819/f8c217db-f7f1-4180-aee1-502c79515d0e)

**Comment by llleixx** [comment]
注释掉后颜色能正常显示。但现版本似乎仍然有控制台报错？

![image](https://github.com/user-attachments/assets/865bfd7d-064d-4ad0-90c7-0474095527ae)

**Comment by H2Sxxa** [comment]
> 注释掉后颜色能正常显示。但现版本似乎仍然有控制台报错？
> 
> ![image](https://github.com/user-attachments/assets/865bfd7d-064d-4ad0-90c7-0474095527ae)
> 
> 

我还没有更新我的博客主题到最新版本......😭

你可以试试自己复现一下
