### ISSUE TITLE
搜索功能 每次点击都要重新获取local-search.xml，网速慢的情况下要加载好久。

### ISSUE THREAD

**Issue by anban9616** [fluid-dev/hexo-theme-fluid#1045]
#### 如是功能需求，请确定符合以下情况
- [ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [ ] 难以通过第三方插件实现

#### 请描述您认为可行的解决方案

local-search.xml 应该要缓存一段时间，不要每次都去请求。
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/32592928/fda76297-91ea-4c76-9438-dfbb61efe99b)

**Comment by zkqiang** [comment]
缓存是你部署环境的策略...  主题可控制不了

可以把 local-search 像图片一样放到 OSS 里
