### ISSUE TITLE
请问，为什么我配置了leancloud后不显示统计信息呢？

### ISSUE THREAD

**Issue by ericQiang** [fluid-dev/hexo-theme-fluid#1046]
![微信截图_20240113181353](https://github.com/fluid-dev/hexo-theme-fluid/assets/11959271/656b9002-49df-403b-8a51-2ed7eda11911)
除了统计信息不显示之外，其它好像均正常。
请问该如何配置。

**Comment by xiyuvi** [comment]
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/38217058/32d983bf-10ef-49c2-9512-79a2498e76ea)
401报错是未授权错误，请检查leancloud中的访问白名单是否已经添加了你博客的域名

**Comment by ericQiang** [comment]
> 

![微信截图_20240117110551](https://github.com/fluid-dev/hexo-theme-fluid/assets/11959271/a34c964e-aa70-4101-afdb-7ead9fb01e86)
谢谢回复。添加了白名单之后，再次打开时，报这个错误。请问如何解决。谢谢。

**Comment by xiyuvi** [comment]
403还是没有权限访问，请再次确认白名单添加正确
