### ISSUE TITLE
Twikoo Comment system update 1.6.29
更新twikoo评论系统前端

### ISSUE THREAD

**Issue by kangimc** [fluid-dev/hexo-theme-fluid#1047]
twikoo The official version of the comment system has reached 1.6.29.I'd like to update it
twikoo官方版本已经更新到1.6.29了，我一样可以更新一下

**Comment by zkqiang** [comment]
modify your fluid config:

https://github.com/fluid-dev/hexo-theme-fluid/blob/2ebdb345b7b058d591fbe5f411c849c0a461b93c/_config.yml#L1096
