### ISSUE TITLE
加密文章中解密之后图片一直加载中

### ISSUE THREAD

**Issue by W1ndys** [fluid-dev/hexo-theme-fluid#1050]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

加密文章中解密之后图片一直加载中，点开才可以看，有跳转链接的就无法看图了

#### 复现步骤
该 Bug 复现步骤如下：
1. 把文章加密之后部署
2. 点开文章查看，图片无法展示

#### 截图

![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/109416673/434e4d6c-bde9-45b6-9a0c-bcd5f92b4fa5)
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/109416673/3b40e4c3-7a4f-444a-a858-cfc12e520a01)

**Comment by xiyuvi** [comment]
更换其他主题后，图片正常吗
