### ISSUE TITLE
something wrong with Katex

### ISSUE THREAD

**Issue by PikaPikaGFY** [fluid-dev/hexo-theme-fluid#1054]
When I was rendering this paragraph, then I encountered such  situation
![12](https://github.com/fluid-dev/hexo-theme-fluid/assets/156816229/8780d02f-cd47-4a92-b896-03b5702f3172)
![13](https://github.com/fluid-dev/hexo-theme-fluid/assets/156816229/e404456e-0fe0-470b-a61e-fd1288a44d27)
I don't expect to emerge  two "E" and as you can see it was even a normal "E"

**Comment by milong26** [comment]
check your katex or math module

**Comment by PikaPikaGFY** [comment]
Thanks!
