### ISSUE TITLE
如何去除掉文章各级标题中添加的#号

### ISSUE THREAD

**Issue by AkiCCLing** [fluid-dev/hexo-theme-fluid#1056]
如何去除掉文章各级标题中添加的#号
已经有了锚图标，#号很多余而且影响界面美观
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/53488343/49ac7f08-c276-4045-bdcc-017740985d69)
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/53488343/7f03ce46-4499-4a8c-a00a-0ef10534d967)

**Comment by zkqiang** [comment]
这似乎是你别的插件产生的，# 也属于锚图标的一种，但不会同时出现

**Comment by AkiCCLing** [comment]
这个是正常的网页源代码
![QQ截图20240131025213](https://github.com/fluid-dev/hexo-theme-fluid/assets/53488343/2ca2280e-bc4b-4198-84b8-6928625ea981)
这个是带有#号的源代码
![QQ截图20240131025246](https://github.com/fluid-dev/hexo-theme-fluid/assets/53488343/7c3966ac-87fe-4ddd-8df9-5890ac33dc2f)

**Comment by zkqiang** [comment]
`class="markdownIt-Anchor"` 应该是这个插件导致的，这个插件并不是 Fluid 引入的
