### ISSUE TITLE
永远加载不完的进度条

### ISSUE THREAD

**Issue by llleixx** [fluid-dev/hexo-theme-fluid#1067]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

NProgress bar 始终加载中。

#994 

#### 复现步骤

[个人博客](https://lllei.top)

可能与网络有关。

#### 截图

![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/75014336/24372c14-d782-4746-a75b-43c9eee51b62)

**Comment by llleixx** [comment]
如 [NProgress 官网](https://rstacruz.github.io/nprogress/) 所示，如果调用了 `NProgress.done()` 之后再调用 `NProgress.inc()` 将重新唤起进度条。

我发现这是因为 load 事件触发后，events.js 中再次调用了 `NProgress.inc` 所致。

利用 `NProgress.done()` 执行后，`NProgress.status` 变为 null 这一点可以修复这个 bug。

如果可以的话，我会提一个 PR。

**Comment by zkqiang** [comment]
非常感谢
