### ISSUE TITLE
提两点增强用户体验的建议

### ISSUE THREAD

**Issue by ZhouShisong** [fluid-dev/hexo-theme-fluid#107]
第一点：感觉右边目录的字号有点大了，标题稍微长一点点就显示成两三行了。能不能把改小一下，尽量让一个标题保持一行显示，一行显示不完的话后面就用...省略掉；

第二点：文章正文中，每个标题的前面可以增加一个绿色的“#”突显标题，增加可阅读小，当然了其他颜色也可以。可以参考一下这个效果：https://vinefiner.github.io/2017/01/06/ReactiveCocoa-进阶/

**Comment by zkqiang** [comment]
第一点  暂时只减小 1px 字号，太小的话，目录太短的话不够美观
第二点 本身有这个功能，配置：`fun_features.anchorjs.icon: '#'`
