### ISSUE TITLE
VSCode插件-方便自動貼上snippet(Hexo Snippet Paste Tool for Fluid v1.0.0釋出)

### ISSUE THREAD

**Issue by f88083** [fluid-dev/hexo-theme-fluid#1075]
寫部落格的時候有些snippet久沒用或是容易打錯，覺得有些麻煩，所以自己嘗試寫了第一個vscode插件，分享給大家，現已上架[marketplace](https://marketplace.visualstudio.com/items?itemName=Shih-Che-Lai-Simon.hexo-snippet-paste-tool-for-fluid)，名稱是`Hexo Snippet Paste Tool for Fluid`

因為是第一個版本，所以目前只能貼入我自己常用的`youtube embed code`，`note`，以及`fold`，未來會陸陸續續添加直到`Fluid`主題支援的snippet都放進去為止

希望大家用得開心，第一次寫vscode插件，還請多多包涵，多多指教，感激不盡

**Comment by f88083** [comment]
`v2.0.0`已釋出，新增了五個新的命令，應該已經包含fluid用到的所有snippet了

**Comment by zkqiang** [comment]
可以写成文章投到这里 https://github.com/fluid-dev/hexo-fluid-blog

**Comment by f88083** [comment]
> 可以写成文章投到这里 https://github.com/fluid-dev/hexo-fluid-blog

感謝告知
