### ISSUE TITLE
在开启代理的情况下前端页面无法正常加载

### ISSUE THREAD

**Issue by lingdongomg** [fluid-dev/hexo-theme-fluid#1076]
#### 请确认
- [x] 是当前最新的 [[Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述
当开启网络代理时，前端页面加载异常。使用网络代理工具为Clash for windows，开启代理加载异常，关闭代理加载正常。和浏览器类型和版本无关。

加载异常截图：
![7107532273715](https://github.com/fluid-dev/hexo-theme-fluid/assets/55029504/cea28e26-59c6-4ab6-b24e-2b472f6c7f6b)
正常加载截图：
![17107532871360](https://github.com/fluid-dev/hexo-theme-fluid/assets/55029504/fbeea437-17de-428d-ad26-d2852bfa5048)
加载异常时命令行截图：
![20240318171631](https://github.com/fluid-dev/hexo-theme-fluid/assets/55029504/579802c2-628b-418a-8b01-7cc43f9c1b25)

经测试，所有的fluid博客均存在网络代理情况下无法正常加载问题，即只要使用Clash for windows进行网络代理即可复现。而其他的hexo主题博客未出现该问题。

**Comment by lingdongomg** [comment]
如果在开启代理后未复现到，可能是因为浏览器缓存了正常的页面。
此时可以试试在浏览器的无痕模式下访问页面。

**Comment by zkqiang** [comment]
因为 Fluid 静态资源默认使用 lib.baomitu.com，你的代理的规则可能对该域名不友好，或者你可以改你自己博客的资源配置
