### ISSUE TITLE
Giscus 评论区背景加载失败

### ISSUE THREAD

**Issue by iamliuzy** [fluid-dev/hexo-theme-fluid#1078]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/59107734/18e4bd28-2b61-4039-b04b-d84d2931ab57)
如图，在 `config.fluid.yml` 中配置好了 Giscus 评论后，评论区背景是黑色的，在白色主题下依然如此。
附上浏览器控制台报错：
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/59107734/491f218c-58c8-4c56-87d2-99df7a62dd2f)
注：这似乎并非是 Giscus 的问题，使用其他主题就没有这个问题。

**Comment by iamliuzy** [comment]
我试了试，用Safari访问就没这问题

**Comment by chergn** [comment]
你是把自己的博客系统部署在github了吗？

**Comment by iamliuzy** [comment]
对的

**Comment by ivyliu1205** [comment]
我也遇到了同样的问题。在`config.fluid.yml`中修改了几个giscus的theme, 都同样会显示这个黑色评论区。我的浏览器是chrome
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/41543107/ec23408a-a4e3-4e30-bc41-186b69467696)

**Comment by llleixx** [comment]
新版本应该没有这个 bug 了。

但控制台报错仍然存在，这个原因是 iframe 还没有 load 就发起了 postMessage。之后有时间我会 PR 一下。

**Comment by iamliuzy** [comment]
好的，我看一下。

**Comment by iamliuzy** [comment]
刚更新了新版本，还是没有修复。`hexo-theme-fluid` 版本 1.9.8 。

**Comment by iamliuzy** [comment]
![image](https://github.com/user-attachments/assets/8cda1721-0a28-432c-ac1a-8d64210be383)

**Comment by llleixx** [comment]
![image](https://github.com/user-attachments/assets/da58b0ea-e1c8-48e6-af2e-ae25271fb51f)

我这里显示你的博客正常，我怀疑是缓存的原因。

你禁用浏览器缓存再试试呢？

**Comment by iamliuzy** [comment]
是的，现在已经好了。
