### ISSUE TITLE
添加 Front-matter不生效

### ISSUE THREAD

**Issue by skyail** [fluid-dev/hexo-theme-fluid#108]
我在文章开头的位置设置了 Front-matter，想要设置文章在首页的缩略图，但是发布后没有生效
![image](https://user-images.githubusercontent.com/24677507/69683752-e34ea900-10f0-11ea-976c-65387cc796d2.png)
![image](https://user-images.githubusercontent.com/24677507/69683762-eba6e400-10f0-11ea-945a-0bd845404fa2.png)

**Comment by zkqiang** [comment]
去掉空行试试..  Front-matter是Hexo自带的功能，主题不会对其进行修改
