### ISSUE TITLE
文章在首页的缩略图可不可以在全局配置啊？

### ISSUE THREAD

**Issue by chergn** [fluid-dev/hexo-theme-fluid#1084]
[现状是需要每个博文都配置 index_img ](https://fluid-dev.github.io/hexo-fluid-docs/guide/#%E6%96%87%E7%AB%A0%E5%9C%A8%E9%A6%96%E9%A1%B5%E7%9A%84%E5%B0%81%E9%9D%A2%E5%9B%BE)，我想可不可以在 _config.fluid.yml 文件统一配置。比如`index_img: false`就关闭博文在首页显示缩略图，默认是`true`开着的。
但是默认取博文的哪个图片呢？随便取一个嘛。如果在[Front-matter](https://hexo.io/zh-cn/docs/front-matter)博文也配置index_img了，那就以博文内的优先

**Comment by zkqiang** [comment]
<img width="905" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/32983588/a213df11-50b2-486d-8fbb-ee9744583b06">

文档下面都写了
