### ISSUE TITLE
分类页面的banner_img是怎么配置的？

### ISSUE THREAD

**Issue by chergn** [fluid-dev/hexo-theme-fluid#1085]
看index、tag、about都是在`_config.fluid.yml`文件直接配置`banner_img`即可，[categories](https://fluid-dev.github.io/hexo-fluid-docs/guide/#%E5%88%86%E7%B1%BB%E9%A1%B5)页面咋就不行了呢？
<img width="1920" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/43592730/0b1aacee-3154-4de0-a2d6-484d6ccf0fd2">

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/2ebdb345b7b058d591fbe5f411c849c0a461b93c/_config.yml#L905

请对照着配置文件来改
