### ISSUE TITLE
怎么使用gitee的评论系统啊？

### ISSUE THREAD

**Issue by chergn** [fluid-dev/hexo-theme-fluid#1086]
[按照教程](https://blog.csdn.net/adobeid/article/details/82261930)我也配置了主题文件的giteement：
<img width="1582" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/43592730/a812b2c2-989f-4df4-bcfe-aa1bbb9087b3">

可是运行报错啊：
<img width="1920" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/43592730/364e13d0-215a-4df1-ab68-3b66136f82fe">

**Comment by mobeicanyue** [comment]
可能需要 fluid 去手动实现，可以提 pr

**Comment by zkqiang** [comment]
这个报错是你 config yaml 语法报错，请检查语法或者缩进是否正确
