### ISSUE TITLE
关于文章页面点击目录后，点击后推键不会退出这个页面而是会跳回上一个目录

### ISSUE THREAD

**Issue by WenJelly** [fluid-dev/hexo-theme-fluid#1087]
# 如题
在文章页面，比如有目录1、2、3，当我点击目录1再点击目录2，当我想回退到上一页时，他会先从目录2页面退回到目录1页面，然后再退出这个页面
，如果点击的目录很多的话，他要依次退出，有点不方便

**Comment by zkqiang** [comment]
浏览器的行为就是如此
