### ISSUE TITLE
如何设置评论插件的 path？

### ISSUE THREAD

**Issue by AnzhiZhang** [fluid-dev/hexo-theme-fluid#1094]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

我在使用 waline 评论插件，想将 path 设置为 `window.location.pathname.replace(/\/$/,'')`，但是在前端会变成 `path: window.location.pathname.replace(/\/$/,&#39;)`，我尝试了使用引号包裹配置项，还有换行，但都没有解决，请问是否有解决方案？

参见：https://waline.js.org/reference/client/props.html#path

**Comment by zkqiang** [comment]
这个参数应该不能去调用函数，这是 waline 的逻辑
