### ISSUE TITLE
tag_map被忽略

### ISSUE THREAD

**Issue by Sving1024** [fluid-dev/hexo-theme-fluid#1096]
#### 问题
如果在站点配置了 tag_map，在生成标签页时仍会使用原来的tag而不是映射过后的tag

**Comment by zkqiang** [comment]
有 tag_map 这个配置的文档吗？没找到相关配置

**Comment by Sving1024** [comment]
https://hexo.io/zh-cn/docs/configuration#%E5%88%86%E7%B1%BB-%E6%A0%87%E7%AD%BE

**Comment by zkqiang** [comment]
这可能是 hexo 之前存在的 bug，但是我在最新版本(v7.3.0) 里发现已经修复
