### ISSUE TITLE
某一分类或者某一标签文章数超过10篇，点击去依旧显示共计10篇文章

### ISSUE THREAD

**Issue by newonexd** [fluid-dev/hexo-theme-fluid#110]
<img width="651" alt="图片"   ##src="https://user-images.githubusercontent.com/44625774/69777364-ea51e600-11da-11ea-9fd4-401b5f8fe652.png">
<img width="228" alt="图片" src="https://user-images.githubusercontent.com/44625774/69777347-d9a17000-11da-11ea-89bc-6730ed17ec6b.png">

**Comment by newonexd** [comment]
<img width="592" alt="图片" src="https://user-images.githubusercontent.com/44625774/69777404-153c3a00-11db-11ea-97fd-e2ebe1d0ae16.png">

**Comment by zkqiang** [comment]
是不是 Hexo 配置没开分页...
