### ISSUE TITLE
内置Tag显示效果优化

### ISSUE THREAD

**Issue by JackeyLea** [fluid-dev/hexo-theme-fluid#1100]
#### 如是功能需求，请确定符合以下情况
- [ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [ ] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

使用内置tag时，如果内容过长，行与行之间会有重叠
![捕获](https://github.com/fluid-dev/hexo-theme-fluid/assets/22772053/9a8bffaa-775e-4422-9d68-e7e3da9d5ef3)

**Comment by zkqiang** [comment]
确定是最新版本吗，把 markdown 原始文本发一下，我没复现出来

<img width="685" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/32983588/2b0070b9-5d28-46f3-a903-1b19c2dc1304">

**Comment by JackeyLea** [comment]
hexo 7.2.0 
hexo-cli 4.3.2
css 3.0.0
hexo-neat 1.0.9
hexo-server 3.0.0
hexo-theme-fluid 1.9.7
Ubuntu 24.04 LTS Linux 6.8.0 nginx 1.24.0
在线效果 https://feater.top/presagis/intro-of-cdb/
原始文件见附件
[CDB简介.md](https://github.com/user-attachments/files/15886285/CDB.md)

**Comment by zkqiang** [comment]
用法不对，请按 [用户文档](https://hexo.fluid-dev.com/docs/guide/#%E4%BE%BF%E7%AD%BE)

<img width="787" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/32983588/0a5c9c54-8a28-45d9-a0bd-b4b1ebe7c95d">
