### ISSUE TITLE
需求：多语言代码块并列展示

### ISSUE THREAD

**Issue by Explorer-Dong** [fluid-dev/hexo-theme-fluid#1102]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

能否实现类似于下图这种多语言代码块**并列展示**的功能？
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/128051718/d82eea04-9d3b-4971-bec2-6ea26b3fe6de)

![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/128051718/0fb296cb-ff9c-4025-8bde-cdeb7a51461d)

上图对应的语法为：
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/128051718/fa457b27-0abe-400f-8b86-2708d960381b)

**Comment by zkqiang** [comment]
这个需求，用一点用但不多，暂时不采纳了
