### ISSUE TITLE
Database load failed. Deleting database.

### ISSUE THREAD

**Issue by jackssxx** [fluid-dev/hexo-theme-fluid#1103]
在尝试创建图集页面之后hexo s后老是出现报错Database load failed. Deleting database .hexo clean也无果，然后创建的新页面markdown正文部分的html代码页面无法正常渲染。
<img width="268" alt="屏幕截图 2024-06-19 152606" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/142096721/c263d612-2a23-4f99-af3a-db8b9911220e">
<img width="749" alt="屏幕截图 2024-06-19 152821" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/142096721/3fb7dbbd-22f9-47c7-84d1-df477ba53711">

**Comment by zkqiang** [comment]
这个是你本地 hexo 问题，和主题无关
