### ISSUE TITLE
[文档] highlightjs.org/demo 更换地址

### ISSUE THREAD

**Issue by ANGJustinl** [fluid-dev/hexo-theme-fluid#1105]
https://github.com/fluid-dev/hexo-theme-fluid/blob/2ebdb345b7b058d591fbe5f411c849c0a461b93c/_config.yml#L65C1-L65C50
->
https://highlightjs.org/demo

**Comment by Explorer-Dong** [comment]
这个已经 merge 进最新的 develop 分支了: https://github.com/fluid-dev/hexo-theme-fluid/pull/1099
