### ISSUE TITLE
文章封面图的裁剪逻辑

### ISSUE THREAD

**Issue by chesha1** [fluid-dev/hexo-theme-fluid#1106]
对于一张不符合显示规则的图，请问显示逻辑是怎么样？

会被缩放然后裁剪吗？还是直接裁剪到某个固定分辨率？

**Comment by zkqiang** [comment]
等比例缩放裁剪，长宽哪个超出裁哪个

**Comment by chesha1** [comment]
> 等比例缩放裁剪，长宽哪个超出裁哪个

在一个正常的16：9浏览器上显示，什么样的长宽比能缩放后不被裁剪？

**Comment by zkqiang** [comment]
大概 3:2 就可以
