### ISSUE TITLE
代码块不能自动换行

### ISSUE THREAD

**Issue by Feiju12138** [fluid-dev/hexo-theme-fluid#1107]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

当代码区域一行文本很多内容时，代码块渲染功能不自动换行，期望自动换行

#### 复现步骤
该 Bug 复现步骤如下：

任何有代码块且一行文本超出的地方

#### 截图

<img width="1552" alt="图片" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/49089085/1397d10f-872e-4e73-8833-e0e83fc1afc6">

**Comment by zkqiang** [comment]
首先代码不能自动换行，换行了代码还有可读性吗

第二你这个样式加载有问题，先排除下是否为其他插件影响

**Comment by Feiju12138** [comment]
好的
