### ISSUE TITLE
折叠块展开或收起操作会导致严重卡顿

### ISSUE THREAD

**Issue by Explorer-Dong** [fluid-dev/hexo-theme-fluid#1108]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

使用 {% fold %} 折叠块语法后，展开和关闭时页面会卡顿至少3秒，无论是 Chrome 还是 Edges 都是如此。卡顿后无法进行任何诸如滚动、点击等操作。

#### 截图

如图：
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/128051718/9025629d-a024-4129-a10c-e386c3516644)

链接：
https://blog.dwj601.cn/GPA/4th-term/MachineLearning/#2-1-%E7%BB%8F%E9%AA%8C%E8%AF%AF%E5%B7%AE%E4%B8%8E%E8%BF%87%E6%8B%9F%E5%90%88
#### 可能的原因推测
不知道是不是自己电脑的原因？还是因为页面内容过多导致卡顿的？还是别的原因？

**Comment by zkqiang** [comment]
我试了并不卡，这个是调用 html 动画，卡也是浏览器渲染问题
