### ISSUE TITLE
替换不安全的 StaticFile CDN

### ISSUE THREAD

**Issue by yzl3014** [fluid-dev/hexo-theme-fluid#1109]
[V2EX: Polyfill.io 和 bootcdn 和 staticfile CDN 被 uBlockOrigin 屏蔽，因疑似被攻击者控制。
](https://www.v2ex.com/t/1053497)

目前这两个CDN的网址已经被 uBlockOrigin 列入屏蔽清单： https://github.com/uBlockOrigin/uAssets/pull/24285

涉及到的网址：
https://github.com/fluid-dev/hexo-theme-fluid/blob/2ebdb345b7b058d591fbe5f411c849c0a461b93c/_config.yml#L1090

可以替换为 CDNJS： `https://cdnjs.cloudflare.com/ajax/libs/waline/2.15.8/`

另：使用 Waline 3.0.0 及以上版本，评论区无法显示。

**Comment by zhullyb** [comment]
cloudflare 在中国大陆访问质量差是老生常谈的问题，不知道有没有什么没有被屏蔽的公共 cdn 可用，眼下可能只能考虑使用境外的 cdn 顶一顶了

**Comment by zhullyb** [comment]
https://registry.npmmirror.com/@waline/client/^2/files/dist/waline.js
https://registry.npmmirror.com/@waline/client/^2/files/dist/waline.css

上述两个 url 可以被正常访问，且由 npmmirror 提供境内的 cdn 支持
唯一的缺点是没有提供 `.min.js` 和 `.min.css`，如果使用 npmmirror 的话需要更改此处的源码
https://github.com/fluid-dev/hexo-theme-fluid/blob/2ebdb345b7b058d591fbe5f411c849c0a461b93c/layout/_partials/comments/waline.ejs#L5-L6

**Comment by zhullyb** [comment]
> [https://registry.npmmirror.com/@waline/client/^2/files/dist/waline.js](https://registry.npmmirror.com/@waline/client/%5E2/files/dist/waline.js) [https://registry.npmmirror.com/@waline/client/^2/files/dist/waline.css](https://registry.npmmirror.com/@waline/client/%5E2/files/dist/waline.css)
> 
> 上述两个 url 可以被正常访问，且由 npmmirror 提供境内的 cdn 支持 唯一的缺点是没有提供 `.min.js` 和 `.min.css`，如果使用 npmmirror 的话需要更改此处的源码
> 
> https://github.com/fluid-dev/hexo-theme-fluid/blob/2ebdb345b7b058d591fbe5f411c849c0a461b93c/layout/_partials/comments/waline.ejs#L5-L6

鉴于 waline 在 npmjs.com 发布的 dist 目录中确实没有自带 `.min.js` 和 `.min.css`，我觉得删除源码中的 `.min` 字段也算合理？

**Comment by zkqiang** [comment]
> > [https://registry.npmmirror.com/@waline/client/^2/files/dist/waline.js](https://registry.npmmirror.com/@waline/client/%5E2/files/dist/waline.js) [https://registry.npmmirror.com/@waline/client/^2/files/dist/waline.css](https://registry.npmmirror.com/@waline/client/%5E2/files/dist/waline.css)
> > 上述两个 url 可以被正常访问，且由 npmmirror 提供境内的 cdn 支持 唯一的缺点是没有提供 `.min.js` 和 `.min.css`，如果使用 npmmirror 的话需要更改此处的源码
> > https://github.com/fluid-dev/hexo-theme-fluid/blob/2ebdb345b7b058d591fbe5f411c849c0a461b93c/layout/_partials/comments/waline.ejs#L5-L6
> 
> 鉴于 waline 在 npmjs.com 发布的 dist 目录中确实没有自带 `.min.js` 和 `.min.css`，我觉得删除源码中的 `.min` 字段也算合理？

感谢，采纳了这个提议

**Comment by limour-blog** [comment]
使用 Service Worker 间接实现了v3支持：
https://github.com/limour-blog/limour-blog.github.io/blob/main/source/sw.js

![](https://github.com/user-attachments/assets/825d0018-7485-43b5-b40f-e6a004a78cce)
