### ISSUE TITLE
为什么我的代码块会自己分隔开？

### ISSUE THREAD

**Issue by foresight100** [fluid-dev/hexo-theme-fluid#111]
<img width="538" alt="截屏2019-12-01上午9 41 10" src="https://user-images.githubusercontent.com/55917944/69908156-f332f980-141e-11ea-8946-4d7dddf987c2.png">
如图

**Comment by zkqiang** [comment]
少了必要的步骤，Hexo 配置里关闭默认的代码高亮
```yaml
highlight:
  enable: false
```
