### ISSUE TITLE
api获取subtitle想要获取到作者

### ISSUE THREAD

**Issue by 0478yhl** [fluid-dev/hexo-theme-fluid#1113]
#### 请描述该需求尝试解决的问题
我在使用这块功能的时候，
```bash
index:
  slogan:
    enable: true
    text: 这是一条 Slogan
    api:
      enable: false
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]
```
看代码（我不会改）貌似只取第一个key的value

我想实现显示subtitle和作者而不仅仅是subtitle。
例如 xxxxxxxxxx ----xxx

#### 请描述您认为可行的解决方案
加个subtitle的格式
我不知道我说的对不对，是否可以实现，还是我没用对呢😊

**Comment by zkqiang** [comment]
那只能获取的文本本身是这个格式，再去拼接就让这个功能太定制化了
