### ISSUE TITLE
长代码没有横向滚动条

### ISSUE THREAD

**Issue by Xwei1645** [fluid-dev/hexo-theme-fluid#1115]
如题所言。
较长的代码会“顶出格”
部署后的网页https://xwei1645.github.io/distribution/ttml-lyrics
![image](https://github.com/user-attachments/assets/1a849d8e-362d-4082-9f4f-82c1d22f3c52)
![image](https://github.com/user-attachments/assets/2f0cfe8e-939d-40a7-8408-aa736b47de5a)

**Comment by zkqiang** [comment]
自定义页面默认没有样式
https://hexo.fluid-dev.com/docs/guide/#%E5%88%9B%E5%BB%BA%E9%A1%B5%E9%9D%A2
