### ISSUE TITLE
更新了 markdown 渲染引擎后，图片显示异常

### ISSUE THREAD

**Issue by Hua-Wu-Que-Code** [fluid-dev/hexo-theme-fluid#1118]
![image](https://github.com/user-attachments/assets/4a06883f-15d0-450e-8e22-847922283d6e)
![image](https://github.com/user-attachments/assets/8684f989-1578-437e-981e-d652116c857a)
之前是可以正常显示的

**Comment by zkqiang** [comment]
但是更新渲染引擎和主题没啥关系吧，而且你这是图裂了，应该先看一下图片资源 url 对不对

**Comment by Hua-Wu-Que-Code** [comment]
> 但是更新渲染引擎和主题没啥关系吧，而且你这是图裂了，应该先看一下图片资源 url 对不对
不是啊，在 typora 中打开是没问题的

**Comment by zkqiang** [comment]
> 不是啊，在 typora 中打开是没问题的

你这句话我都不知道怎么回你，建议你再本地排排错，实在不行部署一个复现的页面发来看看，不然真不知道啥情况
