### ISSUE TITLE
分类页面没有导航栏，还有上方的文章统计数量应该是这一分类的总数量，而不是这一页的总数量

### ISSUE THREAD

**Issue by qingrongirwin** [fluid-dev/hexo-theme-fluid#112]
![17bf6f7ddf20f52e100eea1c75ff0bd](https://user-images.githubusercontent.com/45157131/70111112-2fb75d00-168c-11ea-8567-7ab791313870.png)
上图就是我的一个分类的分类页面，实际上我的文章已经是13篇了，而且本地的public文件夹里面的categories文件夹的page下也有第二页的index.html,也就是说缺一个导航栏

![b1befd2ae17476a119f5b846c49feeb](https://user-images.githubusercontent.com/45157131/70111115-347c1100-168c-11ea-8d76-d135e6449f74.png)
这是归档页面的，我希望分类页面也能像归档页面一样，谢谢

**Comment by zkqiang** [comment]
最新版已修复
