### ISSUE TITLE
主题是否与高版本hexo存在abbrlink插件不适配的问题？

### ISSUE THREAD

**Issue by AKmro** [fluid-dev/hexo-theme-fluid#1122]
#### Make sure
- [x] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] No solution found in [documentations](https://hexo.fluid-dev.com/docs/en/)

#### Describe the question

使用abbrlink插件（版本2.2.1）为文章生产永久链接，结果发现文章引用静态资源404。
查看静态资源URL是这种结构
`https://www.domian.com/test.webp`

注：文章URL是`https://www.domian.com/$abbrlink/`

正常静态资源URL是以下结构
`https://www.domian.com/$abbrlink/test.webp`                   
 注：$abbrlink 表示自定义URL结构

由于使用hexo 生成文章文件时，自动生成文章资源目录，然后把所有静态资源文件全部放到这个资源目录下，使用`![](test.webp)`的方式去引用。

以前使用hexo 5.4.0版本，使用最新主题则没有这个问题，由于版本太旧启动有很多警告，最近则换hexo 7版本，结果主题渲染后，发现文章图片全部404！

**Comment by zkqiang** [comment]
这个问题你应该反馈到 abbrlink 那里，和主题应该没关系
