### ISSUE TITLE
[Fluid] highlightjs style 'github' not found

### ISSUE THREAD

**Issue by Kuhbz** [fluid-dev/hexo-theme-fluid#1123]
我确认 highlight.js/styles/ 目录下有github.css文件，但是启动服务时仍然报错，更换成其他样式也不是，在配置文件中将highlightjs改为prismjs也会报同样的错误：
![image](https://github.com/user-attachments/assets/43e7afd0-0d97-4e72-a444-b7911586298e)

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/94049b2e6da5ae865f5cf7088f0c53917a6dc8bc/_config.yml#L57-L60

看报错信息，lib 指定错了
