### ISSUE TITLE
图片路径生成问题

### ISSUE THREAD

**Issue by FatWang1** [fluid-dev/hexo-theme-fluid#1134]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
本地图片无法展示，无论是本地调试还是github静态页面
简单分析可能是经过generate后生成的图片路径不太对
预期元素应该为:
`<img src="/img/assets.avif" alt="Terraform deployment workflow">`
但实际是
`<img src="/.io//assets.avif" alt="Terraform deployment workflow">`

**Comment by zkqiang** [comment]
这个你要看下 hexo 文档，应该不是主题的问题
