### ISSUE TITLE
waline评论区无法加载

### ISSUE THREAD

**Issue by ElfriedeMagdaleneHolger** [fluid-dev/hexo-theme-fluid#1136]
版本最新，按照教程作以下设置：
  comments:
    enable: true
    type: waline
waline:
  serverURL: 服务器地址最后未加“/”
  path: window.location.pathname
  meta: ['nick', 'mail', 'link']
  requiredMeta: ['nick']
  lang: 'zh-CN'
  emoji: ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
  dark: 'html[data-user-color-scheme="dark"]'
  wordLimit: 0
  pageSize: 10

目前hexo s的时候能加载评论区，但部署后则无法显示，调控制台结论：
![10a71e183054b4aac845240cfa0cc425](https://github.com/user-attachments/assets/2f83623c-b402-4ab2-af96-5051d287b3b0)

目前尝试了取消lazyload等方法都无法解决。

waline用的是vercel部署，绑定国内可访问域名，不知道是否与这个有关。

**Comment by zkqiang** [comment]
CORB 是服务设置问题，和主题无关
