### ISSUE TITLE
valine评论问题

### ISSUE THREAD

**Issue by sai31875515** [fluid-dev/hexo-theme-fluid#1140]
老哥问下为啥  配了这个配置serverURLs: https://rYcxfeAE.api.lncldglobal.com 不挂梯子就显示不出来评论。按理来说应该显示评论，只有挂了梯子就能访问
<img width="1173" alt="87411c43d8ffb82c0e288c487d049a1" src="https://github.com/user-attachments/assets/4e2baa47-5a1e-486d-9552-52388a712d0a">

**Comment by zkqiang** [comment]
应该是你 leancloud 用的是海外节点被墙了
