### ISSUE TITLE
希望正文文本能支持两端对齐

### ISSUE THREAD

**Issue by orphalese13** [fluid-dev/hexo-theme-fluid#1157]
不知道是我这个小白太菜，翻了一遍没找到在哪一段修改还是什么……总之正文段落不是两端对齐，换行多或者一行字数比较少的时候看着影响不大，但是段落一长就显得不大美观，右边参差不齐的。

很喜欢这个主题，只是这点对我这个经常写长文章的人不太友好。（之前用NexT主题的时候默认会两端对齐，就没关注。）

**Comment by zkqiang** [comment]
这个和字体有关，可以从字体 css 方面了解一下如何解决
