### ISSUE TITLE
文章目录支持 markdown 数学公式

### ISSUE THREAD

**Issue by physnya** [fluid-dev/hexo-theme-fluid#1159]
#### 如是功能需求，请确定符合以下情况
- [ ✓ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [ ✓ ] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

文章侧边栏目录不支持 markdown 的数学公式，具体情况如图：
![示例](https://github.com/user-attachments/assets/230411d9-4cbb-4ed8-acb6-41e5e1104178)

#### 请描述您认为可行的解决方案

或许可以通过将 katex 的 js 引入这个位置的方式？

#### 考虑过的替代方案

尽量不在目录中使用数学公式……但是不太可能完全不用。

**Comment by zkqiang** [comment]
从设计上这不太可能支持，不然前端样式完全不可控了
