### ISSUE TITLE
求问打字机怎么做到每个页面打不同的字的

### ISSUE THREAD

**Issue by evpeople** [fluid-dev/hexo-theme-fluid#118]
我成功更改了首页的打字机内容，但没有找到其他页面更改的地方，是我太白了嘛🤣🤣🤣。
尝试把 slogan:  # 首页副标题的独立设置
    enable: true  # 为 false 则不显示任何内容
    text: # 为空则按 hexo config.subtitle 显示
复制粘贴归档页，分类归档页，没有效果

**Comment by evpeople** [comment]
我试了一下，好像是每个页面可以打出两个字？

**Comment by evpeople** [comment]
我又试了一下，似乎是不能更改的吗

**Comment by zkqiang** [comment]
slogan只对首页有效。
如果想更改的话，可以修改 /fuild/languages 里对应的语言文件（虽然不建议这样走）
