### ISSUE TITLE
博客标题栏能不能加头像

### ISSUE THREAD

**Issue by ISPZ** [fluid-dev/hexo-theme-fluid#120]
可不可以在博客标题栏的左边加一个头像框（添加图片，图标都可以）
![](https://user-images.githubusercontent.com/40906222/70760737-93751080-1d85-11ea-8e39-af3917275de4.png)
![](https://user-images.githubusercontent.com/40906222/70760747-9b34b500-1d85-11ea-882a-e19ef453344f.png)

**Comment by zkqiang** [comment]
参考[这条改动](https://github.com/fluid-dev/hexo-theme-fluid/commit/136e7f93acd87e6a4d8b6dca00d628befc26a504#diff-03376c6b39207233b76044165107e7f7R4) 或者更新 master 代码 

然后在 blog_title 里直接加入 <img> 标签来增加图片
