### ISSUE TITLE
诚邀合作事宜

### ISSUE THREAD

**Issue by zhennann** [fluid-dev/hexo-theme-fluid#123]
很喜欢你博客的风格，可否为Cabloy-CMS开发一套（免费/付费）主题，然后发布到Cabloy商店里面？

CabloyJS：是一款顶级NodeJS全栈业务开发框架, 基于KoaJS + EggJS + VueJS + Framework7 
Cabloy-CMS：是基于CabloyJS全栈业务开发框架开发的动静结合的CMS，可以快速构建企业网站、博客、社区、商城等Web应用
Cabloy商店：包括品类广泛的各类模块，满足不同场景的开发需求

CabloyJS介绍：https://cabloy.com/zh-cn/articles/introduce.html
Cabloy-CMS介绍：https://cabloy.com/zh-cn/articles/cms-introduce.html

Cabloy商店运营模式：https://cabloy.com/zh-cn/articles/store.html

**Comment by zkqiang** [comment]
感谢邀约，目前开发组成员都比较忙，有时间一定考虑参与

**Comment by zhennann** [comment]
感谢回复
