### ISSUE TITLE
lazyload 的策略貌似有点保守

### ISSUE THREAD

**Issue by huaxianyan** [fluid-dev/hexo-theme-fluid#124]
我在本地预览的时候，就正常的浏览速度，也会发现经常看到 Loading 图，能否能够激进一些呢？

在这个想法之上，不知道设置项里是否支持加入 lazyload 相关配置参数，手动设置提前加载的参数？顺便再加个参数自定义 loading 图？

其实感觉 Front-matter 加入 lazyload 的参数控制本篇是否使用 lazyload 也还不错，不过这个实用性感觉不是特别高。

**Comment by zkqiang** [comment]
lazyload 主要是为了减缓小水管的压力，目前策略是会提前半屏高度进行加载
建议带宽充足的就不要开这个功能了... 

后续会加入一些相关配置

**Comment by huaxianyan** [comment]
@zkqiang 我觉得这个功能还是有一定的受众群体的，毕竟国内的机器带宽贵流量也贵

我本来就关闭这个功能的，但是前段时间国外机器访问不顺把站点移回国内，即使加了 CDN 也会出现图过多的文章前面的资源不能秒载的情况，才考虑到使用 lazyload

**Comment by zkqiang** [comment]
@huaxianyan  https://github.com/fluid-dev/hexo-theme-fluid/commit/36da050917a5d0964845258985a06b912b679236 先把策略再提高一倍，试试看效果

**Comment by huaxianyan** [comment]
@zkqiang 好了很多，看来体感差异主要来自于节流函数的延迟设置
