### ISSUE TITLE
能否添加支持导航菜单栏图标字体？

### ISSUE THREAD

**Issue by AKmro** [fluid-dev/hexo-theme-fluid#129]
在站点配置文件和nav.ejs想添加菜单图标字体均失败（前端小白）！这个主题用的图标字体是font-awesome，但是我想要的图标字体font-awesome是没有，想导入[icofont](https://icofont.com/)图标字体又出现各种引用问题！

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/commit/08bd64894253f513d04afb62d9d4d6ec0db0da0a  增加自定义 HTML 配置，可用于引入外部 css
