### ISSUE TITLE
首页音乐播放器……

### ISSUE THREAD

**Issue by SuYouge** [fluid-dev/hexo-theme-fluid#131]
想知道有没有什么办法加一个首页的音乐播放器……
想求一个思路……
看了几页issue感觉没人问这个问题 (

**Comment by zkqiang** [comment]
Step 1: 网页版云音乐里点下图红框处（不过很多歌有版权不能生成）
![image](https://user-images.githubusercontent.com/32983588/72229642-20acbe80-35eb-11ea-9d12-e5da130773f1.png)

Step 2: 将代码插入 `layout.ejs` 里或其他页面，并自行添加 css 定位位置（如果是歌单，可以替换为歌单ID，然后 type=0）
![image](https://user-images.githubusercontent.com/32983588/72229879-c280db00-35ec-11ea-9d29-1c198c5bc578.png)

不建议在网页加入音乐并设置为自动播放，突然的声音容易给别人造成烦恼

**Comment by SuYouge** [comment]
谢谢 我来试一试
