### ISSUE TITLE
怎样添加上一篇、下一篇功能

### ISSUE THREAD

**Issue by larva2333** [fluid-dev/hexo-theme-fluid#133]

**Comment by zkqiang** [comment]
暂时不支持

**Comment by QiQiWan** [comment]
可以的，详询<a href='eatrice.top'>吃白饭的休伯利安号</a>

**Comment by 0x2E** [comment]
更新到 master 即可用 [f478490](https://github.com/fluid-dev/hexo-theme-fluid/commit/f47849021bd8db73ce2d52db7fb704c6e5bdb276)
