### ISSUE TITLE
Fontawesome icon on about page issues

### ISSUE THREAD

**Issue by erotavlas** [fluid-dev/hexo-theme-fluid#136]
1 - Icons do not appear to be centred correctly.  It is shifted slightly to the left. Very noticeable when there is only one icon.

2 - comments direct to this url https://fontawesome.com/v4.7.0/icons/ , however some of those icons don't work, and I had to go to the latest version https://fontawesome.com/ to get the working icons. (for example fa-linkedin-square no longer available has been replaced by fa-linkedin.

**Comment by 0x2E** [comment]
Thanks for feedback, fixed.
