### ISSUE TITLE
建议添加mermaid支持

### ISSUE THREAD

**Issue by lancerXXXX** [fluid-dev/hexo-theme-fluid#138]
我下载了mermaid的插件
按照文档进行了配置
但是有问题
用旧版edge 会看到流程图被渲染出来了 但是一秒之后就会不见 就剩下空白的代码块的黑框
F12 看到应该是渲染出来了 但是看不到
用新版edge 看的话 连 那一秒也看不到 就直接是空白的代码块的黑框

**Comment by 0x2E** [comment]
你好，发个链接看一下

**Comment by lancerXXXX** [comment]
https://github.com/webappdevelp/hexo-filter-mermaid-diagrams

**Comment by 0x2E** [comment]
我这里用你的[博客](https://lancerxxxx.github.io/2020/02/04/%E8%BD%AF%E4%BB%B6%E5%B7%A5%E7%A8%8B/%E8%BD%AF%E4%BB%B6%E5%B7%A5%E7%A8%8B%E6%A6%82%E8%BF%B0/)没能复现出这个问题。

旧版edge：
![旧edge](https://user-images.githubusercontent.com/29594728/73809425-37bb8680-480e-11ea-92b0-85fd0a559302.png)

新版edge：
![新版](https://user-images.githubusercontent.com/29594728/73809442-44d87580-480e-11ea-9572-bc8bbb7deb66.png)

**Comment by lancerXXXX** [comment]
![image](https://user-images.githubusercontent.com/42160297/73810929-ff6a7700-4812-11ea-8d89-98af1a77bdd3.png)
myblog\themes\fluid\layout\_partial\footer.ejs
这个是按照他的文档要在这里加东西
![image](https://user-images.githubusercontent.com/42160297/73811039-4a848a00-4813-11ea-9034-b099e65a344b.png)
![image](https://user-images.githubusercontent.com/42160297/73811053-51130180-4813-11ea-8b22-a596380d9c8c.png)
然后我试着在这几个位置加了他让加的那段代码
![image](https://user-images.githubusercontent.com/42160297/73811159-b4049880-4813-11ea-83e3-4f58046ddf9b.png)
但是都不好用
![image](https://user-images.githubusercontent.com/42160297/73811125-98998d80-4813-11ea-84cb-3b789ce8c83c.png)
我就全删了只留这段代码,然后是好用的

我不知道改怎么整才是正确的

**Comment by yrpang** [comment]
我也尝试按照`mermaid `的文档说明添加了一下，发现如果hexo自带的`highlight`功能可以正常显示，使用主题提供的`highlight`会报错`<svg> attribute viewBox: Expected number, "0 0 -Infinity -Infin…`

**Comment by zkqiang** [comment]
@lancerXXXX @yrpang 

[develop 分支](https://github.com/fluid-dev/hexo-theme-fluid/tree/develop) 已更新支持，诚邀测试使用

**Comment by lancerXXXX** [comment]
![image](https://user-images.githubusercontent.com/42160297/77850650-8b42c300-7206-11ea-9959-c3b02b778163.png)
饼图在本地显示
![image](https://user-images.githubusercontent.com/42160297/77850659-9b5aa280-7206-11ea-9e5a-f6dbbea23197.png)
博客上不显示
![image](https://user-images.githubusercontent.com/42160297/77850710-de1c7a80-7206-11ea-87eb-41631662e502.png)
状态图在本地显示
![image](https://user-images.githubusercontent.com/42160297/77850718-ebd20000-7206-11ea-986e-6a74c7842ccc.png)
博客上没有显示
![image](https://user-images.githubusercontent.com/42160297/77850616-50408f80-7206-11ea-84ae-e86747aa60ce.png)
类图在本地显示
![image](https://user-images.githubusercontent.com/42160297/77850628-63535f80-7206-11ea-9a3e-cbfdaab68b88.png)
博客上没有显示有问题
我平时只用甘特和流程图
其他的语法不太熟悉
是语法有些不同嘛
其他正常
![image](https://user-images.githubusercontent.com/42160297/77850735-04421a80-7207-11ea-9f5e-ec2f181e869e.png)
![image](https://user-images.githubusercontent.com/42160297/77850741-0906ce80-7207-11ea-8e2f-03b4ad56a222.png)
![image](https://user-images.githubusercontent.com/42160297/77850744-0c9a5580-7207-11ea-94e2-f1fe7292eb75.png)
![image](https://user-images.githubusercontent.com/42160297/77850748-10c67300-7207-11ea-9dba-cece9c39a2b7.png)

**Comment by zkqiang** [comment]
已解决，不再需要插件了（插件有问题）

**Comment by lancerXXXX** [comment]
今天才有时间试了一下, 很好 👍
