### ISSUE TITLE
How to enable image beside post on the Home page?

### ISSUE THREAD

**Issue by erotavlas** [fluid-dev/hexo-theme-fluid#140]
Hello, How do you enable the images beside posts that are listed on the Home page?
Thank you.

**Comment by zkqiang** [comment]
Add `index_img` in the [front matter](https://hexo.io/docs/front-matter.html)

**Comment by erotavlas** [comment]
Hello, thanks for the quick reply, but it did not work.  In the _config.yml when I enable post asset folder

`post_asset_folder: true`

And create a new post using `hexo new "test"

I place an image in the _post/test/folder.

<img width="296" alt="Screen Shot 2020-02-09 at 11 06 45 AM" src="https://user-images.githubusercontent.com/10454265/74105494-4bc3f880-4b2c-11ea-9f88-dd70a2d64334.png">

I set my post markdown like this

```
---
title: test
date: 2020-02-09 10:54:29
tags:
banner_img: cpu.jpg
index_img: cpu.jpg
---
```

However only the banner image shows up when I enter the post.  The Index page shows a loading animation where the image should be 

<img width="639" alt="Screen Shot 2020-02-09 at 11 05 49 AM" src="https://user-images.githubusercontent.com/10454265/74105486-3353de00-4b2c-11ea-9245-058dc5f4a8fa.png">

It only works if I place and reference the image from the `/themes/fluid/source/img` folder like 

`index_img: /img/cpu.jpg`

**Comment by zkqiang** [comment]
@erotavlas You can try to set `index_img: /cpu.jpg`

**Comment by zkqiang** [comment]
@erotavlas 
Sorry, you can't set `index_img: cpu.jpg`
Because in the index page, the relative path is `/cpu.jpg`, not `/post/test/cpu.jpg`.
So `index_img` is not support `post_asset_folder`
