### ISSUE TITLE
menu菜单先出现滚动条完全打开后不见

### ISSUE THREAD

**Issue by aolog** [fluid-dev/hexo-theme-fluid#142]
### 这是你的网站
![a](https://user-images.githubusercontent.com/48140334/74319067-4e874d80-4db9-11ea-8dd8-bdb6fd767386.jpg)
### 这是我下载最新的直接复制进去的
![b](https://user-images.githubusercontent.com/48140334/74319073-50e9a780-4db9-11ea-81a8-1901607e05c3.jpg)
### 完全打开后又不见了
![c](https://user-images.githubusercontent.com/48140334/74319083-53e49800-4db9-11ea-9024-7a2f48cc1217.jpg)

**Comment by 0x2E** [comment]
你好，从来没遇到过这问题，浏览器和版本说一下。

**Comment by zkqiang** [comment]
我的博客就是最新代码，如果你浏览没问题，那可能是别的原因
最好你能部署一下，给我们访问看看，方便找原因

**Comment by aolog** [comment]
### Microsoft Edge
版本 80.0.361.50 (官方内部版本) (64 位)
### [部署在GitHub](https://aolog.github.io)

**Comment by aolog** [comment]
又可以了，谢谢大佬

**Comment by aolog** [comment]
### 为文章内容中的标题添加锚图标设置为一直可见没有效果
![234055](https://user-images.githubusercontent.com/48140334/74590817-efda0200-504c-11ea-8b5f-73bde718b11b.jpg)
![image](https://user-images.githubusercontent.com/48140334/74590812-e3ee4000-504c-11ea-9d7e-7b621d5ac1b7.png)

**Comment by zkqiang** [comment]
@aolog 
该处的注释有误，新版本已经修改

正确注释：默认悬浮显示，可选：always（一直显示） |  touch（移动端触摸显示）

**Comment by aolog** [comment]
新版注释：一会显示，错别字

**Comment by 0x2E** [comment]
@aolog :ok_hand:

**Comment by aolog** [comment]
新发现，在ie浏览器中样式显示错误
![172654](https://user-images.githubusercontent.com/48140334/74640582-bd461b80-51aa-11ea-827d-9365f909b403.jpg)
只要删了
`<div class="container text-center white-text fadeInUp">`中的 `container`就能正常居中，删了后其它浏览器显示正常。但是那个向下滚动的箭头还是不能居中
![172004](https://user-images.githubusercontent.com/48140334/74641421-3bef8880-51ac-11ea-9a31-d2bf25467b41.jpg)
另一个发现，点搜索后nav栏向左移，它自动向nav添加一个右内边距，关搜索弹框会自动删掉，
![image](https://user-images.githubusercontent.com/48140334/74645071-3eed7780-51b2-11ea-8f50-3f13c83d8488.png)
![image](https://user-images.githubusercontent.com/48140334/74645135-53317480-51b2-11ea-9544-d313c3e8c3e7.png)

**Comment by 0x2E** [comment]
暂不考虑兼容 ie，请使用现代浏览器。
