### ISSUE TITLE
使用了permalink之后，懒加载的gif无法使用了

### ISSUE THREAD

**Issue by DefectingCat** [fluid-dev/hexo-theme-fluid#143]
hexo: 4.2.0，给文章配置了permalink之后，它把文章内的所有图片都加上了permalink的前缀。

例如，我配置了`permalink: /defect/url.html`，图片放在`/images/postname/`下。
然后文章内的图片都会变成:
```
http://11.16.0.223/defect/images/postname/2874899693.png
```
为了图片能正常显示，我只能把图片都挪到`defect`文件夹内。

但是在之前我将主题的配置所需要的图片都转移到和文章的图片一起了。
也就是说，那张gif现在在`defect`的文件夹内：
```
/defect/images/img/loading.gif
```

这时候我就遇到了如标题所说的，在生成静态文件之后，那张gif的路径依然是：
```
/img/loading.gif
```
路径不对导致无法显示

总结就是：gif被移动位置了，而生成了之后还是指向默认的路径，导致的无法显示。（~~当然permalink是影响移动图片位置的主要动机~~）

如果是意料之外的问题，我的建议就是直接在配置文件中可以配置它的路径，就和其他的图片一样。

**Comment by zkqiang** [comment]
如果你更换了资源图片的位置，那么不要忘记修改 [internal_img](https://github.com/fluid-dev/hexo-theme-fluid/blob/170df417964cf074dc36bd270182674d73c6fa70/_static_prefix.yml#L28)

**Comment by DefectingCat** [comment]
感谢，已经解决
另外，主题很棒❤
