### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by 23R3F** [fluid-dev/hexo-theme-fluid#144]
1.建议在每个文章页面中添加上一篇文章和下一篇文章的按钮
2.建议修复一下gittalk无法自动初始化评论区的问题，只能一篇篇手点也太麻烦了
3.建议增加友情链接的功能

**Comment by 0x2E** [comment]
感谢建议。
1，3点会放在v2.0实现。第三点gitalk本身没这功能，请自行实现（可以写个脚本放在github actions里）。主题也支持utterances评论，它是有个bot可以自动创建issue的。
