### ISSUE TITLE
icon图标能否自定义？

### ISSUE THREAD

**Issue by isboyjc** [fluid-dev/hexo-theme-fluid#145]
除支持fontawesome图标外，可否自定义图标或是支持iconfont图标

**Comment by zkqiang** [comment]
暂时不支持，后续会加入

**Comment by isboyjc** [comment]
ok

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/commit/08bd64894253f513d04afb62d9d4d6ec0db0da0a  增加自定义 HTML 配置，可用于引入外部 css
