### ISSUE TITLE
建议加上默认的index_img配置

### ISSUE THREAD

**Issue by MujeyF** [fluid-dev/hexo-theme-fluid#153]
```ejs
  <% if(post.index_img == null) { %>
  <div class="col-12 col-md-4 m-auto">
    <a href="<%- post_url %>" target="<%- theme.index.post_url_target %>">
      <img src="/img/index/default.jpg" alt="--" class="index-img img-fluid rounded index-thumbnails">
    </a>
  </div>
  <% } %>
```

**Comment by 0x2E** [comment]
你好，感谢建议，但没有设置默认图是故意为之。因为有些同学喜欢简洁的文章列表，所以我们把略缩图、摘要、文章元信息部分都做了限制，让使用者自定义想显示的部分。

**Comment by MujeyF** [comment]
好的👌 希望还博客项目发展的原来越好哦 这是我的博客&nbsp;https://mujeyf.cn/&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Rook1e <notifications@github.com&gt;
发送时间: 2020年2月23日 21:16
收件人: fluid-dev/hexo-theme-fluid <hexo-theme-fluid@noreply.github.com&gt;
抄送: MujeyF <miaojief@foxmail.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[fluid-dev/hexo-theme-fluid] 建议加上默认的index_img配置 (#153)

**Comment by 0x2E** [comment]
感谢对 fluid 的认可 :smile:
