### ISSUE TITLE
[Bug反馈] 在Front-matter编写category或者tag后，解析名称并赋予地址的方式不统一

### ISSUE THREAD

**Issue by Harvey-W** [fluid-dev/hexo-theme-fluid#156]
例如：
```
category: [what's new]
```
在导航栏的category页面点击what's new会被识别为https://.../categories/what-s-new/，并以此建立了what-s-new文件夹
但是若在Home页面直接点击文章的what's new则会被识别为https://.../categories/what's%20new/，从而404 not found

**Comment by 0x2E** [comment]
PR #150 已修复，着急的话可以先用 develop 分支。
