### ISSUE TITLE
能否增加一个文章最后更新时间?

### ISSUE THREAD

**Issue by yikakia** [fluid-dev/hexo-theme-fluid#162]
可以通过在文章的开头这样增加一个update项如下

title: 文章标题
tags: [Hexo, Fluid]
index_img: /img/example.jpg
banner_img: /img/post_banner.jpg
date: 2019-10-10 10:00:00
update: 2019-12-12 12:12:12

在文章的上面显示文章的最后更新时间。

当然更好的方案就是直接根据文件的最后编辑时间生成。

**Comment by 0x2E** [comment]
正在做，还没找到合适的显示位置。

**Comment by zkqiang** [comment]
@0x2E 让用户自定义选择吧，在同一个位置显示：手动填写 date ，或者自动获取更新时间

**Comment by yikakia** [comment]
![Snipaste_2020-03-02_13-30-21.png](https://i.loli.net/2020/03/02/pRTglbjQZqG78B1.png)
放在文章的开头感觉也可以，就像这样
