### ISSUE TITLE
对hexo原生的Tag Plugins的支持情况和自定义tags plugins的支持

### ISSUE THREAD

**Issue by demostars** [fluid-dev/hexo-theme-fluid#163]
问题1，在使用过程中，按照hexo官方说明，在markdown中使用tag plugins，如blockquote 无效
https://hexo.io/zh-cn/docs/tag-plugins#Pull-Quote

问题2，是否可以考虑增加自定义md中的tags的功能？如next的一系列tags还是很不错的，或者说能否开放自定义？
https://theme-next.org/docs/tag-plugins/#Centered-Quote

感谢~

**Comment by Royce2019** [comment]
> 问题2，是否可以考虑增加自定义md中的tags的功能？如next的一系列tags还是很不错的，或者说能否开放自定义？
> https://theme-next.org/docs/tag-plugins/#Centered-Quote

目前可使用html代码编写类似next主题的tags，就像文章底部的版权声明那样
`<p class="note note-success">xxxxx</p>`
类似这样的，note和note-xxx样式也可在自定义文件夹中修改样式

**Comment by zkqiang** [comment]
问题1，可能是你使用了 LaTeX 的 renderer 导致的，Hexo 默认的 renderer 是可以的，如下：

![image](https://user-images.githubusercontent.com/32983588/78115347-43ee4980-7435-11ea-93f3-1520a3dc26fb.png)

问题2，可以通过插件实现，有很多插件可以实现，内置有些冗余了，暂时不会添加
