### ISSUE TITLE
lazyload可能存在的问题

### ISSUE THREAD

**Issue by Royce2019** [fluid-dev/hexo-theme-fluid#166]
因为lazyload的图片是441x291的
对于一些方形图可能会出问题
比如about界面的的头像，显示lazyload的时候很明显是变形的
然后还有几次碰到过一张图片在lazyload的时候变形了，加载出来还是变形的
不知道这个和懒加载有没有关系
能不能自动根据图片大小来调整

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/commit/5621f7f653d5c15e387ad6f039f386501f4ec505  已解决
