### ISSUE TITLE
valine字体颜色如何修改

### ISSUE THREAD

**Issue by lil-q** [fluid-dev/hexo-theme-fluid#167]
请问valine字体颜色如何修改，由于用深色背景，字体看不清楚了

**Comment by zkqiang** [comment]
可使用最新版本 [自定义CSS](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html) 功能修改任何样式

**Comment by lil-q** [comment]
非常感谢！

> 可使用最新版本 [自定义CSS](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html) 功能修改任何样式
