### ISSUE TITLE
可否增加时光机功能

### ISSUE THREAD

**Issue by Royce2019** [fluid-dev/hexo-theme-fluid#169]
就相当于自己发动态那样
一个只有评论系统的页面，只能自己能发表，就像图片里的那样
https://i.loli.net/2020/03/07/Et8F3TmyVMg7duN.png
![Snipaste_03-07_14-41-04.png](https://i.loli.net/2020/03/07/Et8F3TmyVMg7duN.png)

**Comment by zkqiang** [comment]
这个自己实现吧....

**Comment by Royce2019** [comment]
> 这个自己实现吧....

咋这么快就回复了(;´༎ຶД༎ຶ`)

**Comment by congjinyebaiya** [comment]
楼主可以看看这个博客[](https://shenshilei1022.gitee.io/)，虽然不是同一个主题，但是实现了这样的功能

**Comment by congjinyebaiya** [comment]
楼主可以看看这个博客，虽然主题不一样，但是实现了你所说的这个功能[](https://shenshilei1022.gitee.io/)

**Comment by congjinyebaiya** [comment]
[](https://shenshilei1022.gitee.io/)

**Comment by JalenChuh** [comment]
嗯，谢谢，我已经在用这个了 https://blog.jalenchuh.cn/artitalk
