### ISSUE TITLE
lazyload的onlypost在自定义页面失效

### ISSUE THREAD

**Issue by Royce2019** [fluid-dev/hexo-theme-fluid#180]
能不能顺便再给首页index_img，友链界面和关于页也加个开关

**Comment by 0x2E** [comment]
没看懂你描述的是什么意思

**Comment by Royce2019** [comment]
> 没看懂你描述的是什么意思

配置文件里lazyload有个onlypost是让懒加载只在文章页中使用，我开开之后发现自定义页面也会使用懒加载。然后希望能给不同的界面都加一个类似这样的开关，让使用者自己选择这类界面需不需要使用懒加载

**Comment by 0x2E** [comment]
明白了，再研究

**Comment by Royce2019** [comment]
谢谢

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/commit/2e7de750bf14939505b7f30f1112e620f140e98b
