### ISSUE TITLE
友链页面的头像有时会变形

### ISSUE THREAD

**Issue by Longhorn3683** [fluid-dev/hexo-theme-fluid#183]

**Comment by zkqiang** [comment]
是否为最新版本

**Comment by Longhorn3683** [comment]
> 
> 
> 是否为最新版本

1.7.2

**Comment by Longhorn3683** [comment]
> 
> 
> 是否为最新版本

已经是1.7.3了

**Comment by zkqiang** [comment]
最新版本理论上不存在此问题，因为图片已经是`object-fit: cover`，可能是CDN 缓存 等其他问题

**Comment by Longhorn3683** [comment]
> 
> 
> 最新版本理论上不存在此问题，因为图片已经是`object-fit: cover`，可能是CDN 缓存 等其他问题

头像有时会变成胶囊状，但是缩小放大之后就正常

**Comment by zkqiang** [comment]
浏览器是什么？
然后看下头像的 CSS 里 `object-fit: cover` 是否存在

**Comment by Longhorn3683** [comment]
> 
> 
> 浏览器是什么？
> 然后看下头像的 CSS 里 `object-fit: cover` 是否存在

浏览器是Firefox 74.0，头像有object-fit: cover

**Comment by zkqiang** [comment]
我用 Firefox 74.0 没有复现出来，可能是别的原因，建议清除缓存或更换浏览器试试

**Comment by Longhorn3683** [comment]
> 
> 
> 我用 Firefox 74.0 没有复现出来，可能是别的原因，建议清除缓存或更换浏览器试试

试过了，还是不行

**Comment by zkqiang** [comment]
那可以尝试自己解决一下，因为我这边实在复现不出来

**Comment by toastsgithub** [comment]
> 试过了，还是不行

有可以访问的demo吗

**Comment by Longhorn3683** [comment]
> 
> 
> > 试过了，还是不行
> 
> 有可以访问的demo吗

longhorn3683.github.io

**Comment by Royce2019** [comment]
> > > 试过了，还是不行
> > 
> > 
> > 有可以访问的demo吗
> 
> longhorn3683.github.io

这个问题我也出现过，后面发现问题是出在 `links.ejs` ，你可以看看那边是不是哪里写错了

**Comment by Longhorn3683** [comment]
> links.ejs

links.ejs没有动过

**Comment by Longhorn3683** [comment]
> 
> 
> > > > 试过了，还是不行
> > > 
> > > 
> > > 有可以访问的demo吗
> > 
> > 
> > longhorn3683.github.io
> 
> 这个问题我也出现过，后面发现问题是出在 `links.ejs` ，你可以看看那边是不是哪里写错了

links.ejs没有动过

**Comment by zkqiang** [comment]
如果有其他用户有类似问题，可提供更多线索

**Comment by zkqiang** [comment]
更新 [v1.7.4](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.7.4) 试一下

**Comment by Longhorn3683** [comment]
> 
> 
> 更新 [v1.7.4](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.7.4) 试一下

更新之后还是一样

**Comment by zkqiang** [comment]
最新修改一次  https://github.com/fluid-dev/hexo-theme-fluid/commit/c8e64763902fc679dfe22c586dfa1793976153d2找群友测试没问题

**Comment by Longhorn3683** [comment]
> 
> 
> 最新修改一次 [c8e6476](https://github.com/fluid-dev/hexo-theme-fluid/commit/c8e64763902fc679dfe22c586dfa1793976153d2) 找群友测试没问题，你可以在 develop 分支下载试下

我试试

**Comment by Longhorn3683** [comment]
> 
> 
> 最新修改一次 [c8e6476](https://github.com/fluid-dev/hexo-theme-fluid/commit/c8e64763902fc679dfe22c586dfa1793976153d2) 找群友测试没问题，你可以在 develop 分支下载试下

没有问题了😂👍

**Comment by zkqiang** [comment]
> 没有问题了😂👍
留下了感动的泪水...
