### ISSUE TITLE
升级主题的时候 ，是不是_config.yml 要重写，感觉有大量的设置阿 

### ISSUE THREAD

**Issue by huanx9** [fluid-dev/hexo-theme-fluid#185]
我现在是1.7.2  如果要升级到1.7.4     可以保留_config.yml 升级吗？

**Comment by 0x2E** [comment]
https://hexo.fluid-dev.com/docs/guide/#%E8%A6%86%E7%9B%96%E9%85%8D%E7%BD%AE

**Comment by huanx9** [comment]
我按照文档 确实大部分设置都转移过来了。。 

#introduce: info / info / info # 支持 HTML
  #icons: # 更多图标可从 https://fontawesome.com/v5.10.0/icons?d=gallery 查找，并以 "图标名: url" 的格式添加在下方
    #"fab fa-github": https://github.com
    #"fab fa-twitter": https://twitter.com
    #"fab fa-weixin qrcode":  # 添加 qrcode 后，点击不再跳转，而是悬浮二维码，因此值需要是二维码图片地址

但是
我已经屏蔽了这部分。。为什么没有跟随 _date里面的 config

**Comment by zkqiang** [comment]
应该是设为空，而不是注释掉，不然就起不到覆盖的作用

```yaml
introduce:   # 空值
icons:   # 空值
```

**Comment by huanx9** [comment]
感谢开发者
