### ISSUE TITLE
mathjax 渲染部分公式的时候出现样式问题

### ISSUE THREAD

**Issue by Macr0phag3** [fluid-dev/hexo-theme-fluid#192]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [x] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述
用 mathjax 渲染部分公式的时候出现样式问题。

浏览器: Chrome，Firefox，Safari

#### 复现步骤

Bug 在线示例：
https://www.tr0y.wang/2017/11/06/CTFRSA/#%E4%BB%8B%E7%BB%8D-7

示例 tex：

`d<\frac{1}{3}n^\frac{1}{4}`

正确的样式：
![image](https://user-images.githubusercontent.com/20874963/77825266-1a86a280-7143-11ea-9c59-ae0ec741ce81.png)

主题渲染的样式：

![image](https://user-images.githubusercontent.com/20874963/77825278-28d4be80-7143-11ea-9094-96b6fa9bc4c9.png)

配置文件如下：
![image](https://user-images.githubusercontent.com/20874963/77825296-42760600-7143-11ea-8e8a-36dbd180c9a4.png)

且已经按照教程卸载原有渲染器：
`npm uninstall hexo-renderer-marked --save`

然后更换渲染器：
`mathjax: npm install hexo-renderer-kramed --save`

**Comment by Royce2019** [comment]
不如换成katex试试，我这katex没问题

**Comment by zkqiang** [comment]
试一下 master 分支是否解决这个问题，昨天有人刚 PR 修复了一下

**Comment by Macr0phag3** [comment]
@Royce2019 @zkqiang 
补丁测试通过，问题已解决

**Comment by zkqiang** [comment]
感谢测试
