### ISSUE TITLE
更新了之后，部分插入图片发生了问题

### ISSUE THREAD

**Issue by huaxianyan** [fluid-dev/hexo-theme-fluid#193]
以前有一些过高的图片，会通过 ``<img src="/images/AAA/BB.jpg" width="57%">`` 这样的方式来缩放图片以取得比较不错的整体观感，这个方法在主题以前的版本也能够良好运作。

但是在更新 1.7.4 之后，使用这种方法插入的图片不会自动居中，图片附近也没有阴影，图片和上下文的间隙也特别近，感觉就没有当成图片去处理了，我没开启懒加载不确定是否会影响懒加载。

不知道开发者有没有让主题本身支持图片缩放特性，比如 ``![](/images/AAA/BB.jpg?57)`` 直接按 57 缩放，毕竟如果处理原图让它合适，点大了看就会劣化，不可兼得。

目前是暂时对所有该方法插入的图片外面括 ``<center></center>``，并在后面跟上 ``</br>``。主要之前用了很长时间，突然一下子不能用了，所有文章都改了一遍还是挺累的。

万分希望开发者能确立一套标准。

**Comment by zkqiang** [comment]
如果你是指文章中的图片，这是后来特意修改的，因为这样可以和 markdown 中 `![](/images/a.jpg)` 的样式区分开，也就是使用 `<img>` 是没有样式的，这样方便插入一些小图片不受居中等 md 样式的影响。

如果非要使用的话，可以使用 `<p><img src=....' /></p>` 这种格式，因为这种格式才是 md 转换过来的结构。

至于 `![](/images/AAA/BB.jpg?57)` 这种，这个可以后边扩展一下这个功能

**Comment by huaxianyan** [comment]
@zkqiang 感谢解惑及解决方案，十分期待扩展的功能

另外还有个小问题虽然和本次 issue 无关，但是因为不太大就不单独开了，在此顺便询问一下：

valine 评论系统能否则增加下 guest_info 支持？我在配置中手动添加这条无效

**Comment by zkqiang** [comment]
这个目前是写死了，那下个版本把它改到配置项里
