### ISSUE TITLE
当web_analytics中的tencent全设置为空时，博客中仍然会出现对tencent analytics的js引用

### ISSUE THREAD

**Issue by DreamWalkerXZ** [fluid-dev/hexo-theme-fluid#194]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [x] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述
当web_analytics中的tencent全设置为空时，博客中仍然会出现对tencent analytics的js引用

浏览器: Chrome 80.0.3987.149（正式版本） （64 位）

#### 复现步骤 && 截图
![配置](https://i.loli.net/2020/03/30/SqGRsrUXPWwcTDH.png)

![浏览器中查看网页源代码](https://i.loli.net/2020/03/30/p9ynIclwY4fqo3h.png)

**Comment by zkqiang** [comment]
感谢，分支已经修复了，过几天再发布
