### ISSUE TITLE
向下滚动箭头不是严格居中的（强迫症

### ISSUE THREAD

**Issue by ayuuvchan** [fluid-dev/hexo-theme-fluid#196]
#### 请描述该需求尝试解决的问题
在大屏的时候不是很明显，但在移动端箭头不居中的比较明显。虽然无伤大雅，但也是一个可以优化的地方。
#### 请描述您认为可行的解决方案
在我实验的过程中发现箭头图标是从中线开始，向右扩展了2rem的距离。所以尝试给箭头加上了1.5rem的padding-right之后严格居中了。
#### 问题截图
![5A168EA9C1D59996F2C14BB438F21CEA](https://user-images.githubusercontent.com/48237017/78108358-ccff8380-7429-11ea-8a90-c90b5725202d.png)

**Comment by zkqiang** [comment]
感谢，已修复
