### ISSUE TITLE
MathJax渲染出错

### ISSUE THREAD

**Issue by AlchemicRonin** [fluid-dev/hexo-theme-fluid#197]
### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [x] 清除浏览器缓存或更换浏览器仍可复现

### Bug 描述
MathJax渲染出错

浏览器: Chrome 80.0.3987.162 64位

### 复现步骤
该 Bug 复现步骤如下：
1. 打开文章页，等待10s
2. 出现MathJax渲染，然后发现出错

### 截图
![2020-04-02 22 19 28 localhost 026552f89c11](https://user-images.githubusercontent.com/38276635/78321108-b98b1000-7530-11ea-955a-9fe9bdf1a75a.png)
![2020-04-02 22 22 05 localhost 6d5c41d90ee8](https://user-images.githubusercontent.com/38276635/78321112-bb54d380-7530-11ea-8523-b4abe0b055d1.png)

**Comment by 0x2E** [comment]
是按文档配置的吗 https://hexo.fluid-dev.com/docs/guide/#latex-%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F

**Comment by zkqiang** [comment]
已知bug已修复，请暂时使用 master 版本

**Comment by zkqiang** [comment]
或者手动做这个修改 https://github.com/fluid-dev/hexo-theme-fluid/commit/f78d9bc111d2a67d2dedc20071b6e08b71132e1e
