### ISSUE TITLE
Markdown语法- [ ]和- [x]不支持

### ISSUE THREAD

**Issue by AlchemicRonin** [fluid-dev/hexo-theme-fluid#199]
### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [x] 清除浏览器缓存或更换浏览器仍可复现

### Bug 描述
Markdown语法- [ ]和- [x]不支持（我记得以前的版本都没有这个问题）

浏览器: Chrome 80.0.3987.132 64位

### 复现步骤
该 Bug 复现步骤如下：
1. 打开文章页

### 截图
![image](https://user-images.githubusercontent.com/38276635/78323996-07a41180-7539-11ea-81f2-76b1348b4b20.png)

**Comment by 0x2E** [comment]
你的 Markdown 渲染插件是 hexo-renderer-markdown-it？

**Comment by ChenYFan** [comment]
支持，但需要切换渲染器：

![image](https://user-images.githubusercontent.com/53730587/78327116-b0d91f00-75ae-11ea-8a2c-90b1de19d7d0.png)

**Comment by AlchemicRonin** [comment]
@0x2E 大佬，能不能指明一下道路？我找过了，没找到什么方案

**Comment by 0x2E** [comment]
@AlchemicRonin 如果是用的 hexo-renderer-markdown-it，那还需要给 markdown-it 安装[插件](https://www.npmjs.com/search?q=markdown-it%20checkbox)，然后在 Hexo 的配置文件中启用。
参考：
- https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration#plugins
- http://baishusama.github.io/2016/12/24/hexo-render-markdown-it-and-its-plugins/#%E9%85%8D%E7%BD%AE
