### ISSUE TITLE
一点小建议-首页文章摘要可以显示样式

### ISSUE THREAD

**Issue by imperio-wxm** [fluid-dev/hexo-theme-fluid#201]
#### 请描述该需求尝试解决的问题
当前的首页文章摘要是无法显示markdown和html样式

#### 请描述您认为可行的解决方案
希望首页的文章摘要可以显示样式，例如用便签写摘要，首页可以显示便签的样式

![image](https://user-images.githubusercontent.com/8111349/78529697-c0f23800-7814-11ea-9a98-ee526282c901.png)

**Comment by zkqiang** [comment]
基本不可能支持样式，因为实际使用中样式各式各样，可能是 <img> <h2> 各种各样标签，会直接导致摘要错乱，反而会给用户造成更多困扰
