### ISSUE TITLE
文章侧栏按分类显示所有文章

### ISSUE THREAD

**Issue by lancerXXXX** [fluid-dev/hexo-theme-fluid#202]
![image](https://user-images.githubusercontent.com/42160297/78546067-6e724500-782f-11ea-9134-505134ce4dd3.png)

就是这种侧栏, 按分类显示文章, 方便在文章之间切换, 就不用先点分类再跳转(就需要等待)

![image](https://user-images.githubusercontent.com/42160297/78546247-ae392c80-782f-11ea-98c6-ec3d11c85c9b.png)

**Comment by 0x2E** [comment]
感谢建议，但暂时没这个计划。后续要做的话再重开这个 issue。
