### ISSUE TITLE
自定义字体和字体大小无效

### ISSUE THREAD

**Issue by imperio-wxm** [fluid-dev/hexo-theme-fluid#203]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [x] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述
修改`source/css/_variables/base.styl` 无效

```shell
$font-family-headings = KaiTi,"Microsoft YaHei",Georgia, sans // 标题，修改成你期望的字体族
$font-family-base = SimHei, Verdana, sans-serif // 修改成你期望的字体族
$font-size-base           = 24px    //修改以前是14，我改成了16
$font-size-small          = $font-size-base - 2px
$font-size-smaller        = $font-size-base - 4px
$font-size-large          = $font-size-base + 2px
$font-size-larger         = $font-size-base + 4px
```

浏览器: Chrome 80.0.3987.163 64位

**Comment by zkqiang** [comment]
因为不是这样改的...

这是从哪学来的改法...

自定义任何样式，请优先使用 [自定义css功能](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html)

**Comment by imperio-wxm** [comment]
@zkqiang 

Hi，

不太懂前端，麻烦能否给出样例？

**Comment by zkqiang** [comment]
比如引入 `custom.css`，内容：

```css
html, body, markdown-body {
  font-family: KaiTi,"Microsoft YaHei",Georgia, sans;
  font-size: 24px
}
```

**Comment by imperio-wxm** [comment]
@zkqiang  谢谢
