### ISSUE TITLE
建议添加复选框功能

### ISSUE THREAD

**Issue by xieldy** [fluid-dev/hexo-theme-fluid#205]
建议添加复选框的功能，如下
```
## 复选框列表
- [x] 需求分析
- [x] 系统设计
- [x] 详细设计
- [ ] 编码
- [ ] 测试
- [ ] 交付
```
![image](https://user-images.githubusercontent.com/22199000/78773897-79aba900-79c6-11ea-95ec-bce7b7db1ae8.png)

**Comment by 0x2E** [comment]
这是 markdown 解析器的工作。hexo-renderer-marked 默认可以渲染出这个效果，hexo-renderer-markdown-it 可以通过插件实现。 
#199
