### ISSUE TITLE
webpjs引入出现打字机速度变得缓慢

### ISSUE THREAD

**Issue by Bryce-huang** [fluid-dev/hexo-theme-fluid#208]
## 现象
直接引入[webpjs](https://webpjs.appspot.com/js/webpjs-0.0.2.min.js)会导致打字机出现速度非常慢
通过以下代码引入时，出现webpjs不生效
```html
<script>(function () {
    const WebP = new Image();
    WebP.onload = WebP.onerror = function () {
        alert("我生气了");
        if (WebP.height !== 2) {
            alert("我需要加载webpjs");
            const sc = document.createElement('script');
            sc.type = 'text/javascript';
            sc.async = true;
            const s = document.getElementsByTagName('script')[0];
            sc.src = 'js/webpjs-0.0.2.min.js';
            s.parentNode.insertBefore(sc, s);
        }
    };
    WebP.src = 'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACyAgCdASoCAAIALmk0mk0iIiIiIgBoSygABc6WWgAA/veff/0PP8bA//LwYAAA';
})();</script>
```

## 复现步骤
在`custom_js` ，引入`custom_js:  /js/webpjs-0.0.2.min.js ` 或者  `custom_html: <script>(function(){const WebP=new Image();WebP.onload=WebP.onerror=function(){alert("我生气了");if(WebP.height!==2){alert("我需要加载webpjs");const sc=document.createElement('script');sc.type='text/javascript';sc.async=true;const s=document.getElementsByTagName('script')[0];sc.src='js/webpjs-0.0.2.min.js';s.parentNode.insertBefore(sc,s)}};WebP.src='data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACyAgCdASoCAAIALmk0mk0iIiIiIgBoSygABc6WWgAA/veff/0PP8bA//LwYAAA'})();</script>   # 自定义底部 HTML 内容（位于 footer 上方），也可用于外部引入 js css 这些操作，注意不要和 post.custom 配置冲突
`
## 期望
引入webpjs 后正常使用，打字机不受影响

**Comment by zkqiang** [comment]
请发 Issue 至 typed 或 webpjs 的仓库
