### ISSUE TITLE
行内代码间插入"公式引用"时不能正常显示

### ISSUE THREAD

**Issue by physxz** [fluid-dev/hexo-theme-fluid#210]
* 公式引用：
  > $\eqref{first}$    无问题
* 行内代码间 公式引用：
  > `$eqref{first}$`    无视行内代码符号 撇 `
* 多加几个 撇 `
  > 依然不行 多出 `$` 符号

效果如下图

![image](https://user-images.githubusercontent.com/40653457/79036122-924ed580-7bf7-11ea-9c1d-0895c84317d1.png)

浏览器: Chrome 80.0.3987.132 64位
hexo版本: 4.2.0
fluid版本: 1.8.0-beta
md编辑器: typora 0.9.86 beta

更新1.4.0-beta后出现的问题，其余软件等都没变，localhost及远端（电脑手机）都是此问题，希望尽快修复，谢谢！

**Comment by physxz** [comment]
第一次提issue，不当之处请见谅

**Comment by zkqiang** [comment]
这个看上去应该是 LaTeX 对应 renderer 的 BUG

但是你说是更新 1.8.0-beta 后出现的，这个有点奇怪，建议回退版本到 1.7.x 试试

**Comment by zkqiang** [comment]
另外我再 KaTeX 测试是没问题的（@upupming/hexo-renderer-markdown-it-plus）

![image](https://user-images.githubusercontent.com/32983588/79036941-c4fccc00-7bff-11ea-8b54-fc926240ecfa.png)
