### ISSUE TITLE
自动摘要过多

### ISSUE THREAD

**Issue by Royce2019** [fluid-dev/hexo-theme-fluid#213]
#### 请确认
- [ x ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ x ] 浏览器不属于 IE 等旧浏览器 
- [ x ] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [ x ] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述
自动摘要过多

浏览器: Chrome 83.0.474.0 64 位

#### 复现步骤
大致 Pad 大小下浏览或者手机大小浏览

https://royce2003.top/

![image](https://user-images.githubusercontent.com/57910033/79059931-4f056d00-7cb2-11ea-8b3f-870421e28313.png)

![image](https://user-images.githubusercontent.com/57910033/79059969-870cb000-7cb2-11ea-8fc8-2841c2c4776a.png)

**Comment by zkqiang** [comment]
代码不完整

```css
.index-excerpt
  color $sec-text-color

  margin 0.5rem 0 0.5rem 0
  height calc(1.4rem * 3)
  line-height 1.4rem
  overflow hidden

  & > div
    float right
    margin-left -0.25rem
    width 100%
    word-break break-word
    display -webkit-box
    -webkit-box-orient vertical
    -webkit-line-clamp 3
```
