### ISSUE TITLE
征集 icon 图标

### ISSUE THREAD

**Issue by zkqiang** [fluid-dev/hexo-theme-fluid#216]
在 [v1.8.0](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.8.0-beta) 中图标库更换为 iconfont，因此征集一些没有内置的图标，包括顶部菜单的图标与关于页社交图标

当前也可以定制自己的 iconfont，这里征集主要是为了方便大家

目前包含的图标如下：

![image](https://user-images.githubusercontent.com/32983588/79293155-83249c00-7f05-11ea-89a8-65c8c4340db7.png)

**Comment by tico88612** [comment]
請求新增 CodeForces Icon  
https://www.iconfont.cn/search/index?q=codeforces

**Comment by zkqiang** [comment]
> 請求新增 CodeForces Icon
> https://www.iconfont.cn/search/index?q=codeforces

收到，会在 1.8.0 正式版中加入

**Comment by physxz** [comment]
请求新增email及bilibili icon
https://www.iconfont.cn/search/index?q=email
https://www.iconfont.cn/search/index?q=bilibili

**Comment by zkqiang** [comment]
@physxz 已经有了，看截图里

**Comment by SwitWu** [comment]
请求新增 download 图标。
