### ISSUE TITLE
希望给一个设置字体族和字体样式的模块

### ISSUE THREAD

**Issue by mxy493** [fluid-dev/hexo-theme-fluid#218]
虽然现在支持自定义样式，但是前端小白真的下不了手。

一方面希望能给一个模板，主要包括设置文章字体，字体样式，尤其是代码块的字体，现在代码块的字体太小了；
另一方面希望把文档再完善一些，讲得细致一些，有一些内容似乎没有即使更新。

**Comment by zkqiang** [comment]
1.8.0 已支持

![image](https://user-images.githubusercontent.com/32983588/79560466-3e059300-80da-11ea-8ecc-7539970dea33.png)
