### ISSUE TITLE
当全局字号``font_size: 14px``时文章页出现左右滑动条

### ISSUE THREAD

**Issue by aolog** [fluid-dev/hexo-theme-fluid#219]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [x] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述
当全局字号``font_size: 14px``或小于14，且多篇文章时，文章页出现左右滑动条

浏览器: 
IOS 13.4.5 Safari浏览器 
Microsoft Edge 版本 80.0.361.109 (官方内部版本) (64 位)

#### 复现步骤
该 Bug 复现步骤如下：
1. 进入文章页
2. 然后向下滚动
3. 会出现左右滑动

部署后能复现的页面地址：
http://c.aolog.cn/test/
#### 截图

![e8bf5d7e923cee2e4406ccd4b2acbf89](https://user-images.githubusercontent.com/48140334/79695195-17955280-82a8-11ea-8b74-e27e07ef9861.gif)

![image](https://user-images.githubusercontent.com/48140334/79692304-ed876480-8296-11ea-9c6b-38aff5843a9b.png)

**Comment by zkqiang** [comment]
dev分支代码试一下

**Comment by aolog** [comment]
nav栏不变色，返回顶部按钮不出现

**Comment by aolog** [comment]
页面地址：
http://c.aolog.cn/test/

**Comment by zkqiang** [comment]
@aolog 再试下，换了一种解决方式

**Comment by aolog** [comment]
好了
