### ISSUE TITLE
1.8.0-beta2 gitalk评论模块引入异常

### ISSUE THREAD

**Issue by DiaosSama** [fluid-dev/hexo-theme-fluid#220]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [x] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述
gitalk评论模块md5()函数未定义，导致gitalk评论模块加载异常
经过与1.7.4版本的比较后发现gitalk.ejs中原本引入md5函数的js被删去，在gitalk.ejs第三行下加入以下代码即可临时修复：
```html
<script defer src="https://cdn.jsdelivr.net/npm/blueimp-md5@2.11.1/js/md5.min.js"></script>
```
是个小bug，大家有引入问题的自己动手解决一下，团队在正式版记得修复一下这个问题。

**感谢团队制作了这么优秀的主题！^ ^**

浏览器: Chrome 80.0.3987.132 64位

#### 复现步骤
该 Bug 复现步骤如下：
1. 正常引入gitalk评论模块

#### 截图
![image](https://user-images.githubusercontent.com/38740934/80002954-ebb9dd00-84f2-11ea-9e4d-1735ded8de26.png)

**Comment by DiaosSama** [comment]
顺手提交了一个PR

**Comment by 0x2E** [comment]
感谢，PR 已合。
