### ISSUE TITLE
使用自定义代码高亮时生成的 RSS 代码无换行符

### ISSUE THREAD

**Issue by ikvarxt** [fluid-dev/hexo-theme-fluid#222]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [x] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述
使用主题设定的代码高亮，利用 [hexo-generator-feed](https://github.com/hexojs/hexo-generator-feed) 生成的 RSS 订阅，无论是 atom 格式还是 rss2 格式，代码没有换行符，显示为只有一行，观感极差。格式在博客页面中是正常的。

浏览器: Chrome 80.0.3987.132 64位

#### 复现步骤
该 Bug 复现步骤如下：
1. 使用主题中的代码高亮设定
2. 使用 hexo-generator-feed 生成 atom 或 rss2 订阅
3. 随便使用一个 rss 阅读器查看

最好提供部署后能复现的页面地址：https://leontuan.me/feed.xml 

#### 截图

![image](https://user-images.githubusercontent.com/40603400/80056046-d75afc00-8555-11ea-89e5-4b65a66644e8.png)

**Comment by zkqiang** [comment]
你用插件有问题应该提到向插件作者提 issue ....

**Comment by ikvarxt** [comment]
我这边发现的一个问题就是使用 hexo 本身的代码高亮，或者关闭主题内的代码高亮设置以后就会正常，所以才向这边提的 issue。

希望作者有时间可以测试一下，我这边确实是发现了这样的问题。

整个测试过程中的变量只有**主题配置中 highlight: enable** 的修改。

**Comment by zkqiang** [comment]
我的意思是我无法改变这种情况

最新版的高亮是 hexo 内置的，主题只负责开启调用

**Comment by ikvarxt** [comment]
好的好的，那我再看看。谢谢。
