### ISSUE TITLE
在使用Valine的时候发现的BUG

### ISSUE THREAD

**Issue by isbest** [fluid-dev/hexo-theme-fluid#225]
在Valine中修改了官方默认头像之后，并没有正确显示，依然是mp默认头像，然后查阅Valine的配置要求之后，发现作者的layout/_partial/comments/valine.ejs的第20行书写错误，应该改为avatar: "<%= theme.valine.avatar %>",就OK了。

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/cb0579fa87fd1ffb8972500b088080d96f39d5dc/layout/_partial/comments/valine.ejs#L16

是正确的格式，而且默认配置是 `retro`，可能你要再看看是不是别的原因
