### ISSUE TITLE
建议：代码段添加可选的滑动条

### ISSUE THREAD

**Issue by dsyx** [fluid-dev/hexo-theme-fluid#226]
主题版本：1.8.0 beta2
截图：
![image](https://user-images.githubusercontent.com/34703581/80504861-2cf43600-89a6-11ea-94e1-64a1af245871.png)

建议：如截图所示，没有任何提示代码的纵向长度，如果可视面刚好是一句结尾，读者容易以为后面没有内容。是否应该添加一个可选的滑动条用于提示读者？

**Comment by zkqiang** [comment]
后续会加的，目前去掉是因为样式有些问题

不过就算加了，根据滚动条的特性，不滚动时也不会显示出来，所以不会达到你要的目的

**Comment by dsyx** [comment]
:ok_hand: 感谢回答
