### ISSUE TITLE
手机端 nav 问题

### ISSUE THREAD

**Issue by Royce2019** [fluid-dev/hexo-theme-fluid#227]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [x] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述

手机端 nav 点击不弹出菜单

id="navbar-toggler-btn" 的 button 在点击时没变化，不知道是不是这个问题
自定义 css，js 全部去掉了仍可复现

浏览器: Chrome 80.0.3987.132 64位

最好提供部署后能复现的页面地址：

https://royce2003.top

**Comment by zkqiang** [comment]
https://github.com/thsmi/sieve/issues/235

jQuery 的 breaking change 导致
