### ISSUE TITLE
覆盖更新最新版本(1.8.0)后 hexo g 提示 TypeError: "listener" argument must be a function

### ISSUE THREAD

**Issue by SuYouge** [fluid-dev/hexo-theme-fluid#228]
#### 请确认
- [yes] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [no] 浏览器不属于 IE 等旧浏览器 
- [不能`hexo g`] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [不能`hexo g`] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述
覆盖更新最新版本，`hexo g`不能执行,。

浏览器: Chrome 80.0.3987.132 64位

#### 复现过程

下载最新release后将原来的fluid修改为fluid_bak，然后解压命名为fluid。
手动修改了主题文件夹内的`_config.yml`，与原有配置文件保持一致。
执行`hexo g` 报错如下图。

#### 截图
![2020-04-30 18-10-53屏幕截图](https://user-images.githubusercontent.com/29477239/80701931-cf312c80-8b12-11ea-8536-4da787f52515.png)

####  hexo版本

```bash
hexo: 4.2.0
hexo-cli: 3.1.0
os: Linux 5.3.0-28-generic linux x64
http_parser: 2.7.0
node: 8.10.0
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

**Comment by zkqiang** [comment]
应该是 node版本太低了。。。

**Comment by SuYouge** [comment]
> 应该是 node版本太低了。。。

node更新到10.0.0就可以了啦

**Comment by SuYouge** [comment]
node 更新到12.0.0就可以啦
