### ISSUE TITLE
部分代码高亮不工作

### ISSUE THREAD

**Issue by huaxianyan** [fluid-dev/hexo-theme-fluid#230]
#### 请确认
- [ x ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ x ] 浏览器不属于 IE 等旧浏览器 
- [ x ] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [ x ] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述
部分代码块的代码高亮不工作，比如这篇中的：https://www.neko7ina.com/make-windows-terminal-great-again.html

最后几个 json 部分，同样是 json 样式，有的高亮有的不高亮，只有最后一块处理了

还有这篇 https://www.neko7ina.com/tools-on-macOS.html 中的 Bash 部分也未生效

**Comment by zkqiang** [comment]
因为其他的 JSON 是错误格式（末尾有逗号），因此不会被正确解析

**Comment by huaxianyan** [comment]
@zkqiang 竟然还有检查格式……

这倒是没想到，看到在 Typora 里正常高亮了就没管
