### ISSUE TITLE
（问题）修改的全局颜色在部署到 Pages 之后失效

### ISSUE THREAD

**Issue by MindSkyHost** [fluid-dev/hexo-theme-fluid#231]
在主题配置文件中，我修改了 `color:` 段，执行 `hexo g` 和 `hexo s` 之后，`localhost` 中的颜色已经变化了；但当我deploy上去之后，我发现在 pages 上的页面颜色仍然是默认的，想询问一下应该怎样修复这个问题？谢谢！

**Comment by MindSkyHost** [comment]
用了 custom css 之后问题解决，抱歉，打扰了

**Comment by zkqiang** [comment]
实际原因只是因为缓存。。。

**Comment by MindSkyHost** [comment]
> 实际原因只是因为缓存。。。

原来如此，谢谢！🤗
