### ISSUE TITLE
自定义 CSS 问题

### ISSUE THREAD

**Issue by Butanediol** [fluid-dev/hexo-theme-fluid#234]
#### 请确认
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [x] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述
自定义 CSS 开头会出现一段 HTML 代码，导致部分 CSS 无效。

```
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/hint.css/2.4.1/hint.min.css">
```

浏览器: Safari 13.1 (15609.1.20.111.8)

#### 复现步骤
该 Bug 复现步骤如下：
1. 填写自定义 CSS
2. `hexo s`
3. 浏览器开发者工具查看自定义 CSS 文件

#### 截图

![自定义 CSS 代码](https://i.loli.net/2020/05/06/r4lVkx6eESwPI8C.png)
![浏览器里已引用](https://i.loli.net/2020/05/06/4JpS2sMknO6yzfY.png)
![在来源中查看，多出一行代码](https://i.loli.net/2020/05/06/ktLZ2iB7z4raqy5.png)

**Comment by zkqiang** [comment]
这个应该是你别的插件影响的
主题本身没有这方面的代码逻辑

**Comment by Butanediol** [comment]
谢谢，确实是插件的问题，出问题的插件是这个：[hexo-reference](https://github.com/kchen0x/hexo-reference)

但这个注脚功能确实很好用，Fluid 能否考虑加入？

**Comment by zkqiang** [comment]
后续可以考虑加入，感谢

**Comment by DogeLasVegas** [comment]
请问题主怎么解决的这个问题，是放弃使用这个插件了吗，还是通过什么方式把插入的HTML代码去掉了
