### ISSUE TITLE
hexo b备份到云服务器

### ISSUE THREAD

**Issue by pxxyyz** [fluid-dev/hexo-theme-fluid#240]
本人小白，刚刚入坑。最近倒腾hexo到服务器，利用`git`和`Nginx`自动化部署发布，参照了[Hexo 博客部署到腾讯云服务器](https://www.muyiio.com/2020/03/28/hexo-bo-ke-bu-shu-dao-teng-xun-yun-fu-wu-qi/)教程，但是`hexo b`不能使用钩子，因此我照着做了一个备份的钩子，可以自动化备份到服务器。详细见[博客](https://pxxyyz.com/2020/05/12/Hexo%E9%83%A8%E7%BD%B2%E6%9C%8D%E5%8A%A1%E5%99%A8/)，希望也为fluid做贡献。

**Comment by zkqiang** [comment]
文章链接挂了，另外文章投稿到 fluid blog 里吧
