### ISSUE TITLE
hexo-renderer-kramed与emoji冲突

### ISSUE THREAD

**Issue by pxxyyz** [fluid-dev/hexo-theme-fluid#241]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
Latex使用`mathjax`引擎，卸载了默认引擎，并
- 修改`/node_modules/hexo-renderer-kramed/lib/renderer.js`
- 修改hexo的渲染源码`/node_modules/kramed/lib/rules/inline.js`
- 停止使用 `hexo-math`，安装 `hexo-renderer-mathjax`
- 设置了`/source/_data/fluid_config.yml`
> post:
>  math:  
>    enable: true  
>    specific: false   
>    engine: mathjax
- 修改目录`_config.yml`
> mathjax: true
- 在`Front-matter`中打开`MathJax`
数学公式能正常使用，`emoji` 无法正确显示。编码在`Typora`可以正常显示表情，在网页上显示的是对应的`emoji` 编码。反而直接复制表情可以显示。

**Comment by zkqiang** [comment]
hexo 的 emoji 需要额外使用插件来支持 
https://github.com/crimx/hexo-filter-github-emojis

**Comment by pxxyyz** [comment]
问题解决了，谢谢:smile:
