### ISSUE TITLE
iconfont的位置

### ISSUE THREAD

**Issue by essesy** [fluid-dev/hexo-theme-fluid#242]
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
想知道iconfont的css是放在什么地方的😂

**Comment by vinceying** [comment]
主题依赖的 JS和CSS 可以在 `_static_prefix.yml` 查看到。
要添加自己的图标，参阅：https://hexo.fluid-dev.com/docs/icon/#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E6%A0%87

**Comment by essesy** [comment]
> 主题依赖的 JS 和 CSS 可以在 `_static_prefix.yml` 查看到。
> 要添加自己的图标 CSS 文件，参阅：https://hexo.fluid-dev.com/docs/icon/#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E6%A0%87

OK的thanks！问题已经解决
