### ISSUE TITLE
文章打赏

### ISSUE THREAD

**Issue by grapesrain** [fluid-dev/hexo-theme-fluid#243]
希望增加微信和支付宝打赏入口

**Comment by vinceying** [comment]
在  `_config.yml` 中 `post.custom` 可以满足以上需求将以下代码中图片链接替换即可。
`<img src="https://octodex.github.com/images/jetpacktocat.png" class="rounded mx-auto d-block mt-5" style="width:150px; height:150px;"> `

**Comment by zkqiang** [comment]
本主题很早就不打算加入打赏了，抱歉
