### ISSUE TITLE
chrome 上文章列表滑动卡顿(掉帧)

### ISSUE THREAD

**Issue by mritd** [fluid-dev/hexo-theme-fluid#244]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [x] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述
chrome 上文章列表滑动卡顿(有明显感觉)，safari 上有缓解。

#### 系统环境

OS: Mac 10.15.4 (19E287)
Chrome: 81.0.4044.138 64 位

硬件为 16寸 64G rmbp，测试时已切换到独立显卡，排除性能不足导致。
已经通过启动新 chrome 实例方式完全排除插件影响可能

```sh
# 启动新实例并完全切换用户数据
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --user-data-dir=~/tmp/ch
```

#### 复现步骤
该 Bug 复现步骤如下：
1. 上下多次滑动文章列表即可复现
2. 能明显感觉到页面卡顿

最好提供部署后能复现的页面地址：

博客正在迁移过程中，暂未对外部开发，如有需要可以发送私有仓库邀请。

#### 截图

![image](https://user-images.githubusercontent.com/13043245/82008516-8bf0c500-969f-11ea-9f26-a3bde39e9469.png)

**Comment by zkqiang** [comment]
谢谢，目前scroll事件监听确实比较多，下个版本会对此着重优化

**Comment by mritd** [comment]
😁好的，感谢。

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/commit/4849c9ed1b43d0e1f7f6d2769be9e61c44386b44

优化了一下，欢迎体验

**Comment by mritd** [comment]
似乎新版本 1.8.9 又开始掉帧了...
