### ISSUE TITLE
写文章的时候，md文件是怎么插入音乐的？

### ISSUE THREAD

**Issue by scarleast** [fluid-dev/hexo-theme-fluid#246]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
文档中没有说明，写文章的时候插入音乐。

**Comment by zkqiang** [comment]
这个可以搜索下，方法很多，都是通用的

比如 https://github.com/MoePlayer/hexo-tag-aplayer
