### ISSUE TITLE
打字机特效的副标题，能否动态的加载今日诗词？https://www.jinrishici.com/

### ISSUE THREAD

**Issue by scarleast** [fluid-dev/hexo-theme-fluid#247]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html)实现的功能（如文末赞赏）
- [x] 难以通过第三方插件实现（如置顶、插入视频）

#### 请描述该需求尝试解决的问题
我希望把副标题静态文字的打字机特效，换成动态的[今日诗词](https://www.jinrishici.com/)，但是不懂前端，这个应该如何修改？

#### 请描述您认为可行的解决方案
不懂前端，不清楚。

#### 考虑过的替代方案
不懂前端，不清楚。

**Comment by zkqiang** [comment]
需要在打字机的js里加上这个请求

**Comment by scarleast** [comment]
打字机的js路径是什么？我想自己试试看，能不能加上。

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/master/layout/_partial/plugins/typed.ejs#L7

接口返回结果替换掉 `data.subtitle` 即可

**Comment by scarleast** [comment]
感谢
