### ISSUE TITLE
显示文章更新时间出错

### ISSUE THREAD

**Issue by pxxyyz** [fluid-dev/hexo-theme-fluid#248]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [x] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述
在博客配置里设置了
updated:  # 在文章开头显示文章更新时间，该时间默认是 md 文件更新时间，可通过 front-matter 中 `updated` 手动指定（和 date 一样格式）

```
enable: true # false #true
  content: 本文最后更新于：  # 描述文字
  relative: false  # 是否使用相对时间表示，比如："3 天前"
```

在`front-matter`设置，例如在`Hello World`中

```
title: Hello World
date: 2020-05-03 10:00:00
update: 2020-05-10 10:00:00
```

但是在网页`Hello World`显示

> 本文最后更新于：2020年5月19日 晚上

**更新时间显示为`.md`文件最近修改的时间，不能显示`front-matter`中设置的时间。**

经过`hexo clean`后，在本地`hexo s` 或者部署到网站上同样出错。

提供部署后能复现的页面地址：
https://pxxyyz.com/2020/05/03/hello-world/

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/27855abb8a818dd727c8a060614dcf99498f863c/_config.yml#L196
请再仔细确认下注释

**Comment by pxxyyz** [comment]
我在front-matter手动指定updated，但是显示的是默认的 md 文件更新时间，不是updated指定时间

**Comment by zkqiang** [comment]
因为你 front-matter 写的是 `update` 而不是 `updated`

**Comment by pxxyyz** [comment]
谢谢强哥，我搞错了名字了。
