### ISSUE TITLE
Vercel一键建站的About页面无法创建

### ISSUE THREAD

**Issue by mas-mirror** [fluid-dev/hexo-theme-fluid#252]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [X] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

如题，我无法手动输入部署命令。

手动创建about文件夹无效。

**Comment by zkqiang** [comment]
没用过这个，但是你可以本地创建好再传上去

**Comment by mas-mirror** [comment]
> 没用过这个，但是你可以本地创建好再传上去

没有用。

**Comment by zkqiang** [comment]
那只能通过其他途径寻求解决办法了，因为我没用过这个东西

**Comment by vinceying** [comment]
Vercel 应该是没有问题的。我部署在 Vercel 的站点是正常的，链接：https://vercel.vince.pub/。
如果是 Hexo 的源文件，推荐使用 Github Actions 部署在另一个仓库，然后 Vercel 选择这个仓库进行部署。

**Comment by mas-mirror** [comment]
> Vercel 应该是没有问题的。我部署在 Vercel 的站点是正常的，链接：https://vercel.vince.pub/ 。
> 如果是 Hexo 的源文件，推荐使用 Github Actions 部署在另一个仓库，然后 Vercel 选择这个仓库进行部署。

谢谢了 问题已解决。

**Comment by dzvision** [comment]
> > Vercel 应该是没有问题的。我部署在 Vercel 的站点是正常的，链接：https://vercel.vince.pub/ 。
> > 如果是 Hexo 的源文件，推荐使用 Github Actions 部署在另一个仓库，然后 Vercel 选择这个仓库进行部署。
> 
> 谢谢了 问题已解决。

我在本地localhost也是确实可以看到能够生成，但是上传GitHub之后，发现Vercel确实没有。（其他主题没这个问题）
即使直接在source下新建about.md 不使用source/about/index.md这个文件，同样也是没有的。
