### ISSUE TITLE
代码高亮的开关打开，根据 style 改变代码背景色也打开，hexo无法生成文件，cpu100%

### ISSUE THREAD

**Issue by zsfblues** [fluid-dev/hexo-theme-fluid#255]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)[v1.8.0]
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [x] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述
代码高亮的开关打开，并且根据 style 改变代码背景色也打开，hexo无法生成文件，cpu一直100%

浏览器: Chrome 80.0.3987.132 64位

#### 复现步骤
该 Bug 复现步骤如下：
1. bg_color设为true
2. hexo clean然后hexo g
3. cpu100%

最好提供部署后能复现的页面地址：

#### 截图
通过 hexo g --debug 一直卡在这个地方
<img width="740" alt="截屏2020-05-25 上午10 03 57" src="https://user-images.githubusercontent.com/9928627/82771636-42f2fa80-9e6f-11ea-9634-5bc34c316429.png">
<img width="456" alt="截屏2020-05-25 上午10 04 23" src="https://user-images.githubusercontent.com/9928627/82771639-46868180-9e6f-11ea-839c-3e67080355e4.png">

```javascript
  if (config.highlight.bg_color) {
    hexo.extend.filter.register('after_render:html', (html, data) => {
      return html.replace(/(?<!<div class="hljs">)<pre.*?(class=".+?".*?)*>(.*?)<\/pre>/gis, (str, p1, p2) => {
        return `<div class="hljs"><pre${p1 ? p1.replace('class="', ' class="hljs ') : ''}>${p2}</pre></div>`;
      });
    });
  }
```
这段文本替换很耗cpu？？

**Comment by zkqiang** [comment]
应该跟高亮和正则没关系，再排查下别的原因吧

**Comment by zsfblues** [comment]
应该是markdown里面有一篇文章包含<prelen>这个符号，和那段文本替换代码冲突，导致有问题，另外背景改变后，很多样式也乱掉了，这个功能貌似不可用

**Comment by zkqiang** [comment]
不会不可用，已经有很多用户成功在用了
