### ISSUE TITLE
项目生成的时候报错

### ISSUE THREAD

**Issue by mambaJun** [fluid-dev/hexo-theme-fluid#257]
9| 
    10| <div class="row links">
 >> 11|   <% for(const each of theme.links.items) { %>
    12|     <% if (!each.title || !each.link) continue %>
    13|     <div class="card col-lg-4 col-md-6 col-sm-12">
    14|       <a href="<%= url_for(each.link) %>" class="card-body hover-with-bg" target="_blank" rel="noopener">

theme.links.items is not iterable

**Comment by zkqiang** [comment]
你配置写错了
