### ISSUE TITLE
Tag页面显示 Page not found

### ISSUE THREAD

**Issue by MyTimeforDevIos** [fluid-dev/hexo-theme-fluid#258]
#### 请确认

- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)

- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
在本地运行的时候 `hexo s` 能点开 tag 页面
但是上传到 Github 上时，发现没有上传 tag 文件夹，导致出现了没有找到页面的问题

请问这种情况会是有什么原因么

**Comment by zkqiang** [comment]
我看目前你的页面是正常的，可能是你本地缓存
