### ISSUE TITLE
代码高亮切换style问题

### ISSUE THREAD

**Issue by nbhtm2014** [fluid-dev/hexo-theme-fluid#259]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
切换了 代码高亮的 style
<https://highlightjs.org/static/demo/>
使用里面的style
但是页面上的样式和demo里的样式应该是出现了冲突，基本无法使用

**Comment by zkqiang** [comment]
麻烦给个截图或者部署后的链接吧...

**Comment by nbhtm2014** [comment]
![image](https://user-images.githubusercontent.com/11625708/82989634-9612ac00-a02d-11ea-8235-5f60036239fa.png)
![image](https://user-images.githubusercontent.com/11625708/82989687-a9257c00-a02d-11ea-8052-5eb2ebee6798.png)

**Comment by zkqiang** [comment]
请看下面那个配置的注释

**Comment by nbhtm2014** [comment]
明白了，误解注释了
