### ISSUE TITLE
感谢作者的工作，两个需求请教下能否实现。

### ISSUE THREAD

**Issue by XSun771** [fluid-dev/hexo-theme-fluid#261]
#### 请确认
- [确定 ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [大致确定] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

第一，希望完全关闭打字机的效果，首页的副标题也好，文章的标题也好，希望就直接文字显示在那里，同时结尾不要有一个打字机的浮标一闪一闪的。

第二，markword文章内部的代码块的行号不想要该怎么整？我在指南中看到介绍说使用代码高亮则不支持行号，太好了，我就不想要行号。。但我开启了代码高亮，行号还是没去掉。。讲道理，这个默认行号的搭配有点点丑。。

最后还是感谢作者的辛苦工作，让我们可以轻松地用上这么好看的主题。鞠躬。

**Comment by zkqiang** [comment]
问题一： `fun_features.typing.enable: false`

问题二：开启高亮不会有行号，如果有可能你哪个地方没弄好，请自查一下

**Comment by XSun771** [comment]
> 问题一： `fun_features.typing.enable: false`
> 
> 问题二：开启高亮不会有行号，如果有可能你哪个地方没弄好，请自查一下

谢谢解答。。第一个问题我我确实设置为false了，然后把`fun_features.typing.cursorChar`也设置为空，这样首页确实没有浮标一闪一闪了。但是文章打开，文章的标题还是使用打字机模式出现的，嫩能禁止么？

额，第二个问题能给点提示么，和高亮，行号相关的设置，我只能找到一个 注释为全局里的：

```
highlight: # 代码高亮
  enable: true
  style: "Atom One Dark" # 高亮样式见：https://highlightjs.org/static/demo/  在页面挑选 style 填入
  bg_color: false # 是否根据 style 改变代码背景色，如果 style 是白色背景最好关闭此项
  copy_btn: false # 是否开启复制代码的按钮
```
我觉得我这样设置没什么问题了吧。。。

谢谢

**Comment by zkqiang** [comment]
问题一，设置false就是全局关闭了，不会区分在哪一页

问题二，主题的高亮是没有行号功能的，所以也不用设置，如果你的有，我猜测是你之前装了别的高亮插件导致

另外最好部署一下发个链接过来吧

**Comment by XSun771** [comment]
> 问题一，设置false就是全局关闭了，不会区分在哪一页
> 
> 问题二，主题的高亮是没有行号功能的，所以也不用设置，如果你的有，我猜测是你之前装了别的高亮插件导致
> 
> 另外最好部署一下发个链接过来吧

谢谢回复。

我用 hexo init 了一个新的文件，代码显示问题解决了，不过第一个需求请看一下这篇文章：
https://xaiversun.gitee.io/blog/2020/02/02/%E6%BB%91%E5%8A%A8%E7%AA%97%E5%8F%A3%E6%B3%95/
就是标题仍然是用打字机效果一个一个出现的，我希望就直接显示在那里。

确定
```
fun_features: # 一些好玩的功能
  typing: # 为 subtitle 添加打字机效果
    enable: fasle
```
fluid的config.yaml中已经这样配置了。

谢谢

**Comment by zkqiang** [comment]
检查一个覆盖配置吧，实际并没有被你关掉

**Comment by XSun771** [comment]
> `false`
> 
> 不是`fasle`。。。

捂脸。。。。

都解决了，谢谢作者！
