### ISSUE TITLE
评论中md语法的标题会混淆右侧栏

### ISSUE THREAD

**Issue by cooper1x** [fluid-dev/hexo-theme-fluid#264]
#### Bug 描述
问题页面：https://hexo.fluid-dev.com/posts/actions-deploy/

#### 复现步骤
该 Bug 复现步骤如下：
1. 打开示例页面
2. 然后向下滚动到评论区
3. 会出现评论内容出现在右侧栏

#### 截图
![image](https://user-images.githubusercontent.com/9080789/83186979-f6a20600-a15f-11ea-8e41-ce75d924e19f.png)

**Comment by zkqiang** [comment]
nice issue
