### ISSUE TITLE
背景图片如何设置呢？

### ISSUE THREAD

**Issue by Desperado1001** [fluid-dev/hexo-theme-fluid#270]
#### Make sure
- [ ] Upgrade the latest [release version](https://github.com/fluid-dev/hexo-theme-fluid/releases).
- [ ] No solution found in [Documentation][https://hexo.fluid-dev.com/docs/en/]

#### Describe the question
A clear and concise description of what the question is.
首页大图可以设置，但是博客的背景图片在哪里设置呢？

**Comment by zkqiang** [comment]
请先认真看文档
https://hexo.fluid-dev.com/docs/guide/#%E6%96%87%E7%AB%A0%E9%A1%B5%E9%A1%B6%E9%83%A8%E5%A4%A7%E5%9B%BE
