### ISSUE TITLE
hexo报错，css加载不出来。

### ISSUE THREAD

**Issue by 2410635019** [fluid-dev/hexo-theme-fluid#272]
![Screenshot_2020-05-31-16-45-56-479_com termux](https://user-images.githubusercontent.com/44385551/83353518-b328e100-a385-11ea-9888-84f81d3c33bc.jpg)
![Screenshot_2020-05-31-15-57-55-593_com termux](https://user-images.githubusercontent.com/44385551/83353519-b623d180-a385-11ea-9d7e-22945411dc95.jpg)
换别的主题不会报错，这个我知道是主题的问题还是我hexo的问题。
我把原先的博客文件夹删了，重新搭建还是这样的，麻烦了。这个主题我蛮喜欢的，没有啥主题想换😂😂

**Comment by zkqiang** [comment]
hexo 有问题，建议整个删掉重新 `hexo init`
