### ISSUE TITLE
hexo本地测试会出错

### ISSUE THREAD

**Issue by 2410635019** [fluid-dev/hexo-theme-fluid#273]
先感谢昨天开发者大大的解答，我已经按照你的说法，重新装了hexo。但是今天hexo s的时候还是和昨天一样，有一点值得注意换别的主题好像不会出错。
![Screenshot_2020-06-01-08-43-29-253_com termux](https://user-images.githubusercontent.com/44385551/83367091-56f5a980-a3e5-11ea-8f20-977412c99377.jpg)
![Uploading Screenshot_2020-06-01-08-40-25-785_com.termux.jpg…]()

**Comment by zkqiang** [comment]
>有一点值得注意换别的主题好像不会出错。

这个没什么值得注意的，主题是有自动测试的，正常情况下生成不会出现错误。

从报错上看，应该是你主题文件夹下的 config.yml 配置项不完整导致的
