### ISSUE TITLE
请求添加ADSence支持。

### ISSUE THREAD

**Issue by mas-mirror** [fluid-dev/hexo-theme-fluid#274]
#### 如是功能需求，请确定符合以下情况
- [X] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html)实现的功能（如文末赞赏）
- [X] 难以通过第三方插件实现（如置顶、插入视频）

添加ADSence支持。

**Comment by zkqiang** [comment]
这个真的可以通过自定义实现的功能
