### ISSUE TITLE
请问如何使图片默认居中？

### ISSUE THREAD

**Issue by zihuanqiu** [fluid-dev/hexo-theme-fluid#279]
我在插入这种格式`<img src="url"/>`的图片默认是靠左的，请问有没有方法使它默认居中呢？谢谢！

**Comment by zkqiang** [comment]
方法很多，比如：

```html
<p align="center">
  <img alt="Fluid Logo" src="https://avatars2.githubusercontent.com/t/3419353?s=280&v=4" width="128">
</p>
```

其他方法请自行搜索"img 水平居中"

**Comment by zihuanqiu** [comment]
如果加入自定义css，改完之后就没有悬浮的效果啦，有没有办法能加入效果呢。（因为我在typora改照片尺寸会直接变成html的格式，一个一个去改环境太麻烦了，所以我还是偏向于全局改，但是这样就没有悬浮的效果啦）

**Comment by zkqiang** [comment]
.markdown-body img {
    margin: auto;
    display: block;
    box-shadow: 0 5px 11px 0 rgba(0,0,0,.18),0 4px 15px 0 rgba(0,0,0,.15);
    border-radius: 3px;
}
