### ISSUE TITLE
gitalk 使用问题

### ISSUE THREAD

**Issue by zh-bupt** [fluid-dev/hexo-theme-fluid#280]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

使用 gitalk 的时候不能根据 pathname 来到对应的 issue，所有页面都是同一个 issue

**Comment by zkqiang** [comment]
试一下这个 fix https://github.com/fluid-dev/hexo-theme-fluid/commit/0740244e8272f37301fbb55a8ef25e925ce44330

**Comment by zh-bupt** [comment]
> 试一下这个 fix [d353abf](https://github.com/fluid-dev/hexo-theme-fluid/commit/d353abf6c040fb4599adda691a6921cba0fecfc9)

可以，已经解决了，谢谢 ^_^
