### ISSUE TITLE
锚点跳转后被导航栏挡住

### ISSUE THREAD

**Issue by pxxyyz** [fluid-dev/hexo-theme-fluid#281]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 本地 `hexo clean && hexo s` 后仍可复现
- [x] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述

使用锚点设定后

```
[说明文字](#jump)
<span id = "jump">说明文字-跳转位置</span>
```

出现跳转位置被导航栏挡住，而标题和脚标应该是给锚点增加偏移量，所以没问题，是不是得给所有的锚点都增加偏移量

提供部署后能复现的页面地址：<https://pxxyyz.com/posts/62931/>

**Comment by zkqiang** [comment]
目前锚点的偏移只对已知的元素支持

**Comment by pxxyyz** [comment]
那能通过参数自己设定偏移吗？另外列表、图片、表格、公式等这些元素能支持偏移锚点的偏移吗？我之前对公式设定标签，再用`$\eqref{eq:label}$`设定跳转，结果公式被挡住看不见了，例如<https://pxxyyz.com/posts/37321/#mjx-eqn-eq%3AfSVD>

**Comment by zkqiang** [comment]
有些锚点设置偏移也不会生效，暂时没什么统一设置的好办法，我只对常用的设置了，比如节标题（h2 h3...） 脚注

**Comment by pxxyyz** [comment]
我找了一种设置锚点的css的方法解决
```
a.anchor {
  display: block;
  position: relative;
  top: -60px;
  visibility: hidden;
}
```
然后用链接形式
```
说明文字-跳转位置<a class="anchor" id="jump"></a>
```
这样的锚点不会被挡住。不过公式:expressionless:
