### ISSUE TITLE
关于我页面，微信二维码在微信端长按不弹出菜单

### ISSUE THREAD

**Issue by hansonfang** [fluid-dev/hexo-theme-fluid#282]
#### Make sure
- [ ] Upgrade the latest [release version](https://github.com/fluid-dev/hexo-theme-fluid/releases).
- [ ] Browser does not belong to IE and other old browsers
- [ ] It can be replicated through `hexo clean && hexo s` in the localhost.
- [ ] It can still be replicated by cleared browser cache or replaced browser.

#### Describe the bug

浏览器：最新微信客户端
长按二维码不提示保存图片或者识别图中二维码选项
#### To Reproduce
1. Go to '...', click on '....'
2. Scroll down to '....'
3. See error

It is better to provide the page link that can be reproduced:

**Comment by zkqiang** [comment]
![image](https://user-images.githubusercontent.com/32983588/84101731-3232af00-aa41-11ea-93a9-202913c4c4e7.png)

我的可以
