### ISSUE TITLE
升级1.8.1 hexo部署失败

### ISSUE THREAD

**Issue by leo-wxy** [fluid-dev/hexo-theme-fluid#283]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

本地升级 fluid1.8.1之后，`hexo s`的时候报如下错误：
```java
TypeError: Cannot set property 'lastIndex' of undefined
    at highlight (../node_modules/highlight.js/lib/highlight.js:511:35)
    at ../node_modules/highlight.js/lib/highlight.js:561:21
    at Array.forEach (<anonymous>)
```
本地再降级1.8之后问题消失

**Comment by zkqiang** [comment]
删除 node_modules 重新安装依赖

**Comment by leo-wxy** [comment]
我刚刚按照你给的操作可以部署了，谢谢
