### ISSUE TITLE
博文中包含http来源的图片时，博文想要加载出图片则无法保持自己的https状态

### ISSUE THREAD

**Issue by XSun771** [fluid-dev/hexo-theme-fluid#284]
#### 如是功能需求，请确定符合以下情况
- [确定] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html)实现的功能
- [大致确定] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题
https://xaiversun.gitee.io/blog/2020/05/30/0x1/#快速为可序列化对象添加版本号

这个小节所属的图片一直在转圈无法显示任何东西。
在地址栏中出现如图提示：http://img.d613.top/https下无法加载脚本.png

点击完成后 https 状态被取消，图片正常加载出来。

http://xaiversun.gitee.io/blog/2020/05/30/0x1/#快速为可序列化对象添加版本号

直接用http协议访问图片也可以直接加载出来。

https的网页中有http的资源，这件事本身并不会导致网页的https退化，我自己测试了一下：

https://v2ex.com/t/680604#reply0

而且根据提示的信息来说好像也是因为引入了奇怪的脚本。

希望能够实现http的图片正常引入。

谢谢！

**Comment by zkqiang** [comment]
https://hexo.fluid-dev.com/docs/guide/#%E5%BC%BA%E5%88%B6%E5%85%A8%E5%B1%80-https

**Comment by XSun771** [comment]
> [强制HTTPS](https://hexo.fluid-dev.com/docs/guide/#%E5%BC%BA%E5%88%B6%E5%85%A8%E5%B1%80-https)

感谢您的解答，我这里开启了之后，图片直接加载不出来了。。但在新标签页打开图片可以，不过自动退化回了http连接，我强制使用https前缀告知不被支持的协议。。估计是要在七牛云（我的图床）那边开启https支持。。但一旦使用https支持的话就不能用七牛云免费额度了。。。so。。可不可以增加不强制https简单使用http图片的功能呢。

谢谢

**Comment by zkqiang** [comment]
没这种功能，这是http协议规范
七牛云https花不了多少钱的...

**Comment by XSun771** [comment]
> 没这种功能，这是http协议规范
> 七牛云https花不了多少钱的...

了解了，谢谢解答。
