### ISSUE TITLE
为每一个post设置单独的author（多人blog）

### ISSUE THREAD

**Issue by vinjohn** [fluid-dev/hexo-theme-fluid#285]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html)实现的功能
- [ ] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

为每一个post设置单独的author。

#### 请描述您认为可行的解决方案

在网上有看到类似的实现，比如：https://yelog.org/2017/02/28/3-hexo-multiple-author/。
官方应该很早就支持在front-matter里添加author（https://github.com/hexojs/hexo/issues/673）
所以应该是可行的。

#### 考虑过的替代方案

对这一块不太懂。

**Comment by zkqiang** [comment]
emm... 
本主题暂时不支持作者这个属性

**Comment by zkqiang** [comment]
dev 分支已增加该功能，欢迎测试

使用方式：
1. 开启功能：
https://github.com/fluid-dev/hexo-theme-fluid/blob/0f98786af79126186dd6c78de8c7fe0218b25c7c/_config.yml#L208

2. 在文章 front-matter 里添加：
```
---
...
author: xxx
---
```

如果不添加，默认按 hexo 配置里 author 值
