### ISSUE TITLE
Utterances 无法加载

### ISSUE THREAD

**Issue by Lao-Liu233** [fluid-dev/hexo-theme-fluid#286]
#### 请确认

- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 本地 `hexo clean && hexo s` 后仍可复现
- [x] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述

浏览器: Chrome 80.0.3987.132 64位
utterances 无法加载。

#### 复现步骤
该 Bug 复现步骤如下：
任何时候/任何网络均可复现。

最好提供部署后能复现的页面地址：
https://blog.laoliu.eu.org/archives/911a91db.html

**Comment by zkqiang** [comment]
应该是接口的问题，其他用户也反馈了

实在不行换一个用吧

**Comment by Lao-Liu233** [comment]
好的，谢谢！
