### ISSUE TITLE
关于某个特定时间首页显示的问题

### ISSUE THREAD

**Issue by luosiwei-cmd** [fluid-dev/hexo-theme-fluid#288]
#### 请确认
- [ x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ x] 浏览器不属于 IE 等旧浏览器 
- [x ] 本地 `hexo clean && hexo s` 后仍可复现
- [ x] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述

首页显示出了问题，F12显示有一个 cdn 的地址的 ip 找不到
浏览器: Chrome 80.0.3987.132 64位

#### 复现步骤
现在的官网就是这样
最好提供部署后能复现的页面地址：
hexo.fluid-dev.com
#### 截图
这个自己就能看到……

**Comment by zkqiang** [comment]
没太明白你的描述...

我这里看没什么问题

**Comment by luosiwei-cmd** [comment]
![image](https://user-images.githubusercontent.com/61175380/84594300-d07ca580-ae83-11ea-83b6-b01e2abc43e9.png)

zhe'zhong'q这种情况很异常啊 @zkqiang

**Comment by luosiwei-cmd** [comment]
![image](https://user-images.githubusercontent.com/61175380/84594312-e7bb9300-ae83-11ea-992a-582a3fe79fdc.png)

还有bao报错

**Comment by luosiwei-cmd** [comment]
![image](https://user-images.githubusercontent.com/61175380/84594322-f6a24580-ae83-11ea-9266-68d6f4f8b57d.png)
@zkqiang

**Comment by zkqiang** [comment]
这个只是你那边的DNS解析或者局部地区CDN出问题了

你可以清理一下DNS缓存，如果解决不了的话，可以等一段时间再看看

你也可以通过 static_prefix.yml 自行更换其他公共CDN

**Comment by luosiwei-cmd** [comment]
@zkqiang 明白~谢谢！
