### ISSUE TITLE
 markdown流程图的背景色问题

### ISSUE THREAD

**Issue by HarrisonLee1998** [fluid-dev/hexo-theme-fluid#289]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
markdown流程图会出现代码块highlight的背景色
![image](https://user-images.githubusercontent.com/43055087/84621642-ac65a680-af0d-11ea-9aaf-9bbbe17967c8.png)
如果是使用的深色背景的话，流程图的字都看不清楚了，所以不得不使用浅色主题，请问这是配置问题还是主题的问题？

**Comment by zkqiang** [comment]
确实有这个问题，下个版本优化

可以先使用自定义CSS强制指定下背景色
