### ISSUE TITLE
表格标题不能居中

### ISSUE THREAD

**Issue by dormirr** [fluid-dev/hexo-theme-fluid#290]
#### 请确认
- [X] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等旧浏览器 
- [X] 本地 `hexo clean && hexo s` 后仍可复现
- [X] 清除浏览器缓存或更换浏览器仍可复现

#### Bug 描述
表格标题无法居中

浏览器: Microsoft Edge 83.0.478.50 64位

#### 复现步骤
`markdown` 代码如下：
```markdown
|  名称   |  版本   |               |
| :-----: | :-----: | :-----------: |
|  Nginx  |  1.16   |               |
| OpenJDK |   11    |               |
| 数据库  | Redis 5 | PostgreSQL 12 |
| Node.js |   12    |               |
```

`hexo g` 后生成的 `html` 如下：
```html
<table>
<thead>
<tr>
<th align="center">名称</th>
<th align="center">版本</th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr>
<td align="center">Nginx</td>
<td align="center">1.16</td>
<td align="center"></td>
</tr>
……
</tbody>
</table>
```

#### 截图
![1](https://user-images.githubusercontent.com/26898200/84879298-9dbdf180-b0bd-11ea-838b-3d29fdc036ba.png)

#### 理论上的样式
|  名称   |  版本   |               |
| :-----: | :-----: | :-----------: |
|  Nginx  |  1.16   |               |
| OpenJDK |   11    |               |
| 数据库  | Redis 5 | PostgreSQL 12 |
| Node.js |   12    |               |

**Comment by zkqiang** [comment]
可以把下面代码加入到自定义 CSS 中

```css
*[align="left"]
  text-align left

*[align="center"]
  text-align center

*[align="right"]
  text-align right
```
