### ISSUE TITLE
代码高亮模块BUG反馈

### ISSUE THREAD

**Issue by reputati0n** [fluid-dev/hexo-theme-fluid#291]
#### Bug 描述

复现步骤
1、修改代码高亮样式，本地及服务器端均无效
2、此时修改 bg_color:  选项，无论是false改成true还是true改为false均可，修改完成后本地的hexo代码高亮效果正常
3、执行hexo clean && hexo d -g 部署到博客之后，代码高亮效果失效，此时再hexo s访问本地hexo，效果同样失效
4、百分百复现

浏览器: Chrome 80.0.3987.132 64位

**Comment by zkqiang** [comment]
你先检查下自己的环境吧...  配置不变的情况下，不可能效果会来回变的

**Comment by reputati0n** [comment]
@zkqiang 已经更换目录重新初始化过hexo(hexo init)，重新下载release版主题，问题依旧，如果需要可以提供演示视频

**Comment by reputati0n** [comment]
已解决

**Comment by zkqiang** [comment]
最后是什么问题导致？

**Comment by reputati0n** [comment]
@zkqiang 是我自己安装的一款文章加密插件引起的，卸载之后效果正常，不好意思打扰了。
