### ISSUE TITLE
覆盖配置更新1.8.1是出现了theme.navbar.menu is not iterable 和Unhandled rejection TypeError:报错

### ISSUE THREAD

**Issue by liutuo008** [fluid-dev/hexo-theme-fluid#296]
![image](https://user-images.githubusercontent.com/33654458/85521774-57c1da00-b637-11ea-9fbd-1173ff2fffe0.png)
![image](https://user-images.githubusercontent.com/33654458/85521800-614b4200-b637-11ea-83f6-84a45a67bcbc.png)

**Comment by zkqiang** [comment]
报错信息很清除了，navbar.menu 配置不对

**Comment by liutuo008** [comment]
没修改过配置，下载下来解压，运行的时候就报错了

**Comment by zkqiang** [comment]
什么都没改不可能报错的...  demo就是原始代码生成的
请再检查下吧
