### ISSUE TITLE
perf : hey bro why the code syntax highlighting is vain

### ISSUE THREAD

**Issue by YUbuntu0109** [fluid-dev/hexo-theme-fluid#297]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

hey bro why the code syntax highlighting is vain and I don't know how to fix it, please refer to this [commit info](https://github.com/YUbuntu0109/YUbuntu0109.github.io/commit/16b4ba6ac73302b5444f57b111b1c0428b297258) and my [hexo blog](ishacker.net)

* google chrome version is latest : `83.0.4103.116`

**Comment by zkqiang** [comment]
Thx, this is a bug, you can use `style: Vs2015`(non space)

**Comment by YUbuntu0109** [comment]
> Thx, this is a bug, you can use `style: Vs2015`(no space)

thanks bro this bug be fixed successfully  and thanks for your works again !
