### ISSUE TITLE
显示数学公式问题

### ISSUE THREAD

**Issue by Ningsir** [fluid-dev/hexo-theme-fluid#301]
![image](https://user-images.githubusercontent.com/34963409/85941496-062a8f80-b956-11ea-806a-21ee3d44dac0.png)

**Comment by Ningsir** [comment]
数学公式拥挤在一块

**Comment by zkqiang** [comment]
请提供一下更详细的信息，比如用的是哪个 render、 md公式源代码、 部署后的页面

**Comment by Ningsir** [comment]
mathjax, katex两个我都试了，都有这样的错误。[部署页面](https://blog.ningxin.site/2020/05/24/V-Net%E7%AC%94%E8%AE%B0/)，数学公式如下：
```
$$
\frac{\partial D}{\partial p_{j}}=2\left[\frac{g_{j}\left(\sum_{i}^{N} p_{i}^{2}+\sum_{i}^{N} g_{i}^{2}\right)-2 p_{j}\left(\sum_{i}^{N} p_{i} g_{i}\right)}{\left(\sum_{i}^{N} p_{i}^{2}+\sum_{i}^{N} g_{i}^{2}\right)^{2}}\right]
$$
```

**Comment by zkqiang** [comment]
应该是 mathjax 版本没更新

https://github.com/fluid-dev/hexo-theme-fluid/blob/7389bbc1d17db84c3575d7dac4934fa0b1b27471/_static_prefix.yml#L56

**Comment by Ningsir** [comment]
大概是浏览器的原因, math renderer选择common HTML就会出现我这个问题。
![image](https://user-images.githubusercontent.com/34963409/85947612-69c8b300-b97e-11ea-9265-6af39ebaacfd.png)

**Comment by zkqiang** [comment]
你先改下你的版本试试，你现在加载的是2.7版本

![image](https://user-images.githubusercontent.com/32983588/85948199-0f315600-b982-11ea-80af-2d333edb7d81.png)

**Comment by Ningsir** [comment]
这个版本应该在哪改呢？

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/7389bbc1d17db84c3575d7dac4934fa0b1b27471/_static_prefix.yml#L56

**Comment by Ningsir** [comment]
我的版本和你的是一样的呀

**Comment by zkqiang** [comment]
查看一下覆盖配置

**Comment by pxxyyz** [comment]
这个我会答🙂，应该是装了`hexo-renderer-kramed`和`hexo-renderer-mathjax`，然后在`/node_modules/hexo-renderer-mathjax/mathjax.html`里加了
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML"></script>
```
把这个改成
```
<script id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg-full.js">
</script>
```
或者直接删了就可以了，_static_prefix.yml里有添加最新的MathJax.js。
可以看我的博客[数学公式](https://pxxyyz.com/posts/32990/#%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F)

**Comment by Ningsir** [comment]
多谢，问题解决了，其实删除掉hexo-renderer-mathjax就行了，不能有多个渲染器。
