### ISSUE TITLE
Too few icons such as no LeetCode icon

### ISSUE THREAD

**Issue by YUbuntu0109** [fluid-dev/hexo-theme-fluid#302]
#### 如是功能需求，请确定符合以下情况
- [ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html)实现的功能
- [ ] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题
 if you add more icons about coding maybe the fluid project will be better although it's already pretty good.
thanks for your work bro.

#### 请描述您认为可行的解决方案
[LeetCode Icon](https://www.iconfont.cn/search/index?searchType=icon&q=leetcode)

**Comment by vinceying** [comment]
可以自己引入。
https://hexo.fluid-dev.com/docs/icon/#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E6%A0%87

**Comment by YUbuntu0109** [comment]
> 可以自己引入。
> https://hexo.fluid-dev.com/docs/icon/#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E6%A0%87

好吧，只能这样了.
