### ISSUE TITLE
有一个地方感觉需要优化下

### ISSUE THREAD

**Issue by Klien-m** [fluid-dev/hexo-theme-fluid#303]
在网页的Category页面下，点击一个合并的分类（箭头向右的那种），展开后画面会生硬的网上移动一段距离，将刚才点击的category的最后一个移向视野中央

**Comment by zkqiang** [comment]
画面不会移动啊

具体可见：https://hexo.fluid-dev.com/categories/

**Comment by Klien-m** [comment]
https://klien-m.github.io/categories/ ，你看下，这个是我刚搭建的博客，
可能是加了那个音乐控件 aplayer 才导致了这种情况，我去掉音乐控件之后，这种情况就消失了

**Comment by Klien-m** [comment]
顺便问下，页面的加载逻辑是在哪里实现的，我看代码没找到，原因是这样的，我是用 hexo-blog-encrypt 插件加密一篇博文时，遇到了这样的问题，如果博文里含有图片，加密后图片就无法正常加载。hexo-blog-encrypt 插件文档里说，找到页面的加载代码，在博文后面添加上或许可以解决加密解密后加载的问题。但是我在你的主题的代码里搜索了下，实在是找不到

**Comment by Klien-m** [comment]
加密后加载图片的问题已经得到了解决，不用麻烦了

**Comment by pxxyyz** [comment]
这个加密图片不显示的我也遇到了，在markdown最后添加
```
<script src="/js/lazyload.js"></script>
<script>
    $('#post img:not(.no-zoom img, img[no-zoom]), img[zoom]').each(
      function () {
        var element = document.createElement('a');
        $(element).attr('data-fancybox', 'images');
        $(element).attr('href', $(this).attr('src'));
        $(this).wrap(element);
      }
    );
</script>
```
就可以了

**Comment by Klien-m** [comment]
我问开发者了，他给的解决方案是这样的，在对应文档最后添加
```
<script>
    Array.prototype.slice.call(document.querySelectorAll('img[srcset]')).forEach(x => x.setAttribute('srcset', x.src));
</script>
```
这样也可以的。

**Comment by pxxyyz** [comment]
图片能显示了，但是fancybox效果没有了。

**Comment by zkqiang** [comment]
比较好的解决办法可以参考 #339 

当然彻底的解决办法还是要 hexo-blog-encrypt 来支持
