### ISSUE TITLE
暗色模式的tag(便签)和图片能不能也相应变暗

### ISSUE THREAD

**Issue by pxxyyz** [fluid-dev/hexo-theme-fluid#307]
#### 如是功能需求，请确定符合以下情况
- [ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html)实现的功能
- [ ] 难以通过第三方插件实现

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/commit/88f005cb2c999bb6cdb3940299bb0d451cee6546

**Comment by pxxyyz** [comment]
我也diy了一下，写在custom.css里了，效果在<https://pxxyyz.com/posts/dark-mode-test/>，不知道有没有用:smile:

**Comment by zkqiang** [comment]
还不错
