### ISSUE TITLE
能否支持一下七牛存储

### ISSUE THREAD

**Issue by wdkGitHub** [fluid-dev/hexo-theme-fluid#309]
能否支持一下七牛存储，把图片放在GitHub上访问速度实在太慢了。如有更好的解决方案也可以。

**Comment by zkqiang** [comment]
这个和主题无关哦，你通过一些工具上传到七牛，然后用绝对链接引用图片即可

推荐 [PicGo](https://github.com/Molunerfinn/PicGo)
