### ISSUE TITLE
评论问题

### ISSUE THREAD

**Issue by wdx13666** [fluid-dev/hexo-theme-fluid#312]
utterances配置好后，页面不显示评论框  Networl有这个链接https://utteranc.es/utterances.html?src=https%3A%2F%2Futteranc.es%2Fclient.js&repo=wdx13666%2Fcomment&issue-term=pathname&theme=github-light&crossorigin=anonymous&url=http%3A%2F%2Flocalhost%3A4000%2F2018%2F11%2F11%2FGit%2F&origin=http%3A%2F%2Flocalhost%3A4000&pathname=2018%2F11%2F11%2FGit%2F&title=Git%20-%20Tuan%20Dog

**Comment by zkqiang** [comment]
试一下dev分支最新代码
https://github.com/fluid-dev/hexo-theme-fluid/commit/ba2f35f8de3365581aff65ea0597cb1dd5aa9919
