### ISSUE TITLE
请问自定义页面如何添加目录？

### ISSUE THREAD

**Issue by hishark** [fluid-dev/hexo-theme-fluid#313]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

请问自定义页面如何添加目录？
我尝试在markdown头部添加`toc: true`没有起作用~

**Comment by hishark** [comment]
https://xiaoqizhang.com/techdiary/
🔼比如这个页面

**Comment by zkqiang** [comment]
不能添加，建议改成文章链上去

**Comment by hishark** [comment]
> 不能添加，建议改成文章链上去

好的，谢谢啦！(≧∇≦)ﾉ

**Comment by hishark** [comment]
> 不能添加，建议改成文章链上去

https://xiaoqizhang.com/1997/07/07/techdiary/
⬆️哈哈哈，你的建议很好！成啦！感谢=v=
