### ISSUE TITLE
Utterances 配置之后插入的 DOM 节点位置有误

### ISSUE THREAD

**Issue by rxliuli** [fluid-dev/hexo-theme-fluid#314]
#### 请确认

- [x] 是最新版本
- [x] Chrome
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

配置完了 Utterances 之后没显示，看了一下 dom 才发现是插入节点的位置在 head 标签里。。。

#### 复现步骤

复现地址：https://blog.rxliuli.com/p/9fbf8bb4/

滚动到最下方，然而并没有评论加载出来。

#### 截图

![image](https://user-images.githubusercontent.com/24560368/87609213-7bf37100-c734-11ea-9d41-ba3ab2758c37.png)

**Comment by zkqiang** [comment]
master 分支已修复
