### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by rxliuli** [fluid-dev/hexo-theme-fluid#315]
#### 请确认

- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

`ts/tsx/marmaid` 显示都有问题

#### 复现步骤

问题页面：

- ts: https://blog.rxliuli.com/p/e4268664/
- mermaid: https://blog.rxliuli.com/p/4e033209/

#### 截图

![image](https://user-images.githubusercontent.com/24560368/87631454-e83c9780-c769-11ea-9b92-44a863975f0a.png)
![image](https://user-images.githubusercontent.com/24560368/87631388-cb07c900-c769-11ea-80ad-a1306f7fa930.png)
![image](https://user-images.githubusercontent.com/24560368/87631398-ce02b980-c769-11ea-8731-b3e5410dff51.png)

**Comment by zkqiang** [comment]
盲猜是你同时装了 highlight 插件

**Comment by rxliuli** [comment]
> 盲猜是你同时装了 highlight 插件

不清楚，吾辈要先对比一下 package.json。。。

**Comment by rxliuli** [comment]
你是对的，之前的 theme 不支持 jsx 然后装了一个插件 hexo-prism-plugin。。。

**Comment by rxliuli** [comment]
说起来官方推荐的 utterances 评论不支持暗模式切换你知道么？

![image](https://user-images.githubusercontent.com/24560368/87634708-63a14780-c770-11ea-8c67-d7ff2bc3bc01.png)

**Comment by zkqiang** [comment]
utterances 主题是自己设的。。这个没太好办法适配暗色

**Comment by rxliuli** [comment]
吾辈观察到该项目依赖了 Highlight 以实现代码高亮，但它并不支持 tsx，参考 https://github.com/highlightjs/highlight.js/issues/1155，是否有计划使用 prismjs？

**Comment by zkqiang** [comment]
prismjs 在 hexo 5 刚支持，等再普及几个月吧

另外 https://github.com/fluid-dev/hexo-theme-fluid/issues/335 这边增加了 utterances 暗色，有空可以参与测试

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/commit/140b77bb3389101071236e24d939845f03e2c4c8

欢迎测试

**Comment by rxliuli** [comment]
@zkqiang 哈，吾辈可不想当小白鼠，除非必要，一般还是不动基建，毕竟博客内容更重要 (*/ω＼*)
