### ISSUE TITLE
leancloud 统计相关

### ISSUE THREAD

**Issue by JalenChuh** [fluid-dev/hexo-theme-fluid#316]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html)实现的功能
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题
leancloud 统计希望能提供 `只增加，不查询` 选项，有时候查询加载挺慢的。

**Comment by zkqiang** [comment]
实现不了，自增必须先查询一次获得 `objectId`

https://github.com/fluid-dev/hexo-theme-fluid/blob/c181c0c12554c8c0cffbf0a80519f74e3658604f/layout/_partial/plugins/leancloud.ejs#L90

**Comment by JalenChuh** [comment]
好吧
