### ISSUE TITLE
个人页部分社交账号无法显示

### ISSUE THREAD

**Issue by congjinyebaiya** [fluid-dev/hexo-theme-fluid#317]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

根据博客使用说明加入了酷安账号和图标，但是无法在网页中正常显示，请问这是什么问题导致的呢？

![Screenshot_2020-07-18-13-07-59-887_com.github.android.jpg](https://user-images.githubusercontent.com/41639269/87845303-b4dc4300-c8f8-11ea-9d9d-37d7b78f714c.jpg)

查看网页源代码可以看到有相应代码

![Screenshot_2020-07-18-13-05-12-901_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/41639269/87845304-b9a0f700-c8f8-11ea-802e-b65938ab2084.jpg)

但是网页中相应部分没有正常显示该帐号

**Comment by congjinyebaiya** [comment]
之前是放置的酷安图标，无法正常显示后我换用了copyright图标上去，还是无法显示

**Comment by zkqiang** [comment]
检查是否一致：
https://github.com/fluid-dev/hexo-theme-fluid/blob/f06c9502de222c0fff07f5db51042abc58227393/_static_prefix.yml#L38

**Comment by congjinyebaiya** [comment]
您好，感谢你的回复，是我自己没有引入自定义css的原因，现在已经可以正常显示了
