### ISSUE TITLE
请求添加代码行号展示和代码自动换行支持

### ISSUE THREAD

**Issue by Navimark** [fluid-dev/hexo-theme-fluid#318]
#### Make sure
- [x] Difficult to implement through [custom](https://hexo.fluid-dev.com/docs/en/guide/#custom-js-css-html).
- [X] Difficult to implement through third-party plugins.

#### Is your feature request related to a problem? Please describe

1. 为代码添加行号显示支持
2. 单行代码过长时自动换行
#### Describe the solution you'd like

考虑过按照 [Hexo高亮](https://www.ieclipse.cn/2016/07/18/Web/Hexo-dev-highlight/) 自定义实现，但本人没有前端编程基础，实在搞不懂这些配置应该写在哪里😪，希望作者考虑将其集成为官方 feature，通过配置选项开启
#### Describe alternatives you've considered

不太懂

**Comment by zkqiang** [comment]
> 1. 为代码添加行号显示支持

这个后续会支持

> 2. 单行代码过长时自动换行

还没见过换行的代码...  代码规范一般单行不超过120字符，请规范你的代码把...
