### ISSUE TITLE
FireFox 中暗黑模式点击事件失效

### ISSUE THREAD

**Issue by JalenChuh** [fluid-dev/hexo-theme-fluid#320]
#### 请确认

- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

浏览器 FireFox 78.0.2 (64 位) 

官方 Demo，暗黑模式手动切换失效（自动切换正常）

**Comment by zkqiang** [comment]
thx 已修复
