### ISSUE TITLE
目录可以调整到左边吗，习惯看左边的目录~

### ISSUE THREAD

**Issue by sulimin-nb** [fluid-dev/hexo-theme-fluid#321]
#### 如是功能需求，请确定符合以下情况
- [ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html)实现的功能
- [ ] 难以通过第三方插件实现

**Comment by sulimin-nb** [comment]
就是可以选择放到右边，也可以选择放到左边那种

**Comment by zkqiang** [comment]
放左边不太协调，有兴趣自己改吧
