### ISSUE TITLE
Chromium Edge 黑暗模式异常

### ISSUE THREAD

**Issue by Lao-Liu233** [fluid-dev/hexo-theme-fluid#322]
#### 请确认
- [ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

最新 pull 版本，用 Chromium Edge 访问显示如下图：

黑暗模式未能生效；
Safari 下可以正常显示。
#### 复现步骤
该 Bug 复现步骤如下：
网址： https://blog.laoliu.eu.org

#### 截图
![image](https://user-images.githubusercontent.com/52364111/88518531-3895de00-d023-11ea-983b-cc13baa1f871.png)

**Comment by zkqiang** [comment]
有没有包括 https://github.com/fluid-dev/hexo-theme-fluid/commit/d6a3bcd0ee916ccdd8a1dc4269e81f2591f3bf72 这个 commit？

我专门下了个 Chromium Edge ，发现没啥问题。。

![image](https://user-images.githubusercontent.com/32983588/88613575-56655080-d0c0-11ea-9274-4a60bf69b898.png)

**Comment by Lao-Liu233** [comment]
今天试了一下有没问题了（捂脸）
