### ISSUE TITLE
首页无法正常显示数学公式

### ISSUE THREAD

**Issue by homesquatsuniversity** [fluid-dev/hexo-theme-fluid#323]
#### 请确认
- [ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

**Comment by zkqiang** [comment]
麻烦写下描述吧...   不然都不知道你是什么情况

请仔细查阅用户指南
