### ISSUE TITLE
lazyload 问题

### ISSUE THREAD

**Issue by wkmyws** [fluid-dev/hexo-theme-fluid#325]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

lazyload设为true（即默认状态）时，
以夸克浏览器为例，
about页面的头像加载失败
#### 复现步骤
该 Bug 复现步骤如下：
1. 夸克访问 https://hexo.fluid-dev.com/
2. 菜单栏目里选择about页面
3. 头像会处于加载状态

同样有问题的是华为自带的浏览器
而QQ内置的浏览器则正常显示（先显示loading.gif，再显示图片）

禁用lazyload则正常显示，
初步看是 `/themes/hexo-theme-fluid/source/js/lazyload.js` 文件的问题
考虑换个lazyload的脚本？

#### 截图
![Screenshot_20200801_104642_com quark browser](https://user-images.githubusercontent.com/45654909/89092423-50cf7980-d3e4-11ea-8e00-53424568ce42.jpg)

**Comment by zkqiang** [comment]
没复现出来，暂时使用 `onlypost` 吧

**Comment by zkqiang** [comment]
这个情况现在还有吗？

是不是只有这里的图片会加载不出来？

**Comment by wkmyws** [comment]
真奇怪，现在又没这个问题了，你把这个问题关了吧:smile:
