### ISSUE TITLE
what is the banner picture used in the example (from README)

### ISSUE THREAD

**Issue by icanotc** [fluid-dev/hexo-theme-fluid#330]
#### Make sure
- [x ] Upgrade the latest [release version](https://github.com/fluid-dev/hexo-theme-fluid/releases).
- [x ] No solution found in [Documentation][https://hexo.fluid-dev.com/docs/en/]

#### Describe the question
the picture in README looked really clean, please share the source of the picture.

also, I felt like there should be themes built on top of the fluid theme

**Comment by zkqiang** [comment]
Sorry, I lost the link to this picture, you can try it here: https://wallhaven.cc/

**Comment by icanotc** [comment]
thank you!

**Comment by icanotc** [comment]
https://wallhaven.cc/w/g8xjqe

found it, but it does indeed look very clean

**Comment by zkqiang** [comment]
All my pictures are from here haha, nice website
