### ISSUE TITLE
评论模块的主题能否跟随网站主题变化？

### ISSUE THREAD

**Issue by xX-Hacbox-Xx** [fluid-dev/hexo-theme-fluid#335]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html)实现的功能
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

使用Utterances评论模块需要手动选择评论模块的主题，但选择深色或者浅色主题后模块在浅色或者深色主题下显得很不和谐
#### 请描述您认为可行的解决方案

评论模块的主题能否跟随网站显示模式（深色/浅色）变化
#### 考虑过的替代方案

暂无

**Comment by zkqiang** [comment]
暂时没什么好办法..
正是因为 Utterances 也是靠配置指定主题，才导致无法统一适配

**Comment by xX-Hacbox-Xx** [comment]
有大佬对Utterances做了汉化处理，官网：[beaudar](https://beaudar.lipk.org/)
在这个界面评论模块主题是可以跟随页面变化的（点击“博客主题”可以更换），不知道能否给予启发？

**Comment by zkqiang** [comment]
感谢，这个确实内置了这种功能，回头有空研究一下

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/commit/a5c1c3ff1b95840177475931811e1bf3b5404342

有空可以帮忙测试一下（我的 Utterances 删除了... ）

**Comment by zkqiang** [comment]
有群友已经测试了，应该没问题了
