### ISSUE TITLE
跳转位置设置点时忽略适配导航栏的高度

### ISSUE THREAD

**Issue by aolog** [fluid-dev/hexo-theme-fluid#337]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

跳转位置设置点时忽略适配导航栏的高度

#### 复现步骤
该 Bug 复现步骤如下：
1. 点击到达跳转位置演示
2. 然后向上滚动
3. 会出现跳转位置设置点被导航栏遮挡

复现的页面地址（该链接仅供测试）:
https://c.aolog.cn/test/2020/07/26/%E6%90%AD%E9%85%8D%20Fluid%20%E5%A6%82%E4%BD%95%E4%BC%98%E9%9B%85%E7%9A%84%E5%86%99%E4%B8%80%E7%AF%87%E6%96%87%E7%AB%A0/

文章转载至作者：Vince
原文地址：https://i.vince.pub/posts/14677127/

#### 截图
![test](https://user-images.githubusercontent.com/48140334/90613390-e324a980-e23b-11ea-88db-e9c97fab3870.gif)

**Comment by zkqiang** [comment]
因为这个不是主题内置的脚注。。。。

![image](https://user-images.githubusercontent.com/32983588/90635285-9224ad80-e25b-11ea-95ea-dcb0af6c67af.png)

这个才是
