### ISSUE TITLE
脚注功能没有

### ISSUE THREAD

**Issue by aolog** [fluid-dev/hexo-theme-fluid#338]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

什么都没有改用的都是默认的，脚注功能默认是开启的
![test](https://user-images.githubusercontent.com/48140334/90616326-e02bb800-e23f-11ea-9e66-6b7f3d779fdf.jpg)

**Comment by aolog** [comment]
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.0.2"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0"
  }
}

**Comment by zkqiang** [comment]
https://hexo.fluid-dev.com/docs/guide/#%E8%84%9A%E6%B3%A8
