### ISSUE TITLE
ToC and Copy Code Button messing up with hexo-blog-encrypt

### ISSUE THREAD

**Issue by cyberwr3nch** [fluid-dev/hexo-theme-fluid#339]
#### Make sure
- [x] No solution found in [Documentation][https://hexo.fluid-dev.com/docs/en/]
- [x] Upgrade the latest [release version](https://github.com/fluid-dev/hexo-theme-fluid/releases).

#### Describe the question
- When I encrypt the posts with [hexo-blog-encrypt](https://github.com/MikeCoder/hexo-blog-encrypt), after unlocking the post, I have to refresh the page to get the TOC / Code Copy Button
- But the code copy button and ToC works fine for unencrypted posts
- I Dont Know weather its a bug / something else. Help me with solving this issue. Thanks

**Comment by zkqiang** [comment]
Maybe the button initialization failed, I will follow this problem

**Comment by pxxyyz** [comment]
It is a a known issue in hexo-blog-encrypt (see the [About Callback](https://github.com/MikeCoder/hexo-blog-encrypt#about-callback) for details)
- You can try the following code at the end of your post as a callback of toc which is a part of [tocjs.ejs](https://github.com/fluid-dev/hexo-theme-fluid/blob/master/layout/_partial/plugins/tocjs.ejs).
```
<script>
  $(document).ready(function () {
      var boardCtn = $('#board-ctn');
      var boardTop = boardCtn.offset().top;
      tocbot.init({
        tocSelector: '#tocbot',
        contentSelector: '#post-body',
        linkClass: 'tocbot-link',
        activeLinkClass: 'tocbot-active-link',
        listClass: 'tocbot-list',
        isCollapsedClass: 'tocbot-is-collapsed',
        collapsibleClass: 'tocbot-is-collapsible',
        scrollSmooth: true,
        headingsOffset: -boardTop
      });
      if ($('.toc-list-item').length > 0) {
        $('#toc').css('visibility', 'visible');
      }
  });
</script>
```
- As for copy button, I don't get this bug. You can see [clipboard-use.js](https://github.com/fluid-dev/hexo-theme-fluid/blob/master/source/js/clipboard-use.js), or use this JS file directly
```
<script src="/js/clipboard-use.js"></script>
```
Hope it helps.

**Comment by cyberwr3nch** [comment]
Thanks, @pxxyyz ,  the TOC is working fine with your help. But the Copy button still fails, I have to  refresh to make it appear

**Comment by zkqiang** [comment]
I suggest that you insert the code in your markdown:

```js
<script>
  if (location.href.indexOf("#reloaded") == -1) {
    location.href = location.href + "#reloaded";
    location.reload();
  }
</script>
```

This code will make the page refresh automatically after enter the password.

Of course, I think better way that hexo-blog-encrypt can support this feature, you can send an issue.
