### ISSUE TITLE
Search Bar results error

### ISSUE THREAD

**Issue by iamdumm** [fluid-dev/hexo-theme-fluid#340]
#### Make sure
- [x] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases).
- [x] No solution found in [documentations](https://hexo.fluid-dev.com/docs/en/)

#### Describe the question
- I have the post named `Hello World` and it is locally hosted, But when i search the post using the search bar.
- Nothing is showing in the outupt
![post-available](https://user-images.githubusercontent.com/36810000/91129118-6e0c0680-e677-11ea-8c3c-467678591a63.png)
- Like this
![search-query](https://user-images.githubusercontent.com/36810000/91129215-9c89e180-e677-11ea-99ab-f5b4c060d882.png)
- Things that I have tried while searching the post
- [x] Enter full post name
- [x] Case sensitive name for the post
- [x] Only the First word of the posts title
- [x] Only the Second word of the posts title

- Someone help, really need help in this search bar thing

**Comment by cyberwr3nch** [comment]
I am here, facing the same problem

**Comment by cyberwr3nch** [comment]
just try to start over, and after cloning the theme give `npm install` to get things work smoothly

**Comment by zkqiang** [comment]
Please give me the url after deployment

**Comment by zkqiang** [comment]
I closed the issue, If the problem still exists, you can reopen it
