### ISSUE TITLE
DisqusJs无法生效

### ISSUE THREAD

**Issue by DefectingCat** [fluid-dev/hexo-theme-fluid#341]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

在使用DisuqusJs时无法生效，按照[DisqusJs](https://github.com/SukkaW/DisqusJS)进行配置的，获取到了public key，并填在了主题的配置文件中。

![image.png](https://i.loli.net/2020/08/27/VLCuUJFINZ8OgE4.png)

不使用DisqusJs的情况下，只用Disqus，在网络通畅的情况下是可以正常加载的。所以Disqus的静态文件应该都能正常加载。

在console里没有任何的文件出现加载错误。关闭缓存进行的刷新也是同样。

![image.png](https://i.loli.net/2020/08/27/YjnphrfzUdBP8qc.png)

这是我的测试站点[https://1v1jyv.coding-pages.com/](https://1v1jyv.coding-pages.com/)

**Comment by LitStronger** [comment]
> #### 请确认
> * [x]  是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
> * [x]  在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法
> 
> #### 问题描述
> 在使用DisuqusJs时无法生效，按照[DisqusJs](https://github.com/SukkaW/DisqusJS)进行配置的，获取到了public key，并填在了主题的配置文件中。
> 
> ![image.png](https://camo.githubusercontent.com/40dfb30f6c01a2b3c431f4248edd6f41e4173f77/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30382f32372f564c4375554a46494e5a384f6745342e706e67)
> 
> 不使用DisqusJs的情况下，只用Disqus，在网络通畅的情况下是可以正常加载的。所以Disqus的静态文件应该都能正常加载。
> 
> 在console里没有任何的文件出现加载错误。关闭缓存进行的刷新也是同样。
> 
> ![image.png](https://camo.githubusercontent.com/edea524b68531b39cf0bc08ed60ec66ad4672c41/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30382f32372f596a6e706872667a556442503871632e706e67)
> 
> 这是我的测试站点https://1v1jyv.coding-pages.com/

配置文件里文章页的评论功能有开启吗？你控制台貌似没加载disqus的js文件

**Comment by DefectingCat** [comment]
上述描述的可能不够详细，这里是我的[config.yml](https://github.com/DefectingCat/DefectingCat.github.io/blob/file/source/_data/fluid_config.yml#L250-#L252)，配置文件应该问题不大，评论应该也是正常打开的。

主要现象就是使用了DisqusJs之后，评论就消失了。

**Comment by zkqiang** [comment]
写错了，修改试一下

https://github.com/fluid-dev/hexo-theme-fluid/commit/ea7cbf0221fdead29a581a91d72046be0cb0934a#diff-c926f7f4d8571817fe020e7b25fdd58eR14

**Comment by DefectingCat** [comment]
修改过已经正常，网通不通的两个模式都能正常加载。感谢❤

![image.png](https://i.loli.net/2020/08/27/TrWudIV4Hiewzop.png)
