### ISSUE TITLE
[BUG] mac chrome 下页面头部图片滑动闪屏

### ISSUE THREAD

**Issue by mritd** [fluid-dev/hexo-theme-fluid#342]
#### 请确认

- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现 
- [x] 已经排除是其他 Hexo 插件影响

hexo 只有 rss 插件，浏览器已经通过 `open -na "Google Chrome" --args --user-data-dir=test_chrome` 完全开启新的 chrome 实例测试。

#### Bug 描述

mac chrome 下页面头部图片部分滑动出现闪屏现象

#### 复现步骤

任意页面滑动皆可复现

测试地址: [mritd.com](https://mritd.com)

#### 截图

录制了一个 gif 图，由于太大(**77MB 请勿手机打开**)目前已上传到 CDN，作者看到以后麻烦回复一下，然后我从 CDN 移除

~~http://.....~~

**Comment by zkqiang** [comment]
我也是 mac， chrome 版本84.0.4147.135，第一次见到这种问题，我在你的地址也没复现出来，暂时定位不到问题的原因

**Comment by akiirokaede** [comment]
我在 Windows 的 Chrome 上也发现了类似的问题（版本为 85.0.4183.83）。

正打算将博客改为 Hexo 搭配 Fluid 主题，然后访问 https://hexo.fluid-dev.com/ 打算预览主题效果的时候复现了这一 bug。

**Comment by DefectingCat** [comment]
我在我的各个测试站点中都有这个情况，就是在首页标题打字机打字的时候，向下滑动背景图就会闪屏。

**Comment by zkqiang** [comment]
@DefectingCat 打字结束后就不会闪屏吗？可以尝试关闭打字机效果试一下？

https://github.com/fluid-dev/hexo-theme-fluid/blob/0a8bf449844cd6f9e5566e2b9c725e40c5020926/_config.yml#L30

**Comment by DefectingCat** [comment]
> @DefectingCat 打字结束后就不会闪屏吗？可以尝试关闭打字机效果试一下？
> 
> https://github.com/fluid-dev/hexo-theme-fluid/blob/0a8bf449844cd6f9e5566e2b9c725e40c5020926/_config.yml#L30

嗯，打字结束后滑动就不闪了，不是整个屏幕闪，只是打字机标题后面的背景图在闪，这个问题复现不是100%，我今天换了台电脑目前情况还好，等下次出现的时候我关了打字机试一下。

**Comment by zkqiang** [comment]
@mritd @akiirokaede 二位也可以一起测试一下

**Comment by DefectingCat** [comment]
@zkqiang 我已经确定问题复现的环境，不是打字机的问题，关了打字机一样闪。**最新的Chrome 85.0.4183.83**，背景图滑动的时候一定会闪白。

我测试了两个站点，一个是我目前在线的，打字机没关。还有个是本地的hexo server，打字机关了，两个都会闪

我也仔细观察了一下，背景闪白的主要原因是：**在滑动的时候背景会消失大概不到一秒钟**，整个背景变成灰色的，之后会立马出来。

我有视频和gif，但是体积略大，所以放在了Onedrive，大佬麻烦自己下载看下。

[file](https://defectink-my.sharepoint.com/:f:/g/personal/i_defectink_onmicrosoft_com/Emfyf_3vSjRPgWGGvYiG9s4BaWdB9O-oGkMnRQraBkdtPg?e=dkPr30)

另外，我录制到了背景消失的帧。

<img width="1362" alt="11" src="https://user-images.githubusercontent.com/25033493/91652153-da976300-eac6-11ea-9649-4d907fb824d0.png">

**Comment by zkqiang** [comment]
@DefectingCat 

麻烦再调试一次吧，把 Main 那一列收起来，我看下所有的线

![image](https://user-images.githubusercontent.com/32983588/91652330-ceaca080-eac8-11ea-8cf7-aa8101eaa2e6.png)

**Comment by DefectingCat** [comment]
还有什么帮上忙的可以随时联系我

<img width="431" alt="批注 2020-08-30 140247" src="https://user-images.githubusercontent.com/25033493/91652394-8c379380-eac9-11ea-8f17-12c0ca3355c9.png">

**Comment by DefectingCat** [comment]
另外，这个console的调试可以导入，这是个是我的[调试log](https://defectink-my.sharepoint.com/:u:/g/personal/i_defectink_onmicrosoft_com/EXbVZGtvwV9Ln35K7TeMv8QBPUD8pGUOFo8DrVTr0CjTTQ?e=cBtneV)。

用这个导入就可以复现我的log了

<img width="368" alt="2" src="https://user-images.githubusercontent.com/25033493/91652435-e89ab300-eac9-11ea-8cd5-235ef471e424.png">

**Comment by zkqiang** [comment]
@DefectingCat 

尝试关闭视差滚动：

https://github.com/fluid-dev/hexo-theme-fluid/blob/0a8bf449844cd6f9e5566e2b9c725e40c5020926/_config.yml#L147

如果成功关闭的话，滚动的时候面板将不会再伸缩，背景图也不会有压缩感（所以注意下有没有生效）

![image](https://user-images.githubusercontent.com/32983588/91652563-2f3cdd00-eacb-11ea-8152-7ceb213e5750.png)

**Comment by DefectingCat** [comment]
@zkqiang  我在本地hexo server测试的，关闭视差滚动后就没有出现了。（我还挺喜欢那个视差滚动的

**Comment by zkqiang** [comment]
@DefectingCat  定位到问题源头就好办，可能这里 transform 动画太消耗性能，我再研究下吧..

**Comment by DefectingCat** [comment]
@zkqiang 没帮上什么忙，

新版chrome访问咱们这个主题的站点貌似都是这个问题，另外，背景图片是全屏的貌似闪的更厉害一点。我用60帧录制大佬的站点，平均15帧率里大概有三帧是白色的。效果堪比闪关灯🤣

<img width="672" alt="3" src="https://user-images.githubusercontent.com/25033493/91652888-d91d6900-eacd-11ea-95cc-eaebc4954269.png">

感觉还是问题还是比较恶性的，大佬加油。

**Comment by zkqiang** [comment]
@DefectingCat  确实是新版chrome才出现的，我通过另一台电脑的chrome更新后，成功复现了

**Comment by mritd** [comment]
我暂时先把视差关掉吧 😁

**Comment by DefectingCat** [comment]
@zkqiang 对，目前这有这个版本的chrome出现的这个问题，大概率还是chrome的问题。我推荐大佬去chromium的[bugs论坛](https://bugs.chromium.org/p/chromium/issues/list)发个issue反馈下看看。我以前发过一个issue，他们的效率还是蛮高的

**Comment by zkqiang** [comment]
@DefectingCat 

试一下这个 commit https://github.com/fluid-dev/hexo-theme-fluid/commit/581722dc82a6922b6ad5dc150638c69e34839425

**Comment by DefectingCat** [comment]
@zkqiang  我在我本地的实例上使用了hexo server，目前这个问题暂时没有复现了。我也将首页背景图调成了100%，也没有出现闪屏的情况。看样子应该是解决了，css我不是很懂，是新chrome加了什么奇怪的东西吗

----------------------------------------------

另外多个嘴，咱们这个版本检测好像失效好久了，要不有空也给它修了吧🤣

<img width="440" alt="332" src="https://user-images.githubusercontent.com/25033493/91653528-5815a000-ead4-11ea-8f8e-d268a89c6c1d.png">

**Comment by zkqiang** [comment]
@DefectingCat 不知道chrome加了什么，`will-change` 可以调用 GPU 来渲染动画

版本检测已修复  https://github.com/fluid-dev/hexo-theme-fluid/commit/08f5dde772d127b35bf4932410f27cd3c0c1763c

**Comment by zkqiang** [comment]
@mritd @akiirokaede  可以一起更新下 https://github.com/fluid-dev/hexo-theme-fluid/commit/581722dc82a6922b6ad5dc150638c69e34839425 这个commit

**Comment by DefectingCat** [comment]
@zkqiang 感谢大佬，两个commit我都试了，目前问题都解决了。

**Comment by akiirokaede** [comment]
@zkqiang 非常感谢，我这边测试了一下，也没有什么问题了

**Comment by mritd** [comment]
OT: 我发现直接将  dev 分支 clone 后放到 themes 目录下，会导致 img 内的 avatar.png 和 favicon.png 被覆盖...不知道有没有啥解决方案
