### ISSUE TITLE
二级分类默认展开

### ISSUE THREAD

**Issue by Klien-m** [fluid-dev/hexo-theme-fluid#343]
二级分类默认是展开的，演示网址https://klien-m.github.io/categories/

**Comment by zkqiang** [comment]
这是个 feature，如果存在子分类，会默认展开

后续我可以做个开关来控制这个 feature

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/commit/90d4d0a6423dbb4bd838e8bf18f180c7823ce5a7
已添加，欢迎测试

**Comment by Klien-m** [comment]
测试成功，没问题了
