### ISSUE TITLE
网站标题支持图片

### ISSUE THREAD

**Issue by wangyz1997** [fluid-dev/hexo-theme-fluid#344]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html)实现的功能
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

目前网站标题（顶栏左侧）只支持文字，希望能够增加对图片标题的支持
#### 请描述您认为可行的解决方案

通过配置文件，可以设置网站标题的图片文件
#### 考虑过的替代方案

暂无

**Comment by zkqiang** [comment]
已经支持了 https://github.com/fluid-dev/hexo-theme-fluid/issues/120
