### ISSUE TITLE
摘要一直显示不完全

### ISSUE THREAD

**Issue by chenwchen** [fluid-dev/hexo-theme-fluid#345]
### 使用fluid主题问题
不管是```auto_excerpt```还是是```````形式设置摘要， 摘要都一直显示不完全。

**Comment by zkqiang** [comment]
麻烦详细说明一下吧...  不然不明白什么情况。

目前显示是什么样子？最好提供一个截图

**Comment by chenwchen** [comment]
使用截断， 但是差了一半截没显示



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张凯强"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 下午3:01
收件人: "fluid-dev/hexo-theme-fluid"<hexo-theme-fluid@noreply.github.com&gt;; 
抄送: "陈忘尘"<2549422435@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fluid-dev/hexo-theme-fluid] 摘要一直显示不完全 (#345)





 
麻烦详细说明一下吧...  不然不明白什么情况。
 
目前显示是什么样子？最好提供一个截图

**Comment by zkqiang** [comment]
系统和浏览器是什么版本？ 我猜你不是chrome或firefox这些主流的

**Comment by chenwchen** [comment]
正正规规的chrome浏览器， 应该不是浏览器的问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张凯强"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 下午3:04
收件人: "fluid-dev/hexo-theme-fluid"<hexo-theme-fluid@noreply.github.com&gt;; 
抄送: "陈忘尘"<2549422435@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fluid-dev/hexo-theme-fluid] 摘要一直显示不完全 (#345)





 
系统和浏览器是什么版本？ 我猜你不是chrome或firefox这些主流的

**Comment by zkqiang** [comment]
你还是抽空提供下截图吧，然后部署一下给一个可访问的博客地址

**Comment by chenwchen** [comment]
博客地址&nbsp;&nbsp;https://wchen.club/
问题博客仓库地址&nbsp;&nbsp;https://github.com/chenwchen/temp.git




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张凯强"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 下午3:08
收件人: "fluid-dev/hexo-theme-fluid"<hexo-theme-fluid@noreply.github.com&gt;; 
抄送: "陈忘尘"<2549422435@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fluid-dev/hexo-theme-fluid] 摘要一直显示不完全 (#345)





 
你还是抽空提供下截图吧，然后部署一下给一个可访问的博客地址

**Comment by zkqiang** [comment]
![image](https://user-images.githubusercontent.com/32983588/92216789-5e878b80-eec9-11ea-8076-5c145b50fdd3.png)

看上去没什么问题？你是什么样的

**Comment by chenwchen** [comment]
我是用<!-- more --&gt;进行截断成文章摘要， 但是只显示了一句话



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张凯强"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 下午4:12
收件人: "fluid-dev/hexo-theme-fluid"<hexo-theme-fluid@noreply.github.com&gt;; 
抄送: "陈忘尘"<2549422435@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fluid-dev/hexo-theme-fluid] 摘要一直显示不完全 (#345)





 

 
看上去没什么问题？你是什么样的

**Comment by zkqiang** [comment]
明白你的问题了

实测 `hexo-asset-image` 卸载就好了，这个插件已经停止维护了，可能和新版 hexo 不兼容，找找别的替换吧

**Comment by chenwchen** [comment]
如果这个卸载的话， 相对路径怎么引用呢？&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张凯强"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 下午4:29
收件人: "fluid-dev/hexo-theme-fluid"<hexo-theme-fluid@noreply.github.com&gt;; 
抄送: "陈忘尘"<2549422435@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fluid-dev/hexo-theme-fluid] 摘要一直显示不完全 (#345)





 
明白你的问题了
 
实测 hexo-asset-image 卸载就好了，这个插件已经停止维护了，可能和新版 hexo 不兼容，找找别的替换吧

**Comment by zkqiang** [comment]
https://hexo.io/zh-cn/docs/asset-folders

参考 Hexo 官方文档

**Comment by chenwchen** [comment]
这种方式不能和typera等编辑markdown平滑切换， 只能舍弃一边。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张凯强"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 下午4:46
收件人: "fluid-dev/hexo-theme-fluid"<hexo-theme-fluid@noreply.github.com&gt;; 
抄送: "陈忘尘"<2549422435@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fluid-dev/hexo-theme-fluid] 摘要一直显示不完全 (#345)





 
https://hexo.io/zh-cn/docs/asset-folders
 
参考 Hexo 官方文档

**Comment by zkqiang** [comment]
那你可以找下类似的功能其他插件，我没有看过这方面

**Comment by chenwchen** [comment]
试了很多方法，hexo-asset-image@0.0.1这个是唯一可行的。然后主题就出问题了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张凯强"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 下午4:52
收件人: "fluid-dev/hexo-theme-fluid"<hexo-theme-fluid@noreply.github.com&gt;; 
抄送: "陈忘尘"<2549422435@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fluid-dev/hexo-theme-fluid] 摘要一直显示不完全 (#345)





 
那你可以找下类似的功能其他插件，我没有看过这方面

**Comment by zkqiang** [comment]
这个跟主题关系不大，主题只处理 Hexo 传过来的参数，也就是一个截取操作

https://github.com/fluid-dev/hexo-theme-fluid/blob/1b9b61ca83156ae1c79ea0a40412e4582c7b3d98/layout/index.ejs#L29

**Comment by chenwchen** [comment]
问题已经解决hexo-asset-link 插件可直接把相对路径编译为官网格式{% asset_path slug %}
{% asset_img slug [title] %}
{% asset_link slug [title] %}





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张凯强"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 下午5:06
收件人: "fluid-dev/hexo-theme-fluid"<hexo-theme-fluid@noreply.github.com&gt;; 
抄送: "陈忘尘"<2549422435@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fluid-dev/hexo-theme-fluid] 摘要一直显示不完全 (#345)





 
这个跟主题关系不大，主题只处理 Hexo 传过来的参数，也就是一个截取操作
 
https://github.com/fluid-dev/hexo-theme-fluid/blob/1b9b61ca83156ae1c79ea0a40412e4582c7b3d98/layout/index.ejs#L29

**Comment by zkqiang** [comment]
可以写一篇最佳实践投稿到这里 https://github.com/fluid-dev/hexo-fluid-blog
