### ISSUE TITLE
首页上下滑动会闪屏

### ISSUE THREAD

**Issue by zhpanvip** [fluid-dev/hexo-theme-fluid#346]
很漂亮的一款主题，感谢作者开源。但是现在似乎碰到一点小bug,首页上下滑动，图片部分会出现白色闪屏，手机端电脑端都有这样的问题。
版本使用的是最新的release.

**Comment by zhpanvip** [comment]
这个问题不是必现的，但是在手机跟pc上都出现过。

**Comment by bobo4629** [comment]
原来不只是我的问题，今天晚上开始出现的应该，老版本也出现了（未支持暗黑模式的版本），尝试更换最新的发行版也无效。 
最神奇的是示例站点 https://hexo.fluid-dev.com/ 没有出现这个问题，今晚整了挺久。 
很喜欢这个主题~希望早日解决！

**Comment by zkqiang** [comment]
@zhpanvip   @bobo4629 

是新版chrome导致，已发布[新版 release](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.8.3)

**Comment by zhpanvip** [comment]
更新到最新的release后这个问题似乎更严重了。更新前是偶尔会出现，几率很小，但是现在成了必现了。

**Comment by zhpanvip** [comment]
使用的chrome浏览器85.0.4183.83版本。

**Comment by zkqiang** [comment]
你现在 github pages 上是最新版本吗？似乎没有更新到最新版

**Comment by zhpanvip** [comment]
> 你现在 github pages 上是最新版本吗？似乎没有更新到最新版

[Gitee](https://gitee.com/zhpanvip/zhpanvip)仓库目前是最新的，我又重新下载了一下release的包试了还是会闪屏。

**Comment by zhpanvip** [comment]
我试了在本地部署跑起来就没有问题，但是部署到gitee或者github上之后就有问题了。。。。

**Comment by zhpanvip** [comment]
应该是浏览器缓存问题，清理了一下缓存恢复了。多谢！
