### ISSUE TITLE
更换至新版本后，报Uncaught ReferenceError错误

### ISSUE THREAD

**Issue by Edwardzcn** [fluid-dev/hexo-theme-fluid#347]
搜索了一下似乎是由于字符串没有加引号导致？但是我使用1.8.1时是没有问题的，开启1.8.2的深色模式后就产生此问题。深色模式按钮失效、模糊效果失效、顶部图片也不能完整显示。
![bug](https://user-images.githubusercontent.com/32711483/92305157-1050b600-efb7-11ea-9a54-70a983f885bb.png)

**Comment by zkqiang** [comment]
没有更新完整

**Comment by Edwardzcn** [comment]
我从GitHub上下载了1.8.2和1.8.3都出现了这个问题，是哪里没有更新完整吗？本地hexo s是正常的，但是deploy以后出现这个问题。

**Comment by zkqiang** [comment]
那跟主题就没关系了，可能是你部署后的缓存或者别的原因
