### ISSUE TITLE
Ver1.8.3 gitalk插件提示错误

### ISSUE THREAD

**Issue by boer0924** [fluid-dev/hexo-theme-fluid#348]
### 升级1.8.3后，gitalk插件提示如图错误：
![image](https://user-images.githubusercontent.com/9416883/92342343-2fecf900-f0f3-11ea-9439-b8c2f8cb8d6c.png)

### 经Google后，问题解决。
https://github.com/gitalk/gitalk/issues/114

![image](https://user-images.githubusercontent.com/9416883/92342475-8823fb00-f0f3-11ea-8e05-d9ec560f0f36.png)

> Tips: 修改文件路径和代码内容见截图红色框部分内容

---

不错是否为普遍现象，希望官方修复。

[~·boer·~ 乌托邦](https://www.boer.xyz/)

**Comment by zkqiang** [comment]
配置修改为  `labels: ['xxxx']` 即可（中括号外面去掉引号）

**Comment by boer0924** [comment]
> 配置修改为 `labels: ['xxxx']` 即可（中括号外面去掉引号）

一针见血，nice！
