### ISSUE TITLE
hexo-tag-aplayer与hexo-generator-feed冲突，rss订阅页面的summary全部变成了aplayer的代码

### ISSUE THREAD

**Issue by scarleast** [fluid-dev/hexo-theme-fluid#350]
#### Make sure
- [x ] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases).
- [x ] Browser does not belong to IE and other old browsers
- [x ] It can be replicated through `hexo clean && hexo s` and cleared browser cache in the localhost.
- [x ] Not affected by other Hexo plugins

#### To Reproduce
1. 安装hexo-generator-feed
2. 安装hexo-tag-aplayer
3. rss订阅页面的summary全部变成了aplayer的代码。

#### Screenshots

![image](https://user-images.githubusercontent.com/14150292/93305621-5583ac00-f831-11ea-8252-50959e62a64f.png)

#### 解决
修改根目录下的_config.yml:
```
aplayer:
  asset_inject: false
```
rss的summary正常了，但文章中调用aplayer就失效了。

**Comment by zkqiang** [comment]
这个问题别提给我。。 这两个插件都不是我写的
