### ISSUE TITLE
首页摘要中没有渲染LaTeX 数学公式

### ISSUE THREAD

**Issue by popesaga** [fluid-dev/hexo-theme-fluid#351]
公式引擎使用的是mathjax，文章内公式可以正确渲染。但是首页中摘要对公式没有渲染。摘要使用的是标记。公式使用的是$O(\log{n})$ 行内公式。

**Comment by Edwardzcn** [comment]
我用的Kramed，也一直都有这个问题，摘要中无法渲染但是内容页正常。

**Comment by zkqiang** [comment]
#323  @popesaga @Edwardzcn
