### ISSUE TITLE
样式文件和js文件无法加载

### ISSUE THREAD

**Issue by woshixiaoguo** [fluid-dev/hexo-theme-fluid#353]
![](https://cdn.jsdelivr.net/gh/woshixiaoguo/imgSite/fluid_issue/Snipaste_2020-09-28_13-28-16.jpg)

**Comment by zkqiang** [comment]
可以自己更换别的CDN：[静态资源](https://hexo.fluid-dev.com/docs/guide/#%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90)
