### ISSUE TITLE
自定义菜单不显示文章

### ISSUE THREAD

**Issue by koevn** [fluid-dev/hexo-theme-fluid#354]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
- 配置过程 

这是在主题配置文件里添加的自定义菜单
```bash
menu:
      - { key: 'happy', link: '/categories/happy', icon: 'iconfont icon-category-fill' }
```
并在站点source文件下创建`/categories/happy/index.md`
vim index.md 
```bash
title: 快乐
type: "快乐"
```
编辑主题文件夹下的zh-cn文件添加happy项
并在站点配置文件添加`categories_tap`

- 遇到的问题

创建文章并添加“快乐”属性分类，渲染部署成功后访问导航菜单`快乐`却看不到一篇文章，而首页文章是有显示分类为"快乐“，点击文章分类”快乐“能显示这个类型菜单所以文章，但样式却像归档，且URL是`www.abc.com/categories/快乐`，正常应该指向`www.abc.com/categories/happy`。

自定义了导航菜单，文章指定了分类菜单部署后却看不到任何文章，这个问题我用hexo默认主题和其他一些主题都没出现过，就是不知道这个问题是不是fluid有其他什么地方需要配置的，我还不知道。

**Comment by songhn233** [comment]
Hexo 本身并没有提供 categories 和 tags page，一般是由主题生成。

在文章 Front-matter 中提供的分类就是分类名，这种新建分类文件夹指定 `type` 的写法应该是特定主题的实现，不是通用的。

**Comment by zkqiang** [comment]
请不要把别的主题用法套用进来...

你这样的话，为什么分类不直接使用中文“快乐”呢

比如：<https://hexo.fluid-dev.com/categories/功能增强/>
