### ISSUE TITLE
段首的缩进长度被压缩了

### ISSUE THREAD

**Issue by C-Yunfeng** [fluid-dev/hexo-theme-fluid#358]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 环境：
- windows系统
- Typora软件

#### 问题描述

使用Typora时，在段首添加了Tab，但上传后缩进的长度被压缩了。如图所示：
在Typora中：
![](https://blogjallery.oss-cn-beijing.aliyuncs.com/img/20201010212840.png)
在本地网站/云端网站中：
![](https://blogjallery.oss-cn-beijing.aliyuncs.com/img/20201010213345.png)
而且多个Tab或空格也会被压缩到一点点。

在查看[网站demo](https://hexo.fluid-dev.com/)里的文章时，我发现都是用列表实现的缩进，没有用tab或空格缩进的。虽然写markdown时的确经常用列表，但有时候还是想用tab缩进的。
麻烦您了。

**Comment by C-Yunfeng** [comment]
今天写文章时发现一个类似的问题，在引用中添加的换行，也会被压缩至一个空格的长度：
- Typora中
![](https://blogjallery.oss-cn-beijing.aliyuncs.com/img/20201011103551.png)
- Typora中的源码模式：
![](https://blogjallery.oss-cn-beijing.aliyuncs.com/img/20201011104144.png)
- 网站中：
![](https://blogjallery.oss-cn-beijing.aliyuncs.com/img/20201011103725.png)

**Comment by zkqiang** [comment]
大部分 markdown 编辑器都会过滤掉段首的空格或者 Tab （取决于你用了什么 renderer），Typora 只是做了特殊处理

引用的换行也是 renderer 差异导致的，建议尾部加两个空格来控制换行

**Comment by C-Yunfeng** [comment]
哦哦好的，明白了。感谢您的开源。
