### ISSUE TITLE
language: zh-CN  # 这里要改为languages: zh-CN  不然报错

### ISSUE THREAD

**Issue by 347900357** [fluid-dev/hexo-theme-fluid#360]
language: zh-CN  # 这里要改为languages: zh-CN  不然报错

**Comment by zkqiang** [comment]
报的什么错？

hexo 配置里没有 `languages` 这一项

**Comment by 347900357** [comment]
> 报的什么错？
> 
> hexo 配置里没有 `languages` 这一项

3. 指定主题
如下修改 Hexo 博客目录中的 _config.yml：

theme: fluid  # 指定主题

language: zh-CN  # 指定语言，会影响主题显示的语言，按需修改

这里

**Comment by 347900357** [comment]
修改了还是显示英文 导航栏
 Home
 Archives
 Categories
 Tags
 About

**Comment by 347900357** [comment]
![image](https://user-images.githubusercontent.com/20179041/95979856-df359200-0e4e-11eb-975e-fba3a4bfdc27.png)


> 修改了还是显示英文 导航栏
> Home
> Archives
> Categories
> Tags
> About

**Comment by zkqiang** [comment]
这个配置写了一年多了吧。。还没人有问题。。

https://github.com/fluid-dev/hexo-fluid-blog/blob/86c72ecabbc5a93013f92b2567afee2aa043136a/_config.yml#L11

**Comment by 347900357** [comment]
> 报的什么错？
> 
> hexo配置里没有`languages`这一项

FATAL YAMLException: duplicated mapping key at line 102, column 1:
    language: zh-CN

**Comment by zkqiang** [comment]
你翻译一下那个报错信息就知道为什么了

102行有一个重复名称的

**Comment by 347900357** [comment]
奥 解决了  谢谢了

**Comment by 347900357** [comment]
> 你翻译一下那个报错信息就知道为什么了
> 
> 102行有一个重复名称的

奥 解决了 谢谢了

**Comment by lnnau** [comment]
在_config.yml的11行已经有language这个参数设置了，所以直接在这个地方修改语言为zh-CN就可以了。
![Uploading image.png…]()
