### ISSUE TITLE
关于导航条样式的建议

### ISSUE THREAD

**Issue by mxy493** [fluid-dev/hexo-theme-fluid#362]
意外发现一个Hexo主题的导航条自定义了样式，感觉还不错，希望Fluid可以尝试做一个这样的导航条
地址：https://www.izhaoo.com
<img width="1080" alt="Snipaste_2020-10-18_16-30-08" src="https://user-images.githubusercontent.com/46776216/96362466-19a97280-1160-11eb-8524-6408591fb488.png">

**Comment by zkqiang** [comment]
不是一种设计思想，可以自己魔改
