### ISSUE TITLE
添加代码块行数显示

### ISSUE THREAD

**Issue by dsyx** [fluid-dev/hexo-theme-fluid#367]
在当前版本（v1.8.3）我没有找到有关代码块行数显示的开关。
希望可以添加这个功能，因为在编写技术文章时可能需要提及代码所在的行数，提供行数显示可便于读者阅读。

**Comment by smoky96** [comment]
很奇怪为什么这个功能一直不加上去，对于技术博客来说代码行数还是挺重要的吧，是实现上有什么困难吗？

**Comment by zkqiang** [comment]
@smoky96  
旧版本是有的，但是更换了高亮库后，和 hexo 自身的行数功能不兼容，想同时兼容目前两个高亮库的话，还是要花些心思的，所以一直搁置了，下个版本争取加回来

**Comment by zkqiang** [comment]
dev 分支已更新，欢迎体验
