### ISSUE TITLE
ERR_EMPTY_RESPONSE : some reponses of js or css file is empty !

### ISSUE THREAD

**Issue by YUbuntu0109** [fluid-dev/hexo-theme-fluid#368]
#### Make sure
- [ ] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases).
- [ ] Browser does not belong to IE and other old browsers
- [ ] It can be replicated through `hexo clean && hexo s` and cleared browser cache in the localhost.
- [ ] Not affected by other Hexo plugins

#### Describe the bug

Hey bro what happended ? ! some reponses of js or css file is empty so try to upgrate theme version now ?

So busy recently so that I just found this bug... please give some suggestions to resolve this issue bro. thanks.

> https://ishacker.net/

#### To Reproduce
1. Go to '...', click on '....'
2. Scroll down to '....'
3. See error

#### Screenshots

![image](https://user-images.githubusercontent.com/43493852/98679847-8ef11780-239b-11eb-8f68-1b05213a5896.png)

**Comment by zkqiang** [comment]
You can modify static_prefix

**Comment by YUbuntu0109** [comment]
thanks bro

**Comment by YUbuntu0109** [comment]
> You can modify static_prefix
> 
> Duplicate: #353

thanks bro
