### ISSUE TITLE
向下滑动的按钮 scroll-down-bar 不能用

### ISSUE THREAD

**Issue by vin9712** [fluid-dev/hexo-theme-fluid#370]
更新了 fluid-1.8.5，在调试完之后，无其他问题，但点击首页的**向下按钮**不能触发滚动事件，遂找回上一个版本的代码来看，找到问题所在。
在 `source/js/utils.js`文件的第14行处，将 `$('body')` 改成 `$('body,html')`后，功能即可恢复。

![原1.8.5的情况](https://user-images.githubusercontent.com/25540422/98818415-80236700-2466-11eb-8855-cb7ef88b040e.png)

替换为

![image](https://user-images.githubusercontent.com/25540422/98818467-97625480-2466-11eb-99d9-e7a7f8d6eb97.png)

**Comment by zkqiang** [comment]
thx 已修复
