### ISSUE TITLE
希望能加入头图移动端自适应功能

### ISSUE THREAD

**Issue by wangyz1997** [fluid-dev/hexo-theme-fluid#371]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html)实现的功能
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

一张横屏的图片在被使用作为PC网页的头图时，可以优雅地被全屏显示。但是，在手机端却只能强制遵循电脑版的高度设置，导致图片两端被截断，这让使用照片作为头图变得基本不可能。

#### 请描述您认为可行的解决方案

在设置中添加选项，可以在移动设备上启动高度自适应功能。这样，在使用一张较宽的图片时，在宽度足够的PC上可以按照设置中的高度比例进行显示；在移动设备等宽度不足的设备上，可以让头图适应图片的高度，覆盖设置中的高度设置，让下方元素上移来适应图片的比例。

**Comment by zkqiang** [comment]
后续开放个配置来自由选择

**Comment by arwenzhou** [comment]
同需要头图移动端适应功能，非常感谢

**Comment by zkqiang** [comment]
@wangyz1997 @arwenzhou 

dev分支更新了此功能
但有所不同的是，需要通过配置来设置图片的宽高比，这是因为页面无法预知图片的尺寸是多少，因此必须需要固定一个高度值

**Comment by wangyz1997** [comment]
感谢作者大大

**Comment by arwenzhou** [comment]
超级感谢，鞠躬！！
