### ISSUE TITLE
升级到 1.8.5出现问题

### ISSUE THREAD

**Issue by io-better** [fluid-dev/hexo-theme-fluid#373]
出现的问题
TypeError: Cannot read property 'lazyload' of undefined
    at Hexo.<anonymous> (/Users/better/IdeaProjects/doc.better.io/themes/fluid/scripts/events/lib/lazyload.js:23:21)
    at Hexo.tryCatcher (/Users/better/IdeaProjects/doc.better.io/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/better/IdeaProjects/doc.better.io/node_modules/bluebird/js/release/method.js:15:34)

hexo配置
{
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}

**Comment by io-better** [comment]
已解决

**Comment by Sakura-cheng** [comment]
怎么解决的啊

**Comment by Sakura-cheng** [comment]
> 已解决

怎么解决的啊

**Comment by io-better** [comment]
把之前的配置文件备份一份 然后把新版本中的配置文件复制一份并替换 就可以了  替换前后注意 clean

**Comment by Sakura-cheng** [comment]
> 把之前的配置文件备份一份 然后把新版本中的配置文件复制一份并替换 就可以了 替换前后注意 clean

感谢，不过我还是不行，我把图片懒加载关了才正常:joy:

**Comment by io-better** [comment]
它只要更新了主题配置  在更新主题时感觉挺容易出错

**Comment by zkqiang** [comment]
@Sakura-cheng  懒加载报错的问题已修复了，现版本先关闭或者使用 `onlypost: true`
