### ISSUE TITLE
不蒜子在 Chrome 85 版本后所有页面统计是同一个数据

### ISSUE THREAD

**Issue by YinAoXiong** [fluid-dev/hexo-theme-fluid#376]
#### 问题描述
在新的规范中Referrer-Policy 并没有延续 Referer这个拼写错误，所以不蒜子源码中的scriptTag.refererPolicy = "no-referrer-when-downgrade",会出现设置无效的问题。
同时由于chrome系列浏览器在85这个版本后Referrer-Policy默认值从no-referrer-when-downgrade改为strict-origin-when-cross-origin。这导致了不蒜子的页面统计功能失效。

### 修复方法
1. 全局修改 Referrer-Policy 
```
<meta name="referrer" content="no-referrer-when-downgrade">
```
2. config 文件中使用修改过后的不蒜子js
```
 busuanzi: https://cdn.jsdelivr.net/gh/YinAoXiong/busuanzi@2.3.0/
```
3. 等待原作者修复，已发邮件告知原作者

**Comment by zkqiang** [comment]
这个还是等待不蒜子的开发者修复，其他人可以先按照楼主的方式临时修复

**Comment by stevenjoezhang** [comment]
原作者在今天早些时候修复了这个问题

**Comment by zkqiang** [comment]
@stevenjoezhang  感谢同步信息
