### ISSUE TITLE
apostrophes have spaces behind them

### ISSUE THREAD

**Issue by icanotc** [fluid-dev/hexo-theme-fluid#377]
#### Make sure
- [x] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases).
- [x] Browser does not belong to IE and other old browsers
- [x] It can be replicated through `hexo clean && hexo s` and cleared browser cache in the localhost.
- [x] Not affected by other Hexo plugins

#### Describe the bug

Apostrophes have spaces behind them

seems like a font issue, the Chinese apostrophe usually have a space behind them, what would be the solution here?

#### To Reproduce
1. Go an article with the ' sign
3. See error

here's one of my blogs
https://icanc.space/2020/11/21/deploying-a-minecraft-server-with-docker/

#### Screenshots
![image](https://user-images.githubusercontent.com/44480394/99886789-47755180-2c0d-11eb-91c2-c1855f0da8e4.png)
![image](https://user-images.githubusercontent.com/44480394/99886790-4e9c5f80-2c0d-11eb-8d77-eb3542283639.png)

**Comment by zkqiang** [comment]
This is indeed a font issue, but I did not reproduce it, maybe you can modify it through config:

https://github.com/fluid-dev/hexo-theme-fluid/blob/f2bc3fe2129669aea9687e469fca4e42205b22c9/_config.yml#L186

**Comment by icanotc** [comment]
this is kinda weird
![image](https://user-images.githubusercontent.com/44480394/100039167-b18b2380-2dd2-11eb-916b-19b56889b69c.png)
![image](https://user-images.githubusercontent.com/44480394/100039191-c1a30300-2dd2-11eb-939e-04c11d537004.png)
when i have the fonts style disabled in chrome, it just fixes itself

![image](https://user-images.githubusercontent.com/44480394/100039235-cff11f00-2dd2-11eb-80c1-86ec267e17a4.png)
![image](https://user-images.githubusercontent.com/44480394/100039267-de3f3b00-2dd2-11eb-99e6-25884593795b.png)
and if i enabled it back up, the problem just comes up again

what should i add to font_family: to fix this?

**Comment by icanotc** [comment]
seems like 微软雅黑 is causing problems, everything worked fine after I removed it from the list

**Comment by zkqiang** [comment]
I modified it to be similar to GitHub

**Comment by icanotc** [comment]
thanks for the fix

but, wouldn't this fix affect Chinese words? since the Chinese font isn't there anymore

**Comment by zkqiang** [comment]
Don’t worry, it will use system fonts first

https://zkqiang.cn/posts/dc4bf29f/
