### ISSUE TITLE
文章目录自动添加数字章节

### ISSUE THREAD

**Issue by ECarry** [fluid-dev/hexo-theme-fluid#379]
在1.8.3版本是没有自动添加的，所以文章标题我都会手动添加如：
一、标题名
二、标题名
的此类标题。更新到1.8.5版本后，文章目录发现自动添加了标题数字，现在变为：
1. 一、标题名 
2. 二、标题名 
是否有开关来关闭自动添加数字标题

**Comment by zkqiang** [comment]
看了一下不属于 Fluid 默认的样式，可能是你引入了别的样式影响到了

![image](https://user-images.githubusercontent.com/32983588/99934397-cfd42d80-2d98-11eb-8aff-160b8a29231e.png)
