### ISSUE TITLE
关于短代码的文档

### ISSUE THREAD

**Issue by oCoke** [fluid-dev/hexo-theme-fluid#380]
Fluid 是一款非常不错的 Hexo 主题！

通过阅读官方博客的「投稿示例」，我发现可以在博客页面添加一些`Notes`，但似乎这并没有在官方的主题文档中出现（也可能是我打开方式不对），希望可以出关于短代码的文档，谢谢！

**Comment by zkqiang** [comment]
https://hexo.fluid-dev.com/docs/guide/#tag-插件
