### ISSUE TITLE
目录视觉优化建议

### ISSUE THREAD

**Issue by dsyx** [fluid-dev/hexo-theme-fluid#381]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html)实现的功能
- [x] 难以通过第三方插件实现

> 对前端了解不太深，所以不知道是否能通过插件实现。

#### 请描述该需求尝试解决的问题

[当前版本（v1.8.5）](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.8.5) 下，当目录中显示的标题足够长时会发生折行。这影响观感，使得目录标题混在一起，显得不够直观。

#### 请描述您认为可行的解决方案

我认为可以根据窗口大小，锁定一个标题最长值，若大于该值则显示省略号而不是换行。并且鼠标停留在该省略标题上时使用停留小窗（好像可以使用 title 属性）显示完整标题。

**Comment by zkqiang** [comment]
已改成 单行过长省略号
