### ISSUE TITLE
希望提供壁纸自动更新功能

### ISSUE THREAD

**Issue by mikeygithub** [fluid-dev/hexo-theme-fluid#382]
可否添加背景图迭代更新，或者支持bing每日壁纸接口

**Comment by zkqiang** [comment]
通过自定义 js 直接修改图片的 url 即可

**Comment by cyang812** [comment]
> 通过自定义 js 直接修改图片的 url 即可

能否说的细一点，在哪里放置js, 以及 js 怎么实现。谢谢
