### ISSUE TITLE
怎么关闭首页文章缩略图

### ISSUE THREAD

**Issue by harvies** [fluid-dev/hexo-theme-fluid#383]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
怎么关闭首页文章缩略图，之前设置了文章的缩略图，现在不想要了

**Comment by zkqiang** [comment]
把 index_img 删掉或者留空就行了
