### ISSUE TITLE
remark42 加载失败

### ISSUE THREAD

**Issue by zhaoyibo** [fluid-dev/hexo-theme-fluid#384]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

评论插件 remark42 配置正确，使用的最新的 v1.8.6 正式版本。
remark42  的评论加载不出来，有报错
![Xnip2020-12-02_14-40-02](https://user-images.githubusercontent.com/11988080/100837871-63e67900-34ac-11eb-84f5-f16711be25f8.jpg)
![Xnip2020-12-02_14-40-34](https://user-images.githubusercontent.com/11988080/100837882-677a0000-34ac-11eb-8102-076c89246e72.jpg)

看了下代码，应该是之前 js 加载重构的时候导致的问题。
https://github.com/fluid-dev/hexo-theme-fluid/commit/130f79b3cf4f5fd8670714685c81bcb7852e2c98#diff-c3b0da25a9e652e0f1806451cbedece3a1f4c232957a78a46808dcf6349871a4L4

这里我试了一下，将配置拿到 `Fluid.utils.waitElementVisible('remark42', function() {` 上边就好了

**Comment by zkqiang** [comment]
emmmm  我大意了

**Comment by zkqiang** [comment]
重新 release 了一次
