### ISSUE TITLE
1. 目录抓取有问题 2. 代码块渲染异常

### ISSUE THREAD

**Issue by zh0ngtian** [fluid-dev/hexo-theme-fluid#387]
#### Bug 描述
1. 文章目录只显示第一个一级标题下面的二级标题
2. 代码块渲染异常

#### 复现步骤
1. 有多级标题的文章都会有这个问题
2. 有代码块的文章都会有这个问题

页面地址：http://www.zh0ngtian.tech/375e0e4d.html

#### 截图
1. 博客目录如下：
![2020-12-13-zybhe8](http://img.zh0ngtian.tech/2020-12-13-zybhe8.png)
实际上这篇文章的目录应该是这样的：
![2020-12-13-CvLCDT](http://img.zh0ngtian.tech/2020-12-13-CvLCDT.png)

2. 渲染异常的代码块如下：
![2020-12-13-5x2KsS](http://img.zh0ngtian.tech/2020-12-13-5x2KsS.png)
代码块前面会多出一块来

**Comment by zkqiang** [comment]
问题一，那是折叠，不是有问题，通过 `toc: collapseDepth` 配置修改

问题二，应该是缓存问题，我这边看是正常的

![image](https://user-images.githubusercontent.com/32983588/102034782-da16a400-3df9-11eb-829a-f21d8234be3f.png)

**Comment by zh0ngtian** [comment]
原来是这样，谢谢！
