### ISSUE TITLE
个别文章右方的 toc 下拉到一定程度后 莫名消失

### ISSUE THREAD

**Issue by RecluseXU** [fluid-dev/hexo-theme-fluid#388]
#### 问题描述  
对于绝大多数文章，其文章右方的 toc 都正常  
https://evilrecluse.top/post/7389a59f/  
但是这篇文章，下拉到一定程度后，toc 会莫名消失  

![b.gif](https://i.loli.net/2020/12/15/E5RIdUZar2lCKjg.gif)  

#### 环境  
WIN10 + Chrome8.7

**Comment by zkqiang** [comment]
以前的BUG，更新最新版 fluid
