### ISSUE TITLE
部署过程中出现Plugin load failed: %s hexo-theme-landscape

### ISSUE THREAD

**Issue by hustrength** [fluid-dev/hexo-theme-fluid#389]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

已经成功部署网站，显示也正常，但出现如下错误，不知道有什么影响，怎么解决？
ERROR {
  err: [Error: EISDIR: illegal operation on a directory, read] {
    errno: -21,
    code: 'EISDIR',
    syscall: 'read'
  }
} Plugin load failed: %s hexo-theme-landscape

**Comment by zkqiang** [comment]
这个是 Hexo 一处 BUG [#4594](https://github.com/hexojs/hexo/issues/4594)

暂时解决办法：
```sh
npm uninstall hexo-theme-landscape
```

**Comment by hustrength** [comment]
> 这个是 Hexo 一处 BUG [#4594](https://github.com/hexojs/hexo/issues/4594)，Hexo 下个版本即将修复
> 
> 暂时解决办法：
> 
> ```shell
> npm uninstall hexo-theme-landscape
> ```

感谢！

**Comment by zkqiang** [comment]
[Hexo 5.3](https://github.com/hexojs/hexo/releases/tag/5.3.0) 已发布，解决了这个问题
