### ISSUE TITLE
Chrome浏览器下渲染数学公式负号“-”不清晰

### ISSUE THREAD

**Issue by hooyuser** [fluid-dev/hexo-theme-fluid#390]
![20201219213803](https://user-images.githubusercontent.com/10691820/102690768-afd24580-4242-11eb-9cd8-fecfb312819a.png)
上标中的负号，有时正常，有时非常浅，接近于消失。
该问题出现在Chrome浏览器，Mathjax3.0.5，缩放比例为100%，且Math renderer为svg时。

使用Edge浏览器时正常。
缩放比例为有些值时正常，其他值时不正常。
Math renderer为CHTML时正常。

网址：https://toposcat.top/2020/12/04/%E5%BE%AE%E5%88%86%E6%B5%81%E5%BD%A2/

**Comment by zkqiang** [comment]
有相同问题的可以留言，实在没复现出来

**Comment by hooyuser** [comment]
> 有相同问题的可以留言，实在没复现出来

感谢您的关注！我最近更换网站服务器后，全部重新配置了一遍，发现该问题已经消失了。或许可以关闭这个issue了。
