### ISSUE TITLE
想问一下文章内图片使用外部图床链接为啥不行呢？

### ISSUE THREAD

**Issue by RicherYY** [fluid-dev/hexo-theme-fluid#391]
我打算使用外部图床来展示我文章内的图片。但是使用```![](https://example.jpg)```这种格式显示不出来图片。
文章内的图片只能本地上传才行吗？
这样的话是不是文章图片越多，每次推送到服务器就越来越慢呢？

**Comment by zkqiang** [comment]
当然可以
显示不出来可能是别的原因，控制台看下就知道了
