### ISSUE TITLE
GitHub 兼容的 Markdown 标题 id 的命名风格

### ISSUE THREAD

**Issue by dsyx** [fluid-dev/hexo-theme-fluid#397]
当前版本 [v1.8.7](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.8.7) 的标题 `id` 的命名风格与 GitHub 的命名风格不同，这导致在 Blog 中可以跳转标题的文章在 GitHub 中失效。希望能提供一个开关以选择标题 `id` 的命名风格。

**Comment by zkqiang** [comment]
没明白啥意思..  标题 ID 指的是？

**Comment by dsyx** [comment]
![image](https://user-images.githubusercontent.com/34703581/103405388-e046a780-4b91-11eb-8b5d-e22216010d59.png)
这个。

**Comment by zkqiang** [comment]
那 “导致在 Blog 中可以跳转标题的文章在 GitHub 中失效” 是什么情况，能说明一下如何复现吗？

**Comment by dsyx** [comment]
比如，在一个 Markdown 文本中，存在标题 `# Hello World`。
在 GitHub 中这个标题可以通过 `[](#hello-world)` 来引用访问，但是在 fluid 中需要使用  `[](#Hello-World)` 才能引用访问。
[https://stackoverflow.com/questions/27981247/github-markdown-same-page-link](https://stackoverflow.com/questions/27981247/github-markdown-same-page-link) 这里描述了 GitHub 的同链接页面中的跳转方式。

**Comment by zkqiang** [comment]
这个是你使用的 renderer 生成的，比如默认的 [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked)，可以通过根目录配置来生成小写的：

```yaml
marked:
  modifyAnchors: 1
```

其他的 renderer 请查看对应的文档

**Comment by dsyx** [comment]
现在可以正常跳转了，感谢！
