### ISSUE TITLE
关于代码块里面行号的问题

### ISSUE THREAD

**Issue by hzjsea** [fluid-dev/hexo-theme-fluid#401]
## 关于代码块里面行号的问题
![image](https://user-images.githubusercontent.com/61597549/103724443-435f9080-500f-11eb-9c0e-84959769d4c1.png)

这里我已经关闭了行号的显示,但是在代码块里面依旧会有行号出来,并且数量是对应不上的,是哪里的设置错过了嘛
![image](https://user-images.githubusercontent.com/61597549/103724356-1317f200-500f-11eb-850a-da19e59f28d2.png)

**Comment by hzjsea** [comment]
已解决 文档里面写了高亮和行号不能并存

**Comment by zkqiang** [comment]
其实现在都支持行号了

你的情况可能是有别的高亮插件影响了

**Comment by hzjsea** [comment]
> 其实现在都支持行号了
> 
> 你的情况可能是有别的高亮插件影响了

嗯呢,我看了下,和上一个主题的设置有关系,prism.js 重复了

**Comment by lileixin888** [comment]
我的也是行号不对应
![Uploading 行号不对应.jpg…]()

**Comment by Nowaterisenough** [comment]
自定义字体的话用gutter，pre字段没用
  .markdown-body gutter code {
    font-family: Monaco, monospace !important; 
    font-size: 75% !important; 
    line-height: 1.8 !important; 
}
