### ISSUE TITLE
通过Front-matter禁用所在页面的文末版权说明

### ISSUE THREAD

**Issue by Y7n05h** [fluid-dev/hexo-theme-fluid#402]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题
博客中的文章可能存在多种许可证，或者在页面内有特殊说明等情况下，在文末仍旧显示默认的版权说明可能造成误解。

#### 请描述您认为可行的解决方案

希望能通过`Front-matter`禁用所在页面的文末版权说明。

---

感谢 `hexo-theme-fluid` 的所有开发者。

**Comment by zkqiang** [comment]
```
copyright: false
```

**Comment by Y7n05h** [comment]
> ```
> copyright: false
> ```

十分抱歉，我并不知晓该功能已被实现。
