### ISSUE TITLE
代码块行数

### ISSUE THREAD

**Issue by imaliang** [fluid-dev/hexo-theme-fluid#407]
1. 使用的是prismjs高亮库，开启行号之后，当滑到页面最后 再向上滑时，行号消失，有时候还会造成渲染markdown样式失败，直接显示
2. 希望在页面加入可以隐藏代码块div的功能
3. 希望增加点击代码块时，代码块全屏显示的功能

**Comment by imaliang** [comment]
![Uploading bug.gif…]()
bug示例

**Comment by zkqiang** [comment]
图片挂了，提供个链接吧

**Comment by imaliang** [comment]
> 图片挂了，提供个链接吧

https://s3.ax1x.com/2021/01/27/svxzSx.gif

**Comment by zkqiang** [comment]
问题1：我暂时没找到原理，但理论上 `preprocess: true` 时行号是静态生成在页面里，所以正常不会莫名其妙消失，可能是其他什么插件或js冲突了

问题2：折叠代码块可以使用 [`<details>`](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/details)

问题3：暂时不考虑添加了
