### ISSUE TITLE
使用hexo-douban图片样式错误

### ISSUE THREAD

**Issue by 0x7b** [fluid-dev/hexo-theme-fluid#409]
#### 问题描述
插件和主题均为最新版本，未修改源码。使用hexo-douban生成书单和电影页面时候图片样式错误
![image](https://user-images.githubusercontent.com/44578190/105823620-57882380-5ff8-11eb-88de-a8185e6ce880.png)
https://www.0x7b.cn/books

地址如上

**Comment by shiyicode** [comment]
+1    blog.shiyicode.com/books/
