### ISSUE TITLE
代码块background-color错误

### ISSUE THREAD

**Issue by Tim-Fang** [fluid-dev/hexo-theme-fluid#411]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述
![图片](https://user-images.githubusercontent.com/60050973/106343245-682de780-62df-11eb-8754-6194e9a32ab7.png)
如图,背景颜色是深色,但是代码块是浅色  
希望颜色一致:smile:

**Comment by zkqiang** [comment]
代码块颜色是根据设置的高亮方案，这没法跟着暗色模式改变，已经对其做了灰度处理
可以自己设置个深色背景的高亮
