### ISSUE TITLE
行内代码块默认颜色如何切换

### ISSUE THREAD

**Issue by novpath** [fluid-dev/hexo-theme-fluid#412]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

已知可以通过.CONFIG文件中的highlightjs-(style字段+bg_color字段)修改默认的代码高亮和多行代码块背
景颜色，不知可否修改诸如Markdown创建的回引号' '以内的**行内代码**的颜色，Fuild主题下默认颜色是粉紫色#e83e8c。<img width="216" alt="fluid行内代码" src="https://user-images.githubusercontent.com/52852930/106697422-ab5ac400-6619-11eb-81e0-26d5c55c0bdf.png">

**Comment by zkqiang** [comment]
通过自定义css

**Comment by novpath** [comment]
谢谢，已解决。通过自定义code{ }和.markdown-body pre code{ }选择器颜色样式改变了行内代码块的默认颜色。
