### ISSUE TITLE
请问如何在友链/关于等界面开启评论。

### ISSUE THREAD

**Issue by Hacker-C** [fluid-dev/hexo-theme-fluid#417]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

我无法在友链界面开启评论。我在 `themes/fluid/layout/links.ejs` 文件中添加了以下代码：
```ejs
<article class="comments" id="comments">
      <% var type = '_partial/comments/' + theme.post.comments.type %>
      <%- partial(type) %>
</article>
```
保存后，在本地 `http://localhost:4000/links/` 下查看，成功修改，该界面出现评论。但是使用命令 `hexo clean && hexo g && hexo s` 后，评论界面消失。似乎是 `hexo clean` 或者  `hexo g` 自动忽略了我对样式的修改。
请问是不能自行修改主题样式吗？

**Comment by zkqiang** [comment]
可以下载 dev 分支的代码，已经加入这个功能
