### ISSUE TITLE
能否增加对分类以及类别下的博客按名称排序的功能

### ISSUE THREAD

**Issue by BlueHeart0621** [fluid-dev/hexo-theme-fluid#418]
感谢作者大大的辛勤付出，请问能否增加「**对分类以及类别下的博客按名称排序**」的功能呢，目前默认只有按时间排序，但如果分类很多或者某一类别下博客很多，按时间排序的话查找博客不是很方便。

**Comment by zkqiang** [comment]
本身已经支持  `order_by: "name"`

https://github.com/fluid-dev/hexo-theme-fluid/blob/f40579f2672879283259664f88dcf3541c3b4708/_config.yml#L770

**Comment by BlueHeart0621** [comment]
`order_by: "name"` 只对分类按照名称排序，分类下的博客仍然是按照时间降序。能否增加一个排序按钮对分类下的博客也按照名称排序呢，就类似文件夹的那种既有按名称排序，又有按创建时间排序的那种。

谢谢作者大大~^-^

**Comment by zkqiang** [comment]
dev已更新
