### ISSUE TITLE
about页面悬浮二维码图片大小问题。

### ISSUE THREAD

**Issue by qqq301-bb** [fluid-dev/hexo-theme-fluid#420]
配置微信二维码图标好小啊
![e](https://user-images.githubusercontent.com/66862645/109044519-753acc80-770d-11eb-88ac-2fee8bbab9c0.png)

**Comment by wuwenyan** [comment]
怎么解决的呢？

**Comment by qqq301-bb** [comment]
没解决

**Comment by zkqiang** [comment]
暂时更新 dev 分支，已修复
