### ISSUE TITLE
Categories do not show posts and sub categories

### ISSUE THREAD

**Issue by MrMoner** [fluid-dev/hexo-theme-fluid#422]
#### Make sure
- [x] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases).
- [x] Browser does not belong to IE and other old browsers
- [x] It can be replicated through `hexo clean && hexo s` and cleared browser cache in the localhost.
- [x] Not affected by other Hexo plugins

#### Describe the bug
Post 1 categories: `['kotlin']`
Post 2 categories: `['kotlin', 'patterns']`
Post 3 categories: `['kotlin', 'error handling']`

*Expected render:*
![image](https://user-images.githubusercontent.com/11072140/109343899-eab9b080-7865-11eb-9888-ce65cf686f3e.png)

*Actual render:*
![image](https://user-images.githubusercontent.com/11072140/109344133-39ffe100-7866-11eb-9f84-38f46f30e55f.png)

The post under the `kotlin` category is ignored while the remaining sub categories are rendered.

#### To Reproduce
1. Have a post with a category `[x]`
2. Have a post with categories `[x, y]`
3. Go to categories page

**Comment by zkqiang** [comment]
thx!
