### ISSUE TITLE
npm安装主题定制翻译

### ISSUE THREAD

**Issue by Edwardzcn** [fluid-dev/hexo-theme-fluid#425]
#### Make sure
- [x] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] No solution found in [documentations](https://hexo.fluid-dev.com/docs/en/)

#### Describe the question

非常感谢主题的开发者们，我一直使用本主题，最近从本地下载主题release版本换用npm安装主题，有一个问题想请教一下，如果希望定制一些语言相关的文字显示，实现如下图效果。
![2{6) 5U DR`_DVQ_OUHREG4](https://user-images.githubusercontent.com/32711483/109620675-1f36b080-7b75-11eb-855d-94547b56978f.png)
![DU%6TDPG7QAQWSO4L58~FYW](https://user-images.githubusercontent.com/32711483/109620701-2493fb00-7b75-11eb-8270-db3bc7d05f36.png)

除了直接修改node_modules/hexo-theme-fluid/languages/zh-CN.yml，有没有其他方法？

另外这样的修改如果使用npm更新主题，是否会失效？

**Comment by zkqiang** [comment]
没什么好办法，语言这块暂时没法进行覆盖配置

使用npm会失效，建议用 release 方式安装

**Comment by Edwardzcn** [comment]
okay 谢谢您的回复。

不过fluid_config.yml可以覆盖配置npm原始的配置，语言定制覆盖应该也可以做，如果研究明白了contribute一波:smile:

**Comment by zkqiang** [comment]
fluid_config.yml 覆盖是 hexo 原生支持的，语言可以仿照 hexo 来自己实现，你可以研究下
