### ISSUE TITLE
顶部大图显示不完全

### ISSUE THREAD

**Issue by promefire** [fluid-dev/hexo-theme-fluid#426]
顶部大图只显示一部分，其余 都是空白

**Comment by zkqiang** [comment]
反馈问题请带截图或者地址

盲猜是图片尺寸问题

**Comment by promefire** [comment]
你好
使用了最新版出现的问题
地址： www.promefire.xyz





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fluid-dev/hexo-theme-fluid"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 下午5:10
收件人:&nbsp;"fluid-dev/hexo-theme-fluid"<hexo-theme-fluid@noreply.github.com&gt;;
抄送:&nbsp;"黎"<1311195013@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fluid-dev/hexo-theme-fluid] 顶部大图显示不完全 (#426)





 
反馈问题请带截图或者地址
 
盲猜是图片尺寸问题

**Comment by zkqiang** [comment]
没看到你说的 “顶部大图只显示一部分，其余 都是空白”，请发截图说明一下吧
