### ISSUE TITLE
about页面悬浮二维码过小

### ISSUE THREAD

**Issue by typoverflow** [fluid-dev/hexo-theme-fluid#427]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
如题，about页面二维码图片过小。
显示器分辨率为2.8k，不知道是不是和高分屏相关？
![11111](https://user-images.githubusercontent.com/41679605/109911697-7e1b3780-7ce5-11eb-9d43-d40e566645a0.png)

**Comment by zkqiang** [comment]
发个部署链接看看

**Comment by Edwardzcn** [comment]
![image](https://user-images.githubusercontent.com/32711483/109924217-e9bbcf80-7cfa-11eb-940f-c92032b1c5d1.png)
我的显示器2k的，二维码图片正常。

**Comment by typoverflow** [comment]
> 发个部署链接看看

http://blog.typoverflow.me/about/

**Comment by zkqiang** [comment]
已修复，可以试下

**Comment by typoverflow** [comment]
> 已修复，可以试下

有效，问题已解决。感谢！
