### ISSUE TITLE
主题字体问题

### ISSUE THREAD

**Issue by lxh20061128** [fluid-dev/hexo-theme-fluid#428]
大佬我想请教一下你，这个主题的字体修改家族名该怎么填？看了你的指南中的说明没有看懂
https://fonts.google.com/specimen/Ma+Shan+Zheng?subset=chinese-simplified&preview.text=%E4%BB%96%E4%BB%AC%E6%89%80%E6%9C%89%E7%9A%84%E8%AE%BE%E5%A4%87%E5%92%8C%E4%BB%AA%E5%99%A8%E5%BD%B7%E4%BD%9B%E9%83%BD%E6%98%AF%E6%9C%89%E7%94%9F%E5%91%BD%E7%9A%84%E3%80%82&preview.text_type=custom
我是直接看上了这个字体然后把家族名填进去没有变化

**Comment by zkqiang** [comment]
字体要本地安装或者引入了才行，请自行搜索具体用法
