### ISSUE TITLE
自动切换style的同时自动切换code highlight style

### ISSUE THREAD

**Issue by guanmengcheng** [fluid-dev/hexo-theme-fluid#429]
#### 如是功能需求，请确定符合以下情况
- [ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [ ] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

当前设置的代码高亮如果是dark类型的，白天的时候看不清，如果设置的light类型的，晚上看不清字体
![Snipaste_2021-03-07_14-32-21](https://user-images.githubusercontent.com/26402869/110231301-f4bc6d00-7f51-11eb-930b-b521a9914ca8.png)

#### 请描述您认为可行的解决方案

根据style切换自动切换

**Comment by zkqiang** [comment]
用深色的话需要打开：
https://github.com/fluid-dev/hexo-theme-fluid/blob/6acf9927091844b24dc20c078924240c058c0d12/_config.yml#L64

**Comment by guanmengcheng** [comment]
打开了，比如我选择代码高亮为‘Monokai'，在白天的时候代码还是看不清，需要切换到dark mode才可以看清，是不是可以考虑使用两个代码高亮类型，一个用于白天，一个用户晚上。
![Snipaste_2021-03-07_14-32-21](https://user-images.githubusercontent.com/26402869/110235006-af576a00-7f68-11eb-84ba-d527b71d1f6a.png)
