### ISSUE TITLE
能否增加文章按更新时间排序？

### ISSUE THREAD

**Issue by guanmengcheng** [fluid-dev/hexo-theme-fluid#433]
#### Make sure
- [ ] Difficult to implemented through [custom](https://hexo.fluid-dev.com/docs/en/guide/#custom-js-css-html).
- [ ] Difficult to implemented through third-party plugins.

#### Is your feature request related to a problem? Please describe

有些文章经常更新，目前是增加sticky强行置顶，能否增加文章按更新时间排序？若没有更新时间，则按生成时间排序

**Comment by zkqiang** [comment]
排序由 hexo-generator-index 插件控制，本主题不做特殊处理
