### ISSUE TITLE
[Hexo] 执行两次 hexo gen 以后，分类页面某些 div ID 不一致

### ISSUE THREAD

**Issue by mritd** [fluid-dev/hexo-theme-fluid#434]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

在多次执行 `hexo gen` 以后发现分类页面(category)的某些 div ID 不一致，这样可能导致搜索引擎认为页面已变更重复抓取；
目前不确定这是 Hexo 的行为还是主题的设置问题，非前端开发，在这里请求帮助。

当前问题站点发布仓库地址: [https://github.com/mritd/mritd.com/commits/master](https://github.com/mritd/mritd.com/commits/master)(相同 commit message 的变更)

以下为格式化后的 html diff 图:

![image](https://user-images.githubusercontent.com/13043245/110783315-3bd49600-82a3-11eb-80ec-28e9dfca4d5c.png)

**Comment by zkqiang** [comment]
已修改为分类名的MD5，这样就不会变化了

**Comment by mritd** [comment]
感谢 👍🏻️
