### ISSUE TITLE
PV UV统计

### ISSUE THREAD

**Issue by LihengXu** [fluid-dev/hexo-theme-fluid#435]
使用leadcloud访问量统计正常，但访客数不增加一直为0

**Comment by zkqiang** [comment]
给你加了 2 ，正常的

**Comment by LihengXu** [comment]
没有，只有访问数量增加了，访客量没变

**Comment by LihengXu** [comment]
我发现问题了，我要用github的二级域名才能增加，用我自己绑定的域名不能增加...

**Comment by zkqiang** [comment]
![image](https://user-images.githubusercontent.com/32983588/110885761-67e32c00-8322-11eb-8c94-bad337c8a6e6.png)
![image](https://user-images.githubusercontent.com/32983588/110885778-6e71a380-8322-11eb-8111-029ccc149139.png)

一个浏览器只能增加一次
