### ISSUE TITLE
覆盖about的intro以及微信二维码大小问题

### ISSUE THREAD

**Issue by kitescat** [fluid-dev/hexo-theme-fluid#437]
![image](https://user-images.githubusercontent.com/34134292/110834819-fdf26480-82d8-11eb-9b12-1d8069af46bb.png)
![image](https://user-images.githubusercontent.com/34134292/110834846-064a9f80-82d9-11eb-9f8b-43b44fed96f5.png)

**Comment by kitescat** [comment]
1. 你好我看了文档发现是没写成introduction 给后来者看看，新手真的没看文档好坑啊
![image](https://user-images.githubusercontent.com/34134292/110839917-15345080-82df-11eb-83d1-2aa1807ee2c4.png)
2. 然后我的wechat二维码也是小小的 更新了之后还是一样小小的
![image](https://user-images.githubusercontent.com/34134292/110840101-4745b280-82df-11eb-97d5-232bc1e42a34.png)

**Comment by kitescat** [comment]
你好，我又重新download了dev branch的包到本地，替换之后就成功了。
![image](https://user-images.githubusercontent.com/34134292/110843919-cfc65200-82e3-11eb-9e08-78002e636ac3.png)

不知道为什么npm install的版本一直都是旧版本，是不是默认旧版本了呢？

**Comment by zkqiang** [comment]
这是个bug，dev分支修复了但是没发版，先用dev的吧
