### ISSUE TITLE
图片懒加载占位符优化

### ISSUE THREAD

**Issue by wangyz1997** [fluid-dev/hexo-theme-fluid#439]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

首先感谢作者优秀的主题。

#### 请描述该需求尝试解决的问题

图片懒加载的占位图片，是一个不透明的白色背景gif，在深色模式下看起来会很违和。
#### 请描述您认为可行的解决方案

可以考虑将占位图改为透明的svg，并使用类似于手机app上的那种比较美观的样式。

**Comment by zkqiang** [comment]
如果有好的图片素材可以提供一下，另外将加入一个自定义加载图片的配置

**Comment by wangyz1997** [comment]
> 如果有好的图片素材可以提供一下，另外将加入一个自定义加载图片的配置

谢谢回复。应该可以使用`font awesome`中提供的矢量`spinner`图标旋转得到，效果应该会不错。

**Comment by zkqiang** [comment]
静态图标进行旋转不适合<img>，会使边框一起旋转，另外透明底我试了一下也并不适合深色模式，后续有灵感再改
