### ISSUE TITLE
关于页二维码变小的问题

### ISSUE THREAD

**Issue by moshiangel** [fluid-dev/hexo-theme-fluid#440]
点击关于界面图像下方的微信图标时显示的二维码过小，无法用微信识别（本人使用的是Chrom浏览器电脑版，手机版未测试）。以下为点击时的图片。
![](https://gitee.com/sasakifeishi/blogimage/raw/master/img/Snipaste_2021-03-14_16-21-57.png)

**Comment by zkqiang** [comment]
请暂时使用 dev 分支，或者下载 [v1.8.9-beta](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.8.9-beta)

**Comment by zkqiang** [comment]
1.
