### ISSUE TITLE
如何进行版本升级呢？？

### ISSUE THREAD

**Issue by Plato-Ideal** [fluid-dev/hexo-theme-fluid#446]
#### 请确认
- [ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

最近遇到了这个问题：
err: Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
查询之后得知需要更新主题版本，但不知道怎么更新fluid？感谢帮助

**Comment by zkqiang** [comment]
`npm i js-yaml@3.14.0` 试试，你环境里的 js-yaml 版本过高

或者用 dev 分支代码试试，更新主题请见文档：
https://hexo.fluid-dev.com/docs/start/#更新主题

**Comment by xiahouwenyu** [comment]
请问最新版本还是报错err: Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.怎么办？
