### ISSUE TITLE
博客中目录无法正常显示

### ISSUE THREAD

**Issue by ZSZ2000** [fluid-dev/hexo-theme-fluid#447]
#### 请确认
- [ x ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ x ] 浏览器不属于 IE 等非主流浏览器 
- [ x ] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [ x ] 已经排除是其他 Hexo 插件影响

#### Bug 描述

我的一篇博客文章的目录无法正常显示，尝试新建项目后，仍然有这样的问题……

#### 复现步骤
该 Bug 复现步骤如下：
1. 创建新项目
2. 修改项目主题为fluid
3. 创建博客，博客内容见附件
[markdown.zip](https://github.com/fluid-dev/hexo-theme-fluid/files/6170993/markdown.zip)

4. 运行项目
5. 目录显示在尾部而非右侧

网页链接：<https://zsz2000.gitee.io/markdown/>

#### 截图
![Screenshot_2021-03-19 markdown 简明语法手册 - ZSZ小站](https://user-images.githubusercontent.com/43663400/111778713-14f41080-88f0-11eb-9ca7-9a45b95bcc2f.png)

**Comment by zkqiang** [comment]
应该是你装了其他高亮插件导致样式异常

比如 `id="language-highlight-code-block"` 这个元素，不是属于本主题里的

**Comment by ZSZ2000** [comment]
谢谢回复
但我是在没有任何插件的环境中进行的测试，所以那个并不是其他的插件
但`id="language-highlight-code-block"`确实是我编写的，用于实现类似html锚点的功能，可以实现两个区块之间的跳转
markdown原生不支持这种功能，但可以用html标签实现
原markdown文件已随附件上传，您可以直接查看，如果因为主题的设置导致这种语法不受支持，请问是否可以提供替代解决方案？

**Comment by ZSZ2000** [comment]
谢谢回复
但我是在没有任何插件的环境中进行的测试，所以那个并不是其他的插件
但`id="language-highlight-code-block"`确实是我编写的，用于实现类似html锚点的功能，可以实现两个区块之间的跳转
markdown原生不支持这种功能，但可以用html标签实现
原markdown文件已随附件上传，您可以直接查看，如果因为主题的设置导致这种语法不受支持，请问是否可以提供替代解决方案？

**Comment by ZSZ2000** [comment]
谢谢回复
但我是在没有任何插件的环境中进行的测试，所以那个并不是其他的插件
但`id="language-highlight-code-block"`确实是我编写的，用于实现类似html锚点的功能，可以实现两个区块之间的跳转
markdown原生不支持这种功能，但可以用html标签实现
原markdown文件已随附件上传，您可以直接查看，如果因为主题的设置导致这种语法不受支持，请问是否可以提供替代解决方案？

**Comment by zkqiang** [comment]
没必要啊，直接

`(参见[加强的代码块](#6-加强的代码块))`

也是有锚点效果，因为每个 <h1> <h2> ... 标签都有 id

**Comment by ZSZ2000** [comment]
谢谢
显然这是一种解决方案，只能暂时用这种方式了
但这种方式直接使用标题id，如`3-3-title`这种标签，部分markdown渲染器不支持，无法实现markdown笔记的直接发布，如果这一主题能直接支持原生的所有html标签，我认为更好……

**Comment by zkqiang** [comment]
我说了，是因为你 `<i id="xxx" />` 写错了，应该是 `<i id="xxx"></i>`，这样就不会出现样式问题，也有锚点作用

**Comment by ZSZ2000** [comment]
谢谢
