### ISSUE TITLE
关于页面使用qrcode显示二维码，二维码图片非常小，怎么能让它变大。

### ISSUE THREAD

**Issue by MengYingjie** [fluid-dev/hexo-theme-fluid#448]
fluid版本：v1.8.9
浏览器版本：chrome-版本 89.0.4389.90
在关于页面中，使用qrcode显示二维码，二维码图片非常小，不知道怎么能让它变大。
页面地址
[https://myj.im/about/](https://myj.im/about/)
```
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/mengyingjie", tip: "GitHub" }
    - { class: "iconfont icon-bilibili-fill", link: "https://space.bilibili.com/99029356", tip: "B站" }
    - { class: "iconfont icon-qq-fill", qrcode: "/img/qq.jpg" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/img/wx-1.jpg" }
```
![image](https://user-images.githubusercontent.com/54539497/111825931-08d57680-8923-11eb-93b6-d341839dc9f8.png)

**Comment by zkqiang** [comment]
1.8.9已经修复了这个问题，可能你没更新完整，请再重新更新试试吧

**Comment by MengYingjie** [comment]
> 1.8.9已经修复了这个问题，可能你没更新完整，请再重新更新试试吧

@zkqiang 谢谢帮助，我用替换文件更新的方法，成功升级到1.8.9
我的问题在于我是用npm升级命令，升级后版本仍是1.8.8，npm库好像没有新版的
```
npm install --save hexo-theme-fluid
```

**Comment by zkqiang** [comment]
是有的

https://www.npmjs.com/package/hexo-theme-fluid

**Comment by MengYingjie** [comment]
> 是有的
> 
> https://www.npmjs.com/package/hexo-theme-fluid
@zkqiang 
我这npm不知道出什么问题了，删除主题后，再安装，有新版本了😂
