### ISSUE TITLE
关于页添加邮箱链接

### ISSUE THREAD

**Issue by SuAdrenine** [fluid-dev/hexo-theme-fluid#449]
#### 请确认
V1.8.9最新版
查看了配置文档：
```
about:
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com', tip: 'GitHub' }
    - { class: 'iconfont icon-douban-fill', link: 'https://github.com', tip: '豆瓣' }
    - { class: 'iconfont icon-wechat-fill', qrcode: '/img/favicon.png' }
```

#### 问题描述
现在问题是我想在这里添加一个邮箱：
我尝试过好几种写法：
 - { class: 'iconfont icon-mail-fill', link: 'xxx@mail.com', tip: '邮箱' }
 - { class: 'iconfont icon-mail-fill', mail: 'xxx@mail.com', tip: '邮箱' }
 - { class: 'iconfont icon-mail-fill', link: \<xxx@mail.com\>, tip: '邮箱' }

上述几种写法都无效，我想知道，正确写法是什么，谢谢~

**Comment by zkqiang** [comment]
```
mailto:xxx@mail.com
```
<a href="mailto:xxx@mail.com">xxx@mail.com</a>


https://www.haorooms.com/post/mailto_link_html

**Comment by SuAdrenine** [comment]
> ```
> mailto:xxx@mail.com
> ```
> 
> [xxx@mail.com](mailto:xxx@mail.com)
> 
> https://www.haorooms.com/post/mailto_link_html

@zkqiang 非常抱歉再次提问，我按照您的提示改成
```
{ class: 'iconfont icon-mail', mailto: xxx@mail.com, tip: '邮箱' }
```
但是，点击的时候，页面会跳转到首页，而不是打开邮箱app或者是展示邮箱地址，这个是我写法问题，还是其他什么呢

**Comment by zkqiang** [comment]
`link: 'mailto:xxx@mail.com'`

**Comment by SuAdrenine** [comment]
> `link: 'mailto:xxx@mail.com'`

可以了，非常感谢
