### ISSUE TITLE
err: TypeError: Cannot read property 'post_default_img' of undefined

### ISSUE THREAD

**Issue by yhy0** [fluid-dev/hexo-theme-fluid#450]
最新版
err: TypeError: Cannot read property 'post_default_img' of undefined

![image](https://user-images.githubusercontent.com/31311038/111873801-1b0bef00-89cd-11eb-87ba-e8ac26922007.png)

**Comment by zkqiang** [comment]
检查配置完整性

**Comment by YuanZhou314** [comment]
同样在恢复博客文件的时候出现了这个问题
