### ISSUE TITLE
Error: Request failed with status code 405

### ISSUE THREAD

**Issue by Surmiloo** [fluid-dev/hexo-theme-fluid#451]
gitalk配置好,登陆的时候报错:Error: Request failed with status code 405

我的gitalk配置:
![image](https://user-images.githubusercontent.com/31952942/112251074-8ab3ff80-8c95-11eb-8422-54a4c3522cdf.png)
![image](https://user-images.githubusercontent.com/31952942/112251092-93a4d100-8c95-11eb-84e2-a6629ed2a1c6.png)

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/53761b1ad8700e2c30fb3b02b1850acac95413e5/_config.yml#L686

注释里写了，需要设置 `proxy`

**Comment by Surmiloo** [comment]
那么在fluid自带的gitalk中我该怎么配置呢?配置哪个文件呢

**Comment by zkqiang** [comment]
就是主题配置，把这个配置项加上就行了

**Comment by Surmiloo** [comment]
![image](https://user-images.githubusercontent.com/31952942/112276977-3d975400-8cbc-11eb-920f-062d83ee4b2d.png)
这个是什么情况呢

**Comment by zkqiang** [comment]
issue 要手动创建，具体见 gitalk 自己的文档

**Comment by Surmiloo** [comment]
解决,感谢感谢
