### ISSUE TITLE
黑暗与日间模式切换时出现的问题

### ISSUE THREAD

**Issue by xiao-ming9** [fluid-dev/hexo-theme-fluid#452]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

您好，非常开心发现了这个主题。在部署完成后发现一个问题，想请教一下。

在 chrome 浏览器中使用，点击暗黑模式与日间模式切换时，会自动弹出新的如下标签页：

![image](https://user-images.githubusercontent.com/38147977/112709844-9a328300-8ef7-11eb-8491-80439630bca0.png)

想请问一下这是怎么回事？在 Safari 浏览器并未出现这一问题。

**Comment by zkqiang** [comment]
`<a class="nav-link" href="javascript:" target="_blank" rel="noopener">`
可能是你某个插件自动给它加上了 `target="_blank"`，导致出现跳转

你可以检查一下，我在dev分支尝试修复了你也可以试试

**Comment by xiao-ming9** [comment]
@zkqiang 使用dev分支就没有问题了，感谢！
