### ISSUE TITLE
文章页图片阴影和圆角边框

### ISSUE THREAD

**Issue by typoverflow** [fluid-dev/hexo-theme-fluid#455]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
如题，在看作者大大的示例博客时发现图片呈现时有圆角边框和阴影
![image](https://user-images.githubusercontent.com/41679605/113496561-61b12b80-952d-11eb-8230-fb25623cf0db.png)

但是我这边无论是是使用`![](/path/to/img)`还是`{% asset_img /path/to/img %}`都没有这个效果
![image](https://user-images.githubusercontent.com/41679605/113496589-c3719580-952d-11eb-8fce-466840a05227.png)

想求助一下怎么添加这个效果，谢谢！

**Comment by zkqiang** [comment]
暂时只支持markdown写法的图片

可以参考 https://hexo.io/zh-cn/docs/asset-folders.html#Embedding-an-image-using-markdown 代替 asset_img

**Comment by typoverflow** [comment]
好的 谢谢！
