### ISSUE TITLE
编辑_config.fluid.yml中的关于页时无法增加评论系统

### ISSUE THREAD

**Issue by heu-kevin** [fluid-dev/hexo-theme-fluid#456]
fluid版本是1.8.9
在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
在编辑_config.fluid.yml文件时，设置了valine评论系统，在post: comments: enable设置为true时，在博客页面正常显示了评论系统，在links: comments: enable设置为true时友链页面也正常，但是在about: comments: enable设置为true时“关于”页面却不出现评论系统，而且我还发现将about: icons全部注释掉仍然会出现GitHub和豆瓣、微信的链接，但是修改about: avatar
却可以正常更改“关于”页面的头像，不知是怎么回事？
仔细检查过了，about下的设置缩进没有问题

**Comment by zkqiang** [comment]
问题一：关于页开启评论是在 Front-matter 里 `comments: true`

问题二：不要把 `icons` 这个key也一起注释掉，不然会被覆盖配置填充上默认的 `icons` 值

**Comment by heu-kevin** [comment]
> 问题一：关于页开启评论是在 Front-matter 里 `comments: true`
> 
> ```yaml
> ---
> title: about
> layout: about
> comments: true
> ---
> ```
> 
> 问题二：不要把 `icons` 这个key也一起注释掉，不然会被覆盖配置填充上默认的 `icons` 值
> 正确方式：
> 
> ```yaml
> about:
>   icons:
>     # - { class: 'iconfont icon-github-fill', link: 'https://github.com', tip: 'GitHub' }
>     # - { class: 'iconfont icon-douban-fill', link: 'https://github.com', tip: '豆瓣' }
>     # - { class: 'iconfont icon-wechat-fill', qrcode: '/img/favicon.png' }
> ```

感谢您的回答，按照您的方法，问题二已经成功解决！不过问题一在Front-matter里加入comments: true还是没有用

**Comment by zkqiang** [comment]
`comment: true` ，上面写错了

**Comment by heu-kevin** [comment]
> `comment: true` ，上面写错了

完美解决，谢谢您！
