### ISSUE TITLE
_config.fluid.yml修改不生效

### ISSUE THREAD

**Issue by Vepoe** [fluid-dev/hexo-theme-fluid#457]
版本1.8.9，_config.fluid.yml配置不生效。

**Comment by zkqiang** [comment]
1. `_config.fluid.yml` hexo5版本以上才支持
2. 可以通过 `hexo s --debug` 看打印配置到底有没有生效

**Comment by Vepoe** [comment]
> `_config.fluid.yml` 是Hexo本身的功能，主题版本不会影响
> 
> 1. `_config.fluid.yml` hexo5版本以上才支持
> 2. 可以通过`hexo s --debug`看打印配置到底有没有强制
[Fluid] Merge data/fluid_config.yml into theme config.
应该是这条吧，使用的是/theme/fluid/_config.yml

**Comment by zkqiang** [comment]
`data/fluid_config.yml` 这个也是覆盖配置，是 fluid 自带的
不要和 `_config.fluid.yml` 同时用

**Comment by Vepoe** [comment]
可是，HEXO下里根本就没有`_config.fluid.yml`
真令人头大

**Comment by zkqiang** [comment]
不是根目录，是 `source/_data/fluid_config.yml`

**Comment by Vepoe** [comment]
我是刚刚装的这个主题，文件结构跟源码一模一样，source下就没有这个文件夹

**Comment by zkqiang** [comment]
那就不是这个问题，实际还是你 `_config.fluid.yml` 配置的问题

**Comment by Vepoe** [comment]
好吧，我直接复制，不纠结了，覆盖不弄了

**Comment by zkqiang** [comment]
这个地方应该不会有问题，很长时间没修改过了，fluid blog 也用的是这种覆盖方式

**Comment by superganplus** [comment]
问题依旧还在哦，麻烦请看：https://github.com/fluid-dev/hexo-theme-fluid/issues/503

**Comment by helloword666888** [comment]
根目录下设置`_config.fluid.yml`不生效

**Comment by zkqiang** [comment]
@helloword666888 原因在2楼已经说了
