### ISSUE TITLE
文章目录失效，有手写的方法没有

### ISSUE THREAD

**Issue by Vepoe** [fluid-dev/hexo-theme-fluid#458]
![QQ截图20210410135833](https://user-images.githubusercontent.com/58576156/114260027-ddffaf00-9a04-11eb-840e-7ff59f34f1cc.png)

**Comment by zkqiang** [comment]
没有，目录是自动生成的

部署后的链接发一个看看？

**Comment by Vepoe** [comment]
https://bhy.cool/2021/04/10/OBS%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8Bv1.0/#

**Comment by zkqiang** [comment]
`<h2>` 标题是你自己写的吧？

改成 `<h2 id="一、直播设置">` 试试

**Comment by Vepoe** [comment]
谢谢，成功了
