### ISSUE TITLE
如何关闭“本博客所有文章除特别声明外，均采用 CC BY-SA 4.0 协议 ，转载请注明出处！”

### ISSUE THREAD

**Issue by ccvv116** [fluid-dev/hexo-theme-fluid#460]
小白求解

文章末尾出现的

“本博客所有文章除特别声明外，均采用 CC BY-SA 4.0 协议 ，转载请注明出处！”

这段要怎么修改或者关闭啊

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/53761b1ad8700e2c30fb3b02b1850acac95413e5/_config.yml#L573

改为 false

**Comment by ccvv116** [comment]
"hexo": {
    "version": "5.4.0"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^4.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0",
    "hexo-theme-fluid": "^1.8.9-a",
    "hexo-theme-landscape": "^0.0.3"
  }

_config.fluid.yml
#是脚注配置么 如果是的话 配置不生效啊
post:
  footnote:
    enable: false

**Comment by zkqiang** [comment]
不是脚注

```yaml
post:
  copyright:
    enable: false
```
