### ISSUE TITLE
关于友链页面的问题

### ISSUE THREAD

**Issue by leicancun** [fluid-dev/hexo-theme-fluid#461]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

大佬,可以把友链页面的数据独立出来放到`_data`文件夹下吗,友链数据多了放一起感觉有点臃肿,如果可以该怎么做?能教我设置一下吗?

**Comment by zkqiang** [comment]
覆盖配置有三种：
1. `_data/fluid_config.yml`
2. 根目录 `_config.fluid.yml`
3. 根目录 `_config.yml` 配置里加入 `theme_config:`

以上三种配合使用，就可以把一些配置独立出去了

**Comment by leicancun** [comment]
大佬,我之前的配置是放在根目录`_config.fluid.yml`里的,我在里面配置了友链
配置是这样的
```
links:
  enable: true
  banner_img: https://cdn.jsdelivr.net/gh/leicancun/JSCDN@main/images/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  banner_mask_alpha: 0.3
  subtitle:
  # 友链的成员项
  # Member item of page
  items:
    - {
      title: "小丁的个人博客",
      intro: "世间所有的相遇，都是久别重逢",
      link: "https://tding.top",
      avatar: "https://tding.top/images/avatar.webp"
    }
    - {
      title: "米奇妙妙屋",
      intro: "逐风揽月登九天 踏浪擒龙游四海",
      link: "https://ifibe.com/",
      avatar: "https://cdn.jsdelivr.net/gh/useblue/ucdn/imgs/avatar.webp"
    }
    - {
      title: "荷戟独彷徨",
      intro: "爱光学，爱生活，爱创造",
      link: "https://guanqr.com/",
      avatar: "https://cdn.jsdelivr.net/gh/guanqr/blog/static/icons/android-chrome-512x512.png"
    }
    - {
      title: "iMaeGoo’s Blog",
      intro: "虹墨空间站",
      link: "https://www.imaegoo.com",
      avatar: "https://www.imaegoo.com/images/avatar.jpg"
    }
    - {
      title: "琉仙の后花园",
      intro: "一起来种花家呀",
      link: "https://blog.lx101.cn/",
      avatar: "https://z3.ax1x.com/2021/03/28/cS2LNV.jpg"
    }
    - {
      title: "LOGI",
      intro: "会点代码的强迫症",
      link: "https://logi.im",
      avatar: "https://code.bdstatic.com/npm/logicdn@1.0.0/logi.im/usr/images/global/logo.webp"
    }

```
根据建议我创建了`_data/fluid_config.yml`,并添加了在里面输入了一下内容
```
links:
  items:
    - {
      title: "测试",
      intro: "这是一个测试友链",
      link: "https://www.myql.xyz",
      avatar: "https://cdn.jsdelivr.net/gh/leicancun/JSCDN@master/images/circle-cropped.webp"
    }
```
我发现它并不生效,这个覆盖配置是否不能同时生效?

其实想单独把这个友链数据分开是因为我在弄`netlify cms`发现如果可行的话,就可以直接通过网页添加并预览友链效果大概是这种样子的
![1](https://i.ibb.co/SmxxJtB/msedge-2-YOJi5-BHin.png)
![2](https://i.ibb.co/mSFT8y0/msedge-Mvv-WDc-Hqsu.png)

这样极大的方便了友链修改,删除,添加,受限于有限的知识,我不能很好的解决目前遇到的问题,如果可以得到你的帮助就太感谢了,如果你很忙,也不要紧,我非常感谢你的回复,谢谢大佬

**Comment by zkqiang** [comment]
你把 `_config.fluid.yml` 里的 `items` 这个键以及内容删掉或者注释掉就行了，覆盖配置之间是有优先级的。

你想单独写的话只能自己鼓捣了，写好单独部署一下然后链接在博客菜单里即可。
Hexo是静态页面，不打算加入这种太复杂的功能

**Comment by leicancun** [comment]
谢谢大佬的帮助,我已经进行到最后一点了,现在遇到的问题是
```
links:
  items:
    - {
      title: "测试",
      intro: "测试友链",
      link: "https://123.com",
      avatar: "https://123.com/images/avatar.webp"
    }
```
如何改成这样使它同样生效?
```
links:
  items:
    - title: "测试",
      intro: "测试友链",
      link: "https://123.com",
      avatar: "https://123.com/images/avatar.webp"
```

**Comment by zkqiang** [comment]
逗号去掉就行了

```yaml
links:
  items:
    - title: "测试"
      intro: "测试友链"
      link: "https://123.com"
      avatar: "https://123.com/images/avatar.webp"
```

具体见 yaml 语法

**Comment by leicancun** [comment]
感谢大佬的帮助😁我可以把双引号去掉使它正常显示吗,这应该是最后一步了,但我不清楚怎么弄,我去搜索了yml语法,通过`netlify cms`输出的结果都是这样不带引号的,不带引号使它生效是否可行呢?感谢大佬的耐心回复😊
```
links:
  items:
    - title: 测试
       intro: 测试友链
       link: https://123.com
       avatar: https://123.com/images/avatar.webp
```

**Comment by zkqiang** [comment]
带不带引号，和带不带花括号，只要符合yaml语法规则，实际都是等效的效果，也能生效

**Comment by leicancun** [comment]
谢谢大佬的耐心解答,非常好的消息,我成功了,效果非常的棒,现在可以直接通过网页添加友链并预览了😁😁😁再次谢谢大佬
![https://i.ibb.co/8xHRJ9C/msedge-Vsc-P2r-Owv-F.png](https://i.ibb.co/8xHRJ9C/msedge-Vsc-P2r-Owv-F.png)

![https://i.ibb.co/bd1CMDD/msedge-tuxzkcfk4-A.png](https://i.ibb.co/bd1CMDD/msedge-tuxzkcfk4-A.png)

![https://i.ibb.co/fdTGD4Z/msedge-IPUB48-Mzd-J.png](https://i.ibb.co/fdTGD4Z/msedge-IPUB48-Mzd-J.png)

**Comment by zkqiang** [comment]
可以整理成文章，分享到 fluid blog 里

https://github.com/fluid-dev/hexo-fluid-blog

**Comment by leicancun** [comment]
好的，我会进行整理，然后去投稿😁这个方法不仅仅局限于友链，其他的设置也是可以改的，我觉得与fluid主题兼容性非常高

**Comment by arleycn** [comment]
@leicancun 抱歉！！！演示站点貌似被我搞坏了，
在添加友链的地方添加了一个站点导致主页样式错乱，具体log看不到
不过整体配置下来很方便
如果可以，还请看下[演示站点](https://qwqmiao.cf/)

**Comment by leicancun** [comment]
> @leicancun 抱歉！！！演示站点貌似被我搞坏了， 在添加友链的地方添加了一个站点导致主页样式错乱，具体log看不到 不过整体配置下来很方便 如果可以，还请看下[演示站点](https://qwqmiao.cf/)

不，是友链页面设置的图片被删除了，所以生成的时候发生了错误，后面我会改一下修复这个问题，请放心的试用演示站点，这就是用来测试体验的

**Comment by arleycn** [comment]
> > @leicancun 抱歉！！！演示站点貌似被我搞坏了， 在添加友链的地方添加了一个站点导致主页样式错乱，具体log看不到 不过整体配置下来很方便 如果可以，还请看下[演示站点](https://qwqmiao.cf/)
> 
> 不，是友链页面设置的图片被删除了，所以生成的时候发生了错误，后面我会改一下修复这个问题，请放心的试用演示站点，这就是用来测试体验的

哈哈好的~
