### ISSUE TITLE
使用GitHub Actions自动部署，会导致所有文章的最后更新时间一致

### ISSUE THREAD

**Issue by ChuYang-FE** [fluid-dev/hexo-theme-fluid#462]
#### 请确认
- [√] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [√] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
全部文章都是刚部署完的时间，即.md文件最后的修改时间。但又不想每次在front-matter写更新时间。有办法解决吗？感谢！
<img width="1229" alt="details" src="https://user-images.githubusercontent.com/45116321/115266057-6e0ec880-a16a-11eb-97a3-0226f90065c8.png">

**Comment by zkqiang** [comment]
没有

**Comment by ChuYang-FE** [comment]
> 没有
😂大佬的回答总是如此简洁有力

**Comment by Lodour** [comment]
可以自己手动设置更新时间
```
---
title: ...
date: ...
updated: ...
---
```
