### ISSUE TITLE
custom_head怎么插入多个meta标签

### ISSUE THREAD

**Issue by FantDing** [fluid-dev/hexo-theme-fluid#463]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
custom_head怎么插入多个meta标签，我看文档只有custom_js，custom_css可以，我用list形式，第二个标签到body中了
![image](https://user-images.githubusercontent.com/21337200/115352393-e5377180-a1e9-11eb-98d9-b7f51dd70fbc.png)

**Comment by zkqiang** [comment]
直接写一起就行了

```yaml
custom_head: '<meta ...><meta ...><meta ...>'
```

**Comment by FantDing** [comment]
感谢，可以
