### ISSUE TITLE
升级hexo5后所有图片都不显示

### ISSUE THREAD

**Issue by WantonX** [fluid-dev/hexo-theme-fluid#464]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

**Comment by WantonX** [comment]
原本是用hexo-asset-image这个包，将图片都存放在了文件夹下，md中使用相对路径索引，升级hexo5后所有图片都不见了。。。恳请帮助。。。谢谢！

**Comment by zkqiang** [comment]
这个和主题无关，应该到 hexo-asset-image 去提问...
