### ISSUE TITLE
打开文章页后，页面标题跳转不准确

### ISSUE THREAD

**Issue by LazyLutra** [fluid-dev/hexo-theme-fluid#466]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

打开文章页后，点击最后两个一级标题跳转错误，跳转到相邻章节的末尾或者章节标题处。
先跳转别的章节，再跳转最后两个一级标题的章节时，不会出现该错误。

清除缓存后仍存在该问题。

chrome 版本 90.0.4430.85
edge 版本 90.0.818.46

**Comment by zkqiang** [comment]
因为图片懒加载的原因，无法预知图片的高度
除了关闭懒加载暂时无法避免

**Comment by LazyLutra** [comment]
> 因为图片懒加载的原因，无法预知图片的高度
> 除了关闭懒加载暂时无法避免

关闭懒加载后可以正常跳转了，非常感谢
