### ISSUE TITLE
页头毛玻璃特效应用失败？

### ISSUE THREAD

**Issue by X-Funny** [fluid-dev/hexo-theme-fluid#470]
我使用npm命令安装了此主题

这是当时的操作流程

1.新建_config.fluid.yml
2.写入配置信息
3.将
ground_glass
  enable: false中的false改为true
4.保存
5.hexo clean (无任何报错)
6.hexo g (无任何报错)
7.分别chrome和firefox清除浏览器缓存
8.访问网站，发现页头没有出现毛玻璃特效

帮助文档中貌似没有与页头毛玻璃特效有关的内容，还是我没有找到？
这是一个bug，还是我进行了错误的操作？

**Comment by zkqiang** [comment]
请对比 https://hexo.fluid-dev.com/ 的效果和配置

https://github.com/fluid-dev/hexo-fluid-blog/blob/3f4a9b28983603e281ef274dc0058564423b8136/_config.fluid.yml#L73-L81

如果确认无误，可以尝试使用 `hexo s --debug` 命令查看打印的配置项是否生效

**Comment by X-Funny** [comment]
> 请对比https://hexo.fluid-dev.com/的效果和配置
> 
> https://github.com/fluid-dev/hexo-fluid-blog/blob/3f4a9b28983603e281ef274dc0058564423b8136/_config.fluid.yml#L73-L81
> 
> 如果确认无误，可以尝试使用`hexo s --debug`命令查看打印的配置项是否生效

我刚才更新了一下主题，并重新写了配置文件，现在能正常显示了
