### ISSUE TITLE
搜索功能异常，一直 loading

### ISSUE THREAD

**Issue by 5ME** [fluid-dev/hexo-theme-fluid#472]
#### 请确认

- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

当进行搜索时，搜索功能经常性无法使用，一直显示 loading
浏览器：

+ 电脑端：最新版 Edge，Chrome
+ 手机端：最新版 夸克，MIUI 自带

另外：已经在 `_config.fluid.yml` 中设置不扫描正文，但是好像设置无效，仍然会扫描正文

#### 复现步骤

该 Bug 复现步骤如下：

1. 在首页点击搜索按钮

#### 截图

![loading](https://gitee.com/ME_WE/my-picture-repository/raw/master/%E9%9B%B6%E7%A2%8E/Fluid%E4%B8%BB%E9%A2%98%E5%BC%82%E5%B8%B81.png)
![](https://gitee.com/ME_WE/my-picture-repository/raw/master/%E9%9B%B6%E7%A2%8E/Fluid%E4%B8%BB%E9%A2%98%E5%BC%82%E5%B8%B82.png.png)
![](https://gitee.com/ME_WE/my-picture-repository/raw/master/%E9%9B%B6%E7%A2%8E/Fluid%E4%B8%BB%E9%A2%98%E5%BC%82%E5%B8%B83.png)

**Comment by fishUPs** [comment]
看看f12浏览器是不是显示跨域了

**Comment by Explorer-Dong** [comment]
文章内容太多了导致生成的localsearch.xml文件体积过大，从服务器加载到本地需要大的资源加载开销。
