### ISSUE TITLE
对于markdown语法的解析疑问

### ISSUE THREAD

**Issue by HideOnLie** [fluid-dev/hexo-theme-fluid#473]
#### Describe the question

最近在捣腾双向链接笔记，想让类似obsidian的软件，在使用双向链接笔记软件使用[[ ]]作为引用链接，同时希望使hexo blog点击这个链接也可以跳转到对应的文章。

在过程中发现，我在一篇文章中使用了[[ ]]这个语法，hexo只会基于当前url来跳转。例子如下：
在`git笔记` 这篇文章中使用了`[[git-add说明文档]]`，当前文章的url为：`localhost:4000/git笔记/`
![image](https://user-images.githubusercontent.com/51672711/116959842-681ff800-acd1-11eb-945a-613aa2a2bdf0.png)
![image](https://user-images.githubusercontent.com/51672711/116969332-af65b300-ace8-11eb-9ae1-a45529d5dd85.png)

![image](https://user-images.githubusercontent.com/51672711/116970244-32d3d400-acea-11eb-9d89-e4c2a0b034d8.png)

此时在hexo的网页中点击这个链接会跳转到这个`localhost:4000/git笔记/git-add说明文档`
但是实际`git-add说明文档`这篇文章的正确url应该为：`localhost:4000/git-add说明文档`，所以会出现跳转失败

对于这个情况，我如何可以让这个链接在hexo中也跳转到我希望的页面呢？

**Comment by zkqiang** [comment]
`[[/git-add说明文档]]`

了解下相对路径和绝对路径

**Comment by HideOnLie** [comment]
> `[[/git-add说明文档]]`
> 
> 了解下相对路径和绝对路径

如果我写成`[[/git-add说明文档]]`，hexo中看到的就是下图一样。没有被解析成url。
![image](https://user-images.githubusercontent.com/51672711/117029184-fd9ea480-ad30-11eb-85bc-da04e83f3aff.png)
所以感觉挺奇怪的，不知道是怎么解析的

**Comment by zkqiang** [comment]
markdown 解析是根据你安装的 renderer 有关，和主题基本没关系，可以参考对应的文档
