### ISSUE TITLE
博客文章网址有无 "/" 导致阅读量不统一

### ISSUE THREAD

**Issue by MSDNicrosoft** [fluid-dev/hexo-theme-fluid#483]
#### 已确认
- 是当前最新的 Release 版本
- 浏览器不属于 IE 等非主流浏览器 
- 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- 排除是其他 Hexo 插件影响

#### 描述
开启此主题的文章阅读次数统计（使用leancloud），当打开的网址末尾有或无 `/` 符号时，阅读次数不统一（如 `https://msdnicrosoft.cn/Sodium-Chineseization` 和 `https://msdnicrosoft.cn/Sodium-Chineseization/`）
(使用 `xxx.cn/xxx/index` 和 
 `xxx.cn/xxx/index.html` 亦是如此)     
末尾无 `/` 符号↓
![ ](https://cdn.jsdelivr.net/gh/MSDNicrosoft/CDN@4.2/img/Screenshot_20210518_193906.jpg)
末尾有 `/` 符号↓
![ ](https://cdn.jsdelivr.net/gh/MSDNicrosoft/CDN@4.2/img/Screenshot_20210518_193849.jpg)
leancloud 存储数据↓
![ ](https://cdn.jsdelivr.net/gh/MSDNicrosoft/CDN@4.2/img/Screenshot_20210518_193819.jpg)

**Comment by zkqiang** [comment]
dev已修复
有没有 `/` 结尾以及 `/index.html` 结尾都会被统一记录为 `/xxxx/` 形式

已统计的数据需要自行手动修复
