### ISSUE TITLE
点击搜索 icon 后输入关键字没有匹配到相关结果

### ISSUE THREAD

**Issue by luohuidong** [fluid-dev/hexo-theme-fluid#485]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

点击导航栏中的搜索 icon，在弹出模态框后输入关键字，没有任何搜索结果展示。

#### 复现步骤

该 Bug 复现步骤如下：
1. 打开 https://hexo.fluid-dev.com/
2. 点击头部导航栏中的搜索 icon
3. 搜索模态框展示后，紧接着输入关键字 "e"
4. 没有展示任何搜索结果

#### 期望结果

有包含 e 关键字的搜索结果展示。

#### 原因分析

搜索功能是依赖 local-search.xml 这个文件的，而看了一下源码（文件 layout/_partial/plugins/local-search.ejs）local-search.xml 这个文件的下载是鼠标点击了搜索模态框的 input 框之后才会下载。所以首次点击 icon 打开模态框的时候，虽然 input 自动聚焦，但是如果鼠标没有点击 input 框，local-search.xml 这个文件是不会下载的。这个时候在 input 框中输入任何的关键字都是不会匹配到任何结果的。

所以如果要达到期望的结果，那么就需要在点击导航栏搜索 icon 的时候，就应该去下载 local-search.xml 这个文件。这样就能确保 input 自动聚焦之后，立刻输入关键字能展示相关的结果。

**Comment by zkqiang** [comment]
非常感谢
