### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by l797w** [fluid-dev/hexo-theme-fluid#487]
哎，我是个自由的人，很简单的建议，就不按着格式写了😂
1.我觉得主题把文章的主体和评论分成两个板块，中间空上一小段距离，像volantis一样，这样是不是更好呢？
![](https://img02.sogoucdn.com/app/a/100520146/9D2CEC07C9919493C28454E540DBE081)
![](https://img01.sogoucdn.com/app/a/100520146/84FE40F46FB3159213335CEC69D921E3)
2.还有侧边栏toc我觉得加上边框比较好
![](https://img04.sogoucdn.com/app/a/100520146/8E142AF8F07ED4B471E4C48060960BB5)
这样的话给主题设置背景会要好一点，不然的话toc可能会跟背景颜色特别像看不清楚

**Comment by l797w** [comment]
3.我觉得话，主题 markdown 引用 的这样样式也不是很好看，就一个白色的条条
![](https://img04.sogoucdn.com/app/a/100520146/4D1C8823860AA4E5E1F6BB53ED8584F9)
可以做成两个小引号一样
![](https://www.hualigs.cn/image/60aa15b384e42.jpg)
当然我只是打一个比方，总之我觉得一个白色的条条看不出来是引用，而且也不好看

**Comment by zkqiang** [comment]
谢谢，v1.9会修改一些外观布局，以上建议会认真考虑的
