### ISSUE TITLE
主题更新新版本后没法显示图片

### ISSUE THREAD

**Issue by arttnba3** [fluid-dev/hexo-theme-fluid#488]
#### 请确认
- [ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
如题，之前用的老版本的fluid没什么问题，后面使用 `npm install --save hexo-theme-fluid` 升级主题版本之后**本地测试正常，推送到GitHub pages上面后，除了头图以外所有的图片都无法加载**，原因不明，希望得到帮助

**Comment by zkqiang** [comment]
查看控制台看是否都图片路径有报错

**Comment by arttnba3** [comment]
在某次推送上github pages后这个问题又莫名其妙消失了...不是很懂什么情况...个人感觉可能是 hexo 没有把更新后的内容完整推送上去导致两个版本的组件存在冲突...

**Comment by zkqiang** [comment]
其实只是因为缓存而已
