### ISSUE TITLE
允许指定深色模式的语法高亮主题

### ISSUE THREAD

**Issue by Potat0000** [fluid-dev/hexo-theme-fluid#489]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题
深色模式下使用其他的代码高亮主题（像utterances评论一样允许定义普通主题和dark mode主题）

主要希望prismjs能实现，highlightjs已经有降低亮度的选项。

谢谢！

#### 请描述您认为可行的解决方案
类似于utterances评论一样

#### 考虑过的替代方案
无

**Comment by Potat0000** [comment]
[这个](https://spectrum.chat/gatsby-js/general/prismjs-syntax-highlighting-with-mode-light-vs-dark-toggle~0ee962a1-501c-4879-960a-242f85387d1c) 可能有用？

**Comment by zkqiang** [comment]
下版本加入

**Comment by Potat0000** [comment]
> 下版本加入

感谢！
