### ISSUE TITLE
首页如何配置分页

### ISSUE THREAD

**Issue by coderlfm** [fluid-dev/hexo-theme-fluid#490]
安装的版本是 `1.8.11`，配置是复制 readme 推荐的配置，里面没有找到 首页配置 文章条数的配置，就是我们通常说的 `page_size`

导致，首页的文章列表显示了全部文章，但其实我想配置成每页10条，没有找到这个配置

**Comment by zkqiang** [comment]
分页是由 Hexo 配置控制，具体见 <https://hexo.io/zh-cn/docs/configuration#分页>
