### ISSUE TITLE
markdown编辑表格并且预览都没有问题，但是发布到博客上就无法渲染出来

### ISSUE THREAD

**Issue by Greenerly** [fluid-dev/hexo-theme-fluid#492]
#### Make sure
- [ ] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] No solution found in [documentations](https://hexo.fluid-dev.com/docs/en/)

#### Describe the question

[](url)

**Comment by Greenerly** [comment]
[](url)
![image](https://user-images.githubusercontent.com/81813388/120882432-82b7fa80-c60a-11eb-82cb-a63474050e84.png)
![ph](https://user-images.githubusercontent.com/81813388/120882457-b004a880-c60a-11eb-9b72-dd44e1bcf1dc.png)

**Comment by zkqiang** [comment]
https://markdown.com.cn/extended-syntax/tables.html

竖线两侧加空格
