### ISSUE TITLE
建议增加DisqusJS评论插件来帮助在网络封锁的环境下查看评论

### ISSUE THREAD

**Issue by 2CW** [fluid-dev/hexo-theme-fluid#496]
#### 如是功能需求，请确定符合以下情况
- [] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [X] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题
DisqusJS被GFW封锁，无法查看已有的评论，也无法直接评论
#### 请描述您认为可行的解决方案

接入DisqusJS，帮助朋友们在中国大陆网络封锁环境下查看DisqusJS，虽然也只有开启特殊服务绕过防火墙才能添加评论，但是能查看已有的也非常Good了

https://github.com/SukkaW/DisqusJS

**Comment by Potat0000** [comment]
该主题已接入，位于[配置文件第663行](https://github.com/fluid-dev/hexo-theme-fluid/blob/master/_config.yml#L663)
