### ISSUE TITLE
希望可以为单篇文章单独设置「版权声明」

### ISSUE THREAD

**Issue by rsreland** [fluid-dev/hexo-theme-fluid#497]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

希望可以为单篇文章单独设置「版权声明」。

例如：整个网站的文章完全开放版权，但某几篇不可用于商业目的。

#### 请描述您认为可行的解决方案

我能想到的有两种方案：

1.在主题的设置文件中，将不同的「版权声明文本」像列表一样存储，每个文本关联一个ID。
   然后，创建文章的时候，可以在Front-matter区域设置要显示的声明的ID。

2.主题设置文件就像现在一样，不改动。
   然后，创建文章时可以在Front-matter区域手动添加「版权声明文本」，如果设置了这个文本，就会覆盖主题设置文件中的「版权声明文本」。

**Comment by zkqiang** [comment]
frontmatter里应该可以手动指定

```yaml
---
copyright: xxxx
---
```

**Comment by rsreland** [comment]
> frontmatter里应该可以手动指定
> 
> ```yaml
> ---
> copyright: xxxx
> ---
> ```

感谢回复，此方法确实可用，谢谢。
