### ISSUE TITLE
桌面端点击搜索导致导航栏发生异常动画

### ISSUE THREAD

**Issue by Potat0000** [fluid-dev/hexo-theme-fluid#499]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述
在桌面端有滚动条的页面点击搜索，搜索框弹出时滚动条消失，进而导致顶部导航栏发生异常动画（左右弹跳）。搜索框关闭时也会出现反方向的异常动画。

#### 复现步骤
该 Bug 复现步骤如下：
1. 在桌面端有滚动条的页面点击搜索
2. 搜索框弹出时观察顶部导航栏
3. 发生异常动画（左右弹跳）
4. 搜索框关闭时也会出现反方向的异常动画

#### 能复现的页面地址
[Fluid's blog](https://hexo.fluid-dev.com/)

**Comment by zkqiang** [comment]
dev 分支已修复
