### ISSUE TITLE
TypeError: Cannot read property 'post_default_img' of undefined

### ISSUE THREAD

**Issue by gunjyo0817** [fluid-dev/hexo-theme-fluid#500]
您好
重新複製[config.yml](https://github.com/fluid-dev/hexo-theme-fluid/blob/master/_config.yml)來配置依舊出現 Cannot read property 'post_default_img' of undefined
請問要如何處理
謝謝

**Comment by zkqiang** [comment]
请检查主题是否为最新版本

如果是最新，可以备份文章，重新安装一次Hexo和主题
