### ISSUE TITLE
如何本地引用 fancybox？

### ISSUE THREAD

**Issue by Potat0000** [fluid-dev/hexo-theme-fluid#502]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

由于我的站点部署在 DCDN 上，故如果将所有 CSS 和 JS 均本地实现会有更好的表现。

操作过程中我发现除了 fancybox 以外的 jsdelivr 引用改为本地都能正常运行，但 fancybox 换为本地后点击查看大图功能会异常。

请问是我忽略了什么吗？谢谢！

PS：顺便一问，请问 hint 为何放在 lib/hint 目录而非 css 目录？

**Comment by zkqiang** [comment]
从描述中没办法判断具体的原因

hint 为何放在 lib/hint 目录而非 css 目录，是因为 lib 目录规划为用于本地存储第三方库代码的，hint 由于当时没找到公共CDN，所以存在本地

**Comment by Potat0000** [comment]
> 从描述中没办法判断具体的原因

具体复现步骤如下（以官方实例站点为例）：

1. 
  ```bash
  git clone https://github.com/fluid-dev/hexo-fluid-blog
  cd hexo-fluid-blog
  git submodule init
  git submodule update --remote
  npm install
  ```
2. 将 [jquery.fancybox.min.css](https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css) 与 [jquery.fancybox.min.js](https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js) 置于 `source/lib/fancybox`
3. 在 `_config.fluid.yml` 中添加：
  ```yaml
  static_prefix:
    fancybox: /lib/fancybox/
  ```
4. `hexo server`
5. 打开任意一篇带图的文章（比如“Hexo Netlify CMS 在线编辑博客”），点击其中一张图片查看大图
6. 发现右上角缺失控制按钮，点击图片外围关闭大图预览后页面来到底端而非原始位置。

以上异常仅限`fancybox`在本地时。其他依赖的CDN库置于本地都可正常运行，`fancybox`使用CDN也可正常运行

**Comment by zkqiang** [comment]
![image](https://user-images.githubusercontent.com/32983588/122667856-b0469b80-d1e7-11eb-9b2b-2488296cc092.png)

按照上述步骤操作了，没有复现出问题

**Comment by Potat0000** [comment]
> 按照上述步骤操作了，没有复现出问题

感谢跟进测试！

我在本地和线上都出现了这个问题。

这是我的博客：https://potat0.cc/posts/20210617/UPX_Manual_Unpack/

![image](https://user-images.githubusercontent.com/11223244/122670515-12f26400-d1f5-11eb-8ad0-d16ed4da2c14.png)

源码在这里：https://github.com/Potat0000/Blog

不过应该和源码关系不大，因为我在本地用实例站点也出现了问题。更换设备/浏览器同样出现问题。

**Comment by zkqiang** [comment]
![image](https://user-images.githubusercontent.com/32983588/122670949-0a029200-d1f7-11eb-8668-d1c0a31198df.png)

对比了一下你本地存储的和原代码有明显出入的，比如上图红圈部分，你可以搜一下`{{ERROR}}`

再去 [jquery.fancybox.min.js](https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js) 搜一下

![image](https://user-images.githubusercontent.com/32983588/122671002-3ae2c700-d1f7-11eb-9c55-d0340c1a4524.png)

**Comment by zkqiang** [comment]
我的错，不是你本地存储的问题，可能是你某个插件把 `{{...}}` 给过滤掉了，我看的是浏览器加载后的结果

**Comment by Potat0000** [comment]
> 可能是你某个插件把 `{{...}}` 给过滤掉了

但是 https://github.com/fluid-dev/hexo-fluid-blog 也会出这个问题

**Comment by Potat0000** [comment]
问题找到了。[是Hexo的锅](https://hexo.io/zh-cn/docs/troubleshooting#%E6%B3%84%E9%9C%B2%EF%BC%88Escape%EF%BC%89%E5%86%85%E5%AE%B9)。Hexo本身会自动把`{{ }}`包裹的吃掉。

将js用`{% raw %}`和`{% endraw %}`包裹即可。

再次感谢！
