### ISSUE TITLE
_config.fluid.yml 不生效

### ISSUE THREAD

**Issue by superganplus** [fluid-dev/hexo-theme-fluid#503]
#### 问题描述
根据文档，通过 npm 方式 安装 fluid 主题
方式一：

Hexo 5.0.0 版本以上，推荐通过 npm 直接安装，进入博客目录执行命令：

npm install --save hexo-theme-fluid
然后在博客目录下创建 _config.fluid.yml，将主题的 _config.yml 内容复制进去。

结果：
不论我在博客根目录创建 _config,fluid.yml，还是 _data/fluid_config，还是 _data/_config.fluid.yml
配置 都不会生效，依然是以 hexo的 _config.yml 配置生效

**Comment by zkqiang** [comment]
`_config.fluid.yml` or `_data/fluid_config.yml`
注意文件名与后缀

**Comment by superganplus** [comment]
嗯嗯，实际文件名确实是 _config.fluid.yml 和 fluid_config.yml
_config.fluid.yml 在项目根目录下 / ，
fluid_config.yml  在 /_data/下

我反复重建很多次项目了，主题配置一直不生效
hexo 5.4.0
fluid 1.8.11

**Comment by zkqiang** [comment]
麻烦把整个目录打包上传，或者推到GitHub上吧

**Comment by superganplus** [comment]
[my-blog.zip](https://github.com/fluid-dev/hexo-theme-fluid/files/6690770/my-blog.zip)

**Comment by superganplus** [comment]
> 麻烦把整个目录打包上传，或者推到GitHub上吧

已上传，请看这里哦
[my-blog.zip](https://github.com/fluid-dev/hexo-theme-fluid/files/6690774/my-blog.zip)

**Comment by zkqiang** [comment]
`_config.fluid.yml` or `_data/fluid_config.yml` 两个配置是等效的，所以内容也是一样的，都是主题配置

你的 `_config.fluid.yml` 内容不对

然后 `_data/fluid_config.yml` 是对的，也是生效的

请再仔细阅读下文档

**Comment by superganplus** [comment]
明白了，我不应该是把 _config.fluid.yml 当成了博客配置的覆盖文件，而是fluid主题的配置文件。谢谢
