### ISSUE TITLE
增加日历云支持

### ISSUE THREAD

**Issue by owenyk** [fluid-dev/hexo-theme-fluid#504]
#### 如是功能需求，请确定符合以下情况
- [ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [ ] 难以通过第三方插件实现
https://github.com/icecory/theme-next-calendar日历云不知道怎么能添加到主题之下？

**Comment by zkqiang** [comment]
> 提取自Landscape-F主题, 修改后适配theme-next

这是一个适配 next 主题的插件
