### ISSUE TITLE
代码块增加自动换行的功能

### ISSUE THREAD

**Issue by Gwzlchn** [fluid-dev/hexo-theme-fluid#505]
#### 如是功能需求，请确定符合以下情况
- [ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [ ] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

![image](https://user-images.githubusercontent.com/23080717/122944207-33175400-d3aa-11eb-8ee9-35a79491ea58.png)
插入一行过长的代码片段时，需要拖动横向混动条来看到完整的一行代码，不够直观，是否可以增加自动换行的功能（line wrap）

#### 请描述您认为可行的解决方案

（尚不清楚）
#### 考虑过的替代方案

（无）

**Comment by zkqiang** [comment]
代码当然不能有换行，python代码换行后还能运行吗...
