### ISSUE TITLE
字数统计 Bug

### ISSUE THREAD

**Issue by ouuqqo** [fluid-dev/hexo-theme-fluid#506]
在我的一篇上千字的文章中字数统计仅为 67 字：https://ouuqqo.github.io/2021/06/19/shi-neng-fen-xi/

这是我安装的插件：

```
+-- hexo-blog-encrypt@3.1.6
+-- hexo-deployer-git@3.0.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-baidu-sitemap@0.1.9
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-sitemap@2.1.0
+-- hexo-generator-tag@1.0.0
+-- hexo-math@4.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-kramed@0.1.4
+-- hexo-renderer-stylus@2.0.1
+-- hexo-server@2.0.0
+-- hexo-theme-landscape@0.0.3
+-- hexo-wordcount@6.0.1
`-- hexo@5.4.0
```

无论安不安装 hexo-wordcount 插件该 Bug 均生效，新建一篇 post 将内容粘贴进去字数统计仍显示 67 字。

**Comment by zkqiang** [comment]
请把你博客目录打包下上传了吧，仅凭这些没法判断

**Comment by ouuqqo** [comment]
已上传 https://github.com/ouuqqo/ouuqqo.github.io/releases/tag/0.1

**Comment by ouuqqo** [comment]
> 请把你博客目录打包下上传了吧，仅凭这些没法判断

已上传：https://github.com/ouuqqo/ouuqqo.github.io/releases/tag/0.1

**Comment by ouuqqo** [comment]
> 请把你博客目录打包下上传了吧，仅凭这些没法判断

我将所有独占一行的大公式删除后字数统计恢复了正常：https://ouuqqo.github.io/2021/06/28/new/，目测就是大公式的括号匹配出了问题。

**Comment by ouuqqo** [comment]
我将所有独占一行的大公式删除后字数统计恢复了正常：https://ouuqqo.github.io/2021/06/28/new/

目测就是大公式的括号匹配出了问题。

**Comment by zkqiang** [comment]
最新版本应该没这个问题了
