### ISSUE TITLE
关于页配置已经是true了，也设置了相关字段，但是about页面没有展示

### ISSUE THREAD

**Issue by fangge** [fluid-dev/hexo-theme-fluid#509]
![image](https://user-images.githubusercontent.com/1671513/123739447-41e59580-d8d9-11eb-9cc7-d3b1a9e23dca.png)
RT，已经是true了，但是about页展示出来的还是空的
![image](https://user-images.githubusercontent.com/1671513/123739530-5d50a080-d8d9-11eb-8a40-d31eceebc7a4.png)

**Comment by fangge** [comment]
也已经新建好about页了
![image](https://user-images.githubusercontent.com/1671513/123739579-72c5ca80-d8d9-11eb-808c-8bab925f8e60.png)

**Comment by womine** [comment]
同问, 我也遇到这个问题了
