### ISSUE TITLE
首页的banner图片怎么设置，文档没找到，只找到文章的banner

### ISSUE THREAD

**Issue by liulingfeng** [fluid-dev/hexo-theme-fluid#511]
#### 请确认
- [ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/e599c33b72a697a8318e3d07e42b6ee6572fc344/_config.yml#L412-L415
