### ISSUE TITLE
头图手机端无法全屏

### ISSUE THREAD

**Issue by zsbai** [fluid-dev/hexo-theme-fluid#513]
#### 请确认
- [ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

<img width="475" alt="截屏2021-07-07 下午9 51 56" src="https://user-images.githubusercontent.com/62942942/124771243-8de5a980-df6d-11eb-9b3d-fa7682b975e8.png">
设置为100，电脑端正常显示，手机端仍会占用百分之五十左右的空间，手机端为xr，我拉动浏览器的分辨率的时候文章栏也会向上移动

**Comment by zkqiang** [comment]
全屏后图片会被裁剪，按需自己设置

https://github.com/fluid-dev/hexo-theme-fluid/blob/e599c33b72a697a8318e3d07e42b6ee6572fc344/_config.yml#L342-L344

**Comment by zsbai** [comment]
奥，不好意思我使用还是旧版配置文件，没找到这个选项

**Comment by zsbai** [comment]
> 全屏后图片会被裁剪，按需自己设置
> 
> https://github.com/fluid-dev/hexo-theme-fluid/blob/e599c33b72a697a8318e3d07e42b6ee6572fc344/_config.yml#L342-L344

不论改为0还是1.0仍然会出现这样的情况

**Comment by zsbai** [comment]
<img width="536" alt="截屏2021-07-07 下午10 08 32" src="https://user-images.githubusercontent.com/62942942/124773820-e0c06080-df6f-11eb-8c1d-1517402a18bc.png">
配置文件如下
