### ISSUE TITLE
leancloud统计pv，能否选择把网址的全文当作target

### ISSUE THREAD

**Issue by AnRFDev** [fluid-dev/hexo-theme-fluid#514]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题
- leancloud目前将所有localhost访问放行。本地测试时会增加pv，uv。
- 部署到测试站（测试网址）的时候，访问测试站 pv，uv也会增加。

测试数据和正式数据混在一起了。

#### 请描述您认为可行的解决方案
yml增加一个配置，允许统计时将整个页面url作为target。默认是关闭(`false`)。

目前是以文章路径为`target`，例如`/2019/02/26/Database/MySQL-install_and_config_Mac/`，
能否允许改成`rustfisher.com/2019/02/26/Database/MySQL-install_and_config_Mac/`

- 正式站 `target`: `rustfisher.com/2019/02/26/Database/MySQL-install_and_config_Mac/`
- 测试站 `target`: `test.rustfisher.com/2019/02/26/Database/MySQL-install_and_config_Mac/`

#### 考虑过的替代方案
暂无

**Comment by zkqiang** [comment]
修改成和评论类似，可以指定获取路径的属性
