### ISSUE TITLE
缺少twikoo评论插件教程

### ISSUE THREAD

**Issue by Winliam** [fluid-dev/hexo-theme-fluid#515]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

fluid的配置指南中关于评论插件，说：使用方式和参数设置请点击上面链接查看各自的文档；

但是twikoo的链接，给出的答案是：
>在 hexo-theme-fluid主题使用
>请参考 配置指南-评论 进行配置

死循环了啊。。。

**Comment by zkqiang** [comment]
每个评论插件就那几个配置项，根据文档搞清楚应该填什么就行了

**Comment by Winliam** [comment]
> 每个评论插件就那几个配置项，根据文档搞清楚应该填什么就行了

大佬，真心求教，配置文件中看到的确是只有三个配置项（其中两个你也都已经填好了）
>envId: 
>region: ap-shanghai
>path: window.location.pathname

但是，还想问：
1. 这个envid只需要填上自己腾讯云开发环境的ID就可以了吗？
2. 还需要创建云函数这些吗？
3. 创建了云函数之后，本地部署的确看到了的插件，但是插件的设置页面显示：“前端版本1.3.1与云函数版本1.4.0不一致”，然后部署到云端后就不显示插件了。如果是云函数版本低倒是可以按照twikoo的教程进行更新，但是现在是前端版本低，推测是否应该从fluid这头入手，修改什么东西？

大佬，真心请求指导！！感谢！！！

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/e599c33b72a697a8318e3d07e42b6ee6572fc344/_config.yml#L985

这里可以修改版本

**Comment by RookieTerry** [comment]
同问，我twikoo的云函数部署在netlify上，请问region这一项应该怎么填写？
