### ISSUE TITLE
副标题显示

### ISSUE THREAD

**Issue by Ricardo-M-Sakura** [fluid-dev/hexo-theme-fluid#516]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

**Comment by Ricardo-M-Sakura** [comment]
我之前设置副标题的时候修改theme下的配置文件来修改副标题是行不通的，修改source下的配置文件才能生效。。另外我想请问首页背景的配置问题，我把图片的绝对路径放在banner_img的后面，重新部署之后仍然无法生效.
以上。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月12日(星期一) 晚上9:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fluid-dev/hexo-theme-fluid] 副标题显示 (#516)





 
请完整描述你的问题

**Comment by zkqiang** [comment]
source下的配置文件属于覆盖配置，优先级比theme下的要高，建议只设置source下的（这些文档有详细说明）

设置不生效也有可能是上面这个原因，再仔细确认一下，实在不行用 `hexo s --debug` 会打印出最终生效的配置，看里面有没有你设置的内容
