### ISSUE TITLE
请问百度 Google可以搜索到博客怎么实现

### ISSUE THREAD

**Issue by liulingfeng** [fluid-dev/hexo-theme-fluid#517]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

**Comment by Potat0000** [comment]
可以尝试使用 [sitemap](https://github.com/hexojs/hexo-generator-sitemap) 或主动向搜索引擎提交

**Comment by liulingfeng** [comment]
试了下貌似没用，可以具体点吗

**Comment by zkqiang** [comment]
提交不会很快被收录，建议了解一下各搜索引擎收录的说明和规则

**Comment by liulingfeng** [comment]
好的，谢谢
