### ISSUE TITLE
封面banner翻转

### ISSUE THREAD

**Issue by RoyRao2333** [fluid-dev/hexo-theme-fluid#518]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

在设置好页面banner后，hexo clean并编译，用Safari（macOS和iOS）打开博客，banner就是正常的，但是当我用Edge打开，banner就会顺时针旋转90°。MacBookPro和iMac都测试了，结果相同。

#### 复现步骤
该 Bug 复现步骤如上。

#### 截图
Safari
<img width="1318" alt="Safari" src="https://user-images.githubusercontent.com/31413093/126420610-bf84d954-fac3-415e-8044-ccd789fdc3ac.png">

Edge
<img width="1669" alt="Edge" src="https://user-images.githubusercontent.com/31413093/126420614-204e30dd-50ce-4164-894a-f4bf22db2f35.png">

**Comment by zkqiang** [comment]
非常有意思的问题，这是因为原图 EXIF 里包含了翻转信息

![image](https://user-images.githubusercontent.com/32983588/126424921-a736738b-5bf1-4d71-837c-51647054be4c.png)

而 Chrome 没有读取这个信息，也就没有对原图进行翻转，其他浏览器都读取了（也就是说，原图本身就是翻转的，信息里指定了需要再顺时针翻转270度）

解决办法也很简单，先自己编辑图片翻转270度，然后用一些工具去除 EXIF 信息即可，例如 https://tinypng.com/

参考资料：
https://stackoverflow.com/questions/16473202/why-chrome-rotate-a-image-and-firefox-not
https://stackoverflow.com/questions/42401203/chrome-image-exif-orientation-issue
https://stackoverflow.com/questions/42401203/chrome-image-exif-orientation-issue

**Comment by RoyRao2333** [comment]
> 非常有意思的问题，这是因为原图 EXIF 里包含了翻转信息
> 
> ![image](https://user-images.githubusercontent.com/32983588/126424921-a736738b-5bf1-4d71-837c-51647054be4c.png)
> 
> 而 Chrome 没有读取这个信息，也就没有对原图进行翻转，其他浏览器都读取了并翻转。也就是说，原图本身就是 Chrome 看到的样子，信息里指定了需要再顺时针翻转270度，如果浏览器照做了，才是我们看上去正常的样子（至于为什么不直接翻转原图，可能是图片来源者用了一些奇怪的工具导致）。
> 
> 解决办法也很简单，先自己编辑图片翻转270度，然后用一些工具去除 EXIF 信息即可，例如图片压缩工具 https://tinypng.com/
> 
> 参考资料：
> https://stackoverflow.com/questions/16473202/why-chrome-rotate-a-image-and-firefox-not
> https://stackoverflow.com/questions/42401203/chrome-image-exif-orientation-issue
> https://www.computing.dcu.ie/~humphrys/chrome.bug.html

一语中的！确实之前我刚下载这张图片的时候，它是顺时针翻转90°的（竖着），然后我使用macOS自带的Preview翻转到正常样子（横着），然后再应用到博客上去的，结果没想到会这样🤣感谢你的回答！
