### ISSUE TITLE
文档图片边框阴影问题

### ISSUE THREAD

**Issue by laobanjiu9527** [fluid-dev/hexo-theme-fluid#523]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

请问怎么把上传的文章里图片四周的阴影给去掉，让图片融入背景，就像最下面那张图一样。前端小白刚开始搭建博客，不会的地方也没人问，只好斗胆来这儿请教大神了...

网页端有边框阴影
![01](https://user-images.githubusercontent.com/72090271/126965092-a7917ab2-ce54-40cf-8c72-0ada6ef5b397.png)

本地typora无边框阴影
![02](https://user-images.githubusercontent.com/72090271/126965118-c25a979e-9b21-4608-9d90-ea8e05f1bfe7.png)

**Comment by hyoban** [comment]
这个是可以配置的吗？在哪
