### ISSUE TITLE
部署至github pages与gitee pages时博客加载不全

### ISSUE THREAD

**Issue by leaf2006** [fluid-dev/hexo-theme-fluid#527]
#### 问题描述

在部署至github pages与gitee pages时，出现了博客加载十分不全的情况：

![image](https://user-images.githubusercontent.com/51502183/127666730-fd52bba4-978a-4f7e-90f8-d09ab5bd207e.png)

希望有人能够帮助，谢谢

**Comment by leaf2006** [comment]
我等了好久这个博客依然是这样，希望有人能帮助我，谢谢

**Comment by zkqiang** [comment]
浏览器console看看就知道了，资源文件都报错了，路径配的不对

**Comment by leaf2006** [comment]
> 浏览器console看看就知道了，资源文件都报错了，路径配的不对
> 
> 把路径里的 `/blog` 删掉试试

问题已经解决，十分感谢💖
