### ISSUE TITLE
twikoo评论功能配置

### ISSUE THREAD

**Issue by DongHaoS** [fluid-dev/hexo-theme-fluid#529]
#### twikoo配置首字母一定要大写
- [ ] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] No solution found in [documentations](https://hexo.fluid-dev.com/docs/en/)

#### 问题
配置成大写后，评论功能报错，envId中配置的地址，在发出post的url中 还会带上http,我不知道这个是我配置问题还是个程序bug?

**Comment by zkqiang** [comment]
没明白什么意思，能提供一个demo吗
