### ISSUE TITLE
除主页外，banner头图都不显示

### ISSUE THREAD

**Issue by bingheng-wlm** [fluid-dev/hexo-theme-fluid#533]
全部指定为了https://pic.imgdb.cn/item/610777c85132923bf8c3c257.png
但只有主页可以显示
部署在了 bhwlm.top

**Comment by zkqiang** [comment]
明明都有啊

只是每个遮罩透明度设置不一样而已

https://github.com/fluid-dev/hexo-theme-fluid/blob/be2c78410d7daef3f6ac1685f8d8b735a332a79c/_config.yml#L422-L425
