### ISSUE TITLE
在一个页面内单独插入js和css

### ISSUE THREAD

**Issue by DogeLasVegas** [fluid-dev/hexo-theme-fluid#534]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

我想只在自定义页面内插入指定的js和css文件，其他页面不插入，使用主题配置文件中的custom_js和custom_css似乎是在所有页面中都插入文件，请问还有什么办法可以只在某个页面内单独引入指定文件吗

**Comment by zkqiang** [comment]
直接在 md 文件里写 `<script>` `<link>` 就行了

**Comment by DogeLasVegas** [comment]
直接写也不好用，我引入js文件之后又在后面写script标签进行初始化，但是浏览器控制台报错，提示我初始化的东西undefined，而且我在页面里也没找到我引入的文件

**Comment by zkqiang** [comment]
那是你写的有问题...   `custom_js` 实际和直接写是一回事

**Comment by DogeLasVegas** [comment]
![Uploading IMG_20210803_115924.jpg…]()
麻烦能帮我看看哪写的不对吗。。昨晚上试了一晚上没改出来😥

**Comment by zkqiang** [comment]
你直接部署上去发链接就行

**Comment by DogeLasVegas** [comment]
https://dogelasvegas.github.io/collect/other
密码是123456

**Comment by zkqiang** [comment]
哦，用加密报错正常。。

**Comment by DogeLasVegas** [comment]
有解决办法吗，是因为用了加密所以才没有加载文件，还是写法有问题导致加载失败

**Comment by zkqiang** [comment]
加密插件本身影响了正常加载

插件文档里也已经说明了这个问题：https://github.com/D0n9X1n/hexo-blog-encrypt#about-callback

**Comment by DogeLasVegas** [comment]
就是说只能用回调但是不能直接加载文件了，完蛋
