### ISSUE TITLE
建议增加 mathjax 3.2.0 自带的懒加载功能

### ISSUE THREAD

**Issue by hooyuser** [fluid-dev/hexo-theme-fluid#537]
目前，图片支持懒加载，但 mathjax 数学公式则不支持懒加载。

因为在 mathjax 3.2.0 中开启懒加载非常方便，只需要在 `math.ejs` 文件中为 mathjax 配置 `MathJax = { }` 增加一项 `loader: {load: ['ui/lazy']}`，因此可否考虑加入这一功能？

比如说，在开启图片懒加载的情况，默认也开启 mathjax 的懒加载。或者说，允许 mathjax 独立开启懒加载这一功能。

**Comment by zkqiang** [comment]
已增加
