### ISSUE TITLE
有大佬会完整的往Fluid主题里添加豆瓣页吗

### ISSUE THREAD

**Issue by MerickBao** [fluid-dev/hexo-theme-fluid#539]
目前自己按照网上的教程添加了豆瓣页，但是效果不是太好。比如，无法像butterfly主题那样自定义电影页图片。搜了好久也没有关于fluid添加豆瓣页的教程，希望大佬指点指点。

**Comment by zkqiang** [comment]
https://www.0x7b.cn/books/

**Comment by MerickBao** [comment]
> https://www.0x7b.cn/books/
> 
> https://blog.shiyicode.com/books/
> 
> 我没使用过，但是看别人有成功的，应该没问题

我也是没问题，正常显示豆瓣页。但是就是豆瓣页的banner图片不知道咋自定义，现在是默认的和首页一样的图片。就是想换一换。

**Comment by jerryoung** [comment]
https://hexo.fluid-dev.com/docs/guide/#配置

看看这个能不能帮到您哈。
