### ISSUE TITLE
同时支持多种评论系统

### ISSUE THREAD

**Issue by gcnyin** [fluid-dev/hexo-theme-fluid#540]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

我想同时使用disqus和utterances

#### 请描述您认为可行的解决方案

同时支持多种

#### 考虑过的替代方案

暂无

**Comment by Potat0000** [comment]
与 #469 类似？
