### ISSUE TITLE
首页标题调用api失败

### ISSUE THREAD

**Issue by Unlasting-Q** [fluid-dev/hexo-theme-fluid#548]
#### 问题描述
按照提示开启调用api的功能，输入了调用api所需的相关参数，网页标题未显示。
之后又测试api结果如图1：
<img src="https://i.loli.net/2021/08/13/zupWQXSM5ifGI1o.png" style="zoom:80%" />
有关代码如图2：
<img src="https://i.loli.net/2021/08/13/JQYVBoTW5avDKnC.png" style="zoom:80%" />

**Comment by zkqiang** [comment]
`keys: ['content']`

**Comment by Unlasting-Q** [comment]
![EWYK$)4YNBBL4~XVXE14LR9.png](https://i.loli.net/2021/08/13/QwhEqFbatDBrJ79.png)
大佬请问page.subtitle !== false这一句是啥意思
