### ISSUE TITLE
这条latex公式没有渲染

### ISSUE THREAD

**Issue by 1357310795** [fluid-dev/hexo-theme-fluid#554]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [ ] 已经排除是其他 Hexo 插件影响

#### Bug 描述
1. $ \frac{1}{n(n+k)}=\frac{1}{k}\left(\frac{1}{n}-\frac{1}{n+k}\right) $
2. $ \frac{1}{n(n+1)(n+2)}=\frac{1}{2}\left(\frac{1}{n(n+1)}-\frac{1}{(n+1)(n+2)}\right) $
3. $ \frac{1}{(2n-1)(2n+1)}=\frac{1}{2}\left(\frac{1}{2n-1}-\frac{1}{2n+1}\right) $
4. $ \frac{1}{\sqrt{n}+\sqrt{n+k}}=\frac{1}{k}\left(\sqrt{n+k}-\sqrt{n}\right) $
5. $ \sum^{n}_{i=1}\left(2i-1\right)=n^2 $
6. $ \sum^{n}_{i=1} i^3=\left[\frac{n(n+1)}{2}\right]^2=\left(\sum^{n}_{i=1} i\right)^2 $

第六条公式无法渲染
而在typora和[latexlive](http://latexlive.com)中正常

![QQ截图20210816121715](https://user-images.githubusercontent.com/35869804/129510823-cf2b5a2f-fd49-48d8-87a1-e1672d5d4a9b.png)

#### 关于插件
已按教程选择了mathjax引擎，安装了hexo-renderer-kramed渲染器

#### 复现步骤
部署后能复现的页面地址：[我的博客](https://1357310795.github.io/2021/08/15/%E9%AB%98%E4%B8%AD%E6%95%B0%E5%AD%A6%E7%AC%94%E8%AE%B0%EF%BC%88%E5%B0%8F%E6%8A%84%EF%BC%89/#%E5%B8%B8%E8%A7%81%E8%A3%82%E9%A1%B9)

**Comment by zkqiang** [comment]
主题本身不处理渲染，请考虑是 hexo-renderer-kramed 的问题
