### ISSUE TITLE
深色模式tag插件样式适配

### ISSUE THREAD

**Issue by eoinli** [fluid-dev/hexo-theme-fluid#558]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题
深色模式下，tag插件依然保持亮色，会影响观感体验
![image](https://user-images.githubusercontent.com/88650074/129831970-ee0d7b90-b868-48ca-a404-d4aa6bf1387f.png)

#### 请描述您认为可行的解决方案
如果可以的话，希望能添加深色模式下，tag插件能自动切换成深色的样式，如下仅供参考
![image](https://user-images.githubusercontent.com/88650074/129832057-d4d2f829-adc3-47a1-8bfe-d6e4ea7c48a7.png)

**Comment by zkqiang** [comment]
可以发个 PR
