### ISSUE TITLE
支持 Twitter Card

### ISSUE THREAD

**Issue by TennyZhuang** [fluid-dev/hexo-theme-fluid#560]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

目前网站文章分享到 Twitter/Facebook 等网站时无法自动站开成 card。

#### 请描述您认为可行的解决方案

根据这篇文章的介绍，需要在合适的地方调用  `open_graph`，这个似乎并不容易自定义解决。

https://zhuanlan.zhihu.com/p/378696561

**Comment by Potat0000** [comment]
#550

**Comment by TennyZhuang** [comment]
Close due to duplication
