### ISSUE TITLE
请问valine评论系统的头像怎么改呀？我发现gravatar已经打不开了，请问还有什么别的解决方法吗？

### ISSUE THREAD

**Issue by Remoonecho** [fluid-dev/hexo-theme-fluid#561]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

**Comment by zkqiang** [comment]
请参考valine的文档
