### ISSUE TITLE
latex公式 不能显示多行

### ISSUE THREAD

**Issue by Sepush** [fluid-dev/hexo-theme-fluid#563]
latex的公式换行无法正常显示
按照文档进行了配置 并已经移除多余渲染引擎
https://hexo.fluid-dev.com/docs/en/guide/#math

期待
![image](https://user-images.githubusercontent.com/39197136/130877982-daea723b-0194-47a7-aaad-83ec409d9fd0.png)

实际上
![image](https://user-images.githubusercontent.com/39197136/130877943-c7dfc8f7-70a8-4199-a3fc-f87f23d7f300.png)

**Comment by zkqiang** [comment]
源文本发一下？ 用的什么引擎

**Comment by Sepush** [comment]
引擎：mathjax: npm install hexo-renderer-kramed --save
![image](https://user-images.githubusercontent.com/39197136/131218104-eb556104-1630-4b1a-9704-bad7af2726b4.png)
原文：
---
mathjax: true
---
$$
f:X \rightarrow Y 表示从 X 映射到 Y 的函数 f \\
X \rightarrow Y 表示从 X 到 Y 的所有函数 \\
$$

**Comment by zkqiang** [comment]
https://github.com/mathjax/MathJax/issues/2312
>Linebreaks are not yet implemented in version 3. This is one of the significant features from version 2 that has not yet been ported to version 3.

里面有一些临时的解决方案
