### ISSUE TITLE
根目录_config.yml加了root: /blog/ 后，搜索功能使用不了

### ISSUE THREAD

**Issue by E-10000** [fluid-dev/hexo-theme-fluid#565]
#### 请确认
- [ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

**Comment by zkqiang** [comment]
thx, fixed
