### ISSUE TITLE
markdown斜体语法与内联公式冲突

### ISSUE THREAD

**Issue by ZoroGH** [fluid-dev/hexo-theme-fluid#566]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

我写了2个内联的数学公式,在一行内,本地typora显示的是公式,但是hexo server后显示的却是斜体.
即markdown双下划线斜体的语法和这个latex冲突了.求助
![P}L{8(N }YQJAWSB F)MX82](https://user-images.githubusercontent.com/67215466/131353473-a8a7b37d-f130-4f0c-8850-fac3d79a4ce2.png)
![84(TN01@UL9A1TNT61UXU8E](https://user-images.githubusercontent.com/67215466/131353500-d1ffdf35-69dd-4e67-8b22-f8d9cc087503.png)

**Comment by zkqiang** [comment]
使用的什么引擎？

这一段 latex 复制给我

**Comment by ZoroGH** [comment]
> 使用的什么引擎？
> 
> 这一段 latex 复制给我


post:
  math:
    enable: true
    special: true
    engine: mathjax

引擎用的mathjax


latex
$\Omega$中若干元素的几集合称为$\mathcal{F}$,满足如下性质

-   事件$A\in F$则$\bar A \in \mathcal{F}$ , $\bar A = \Omega - A$
-   $\Omega\in \mathcal{F}$
-   若$A_i\in\mathcal{F},i=1,2\cdots n$,则$\bigcup_{i=0}^n A_i\in\mathcal{F}$

$\mathcal{F}$规定在$\Omega$中讨论有意义

**Comment by zkqiang** [comment]
原因是 `hexo-renderer-kramed` 插件的问题，请根据最新文档更换渲染插件：
1. `npm uninstall hexo-renderer-kramed --save`
2. `npm install hexo-renderer-pandoc --save`
3. 还需安装 [pandoc](https://github.com/jgm/pandoc/blob/master/INSTALL.md)
