### ISSUE TITLE
部署到Github不能显示图片,已经绑定域名

### ISSUE THREAD

**Issue by Beoo-666** [fluid-dev/hexo-theme-fluid#568]
![image](https://user-images.githubusercontent.com/55978588/131427566-63ec8134-9646-4b31-9841-9694fa2099a8.png)

**Comment by Potat0000** [comment]
麻烦提供相关链接。[该域名](http://mcxx.cc/)目前404，[仓库](https://github.com/Beoo-666/Beoo-666.github.io)为空

**Comment by Beoo-666** [comment]
我准备重新部署一下

**Comment by Beoo-666** [comment]
不知道为啥部署不上去了
![image](https://user-images.githubusercontent.com/55978588/131429780-99c3468c-80d0-4b84-885f-7f833d8d48f9.png)

**Comment by Potat0000** [comment]
可以尝试 `generate` 以后手工将 `public` 目录推到仓库

**Comment by Beoo-666** [comment]
部署上去了,还是不显示图片.    mcxx.cc

**Comment by Potat0000** [comment]
`_config.yml` 中是否设置有 `root: /Beoo-666/`？如有请移除

**Comment by Beoo-666** [comment]
没有root开头的, 有这个
![image](https://user-images.githubusercontent.com/55978588/131430440-74c24003-dcd4-482a-b7f8-adf4a9a43040.png)

**Comment by Potat0000** [comment]
改为 `url: https://mcxx.cc/`

**Comment by Beoo-666** [comment]
好像还是不行

**Comment by Beoo-666** [comment]
可以了

**Comment by Potat0000** [comment]
问题解决后请及时 close issue。

BTW，可以将 CNAME 文件放置在 `source` 目录中，每次会自动生成在 `public` 目录里。

**Comment by Beoo-666** [comment]
CNAME ?

**Comment by Beoo-666** [comment]
好的, 知道了

**Comment by Beoo-666** [comment]
BTW 是啥

**Comment by Potat0000** [comment]
> BTW 是啥

By the way

**Comment by Beoo-666** [comment]
好的, 感谢.
