### ISSUE TITLE
Type.js打字效果可以通过 \n 换行

### ISSUE THREAD

**Issue by guotg5** [fluid-dev/hexo-theme-fluid#569]
在style中增加 white-space: pre-wrap; 即可
<span style="white-space: pre-wrap;" class="h2" id="subtitle" title="<%- subtitle %>">

**Comment by Carlmaxace** [comment]
附议

**Comment by Carlmaxace** [comment]
> 在style中增加 white-space: pre-wrap; 即可

可以用<br/>换行，另外为了打字机不占位，句末再加一个<br/>

**Comment by zkqiang** [comment]
自行通过自定义CSS添加即可
或者使用 `<br>` 换行
