### ISSUE TITLE
如何使用自定义JS捕获夜间模式切换事件/获取当前是否开启夜间模式？

### ISSUE THREAD

**Issue by dajia-1701** [fluid-dev/hexo-theme-fluid#570]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

**Comment by zkqiang** [comment]
获取当前模式 light / dark
```
document.documentElement.getAttribute('data-user-color-scheme')
```

**Comment by dajia-1701** [comment]
谢谢
