### ISSUE TITLE
手机端展开 nav bar 后不能收回和展开二级分类

### ISSUE THREAD

**Issue by Trotyl15** [fluid-dev/hexo-theme-fluid#580]
展开 nav bar 后不能收回和展开二级分类
不知道是我自己的问题还是什么

![4kpjb-o0y12](https://user-images.githubusercontent.com/55414757/133869599-3535344d-3509-4be6-a1b4-38ef1e92638e.gif)

演示网址：[blog.trotyl.xyz](https://blog.trotyl.xyz)

**Comment by Trotyl15** [comment]
好吧现在发现不光手机端，网页端如果放到很窄的话也不行了

**Comment by zkqiang** [comment]
https://hexo.fluid-dev.com/

**Comment by Trotyl15** [comment]
> 目测是某个插件冲突，或者你修改源码导致的
> 
> 可以在这里试下原版的 https://hexo.fluid-dev.com/

**Comment by Trotyl15** [comment]
谢谢，我改天把几个插件啥的关了试试
