### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by TungstenVn** [fluid-dev/hexo-theme-fluid#581]
#### Make sure
- [x] No solution found in [documentations](https://hexo.fluid-dev.com/docs/en/)
- [x] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases)

#### Describe the question

Hello, i just know about this, and i wonder if there is any chat group i can join. QQ, wechat or any else. thanks a lot

**Comment by zkqiang** [comment]
Wechat group

![](https://cdn.jsdelivr.net/gh/fluid-dev/static@master/hexo-theme-fluid/wechat.png)

**Comment by TungstenVn** [comment]
can you help me verify my registration 
![image](https://user-images.githubusercontent.com/40385888/134760602-0aa49d73-8331-4462-8bcd-5b60e537b451.png)

**Comment by zkqiang** [comment]
Sorry, this QR code has expired

**Comment by TungstenVn** [comment]
can you try this for me 
![image](https://user-images.githubusercontent.com/40385888/134792205-5cf07078-1704-4841-b66b-69f643933418.png)

**Comment by zkqiang** [comment]
Wechat tell me:
> Your account is not qualified for auxiliary verification. Please ask the other person to contact other friends to complete auxiliary verification

**Comment by TungstenVn** [comment]
can you help me scan a qr code again, this one should not be expired 
![image](https://user-images.githubusercontent.com/40385888/134792332-19302d92-b81f-4db6-89dc-fe1dc39991c5.png)

**Comment by zkqiang** [comment]
I was notified that it is still expired
