### ISSUE TITLE
根目录下source内的图片资源会被主题目录下source内的同名资源覆盖

### ISSUE THREAD

**Issue by SkeathyTomas** [fluid-dev/hexo-theme-fluid#584]
根目录下source内的图片资源会被主题目录下source内的同名资源覆盖。

如：在根目录下source文件夹内创建 /img/avatar.png，设置浏览器标签图标 favicon: /img/avatar.png后使用了主题自带的avatar.png

考虑到当前hexo主题逻辑，未方便资源配置和切换主题，应该是根目录下资源覆盖掉主题中的资源。

**Comment by zkqiang** [comment]
这个覆盖逻辑是 Hexo 本身的，主题无法控制
