### ISSUE TITLE
使用hexo写的原创文章怎么防止被爬虫爬取呢，爬虫直接copy，还不留文章来源那种，有点恶心

### ISSUE THREAD

**Issue by java-aodeng** [fluid-dev/hexo-theme-fluid#587]
#### 如是功能需求，请确定符合以下情况
- [ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [ ] 难以通过第三方插件实现

**Comment by zkqiang** [comment]
可以添加 [robots.txt](https://www.robotstxt.org/robotstxt.html) 到 source 目录，但是实际上大部分爬虫也不会遵守 robots 协议规则，所以除了维权没有什么好办法
