### ISSUE TITLE
代码块内代码和行号不对齐，错位，

### ISSUE THREAD

**Issue by fishUPs** [fluid-dev/hexo-theme-fluid#588]
长代码尤其明显，图片分别是官方博客，我的博客，另一位也这个主题的人的博客，内容都是一样的，但是官方的和我的都出现了行号错位，那位的一切正常
![](https://i.loli.net/2021/09/29/jI4uEV5ChARzokN.png)
![](https://i.loli.net/2021/09/29/pcGTOSXgdYBAtQe.png)
![](https://i.loli.net/2021/09/29/cLi7yotuAQkGwhP.png)

**Comment by zkqiang** [comment]
把这段内容复制出来让我试试

**Comment by fishUPs** [comment]
> 把这段内容复制出来让我试试

这是那位显示正常的也是这个主题的人的网址https://www.myql.xyz/post/e00ab0f6/
这是官网那篇文章的网址https://hexo.fluid-dev.com/posts/hexo-netlify/
2篇文章是一样的，错位地点是折叠代码的位置

**Comment by zkqiang** [comment]
![image](https://user-images.githubusercontent.com/32983588/135296637-3636ba41-f464-4936-ad86-fc8754072989.png)

我这里显示没什么问题

系统版本号和浏览器版本号发我下

**Comment by zkqiang** [comment]
我在 Chrome / Safari / IE 浏览器都没复现出来...

可能是你本地某些本地配置或者插件影响的

**Comment by fishUPs** [comment]
> 我在 Chrome / Safari / IE 浏览器都没复现出来...
> 
> 可能是你本地某些本地配置或者插件影响的

Microsoft Edge
版本 94.0.992.31 (官方内部版本) (64 位)
版本	Windows 10 专业版
版本号	20H2
安装日期	‎2021/‎7/‎24
操作系统内部版本	19042.1237
序列号	PF18NEBF
体验	Windows Feature Experience Pack 120.2212.3530.0

**Comment by zkqiang** [comment]
![image](https://user-images.githubusercontent.com/32983588/135299275-d22ea274-e41b-448f-8a06-f71e7637dff3.png)


![image](https://user-images.githubusercontent.com/32983588/135299261-c2aece5a-a42d-4d2f-bfb5-80cc4d000744.png)


找别人实测的，也没什么问题...

**Comment by fishUPs** [comment]
我iPad看也一切正常，应该是我本地有问题，大佬了解什么状况会出现这个问题吗

**Comment by zkqiang** [comment]
这个不清楚..

看看是不是一些设置或者插件会影响到
