### ISSUE TITLE
配置文件示例错误

### ISSUE THREAD

**Issue by czqu** [fluid-dev/hexo-theme-fluid#593]
#### Bug 描述
配置文件里：通过 API 接口作为首页副标题的内容，必须返回的是 JSON 格式，如果请求失败则按 text 字段显示，该功能必须先开启 typing 打字机功能 示例给的是 ['data', 'content'] 但是实际代码却是 split('.') 按这样配置根本解析不了多层的json

**Comment by zkqiang** [comment]
dev 分支已修复，可以试下

模板取出来会变成 `'data,content'`，所以要用 `split`
