### ISSUE TITLE
插入HTML表格后表格无法调整成设定的宽度 & 不支持任务列表

### ISSUE THREAD

**Issue by Firestar-Reimu** [fluid-dev/hexo-theme-fluid#598]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

如图，插入HTML表格后表格无法调整成设定的宽度，不管是表格整体还是单独设定某一列，也不支持任务列表（打勾的选择框）

源代码：https://github.com/1900011604/Blog-source/blob/master/hexo/source/tools/time-calculator/time-calculator.html

![图片](https://user-images.githubusercontent.com/65082432/137572082-a7c74653-4b49-40f4-9be9-befd881761cb.png)

也可以直接看 https://blog.firestar-reimu.top/tools/time-calculator

浏览器：Firefox Developer Edition 94.0b5 (64 bit)

放大倍率：80%

PS：为什么网址没有高亮？将layout从page改为post即可

**Comment by 1900011604** [comment]
但是Edge（Chronium版）上显示是正常的：
![image](https://user-images.githubusercontent.com/65082432/137921586-1dcc4de7-aaec-4572-b5e6-7fa2f8693077.png)

**Comment by zkqiang** [comment]
Firefox Developer Edition 94.0b8 没有复现出来

另外既然是HTML，样式应该你自己去适配... 

网址的问题可以把上面文字部分包裹上 `<div class="markdown-body">`

**Comment by Firestar-Reimu** [comment]
![Screenshot_20211103_085750](https://user-images.githubusercontent.com/65082432/139973067-03b1de96-90fc-4565-9692-75645358b591.png)

又试了一下，复选框☑确实不支持，即使是文章页面（不是自定义页面）也渲染不出来

**Comment by Firestar-Reimu** [comment]
现在网站在Firefox和google chrome上渲染分别是这样：

Firefox
![Screenshot_20211103_093843](https://user-images.githubusercontent.com/65082432/139999311-3b5b2621-bc30-41ee-b1bd-35333954de42.png)

Chrome
![Screenshot_20211103_093931](https://user-images.githubusercontent.com/65082432/139999315-9fbda475-759d-435f-88a0-f09a544348e6.png)

**Comment by Firestar-Reimu** [comment]
测试发现是本来就不支持表格居中，希望fluid能予以改进，将会开一个新的issue
