### ISSUE TITLE
关于页面的微信图悬浮图片大小怎么修改？

### ISSUE THREAD

**Issue by dianmaomao** [fluid-dev/hexo-theme-fluid#600]
#### 微信图标悬浮图太小了
![image](https://user-images.githubusercontent.com/42103546/137733700-911ce031-9425-4622-9a47-a069a72a10ef.png)
默认的悬浮图标太小了，我经过给修改图片css 还是很小 请问有什么办法修改？
![image](https://user-images.githubusercontent.com/42103546/137733591-35dea34b-9cf1-4230-8906-69b8c0f69438.png)

**Comment by zkqiang** [comment]
升级最新版本试试
