### ISSUE TITLE
Leancloud不统计localhost域名统计数据

### ISSUE THREAD

**Issue by rama291041610** [fluid-dev/hexo-theme-fluid#603]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题
[用户指南-展示 PV 与 UV 统计](https://hexo.fluid-dev.com/docs/guide/#%E5%B1%95%E7%A4%BA-pv-%E4%B8%8E-uv-%E7%BB%9F%E8%AE%A1)中写道：
> LeanCloud 在 localhost 域名下不会增加数据。

实际上localhost测试时，由于默认path设置是`path: window.location.pathname`，统计依然会增加。

#### 请描述您认为可行的解决方案
代码中对`window.location.hostname`进行处理，localhost/127.0.0.1只查询不自增。

**Comment by Potat0000** [comment]
#514 
bd1e34dd2151980c6344b9b81f7d406ac0f38148
