### ISSUE TITLE
【求助】如何给文章页面增加「分享到」功能

### ISSUE THREAD

**Issue by Kukmoon** [fluid-dev/hexo-theme-fluid#605]
#### 请确认
- [ ✅ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ✅ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
我想给文章页面增加一个「分享到」功能，但 Fluid 未提供此功能。
我留意到 Fluid 有提供「自定义JS、CSS、HTML」功能，不知道能不能用这个功能实现。
请问开发者大佬能不能给点提示，哪怕几个关键词也行。具体怎么实现，我自己再去摸索。我虽然是小白，但是坚决不做伸手党。

**Comment by zkqiang** [comment]
现在浏览器本身都有分享功能，所以没有必要再内嵌分享功能

如果非要加入，可以搜索`Hexo+分享`，然后通过自定义JS功能加入

**Comment by Kukmoon** [comment]
感谢大佬，我正在摸索用自定义JS功能加入分享。
现在有个问题。
我修改 Fluid 的 `_config.fluid.yaml` 文件，引入若干行 HTML 语句。
![图片](https://user-images.githubusercontent.com/16938012/139570199-eac47c76-c398-4d0d-a7f4-5842f36ac753.png)

但是用 `hexo g` 编译时在句点处报错。
![图片](https://user-images.githubusercontent.com/16938012/139570215-e05b2218-7fed-46c3-8628-a53d81f03834.png)

但是出错的这一句又很重要，需要 new 一个对象，才能显示分享栏。

我试着在句点前面加反斜杠作为转义字符，无效。

请问应该怎么办？

**Comment by zkqiang** [comment]
写在一句里试试，不用换行

**Comment by Kukmoon** [comment]
不，我知道问题出在哪里了。单引号。
要导入外部HTML语句，需要用单引号把它引起来。
但是我要导入的HTML语句里偏偏也存在单引号。
Hexo的编译器把句点前面的单引号识别为引用内容的结束符，这样，从句点开始，就会报错。

请问有什么转义字符可以规避这个问题吗？

**Comment by zkqiang** [comment]
你把语句里的单引号换成双引号就行了。。是一样的

**Comment by Kukmoon** [comment]
刚才试了，双引号不行，Hexo 编译器不认。
不过我也找到解决方案了。单引号之中如果还有单引号，必须连续使用两个单引号转义。
————
我解决了所有的困难，终于把外部CSS、外部JS都导入了文章页面，也new了一个新的「分享到」对象，用div插入了一个新的「分享到」实例，但是那个「分享到」实例，始终没有出现……
我决定不搞了，等我上完前端培训班再回来搞。
