### ISSUE TITLE
Post 在 Twitter iOS 内置浏览器中页边距过小

### ISSUE THREAD

**Issue by matchy233** [fluid-dev/hexo-theme-fluid#606]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

朋友使用 **iPhone 13 Pro，Twitter iOS客户端内置浏览器** 查看我的博文发现页边距过小，锚点(`#`) 被裁切。
图中相关博文: https://matchy233.github.io/2021/10/31/jetbrains-projector/

👇朋友提供的截图
![截图](https://user-images.githubusercontent.com/32197833/139616623-24f8d365-fb55-4315-9949-4682b7d7dfa4.png)

**Comment by Yuk-0v0** [comment]
我也遇到了

**Comment by KiyanYang** [comment]
原因应该来自：

article.post-content.mx-auto 元素的样式

<img width="316" alt="Snipaste_2022-01-03_00-31-01" src="https://user-images.githubusercontent.com/50903774/147882498-970043c7-c211-4e2c-a84d-a11ef4cef816.png">

当屏幕宽度小于 424 px 时，会将左右边距重设为 1 rem，导致锚点被遮挡。可以将此属性的值设为最大宽度 767 px 的样式一样即 2 rem。

@zkqiang 这应该是个 Bug。

**Comment by zkqiang** [comment]
@matchy233 @Yuk-0v0 @KiyanYang 

Twitter 内置浏览器设定的屏幕宽度小于 425 px，可视空间比较窄，所以按适配样式缩小两侧的边距，与锚点造成了冲突。
不过增大边距太浪费空间，所以我选择了在这种情况下隐藏左侧的锚点 https://github.com/fluid-dev/hexo-theme-fluid/commit/a1281709bfe89a687bc0a27871bf25bb19f1084d
