### ISSUE TITLE
便签如何去圆角？还有整体的背景颜色

### ISSUE THREAD

**Issue by hjzCy** [fluid-dev/hexo-theme-fluid#608]
默认的便签：

![image](https://user-images.githubusercontent.com/39392770/140599745-310f9a79-1950-4cd7-a833-189ee013f1c5.png)

想要这种便签怎么做：

![image](https://user-images.githubusercontent.com/39392770/140599802-79a3cde8-e165-43ad-bb93-c38ba5fb6ad0.png)

![image](https://user-images.githubusercontent.com/39392770/140599810-17718e14-56bc-44fe-92d2-a7cdcc939757.png)

就是左侧竖线的圆角（不想有圆角）、宽度和便签的背景、文字颜色。。能定制吗？

**Comment by zkqiang** [comment]
自定义CSS
