### ISSUE TITLE
min2read计算为NAN分钟

### ISSUE THREAD

**Issue by dianmaomao** [fluid-dev/hexo-theme-fluid#609]
#### 请确认
- [ ✅] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ✅] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

####描述

在配置文件中设置好了min2read之后，显式分钟为NAN，可能是计算出错了
![image](https://user-images.githubusercontent.com/42103546/141717479-8f883b88-67da-454c-99ba-4de124630f51.png)

复现地址：
http://localhost:4000/2021/11/08/nginx+docker+jenkins%E8%87%AA%E5%8A%A8%E5%8C%96%E6%9E%84%E5%BB%BA%E9%83%A8%E7%BD%B2%E5%89%8D%E7%AB%AF%E9%A1%B9%E7%9B%AE/

#### 截图
![image](https://user-images.githubusercontent.com/42103546/141717552-fba603c6-d363-421a-9ad8-bfffcbad919e.png)

**Comment by zkqiang** [comment]
你发的链接是本地路径...

**Comment by dianmaomao** [comment]
> 你发的链接是本地路径...

抱歉抱歉，复现地址：
https://findly.gitee.io/2021/11/08/nginx+docker+jenkins%E8%87%AA%E5%8A%A8%E5%8C%96%E6%9E%84%E5%BB%BA%E9%83%A8%E7%BD%B2%E5%89%8D%E7%AB%AF%E9%A1%B9%E7%9B%AE/

**Comment by zkqiang** [comment]
新版本配置有变更，同步更新一下：

```diff
min2read:
- words: 100
+ awl: 2
+ wpm: 160
```

**Comment by dianmaomao** [comment]
> 新版本配置有变更，同步更新一下：
> 
> ```diff
> min2read:
> - words: 100
> + awl: 2
> + wpm: 160
> ```

好的 感谢
