### ISSUE TITLE
Hexo 5 使用 npm 安裝主題可否在特定文章加入自訂模板

### ISSUE THREAD

**Issue by hms5232** [fluid-dev/hexo-theme-fluid#610]
#### 请确认
- [X] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [X] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

目前使用環境：
* Nodejs 14.16.1
* Hexo 5.4.0
* fluid 1.8.12

雖然有在頁尾自訂 html 的設定選項，但我只想在 post 及特定一些 page 中插入一些模板（例如 LikeCoin 之類的按讚按鈕）而不是全部都加。研究之後發現如果是用 submodule 或直接 clone 的話，直接進入主題內修改 ejs 應該就可行了；但如果是使用 hexo 5 新方式── npm 安裝主題的話，就不能用此方式新增 ejs。

想問有沒有什麼我遺漏的地方有這項功能或是什麼方法可以達成呢？原本想在 `source` 底下直接放 ejs，然後在寫 post 的時候引入，結果寫到一半才想到不知道怎樣才能在 md 裡面引入 ejs 🥲

**Comment by zkqiang** [comment]
https://hexo.io/zh-tw/api/injector

**Comment by hms5232** [comment]
> https://hexo.io/zh-tw/api/injector Hexo有功能可以直接向 post 等特定页面插入代码，再精细一些你可以通过 JS 加入一些判断进去

之前在加 GA 的時候有試過，後來放棄了乖乖放主題設定檔。這次再來試試看好了，感謝提供方向。

**Comment by hms5232** [comment]
> https://hexo.io/zh-tw/api/injector Hexo有功能可以直接向 post 等特定页面插入代码，再精细一些你可以通过 JS 加入一些判断进去

不好意思我實際測試後發現，要將入口 js 放在 `scripts` 底下才能發揮作用；如果用 npm 安裝主題的話，就只能去 `node_modules` 裡面做，可是這樣就必須要將這個資料夾也加入 git 一起 commit......請問是否是我哪裡遺漏了呢？

我是參考這篇下去做的：https://hexo.fluid-dev.com/posts/hexo-injector/

----

目前有想到另外一個方法：寫一個 \<div> 給他 id，然後用 js 指定 id 寫入 html，最後去主題設定中加入自訂的 js。

**Comment by zkqiang** [comment]
`scripts` 放在 blog 目录下即可，不需要放在 `node_modules ` 里面

**Comment by hms5232** [comment]
> `scripts` 放在 blog 目录下即可，不需要放在 `node_modules ` 里面

沒想到是我太眼殘，沒看清楚 😂。非常感謝您的幫忙！
