### ISSUE TITLE
blog_title  属性改了但是页面的标题还是hexo，大佬帮帮忙。

### ISSUE THREAD

**Issue by madechao1995** [fluid-dev/hexo-theme-fluid#611]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

**Comment by Kukmoon** [comment]
不是 blog_title 属性。
是 _config.yml 文件中 Site 节下面的 title: 属性。
![图片](https://user-images.githubusercontent.com/16938012/142639557-16e0c57d-e738-4ebb-a9c5-dd533ad0305d.png)
