### ISSUE TITLE
我做了个打赏模块

### ISSUE THREAD

**Issue by Kukmoon** [fluid-dev/hexo-theme-fluid#612]
本前端小白做了个简单的打赏模块，大佬们有兴趣合并到master吗？

没有用JS，而是在 post.ejs 里面，增加了一组 HTML 代码，展示打赏提示和打赏二维码。最终效果见[这里](https://blog.kukmoon.com/eef01390.html)

![在 post.ejs 中增加了一组 HTML 代码](https://user-images.githubusercontent.com/16938012/142402493-7987d2f2-3206-47ac-b0dc-6e9e795f64ee.png)

![在 _config.fluid.yaml 中增加了一个 donate 节](https://user-images.githubusercontent.com/16938012/142402585-f4652d73-14cf-47e1-90a1-d4e90ca9e53c.png)

![最终效果图](https://user-images.githubusercontent.com/16938012/142402704-08271fea-8463-4531-964e-6447e3b28be5.png)

**Comment by zkqiang** [comment]
这个可以通过自定义功能引入，就不专门加到项目里了

**Comment by Kukmoon** [comment]
自定义是把打赏模块放到页脚里，我认为不好看而且不方便。
![图片](https://user-images.githubusercontent.com/16938012/142766366-6166cba2-1e75-4000-bb87-cf615273c501.png)

所以我修改了 `post.ejs` 文件，把打赏模块放到了文章内容里。
