### ISSUE TITLE
默认iconfont的coolapk图标不能正确显示

### ISSUE THREAD

**Issue by zhouym233** [fluid-dev/hexo-theme-fluid#613]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

默认iconfont的coolapk图标不能正确显示，只有一个实心圆圈
```
icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/test', tip: 'GitHub' }
    - { class: 'iconfont icon-coolapk', link: 'http://www.coolapk.com/test', tip: 'Coolapk' }
```
#### 复现步骤
该 Bug 复现步骤如下：
1. 引用iconfont icon-coolapk即可复现

#### 截图

![coolapk](https://user-images.githubusercontent.com/26868483/142754504-bca56f3f-9323-4a15-b363-1821bd2695bf.png)

**Comment by zkqiang** [comment]
配置里更新链接试试
`iconfont: //at.alicdn.com/t/font_1736178_lbnruvf0jn.css`
