### ISSUE TITLE
npm 安装主题 img 文件不生效

### ISSUE THREAD

**Issue by kmq116** [fluid-dev/hexo-theme-fluid#614]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

1. 本地通过 npm 安装主题，并在 source 下放置了 img 文件夹，在根目录新建了主题配置，然后进行 本地 build 命令，打包之后的 public 文件夹下的 img 文件里的图片还是 fluid 默认的那几张图片，本地的主题配置没有生效。期间确定执行了 hexo clean   

2. 尝试删除 node_module 下 fluid 包里的 img 文件夹，删除后 bug 消失，又重新安装主题打包 ，bug 复现  

3. hexo s 本地服务起来也一样的 bug
#### 复现步骤
该 Bug 复现步骤如下：
npm 方式安装 ，执行 build 命令

#### 截图
版本号与目录结构与配置文件层级
![BUG](https://user-images.githubusercontent.com/59247607/143462532-c290b375-f8aa-4889-9ccb-8adc7a4e8643.png)

**Comment by zkqiang** [comment]
你自己的img修改成别的文件名并在配置里指定试试
