### ISSUE TITLE
页面顶部头图中的文字如何修改

### ISSUE THREAD

**Issue by guowei-gong** [fluid-dev/hexo-theme-fluid#615]
#### 请确认
- [X] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [X] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

> 我还查询了 close issue 中是否存在相似的问题，通过 `标题` 的关键字 

#### 问题描述
在配置文件中，我将 menu 下的 { key: "categories", link: "/categories/", icon: "iconfont icon-category-fill" }
修改为：{ key: "专题", link: "/categories/", icon: "iconfont icon-category-fill" }

我希望图中的两处显示一致，谢谢你的帮助 \(^o^)/~

![image](https://user-images.githubusercontent.com/62499904/143532049-14470a77-dd60-40cb-8b2a-f89feeebe55b.png)

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/099445937b8b1c4fa05024bb3869b4deecd57b99/_config.yml#L805-L810

`subtitle` 可以指定
