### ISSUE TITLE
使用移动端浏览的话，如果脚注出现在屏幕偏右侧，页面右侧会出现留白

### ISSUE THREAD

**Issue by zhullyb** [fluid-dev/hexo-theme-fluid#616]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

对于部分文章，移动端右侧出现留白，有些难描述，具体情况见图一。

#### 复现步骤
Bug产生原因是因为我使用了markdown的「脚注」功能，导致在移动端上脚注的气泡超出了屏幕范围，右侧出现了一大块留白（见图二）
这取决于手机的分辨率、字体等，如果这个气泡没有被浏览器渲染在右侧边缘，是不会出现留白的。因此我刻意写了一篇全都是脚注的文章，应该可以帮助你们复现: https://blog.zhullyb.top/2021/11/27/debug/

#### 截图
![图1](https://user-images.githubusercontent.com/43305366/143679034-90a80747-ab25-436c-ba02-9ec951b3c1d6.png)
![图2](https://user-images.githubusercontent.com/43305366/143679053-3b3da625-5f18-4ca2-927d-c8773a0aca3d.png)

**Comment by zkqiang** [comment]
只能暂时解决超出部分，会截取掉超出的悬浮文字，浮框使用的库暂时无法自适应（也可能是我没找到方法），先不处理了

**Comment by zhullyb** [comment]
那这个页面我先撤掉了，如果有别的开发者需要查看这个出问题的页面的话，我在 archive.org 做了备份。
http://web.archive.org/web/20211128181455/https://blog.zhullyb.top/2021/11/27/debug/

另外感谢 skqiang 的回复。

**Comment by H3arn** [comment]
Found a problem with this fix.
When the width of the page is smaller than 767px, the upper half of the avatar will not be displayed.
Go to https://blog.zhullyb.top/about/ and you can reproduce that problem. 

I am working on this too, will update if I could come up with new workaround.

**Comment by zkqiang** [comment]
@H3arn Thx, I tried to fix it

**Comment by zhullyb** [comment]
看上去确实是没问题而了
------
LGTM
