### ISSUE TITLE
头图与背景色

### ISSUE THREAD

**Issue by jeam-xyz** [fluid-dev/hexo-theme-fluid#618]
提个建议：头图不上图片可以跟当前的背景色的颜色一致
![](https://raw.githubusercontent.com/jeam-xyz/image/main/202112042358361.png)
![](https://raw.githubusercontent.com/jeam-xyz/image/main/202112042358325.png)

**Comment by zkqiang** [comment]
可以试试把 `banner_mask_alpha: 0`
