### ISSUE TITLE
index.html生成的代码异常

### ISSUE THREAD

**Issue by Wanda0104** [fluid-dev/hexo-theme-fluid#622]
![image](https://user-images.githubusercontent.com/56828756/145691420-af88628a-0abd-457e-8266-8aecb1db2cc1.png)

当前是在blog目录下，没有任何地方配置这段文字"GEM0816的自留地"，但是每次生成出来的index.html 的title都是这段字符串

**Comment by zkqiang** [comment]
这个跟主题没关系，请检查自己的配置
