### ISSUE TITLE
Waline 评论的头部标签在水平方向未对齐

### ISSUE THREAD

**Issue by KiyanYang** [fluid-dev/hexo-theme-fluid#623]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

Waline 评论的头部标签在水平方向未对齐

#### 复现步骤
该 Bug 复现步骤如下：
1. 配置 Waline 评论
2. 打开任意包含评论的文章或页面
3. 会出现“Waline 评论的头部标签在水平方向未对齐”
4. [复现页面](https://kiyanyang.github.io/links/)，备注：我的博客可能会很快被修复，此时可以参阅其他 Waline 用户（在 issue 搜索 `Waline` 获取用户）。

#### 截图

<img width="376" alt="水平未对齐" src="https://user-images.githubusercontent.com/50903774/145700915-88a19531-b7f0-4f18-966e-729ed16cde56.png">

#### 简单分析

<img width="230" alt="Label 查看结果" src="https://user-images.githubusercontent.com/50903774/145701369-32b97cf4-87d0-4308-9f33-c7d1a1858e43.png">
<img width="309" alt="Label 样式" src="https://user-images.githubusercontent.com/50903774/145701371-a1ca8ede-569a-4714-bce9-dee6b28bcd97.png">

备注：`_reboot.scss` -> `https://cdn.jsdelivr.net/npm/bootstrap@4/scss/_reboot.scss`

#### 临时解决措施

1. 在 `source/css` 新建 css 文件，比如 `waline.css`
2. 在文件中添加如下代码
   ```css
   #waline label {
     margin-bottom: 0;
   }
   ```
3. 在主题配置 `custom_css` 中添加上述文件地址，比如 `/css/waline.css`

**Comment by zkqiang** [comment]
dev已修复
