### ISSUE TITLE
请问一下为何配置了CNZZ的ID但是看不到网站统计？

### ISSUE THREAD

**Issue by SalHe** [fluid-dev/hexo-theme-fluid#627]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

已按照文档配置了 web_analytics.enable = true, web_analytics.cnzz=<cnzz的id>，但是网站底部还是没出现网站访问统计。

**Comment by zkqiang** [comment]
底部统计只支持不蒜子和LeanCloud，具体请查看文档

**Comment by SalHe** [comment]
> 底部统计只支持不蒜子和LeanCloud，具体请查看文档

好的，所以CNZZ只能在后台看数据，但是不能用于前台展示是吗？

**Comment by zkqiang** [comment]
是的

**Comment by SalHe** [comment]
> 是的

好的，感谢
