### ISSUE TITLE
官网样式错乱

### ISSUE THREAD

**Issue by dianmaomao** [fluid-dev/hexo-theme-fluid#635]
![image](https://user-images.githubusercontent.com/42103546/146738390-06f900c5-17a8-45f0-8f18-df6ed19c9af0.png)
昨天部署了一下博客，发现样式错乱了，今天进了fluid主题官网也发现同样的样式错乱了

**Comment by Enderfga** [comment]
我也出现了这个问题，重装了4,5次，原来不是被我搞崩了

**Comment by dianmaomao** [comment]
恢复了 看样子是cdn中jq的链接出问题了

**Comment by Enderfga** [comment]
请问您是怎么解决的？

**Comment by dianmaomao** [comment]
> 请问您是怎么解决的？

强制刷新一下试试 我刷新了一下就好了

**Comment by linnn-xiinn** [comment]
需要全局代理，我刚刚也出现了这个问题

**Comment by zkqiang** [comment]
@dianmaomao @linnn-xiinn @Enderfga 
是因为今天 jsdelivrCDN 在大陆地区的服务挂掉了，等恢复就行了

**Comment by zkqiang** [comment]
不信任 jsdelivr 的话可以自己配置里更换一套
