### ISSUE TITLE
fluid主题样式全部丢失啦！！！！

### ISSUE THREAD

**Issue by linnn-xiinn** [fluid-dev/hexo-theme-fluid#636]
样式丢失啦！！！！！！！快来维护呀！！！！！

**Comment by linnn-xiinn** [comment]
需要全局代理挂梯子，js和css样式才恢复正常

**Comment by love4taylor** [comment]
cdn.jsdelivr.net 证书炸了，确实得考虑换一个公共镜像了

**Comment by linnn-xiinn** [comment]
霍，今天有好几些网站样式都丢了，影响范围不小啊

**Comment by love4taylor** [comment]
https://github.com/jsdelivr/jsdelivr/issues/18348

**Comment by zkqiang** [comment]
@linnn-xiinn @love4taylor 
不信任 jsdelivr 的话可以自己配置里更换一套
