### ISSUE TITLE
导航栏头顶的菜单如何设置二级菜单

### ISSUE THREAD

**Issue by YoujiaZhang** [fluid-dev/hexo-theme-fluid#637]
#### 请确认
- [ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

**Comment by zkqiang** [comment]
请阅读文档
<https://hexo.fluid-dev.com/docs/guide/#导航菜单>
