### ISSUE TITLE
头像在移动端无法正常显示

### ISSUE THREAD

**Issue by RickWayne1125** [fluid-dev/hexo-theme-fluid#638]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

关于页面下的头像在小窗口和移动端下无法正常显示

#### 截图
正常显示下截图：
![image1](https://user-images.githubusercontent.com/44436897/147404392-82086bea-f04a-4cf6-8e79-f609a0852e37.png)
小窗下截图：
![image2](https://user-images.githubusercontent.com/44436897/147404406-aaef6ab6-444c-4912-bfa5-c2c4c3e8db9c.png)
移动端截图：
![image3](https://user-images.githubusercontent.com/44436897/147404515-fd150396-090e-417e-8afd-3692b5ee24c8.jpg)

**Comment by zkqiang** [comment]
dev分支已修复，可以试下 https://github.com/fluid-dev/hexo-theme-fluid/commit/d8df838d881963231bc470bb4006ab28525e794d

**Comment by RickWayne1125** [comment]
> dev分支已修复，可以试下 [d8df838](https://github.com/fluid-dev/hexo-theme-fluid/commit/d8df838d881963231bc470bb4006ab28525e794d)

问题已解决，感谢！:+1:
