### ISSUE TITLE
TOC 光标错位

### ISSUE THREAD

**Issue by KiyanYang** [fluid-dev/hexo-theme-fluid#639]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

当目录上移，也即目录最上面被遮挡时，TOC 光标错位。

#### 复现步骤
该 Bug 复现步骤如下：
1. 在含有较多标题页面
2. 向下滚动，让最上方的标题被遮挡
3. 会出现 TOC 光标错位。

#### 截图

<img width="148" alt="Snipaste_2022-01-01_00-23-32" src="https://user-images.githubusercontent.com/50903774/147832333-aad1f653-2eb5-422b-b91d-e1f692b10cb5.png">

更加明显的错位：

<img width="124" alt="Snipaste_2022-01-01_00-25-15" src="https://user-images.githubusercontent.com/50903774/147832351-3e9e9063-3d36-4d75-a9af-e4d6461c91c2.png">

## 解决方案

由于 .toc-body 是上下可动的，而光标默认依赖位置不在 .toc-body 上，所以会出现目录移动而光标不动，造成错位。
因此需要设置其依赖位置。

```stylus
// 光标依赖位置
.toc-body > ol {
  position: relative;
}
```

不过这种方法也存在问题：

正常的：

<img width="82" alt="Snipaste_2022-01-01_00-38-18" src="https://user-images.githubusercontent.com/50903774/147832660-e87f6a96-7ef9-4078-bcc0-ea26af45d38a.png">

在某些页面上导致目录上移：

<img width="107" alt="Snipaste_2022-01-01_00-38-07" src="https://user-images.githubusercontent.com/50903774/147832677-bec2e726-6eba-4045-a067-9b0a8ccffeaf.png">

原因不太清楚。举个网页实例：在 [文章 1](https://kiyanyang.pages.dev/posts/277e1260/) 中就看不出这个问题，但是在 [文章 2](https://kiyanyang.pages.dev/posts/f92be1eb/) 就会有这个问题。

**Comment by zkqiang** [comment]
试一下
```css
/* .toc-body > ol { */
/*  position: relative; */
/*} */

.tocbot-list {
  position: relative;
}
```

**Comment by KiyanYang** [comment]
> 试一下
> 
> ```css
> /* .toc-body > ol { */
> /*  position: relative; */
> /*} */
> 
> .tocbot-list {
>   position: relative;
> }
> ```

这个确实不错，不会出现错位，也不会出现目录上移。

只不过这个和标题固定，左右位置会变动，我个人比较喜欢之前不变的那种。😂

<img width="121" alt="Snipaste_2022-01-02_14-36-57" src="https://user-images.githubusercontent.com/50903774/147868527-51964bfe-6144-4c31-bed8-002657742566.png">
