### ISSUE TITLE
复制按钮的颜色判定似乎失效

### ISSUE THREAD

**Issue by KiyanYang** [fluid-dev/hexo-theme-fluid#640]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

复制按钮的颜色判定似乎失效。

复制按钮的颜色判断应该是发生在这里：

https://github.com/fluid-dev/hexo-theme-fluid/blob/1d524d06af1571aca4a27b3f8efed5604cd24eaf/source/js/plugins.js#L127-L134

但是我在浏览器调试时发现 `rgbArr` 总是得到 `["0", "0", "0", "0"]`，无论是在 [Fluid's blog](https://hexo.fluid-dev.com/)、[zkqiang's blog](https://zkqiang.cn/)或者[我的博客](https://kiyanyang.github.io/)，这似乎有些问题。而且在我的博客之前的[历史版本](https://6d3c5d2b.kiyanyang.pages.dev/)中，`rgbArr` 得到的是 `['246', ' 248', ' 250']`，而在这两个版本之间我没做颜色方面的修改，所以这让我感觉很困惑。

**Comment by zkqiang** [comment]
dev 已修复
