### ISSUE TITLE
本地右侧目录显示还有返回顶部的按钮能用，部署后不能正常显示

### ISSUE THREAD

**Issue by Poluk2001** [fluid-dev/hexo-theme-fluid#642]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

**Comment by zkqiang** [comment]
部署的问题不属于主题问题，请检查缓存等因素

**Comment by Poluk2001** [comment]
> 部署的不属于主题问题，请检查缓存等问题

已经检查过了，但还是不可以...清除了缓存问题了
