### ISSUE TITLE
关于手机上不能显示目录

### ISSUE THREAD

**Issue by mxrmiss** [fluid-dev/hexo-theme-fluid#643]
- 在电脑上面可以显示目录，但是手机上面不能显示目录，有什么办法可以解决吗？
- 图片下面显示的文字怎么能够去除？
- 感谢这个主题的开发者们，谢谢，希望你们能帮助我解决这些问题。

**Comment by zkqiang** [comment]
问题1: 移动端暂时没有目录功能，未来某个版本再添加

问题2：下个小版本增加单独控制项

**Comment by mohuishou** [comment]
> 问题1: 移动端暂时没有目录功能，未来某个版本再添加

这个其实我也改过了，后面有空可以整理一下再提个 PR

![image](https://user-images.githubusercontent.com/15172509/150065739-60bd0e6a-7f95-48db-b5b1-b7aca83fc000.png)

**Comment by cxw745** [comment]
两年了，还是没有目录

**Comment by ElfriedeMagdaleneHolger** [comment]
搜到问题本来想问结果已经有了，还是希望能有移动端目录功能，对于文字为主的博客来说确实非常必要。
