### ISSUE TITLE
图片名字和图片重叠了

### ISSUE THREAD

**Issue by xiaoleGun** [fluid-dev/hexo-theme-fluid#644]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
任何设备浏览下，图片名字在图片底部，与图片重叠

**Comment by zkqiang** [comment]
dev 分支已修复

**Comment by xiaoleGun** [comment]
感谢，没想到这么快就修复好了QwQ
这样的主题才是好主题，有求必应！！！
