### ISSUE TITLE
想请问一下引用静态资源的详细列表

### ISSUE THREAD

**Issue by huaxianyan** [fluid-dev/hexo-theme-fluid#645]
#### 请确认
- [ x ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ x ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

因为最近 jsDelivr 风波，使得博客受到了影响。因为我个人是使用了国内的 CDN，所以就考虑把依赖的静态资源在自己的 CDN 上放一份来使用。

但是对着配置文件里 ``static_prefix`` 里把东西都部署上去之后发现有一些问题，有一些引用的静态文件缺失了。

比如 highlight.js 里有一个 ``github-gist.min.css``，但是从 npm 拉下来的 highlight.js@10 里没有这个文件，访问 CDN 上的文件发现是 jsDelivr 自己缩小的，但是我并不知道，所以就缺失了。

我已经把目前能看得到的缺失的都自己保存下来并重新部署上去了，目前随便点点都没有发现有引用失败的问题，但是担心可能会在哪里没测试到的地方存在这样的问题，所以能否询问一下有没有一个简单的 list 告知具体引用了文件，我想全去处理一遍。

**Comment by zkqiang** [comment]
理论上 CDN 都会有 `min.css` 这种压缩版本，这个并不是 jsDelivr 独有的

至于你说的 list 我是没有的，我没有统计过

**Comment by huaxianyan** [comment]
@zkqiang 好的，感谢。

因为是打算放在博客本地不用现成的 CDN 静态资源了，有没有一个思路可以防止此种问题？

就好比 https://cdn.jsdelivr.net/npm/highlight.js@10/github-gist.min.css 是能访问到文件，但是直接访问 https://cdn.jsdelivr.net/npm/highlight.js@10/ 看列表里是没有 github-gist.min.css 的。

**Comment by zkqiang** [comment]
列表看不到可能只是因为显示省略掉了...  但是每个 css 理论都有一份 min.css

你如果自己搞，可以把所有的 css 文件压缩成 min.css （应该有批量压缩的脚本），或者直接重命名也没什么问题

**Comment by huaxianyan** [comment]
@zkqiang 非常感谢您的帮助，同时也希望 jsDelivr 能够早日恢复
