### ISSUE TITLE
希望在 config 添加更多颜色自定义

### ISSUE THREAD

**Issue by matchy233** [fluid-dev/hexo-theme-fluid#647]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

用户自定义 body 背景色后 button 和 checkbox 颜色甚是不和谐。

![button and checkbox](https://user-images.githubusercontent.com/32197833/150132604-a5d59621-e65b-41d1-8a73-5f7b073f3273.png)
![button hover](https://user-images.githubusercontent.com/32197833/150132756-78e92c2c-de74-4455-aa4a-7d5d6dcb94c3.png)

表格边框样式也甚是不和谐。

![table](https://user-images.githubusercontent.com/32197833/150140774-ad73e491-a67f-4495-87b3-9ace14763362.png)

#### 请描述您认为可行的解决方案

在 config 添加 button、checkbox 和 line color 颜色自定义，在 `source/css/_variables/base.styl` 添加相关变量，修改相应的 stylus 文件配置。button hover 可以直接复用 link-hover-color 的颜色。

#### 考虑过的替代方案

虽然能够通过自定义 css 解决，但需要手动指定大量的样式。特别是 line-color-dark 已有现成变量了，可以利用起来。

**Comment by zkqiang** [comment]
dev已添加
