### ISSUE TITLE
希望使用CodeMirror等替换hexo内置的highlight，或提供选择

### ISSUE THREAD

**Issue by dr34-m** [fluid-dev/hexo-theme-fluid#648]
#### 原因
自带的highlight虽然号称支持很多语言，但实际有些语言支持效果很差，例如shell等，几乎都是黑色的

#### 解决
使用CodeMirror等替换hexo内置的highlight，或提供选择

**Comment by zkqiang** [comment]
高亮目前只考虑基于 Hexo 内置，使用其他的适配并不容易，感兴趣可以自己研究下
