### ISSUE TITLE
夜间模式下的代码块

### ISSUE THREAD

**Issue by dajia-1701** [fluid-dev/hexo-theme-fluid#649]
#### 如是功能需求，请确定符合以下情况
- [X] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [X] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

开启夜间模式后，白色的代码块极其刺眼。

高亮使用`highlightjs`，`Github Gist`主题。

#### 请描述您认为可行的解决方案

在开启夜间模式后切换`highlightjs`的主题。

#### 考虑过的替代方案

自定义JS也许可以？但我不会写。

**Comment by dajia-1701** [comment]
比如这篇文章 https://www.d0j1a1701.cc/p/c7a0ecbe/

**Comment by zkqiang** [comment]
duplicate #489
