### ISSUE TITLE
文章底部的版权申明部分字体修改失效

### ISSUE THREAD

**Issue by fdvzs** [fluid-dev/hexo-theme-fluid#654]
#### 请确认
- [ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 是当前最新的 Dev 版本
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述
可以算是一个 Bug，但不是功能性的，只是影响美观：

文章底部的版权申明部分，文字使用的是默认字体而不是主题配置文件中配置的字体。

因为那部分设置了 `class="license-box iconfont"`，而 iconfont 的 css 中有：

```
.iconfont {
  font-family: "iconfont" !important;
```

iconfont 的字符中并不包含版权申明的文字，但是又没有设置低优先级的字体，所以遇到 iconfont 中没有的字符就会自动使用默认字体，而不是主题配置文件中配置的字体。

解决方法如下：

`\source\css\_variables\base.styl` 添加以下这行代码：

```
.iconfont {font-family: iconfont,$font-family !important}
```

sorry 啊，我不会 stylus，所以只能这样写了。

总之也就是这个意思，作者你看到以后自己改一下就好啦~

**Comment by zkqiang** [comment]
已修复
