### ISSUE TITLE
首页文章分类显示优化

### ISSUE THREAD

**Issue by ziguanqing** [fluid-dev/hexo-theme-fluid#657]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

一篇文章的分类关系是父子关系的话，在首页无法有效的展示出来。如下：
![](https://gitee.com/jinghu-moon/imgbed/raw/master/images/20220207154625.png)
可以参考下 Butterfly 样式。个人认为可以较好地展示分类关系。

![](https://gitee.com/jinghu-moon/imgbed/raw/master/images/20220207155004.png)

**Comment by zkqiang** [comment]
感谢，dev 分支已优化，待发布
