### ISSUE TITLE
如果我从master换到dev，有没有什么快速的方式？

### ISSUE THREAD

**Issue by king-zhangbn** [fluid-dev/hexo-theme-fluid#659]
#### 请描述您认为可行的解决方案
由于我在 HEXO 根目录下已经有 _config.fluid.yml 文件，我能否git dev的完整包，然后将 fluid文件夹直接替换

**Comment by zkqiang** [comment]
可以的，直接替换文件夹就行

**Comment by king-zhangbn** [comment]
顺便问问，后期会不会加入相册，音乐等集成fluid，有点期待

**Comment by zkqiang** [comment]
这个要自己通过自定义功能实现，暂时不打算集成

**Comment by king-zhangbn** [comment]
好滴好滴
