### ISSUE TITLE
markdown-body 分割线不受配置文件控制

### ISSUE THREAD

**Issue by dnccx** [fluid-dev/hexo-theme-fluid#660]
#### 请确认
- [x] 是当前最新的 [develop 版本](https://github.com/fluid-dev/hexo-theme-fluid/tree/develop)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

主题配置文件中的

```
  # 分隔线和表格边线的颜色
  # Color of horizontal rule and table border
  line_color: "#435266"
  line_color_dark: "#435266"
```

只能控制 `版权声明` 上面的那条分割线的颜色，而不能控制文章中的分割线颜色。

#### 复现步骤

该 Bug 复现步骤如下：
随便在一篇文章中输入 `---` 分割线，`hexo s` 看到这条分割线的颜色并不是主题配置文件中设置的颜色，而是 `rgba(0, 0, 0, .1)` ，在深色背景下基本无法被看清。

#### 修复方法

`fluid\source\css\_pages\_base\rewrite.styl`

第241行，和229行一样，也修改为

```
border-top-color var(--line-color)
```

**Comment by zkqiang** [comment]
thx，已修复
