### ISSUE TITLE
leancloud只增加访问量，不增加访问人数

### ISSUE THREAD

**Issue by XXiaoA** [fluid-dev/hexo-theme-fluid#661]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
leancloud底部只有访问量增加，访问人数始终为0

**Comment by zkqiang** [comment]
有没有可能，确实没有人访问，比如现在我访问了就变成了1

**Comment by zkqiang** [comment]
@dnccx  我让群友帮他加了人气

**Comment by XXiaoA** [comment]
现在正常了 谢谢
@dnccx @zkqiang 
另一个问题

**Comment by XXiaoA** [comment]
> @dnccx  我让群友帮他加了人气

我说怎么突然这么多访问，谢谢哈😃

**Comment by XXiaoA** [comment]
另一个问题，右上角点击没反应怎么回事

**Comment by zkqiang** [comment]
> 另一个问题，手机端右上角点击没反应怎么回事

我访问你是好的，看是不是缓存问题

**Comment by XXiaoA** [comment]
> > 另一个问题，手机端右上角点击没反应怎么回事
> 
> 我访问你是好的，看是不是缓存问题

确实是 我刚删掉就发现您回复了😂，请问你邮箱可以直接收到issue信息？我要等很久才收到

**Comment by zkqiang** [comment]
> 确实是 我刚删掉就发现您回复了😂，请问你邮箱可以直接收到issue信息？我要等很久才收到

我的就延迟几分钟，QQ邮箱
