### ISSUE TITLE
加入各搜索引擎的HTML验证代码

### ISSUE THREAD

**Issue by XXiaoA** [fluid-dev/hexo-theme-fluid#662]
如题，是否有打算实现。

**Comment by XXiaoA** [comment]
> 我拒绝，这个完全可以靠注入器完成

啊这，好的，另外友链页如何在某个友链前/后添加内容，

**Comment by zkqiang** [comment]
1.8.x 版本可使用 [custom_head](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html)

1.9.0 以后版本可使用 [注入代码功能]()https://hexo.fluid-dev.com/docs/advance/#注入代码

**Comment by XXiaoA** [comment]
> 1.9.0 以后版本可使用 注入代码功能https://hexo.fluid-dev.com/docs/advance/#注入代码

谢谢
