### ISSUE TITLE
如何在博客首页大标题下方加一行文字

### ISSUE THREAD

**Issue by Kukmoon** [fluid-dev/hexo-theme-fluid#664]
#### 请确认

- [ 否 ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ 是 ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

我想在博客首页大标题下方的位置（如下图中的红框所示）加一行文字，请问该修改主题的哪个文件呀？

![图片](https://user-images.githubusercontent.com/16938012/155046613-d7a7c6fc-4928-419b-9774-c57dd9944a6f.png)

**Comment by zkqiang** [comment]
直接在 slogan 里写 HTML，比如 `xxxxx  <br/>  yyyy`
