### ISSUE TITLE
如何去掉鼠标指向博客副标题时显示的提示

### ISSUE THREAD

**Issue by Kukmoon** [fluid-dev/hexo-theme-fluid#665]
#### 请确认
- [ 否 ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ 是 ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
感谢 @zkqiang 帮我解决了上次提的 [Issue \#664 如何在博客首页大标题下方加一行文字](https://github.com/fluid-dev/hexo-theme-fluid/issues/664) 。不过我又遇到新问题了：鼠标指向博客副标题（subtitle）时，会显示一长串提示（tip），把我写的 HTML 代码都暴露出来了，很丑。

我发现这个提示与红色箭头指向的这一段 HTML 代码有关。那么，请问请问应该修改 theme/fluid 文件夹中的哪个文件，才能不让渲染生成的 HTML 网页中包含这个 title 属性呢？

![图片](https://user-images.githubusercontent.com/16938012/155085533-bc774b89-18cb-46f7-80d9-85c26b0c854f.png)

**Comment by zkqiang** [comment]
这是你里面的 `<a>` 标签问题

https://www.w3school.com.cn/tags/tag_a.asp

**Comment by Kukmoon** [comment]
不是，弹出的提示包括了整个 subtitle 的内容。不只是 `<a>`  标签。

**Comment by zkqiang** [comment]
可以给 subtitle 加一个 css：

```css
#subtitle {
  pointer-events: none;
}
```

**Comment by Kukmoon** [comment]
这是个好主意，但是又无法点击链接了。有没有什么办法让它不显示这个提示，又可以点击链接呢？

**Comment by zkqiang** [comment]
这个慢慢研究下 css 就行，不涉及修改主题

**Comment by Kukmoon** [comment]
我用谷歌搜了一圈，发现目前的CSS3没有只隐藏屏幕提示但是又可以点击的方法……

不过我用修改 `layout.ejs` 文件的方式实现了目的，代价是禁用打字机动画。换句话说，用打字机动画显示博客副标题，与隐藏屏幕提示不可兼得。

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/commit/46b6c6347d3926356047dcf1bbe9e00d839f51e8

可以参考我这个修改

**Comment by Kukmoon** [comment]
谢谢大佬。不过不好意思，我基本上看不懂……等我学完前端再来认真学习您的代码……

**Comment by Kukmoon** [comment]
我 fork 了 stable 分支，然后改了点代码

**Comment by Kukmoon** [comment]
总之，至少目前搞定了。

![最终效果](https://user-images.githubusercontent.com/16938012/155118981-63036787-cb10-4fd9-b983-e29436b02f81.png)

改了 `layout.ejs` ，加了一点内容。

![layout.ejs](https://user-images.githubusercontent.com/16938012/155119237-d71d6277-11b7-4ae6-9077-dd0b408ecf1b.png)

改了 `_config.fluid.yml` ，加了一点内容，关掉了打字机动画。

![_config.fluid.yml 1](https://user-images.githubusercontent.com/16938012/155119343-3bdab605-8ff4-4c57-94e6-61208af86def.png)

![_config.fluid.yml 2](https://user-images.githubusercontent.com/16938012/155119414-2f3fcfd9-36d5-4614-a873-7beb4ece2098.png)
