### ISSUE TITLE
如何自定义文章标题？

### ISSUE THREAD

**Issue by Xu-128** [fluid-dev/hexo-theme-fluid#666]
在博客根目录下的_config.yml里设置了subtitle，但是在文章界面的subtitle仍然和主页一样，有什么办法可以帮助我自定义每一篇文章的subtitle吗？感谢！

**Comment by Xu-128** [comment]
应该是我改配置文件改挂了（
翻文档也没找到

**Comment by zkqiang** [comment]
在 Front-matter 里的指定 `subtitle`，不设置就是 `title`
