### ISSUE TITLE
首页 banner 图滑动动画抖动

### ISSUE THREAD

**Issue by kmq116** [fluid-dev/hexo-theme-fluid#671]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### 复现步骤
该 Bug 复现步骤如下：
1. 在首页面 banner 图上下滑动的时候动画执行会抖动，滑动到设定的 96px 之后就不再抖动，之前没注意过这个
2. 动画执行路径在  fluid/source/js/events.js   55 行，但是不知道怎么解决

#### 截图
![bug](https://user-images.githubusercontent.com/59247607/156809323-79ca7916-14c9-43e5-a508-be5935f7d2d5.gif)
下面是文章位置正常的对比
![bug](https://user-images.githubusercontent.com/59247607/156809744-50357862-037e-45e8-9073-50aec5ffdbb7.gif)
文章位置的对比

**Comment by zkqiang** [comment]
我看你是做前端的，可以尝试在 console 的 performance 里提供下更多的信息（如果能分析出一些可能原因当然更好）

**Comment by kmq116** [comment]
> 我看你是做前端的，可以尝试在 console 的 performance 里提供下更多的信息（如果能分析出一些可能原因当然更好）

我尝试过 debug  , 在 2k 和 1080p 下没有这个问题，4k 分辨率下有出现，我尝试过 debug , 无果🤔🤦‍♂️
