### ISSUE TITLE
使用npm安装的Fluid主题该如何使用Dev版？

### ISSUE THREAD

**Issue by Morax-xyc** [fluid-dev/hexo-theme-fluid#672]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

我第一次用hexo，所以就选择了使用文档中推荐的npm安装方式。但后来发现这种安装方式的文件结构与其他安装方式的文件结构差距过大。

我想要安装Fluid的Dev版本以试验最新功能，但看着我拉取过来的dev分支中与主分支几乎截然不同的结构实在是不知道如何merge。

请问这种情况该怎么解决？或者能否提供一份dev版的npm包以便使用npm安装的用户更方便的体验dev版？

期待您的回复!

**Comment by zkqiang** [comment]
更新主题请参考：https://hexo.fluid-dev.com/docs/start/#%E6%9B%B4%E6%96%B0%E4%B8%BB%E9%A2%98

任何情况下都不推荐merge，直接替换整个文件夹即可

dev 分支属于未正式发布的分支，不提供npm

**Comment by Morax-xyc** [comment]
那好吧，我直接重新来一遍，手动对比
