### ISSUE TITLE
图片的alt文字不应像title一样显示出来

### ISSUE THREAD

**Issue by VickyLu001** [fluid-dev/hexo-theme-fluid#673]
#### 如是功能需求，请确定符合以下情况
- [True] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [True] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题
现在当插入图片时，alt文字会像title一样显示出来。

解释：alt属性是一个残障友好设计，在视障用户使用有声书功能时，图片的alt文字会被朗读出来；或者图片加载不出来时，alt会作为文字显示出来；或者鼠标悬停时显示出来。而title是给视觉正常的用户显示的。

举个例子：我在文中放了一张猫的图片，我为盲人设计的alt会是“一张猫的图片”，我为视觉正常的用户设计的title会是“猫”

现在的主题中，alt会直接显示在图片下方，如

```
<img src="\images\efile\sprintax.png" style="display: block; margin: 0 auto" alt="Sprintax Logo">
```

的显示效果是

![Imgur](https://i.imgur.com/d6wI2fD.png)

主题很好看+很好用，感谢作者！

**Comment by zkqiang** [comment]
最初我也是这么想的，但是 markdown `![xxx](./image.jpg)` 插入图片时会渲染成 `alt="xxx"`，没有 title 属性，所以如果只取 title 的话是取不到的

**Comment by VickyLu001** [comment]
嗯，是的，但是 `![xxx](./image.jpg)` 里本来就不应该有title。比如在github issue里，我主楼的放的那张图片，`![xxx](sprintax.jpg)`中的xxx就没有显示在图片下方。

markdown是一门鼓励大家为图片写alt，无所谓大家写不写title的语言，它的这个设计也也一直广受称赞。

**Comment by zkqiang** [comment]
但是这个图片标题的设计，就是为了显示 `![xxx]` 的内容，如果觉得多余那可以考虑关掉它，否则除了自己手写 `<img title="xxx" />` 之外基本没可能显示出标题了

dev 分支这个功能已经是可以通过配置关闭了：

https://github.com/fluid-dev/hexo-theme-fluid/blob/7e66f53bf92818df58e1c3ff1cdfccc3c0f980ec/_config.yml#L670-L673

**Comment by VickyLu001** [comment]
所以在markdown里一般的加title的方法`![Alt](/path/to/img.jpg “image title”)`不可行吗？

**Comment by zkqiang** [comment]
> 所以在markdown里一般的加title的方法`![Alt](/path/to/img.jpg “image title”)`不可行吗？

确实也可以，所以我写了 `title || alt` 来兼顾这两种情况，不过我还是会认真考虑下这个问题

**Comment by F7kyyy** [comment]
> 

我从dev分支clone后替换npm安装的主题文件，替换_config.fluid.yml文件后将image_caption 选项设置为false ,markdown 中插入图片 `![img_name](/path/to/img.jpg ` 标题 依旧会显示在图片的左下角，而使用`<img src="/path/to/img.jpg" alt="img_name">`时就没有标题；描述问题的页面https://f7kyyy.github.io/2022/03/10/%E5%BC%80%E5%A7%8B%E5%A4%8D%E4%B9%A0%E6%9C%89%E6%84%9F/

**Comment by zkqiang** [comment]
@F7kyyy dev已修复
