### ISSUE TITLE
请问如何设置关于页为博客首页

### ISSUE THREAD

**Issue by VisionTheta** [fluid-dev/hexo-theme-fluid#675]
想请教下如何设置关于页为博客首页。

我知道这个需求可能有点奇怪，但是想知道大概的实现方式。我有一定的动手能力，希望大家给予一些指点。

**Comment by zkqiang** [comment]
你可以看下 hexo 怎么生成首页的，然后通过 `generator.register` 类似的方式给他覆盖掉

**Comment by VisionTheta** [comment]
感谢指路。我研究下，这个issue先关闭了。

**Comment by davidwuya** [comment]
我也有一样的需求， @VisionTheta 琢磨出来怎么改了吗？
