### ISSUE TITLE
如何给api调用的首页文字加上作者？

### ISSUE THREAD

**Issue by Morax-xyc** [fluid-dev/hexo-theme-fluid#676]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

我使用了hitokoto的api内'hitokoto'作为首页文字，由于调用api时同时get了'from'的值，我就想要加上文字来源。

但发现注释和文档都没有提供操作空间。ejs文档内api调用同时与打字机集成，我不是很懂ejs和JavaScript，也不可能机械地复制一份。

请问应该怎么做才能同时使用两个键的值？如果可以更近一步，能否将文字来源加上破折号放在首页文字斜右下处，并提供处理的参数，比如调整字号、设定斜体？

感谢您的回复！很抱歉叨扰了。

**Comment by zkqiang** [comment]
除了自己实现没什么好办法

把主题自带的打字机关掉，自己写 js 引入进去就行了

**Comment by Morax-xyc** [comment]
ok我试试
