### ISSUE TITLE
如何使用本地图片？（不是图标）

### ISSUE THREAD

**Issue by shmilyty** [fluid-dev/hexo-theme-fluid#678]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

完全按照该用户指南的指示，所有版本均为最新，没有百度到相关方法，本地样式也不对。
#### 问题描述

浏览器：chrome

系统：windows10

例如在about页面里，有：```avatar: /img/avatar.png```这样的图片，在本地文件夹可以找到该图片的路径（\public\img）。

但如果想在该文件夹里增加更多图片，就会在上传的时候被覆盖。

指南中提到，这种图片应该在/source/img里，但是该文件夹一开始只有/_posts和/about，新建/img文件夹之后无法使用。

不仅如此，所有post里都无法使用本地图，只能通过图床来放图。

麻烦各位大佬教教我怎么搞/kel

**Comment by zkqiang** [comment]
没明白 “上传的时候被覆盖” 是什么意思，可以尝试把图片改成别的名字然后配置里指定

“所有post里都无法使用本地图”  还是因为 post 里指定的图片路径不对，可以跟生成后的 public 文件里对比确认一下

**Comment by shmilyty** [comment]
很抱歉我的叙述不是很清楚

我重新试了一下，上述问题似乎解决了，可能和我的文件名有关

还想请教一下如何修改标签页上的图标，比如
![image](https://user-images.githubusercontent.com/61276699/158022978-d1eaf9b1-7a0e-4dd4-921f-f0f74c0f8c97.png)

在哪里可以更改这个设置

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/1d524d06af1571aca4a27b3f8efed5604cd24eaf/_config.yml#L19-L21

**Comment by shmilyty** [comment]
好欸，麻烦您了
