### ISSUE TITLE
1.8.13版本配置改变(弃用)未在release notes中说明

### ISSUE THREAD

**Issue by VisionTheta** [fluid-dev/hexo-theme-fluid#679]
严格讲这并不是一个bug, 而是在release notes中未对修改(弃用?)的配置项进行说明。

问题发现步骤：

1. 主题版本从1.8.11更新到1.8.14后(npm update --save hexo-theme-fluid)，生成静态网页后，关于页的社交图标在光标悬浮的情况下不会出现hint / tip
2. 发现是/lib/hint.min.css请求404. 回滚主题到1.8.11后，对比发现，1.8.11版本中该文件在source/lib/hint.min.css，但是在1.8.13版本中该文件被移除（实际上是commit 00cd81c更新了hint.css版本）

因为本人Web开发经验几乎为零，上面操作是乱试出来，请见谅。因为在主题网站看到升级方式就是运行npm update命令，然后翻看release notes中也没有标明有breaking changes，所以一开始就没有怀疑主题的问题。

感谢作者为我们带来这么棒的主题，给您提个小建议。如果主题更新后有breaking changes, 可以在release中提醒用户对应的修改配置文件。

最后请教一个小白问题，更新主题后，package.json和package-lock.json中的这部分配置"hexo-theme-fluid": "^1.8.11",的版本要手动修改成1.8.14吗？

```json
"name": "hexo-site",
  "version": "0.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "hexo-site",
      "version": "0.0.0",
      "dependencies": {
        "hexo": "^5.0.0",
        "hexo-generator-archive": "^1.0.0",
        "hexo-generator-category": "^1.0.0",
        "hexo-generator-index": "^2.0.0",
        "hexo-generator-sitemap": "^2.1.0",
        "hexo-generator-tag": "^1.0.0",
        "hexo-renderer-ejs": "^1.0.0",
        "hexo-renderer-marked": "^4.0.0",
        "hexo-renderer-stylus": "^2.0.0",
        "hexo-server": "^2.0.0",
        "hexo-theme-fluid": "^1.8.11",
        "hexo-theme-landscape": "^0.0.3"
      }
    },
```

**Comment by zkqiang** [comment]
1.8.14 里的 hint 改成了使用 CDN 

https://github.com/fluid-dev/hexo-theme-fluid/blob/1d524d06af1571aca4a27b3f8efed5604cd24eaf/_config.yml#L1015

确实我忘记在 breaking change 里写了

`"hexo-theme-fluid": "^1.8.11"` 里 `^` 代表 `1.x.x` 最新版本，所以可以不改，改的话只改 `package.json` 即可

**Comment by VisionTheta** [comment]
hint这个我已经对比发现了要改。

这个^(caret symbol)的作用学到了，谢谢谢谢！

如果您没有其他问题，这个issue可以关闭了
