### ISSUE TITLE
字体大小调整

### ISSUE THREAD

**Issue by Young-Flash** [fluid-dev/hexo-theme-fluid#681]
能够调整字体大小？感觉默认的略小

**Comment by zkqiang** [comment]
请阅读用户文档

https://hexo.fluid-dev.com/docs/guide/#%E5%85%A8%E5%B1%80%E5%AD%97%E4%BD%93

**Comment by Young-Flash** [comment]
实现了，感谢！！在文档中搜索 "字号" 没找到还以为没有
