### ISSUE TITLE
怎么去掉An elegant Material-Design theme for Hexo这一行字啊

### ISSUE THREAD

**Issue by Sadfish0** [fluid-dev/hexo-theme-fluid#683]
![image](https://user-images.githubusercontent.com/101093506/158608845-270a13d1-68ea-4756-ab99-5fd91a30f82d.png)

**Comment by zkqiang** [comment]
请阅读用户文档：

https://hexo.fluid-dev.com/docs/guide/#slogan-%E6%89%93%E5%AD%97%E6%9C%BA
