### ISSUE TITLE
分类页层级无法自动展开

### ISSUE THREAD

**Issue by Deeperand** [fluid-dev/hexo-theme-fluid#684]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

设置分类页 `collapse_depth: 1` 后, 分类页层级无法正常自动展开, 如

<img width="911" alt="Screen Shot 2022-03-18 at 11 33 20" src="https://user-images.githubusercontent.com/42906615/158933342-5d4036c0-2176-4817-ad8d-2d89f822393d.png">

期望的结果为

<img width="911" alt="Screen Shot 2022-03-18 at 11 33 42" src="https://user-images.githubusercontent.com/42906615/158933352-86cf6284-e385-40de-afb0-f3f54f29e262.png">

**Comment by zkqiang** [comment]
dev 分支已修复
