### ISSUE TITLE
关于文章点击图片不会放大

### ISSUE THREAD

**Issue by 444783764** [fluid-dev/hexo-theme-fluid#685]
我文章文章点击图片没效果不像别人fluid一样会放大显示，我按教程也把配置文件的image_zoom:开启了还是没效果，不知道是bug冲突还是怎么样，我也网上找不到别的教程，又不敢重新安装主题因为重新安装要改回去要很久而且有些地方都忘
![QQ截图20220319153202](https://user-images.githubusercontent.com/93808587/159112106-426933ac-d6ad-497e-9f69-c7e9462be64e.png)
了

**Comment by zkqiang** [comment]
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/32983588/159148324-0accda13-dd1e-4480-a697-c9b44d335cda.png">

经我测试正常，请检查是不是你本地的缓存

**Comment by 444783764** [comment]
这就奇怪了，我清除缓存了也不行我让别人试过他说也点击没效果

**Comment by zkqiang** [comment]
缓存问题我无法帮忙解决
