### ISSUE TITLE
一个小bug

### ISSUE THREAD

**Issue by arleycn** [fluid-dev/hexo-theme-fluid#688]
#### 请确认
- [✓] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [✓] 浏览器不属于 IE 等非主流浏览器 
- [✓] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [✓] 已经排除是其他 Hexo 插件影响

#### Bug 描述

任意界面点击`搜索`，弹窗同时`顶部导航栏`由于右侧`滚动条消失`导致抖动
#### 复现步骤
该 Bug 复现步骤如下：
1. 在 任意 页面点击 搜索 按钮
2. 顶部导航栏 抖动

网址：[Arley](https://blog.arley.cn/)

#### 截图
https://cdn.jsdelivr.net/gh/arleycn/cdn@master/pic/fluid_bug.gif

**Comment by zkqiang** [comment]
#499 已知问题，待解决
