### ISSUE TITLE
怎么让表格整体居中

### ISSUE THREAD

**Issue by EastMonster** [fluid-dev/hexo-theme-fluid#689]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
Markdown 表格似乎是强制居左的，自定义 CSS 也没用，要怎么让它居中呢？居左看着好奇怪。
![](https://s2.loli.net/2022/03/21/yuws8USjM9rbhBK.png)

**Comment by zkqiang** [comment]
这个要看 renderer 有没有实现相关语法
