### ISSUE TITLE
Gitalk评论区输入界面与Grammaly类插件冲突

### ISSUE THREAD

**Issue by TommyZeng777** [fluid-dev/hexo-theme-fluid#690]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

很好复现，这是个语病自动纠察的插件，valine的评论区不会有这个bug，但再gitalk里一输入然后这个插件检测输入内容时会把输入框的选中输入状态弹出，导致无法输入，必须反复点击输入框

#### 复现步骤
该 Bug 复现步骤如下：
1. 配置好评论区gitalk并打开评论区
2. 再grammarly插件启用的情况下输入即复现
3. 禁用插件后就没这个问题了，不过插件用途比较广泛，希望能修复一下

#### 截图
因为这个bug不是界面性质的bug，所以截图看不出来

**Comment by lingan1996** [comment]
遇到同样的问题

**Comment by zkqiang** [comment]
这个问题，你应该提到 gitalk 的 issues，主题只是引用...

**Comment by TommyZeng777** [comment]
> 这个问题，我觉得你应该提到 gitalk 的 issues，主题只是引用...
> 
> 当然如果你在 gitalk demo 里不能复现，我会继续追踪这个问题

你说得对，提交bug提交错地方了，新人经验不足，您多多包涵哈哈

**Comment by zkqiang** [comment]
那我先关闭，如果只是主题这边能复现，可以重新打开后反馈
