### ISSUE TITLE
表格异常

### ISSUE THREAD

**Issue by Lostiz** [fluid-dev/hexo-theme-fluid#694]
在v1.9.0-beta.6中，如图
![code](https://user-images.githubusercontent.com/99953892/160969526-360ee11d-bd00-4793-a1e7-ff563513ffcc.jpg)
![页面显示](https://user-images.githubusercontent.com/99953892/160969530-a20040d3-ab39-4b81-9aaf-e6039fff0f37.jpg)

**Comment by zkqiang** [comment]
能否提供一个可以复现的链接？

**Comment by Lostiz** [comment]
https://s12h.top/表格
![版本](https://user-images.githubusercontent.com/99953892/161369112-491bb3fe-f2b7-45d8-b432-1bd5721dbec7.jpg)
![代码coonfig](https://user-images.githubusercontent.com/99953892/161369118-4097e8c2-f07a-491a-bf99-6780b2823e3a.jpg)
代码框也有问题

**Comment by zkqiang** [comment]
自定义页面正文默认没有 Markdown 样式，如果希望和文章相同的样式，可以加上

```html
<div class="markdown-body">
正文
</div>
```
