### ISSUE TITLE
page 页面无法渲染 latex

### ISSUE THREAD

**Issue by Cat-shao** [fluid-dev/hexo-theme-fluid#695]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

任何一个 page 页面都无法正常 latex ，无论是 mathjax 还是 katex 。

#### 复现步骤

fluid 主题的配置文件：

![Snipaste_2022-04-03_22-57-43](https://user-images.githubusercontent.com/55950034/161434076-e2adafc2-e97e-4553-822c-bc45c356db02.png)

```
hexo new page test
```

并在 test/index.md 中写入 `$\sum_{i = 1}^N a_i$`

hexo s ，到 test 页面中发现压根就没渲染：

![Snipaste_2022-04-03_22-59-01](https://user-images.githubusercontent.com/55950034/161434187-4d8f7b73-e668-453d-b783-0e2031d3b554.png)

插件只装了一个：hexo-auto-category 。

博客没有部署到网上，无法给出没渲染页面的链接。

F12 ，在这个页面对应 html 中找不到 `mathjax` 或是 `latex` 的字眼。
![Snipaste_2022-04-03_23-02-49](https://user-images.githubusercontent.com/55950034/161434307-75c42d2c-5e93-4295-b610-767322a72252.png)

望修复，谢谢

**Comment by zkqiang** [comment]
![Uploading image.png…]()

**Comment by Cat-shao** [comment]
> <img alt="image" width="576" src="https://user-images.githubusercontent.com/32983588/161891022-7af37ea0-2af7-48e7-9881-132f7cf501bc.png">

还是不好用啊。

这次以 about 页为例

![image](https://user-images.githubusercontent.com/55950034/164885168-925a196b-ab90-4c55-940a-d1de01c2b7d4.png)

![image](https://user-images.githubusercontent.com/55950034/164885190-3be55ba6-7302-4b21-ae16-585385978b2b.png)

您那边能复现吗？

**Comment by Cat-shao** [comment]
@zkqiang 见上。
