### ISSUE TITLE
请求加入背景音乐

### ISSUE THREAD

**Issue by shmilyty** [fluid-dev/hexo-theme-fluid#697]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

想在 fluid 里加入音乐类型的插件，支持小窗口
#### 请描述您认为可行的解决方案

利用现有的 hexo 音乐插件，使得与本主题更适配
#### 考虑过的替代方案

我目前用的是 [hexo-aplayer](https://github.com/MoePlayer/hexo-tag-aplayer)，但是这个插件有以下两个小问题：
- 只能通过在文章中插入代码的方式添加音乐：
在一篇文章中插入如下代码后
![image](https://user-images.githubusercontent.com/61276699/161489313-72d2a533-0359-4cc1-9971-7f6a1091d422.png)
会在该文章中**独立**显示
![image](https://user-images.githubusercontent.com/61276699/161488926-ebae2324-3e8f-421d-9124-345a69dfab9e.png)
但是我希望这个歌单在所有文章能同时使用，目前只能这段代码复制到所有文章里去，这样做在主页一类的地方就无法使用。
- 另一个问题相对次要，该插件和比较常用的“显示博客运行时间”功能不兼容，问题应该是 `duration.js` 里会被该插件加入代码。
希望能将所有页面左下角的部分定为“背景音乐”，并且可以做到所有页面同步.

**Comment by zkqiang** [comment]
Duplicate #578 #543 #375
