### ISSUE TITLE
页面配置了建站时间后，访问统计不能正常显示出来

### ISSUE THREAD

**Issue by nieweixing** [fluid-dev/hexo-theme-fluid#698]
#### Make sure
- [ ] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases).
- [ ] Browser does not belong to IE and other old browsers
- [ ] It can be replicated through `hexo clean && hexo s` and cleared browser cache in the localhost.
- [ ] Not affected by other Hexo plugins

#### To Reproduce
1. Go to '...', click on '....'
2. Scroll down to '....'
3. See error

**Comment by zkqiang** [comment]
建站时间输入自定义功能，请自行检查代码是否正确

**Comment by nieweixing** [comment]
已经显示正常了
