### ISSUE TITLE
如何使用 Hexo 注入器

### ISSUE THREAD

**Issue by shmilyty** [fluid-dev/hexo-theme-fluid#700]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

hexo版本：6.0
![image](https://user-images.githubusercontent.com/61276699/161963444-3c929e03-2549-4440-b74a-7d55291a0580.png)
我对着 [这个](https://hexo.fluid-dev.com/posts/hexo-injector/#aplayer-%E9%9F%B3%E4%B9%90%E6%92%AD%E6%94%BE%E5%99%A8) 进行的配置，本地文件如下：

![image](https://user-images.githubusercontent.com/61276699/161963554-e6e1b989-1b54-4618-bd3b-999be9eb7a2e.png)

![image](https://user-images.githubusercontent.com/61276699/161963590-02be8ee3-310e-43f2-976e-b41bb2db90e2.png)

hexo clean + g + s 后，并没有出现希望的 aplayer ，页面如下：
![image](https://user-images.githubusercontent.com/61276699/161963919-8945d5c0-0bc0-4bd0-9105-118d1e3d6216.png)

**Comment by zkqiang** [comment]
看一下是否为 `hexo.extend.injector.register` 这部分代码的问题呢？

再看下浏览器控制台具体的报错

**Comment by shmilyty** [comment]
大概找到了问题，但是不是很会解决
![image](https://user-images.githubusercontent.com/61276699/162177454-9d76b6c9-8ade-43a9-8275-e949ca58314f.png)
应该是aplayer.js的问题，该文件在hexo g编译后会变成这样
![image](https://user-images.githubusercontent.com/61276699/162177682-8a59b8cf-3883-4db0-8c78-69e222dec42f.png)
~~似乎开头多了点东西~~
我在/public/js找到了这个修改后的文件，但是修改这个文件没有任何用
应该怎么办呢/kel

**Comment by zkqiang** [comment]
还是写的有问题

不要去修改 public 里的，那是 hexo g 生成的文件

**Comment by shmilyty** [comment]
解决了，我似乎是通过 `skip_render` 跳过 `aplayer.js` 的渲染来完成的
