### ISSUE TITLE
如何引入动画效果js？

### ISSUE THREAD

**Issue by 2w1nd** [fluid-dev/hexo-theme-fluid#704]
#### 请确认
- [ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

我想引入https://github.com/VincentGarreau/particles.js
在config.js设置了
```
custom_js: /js/particles.js
```
但没有生效，我还需要加什么配置吗？

**Comment by zkqiang** [comment]
似乎是你缺少 `<div id="particles-js"></div>`

另外建议用 https://hexo.fluid-dev.com/posts/hexo-injector/

**Comment by 2w1nd** [comment]
我在`fluid\scripts`下新建了`injector.js`并填入以下代码，还是没有生效
```
hexo.extend.injector.register('body_begin', `
  <div id="particles-js"></div>
`);
```

**Comment by zkqiang** [comment]
建议你先通过控制台判断是什么问题

**Comment by 2w1nd** [comment]
嗯感觉应该是这个js的问题。js和div都已经加载但还是没有显示
![image](https://user-images.githubusercontent.com/64266855/162745049-fd73f30e-fc49-4786-86bd-4a14ea8e4bce.png)

**Comment by zkqiang** [comment]
但是你要看下 `<script src="/js/particles.js"` 在网络里实际有请求吗

**Comment by 2w1nd** [comment]
如果是指是否请求到js的话，是请求到的
![image](https://user-images.githubusercontent.com/64266855/162753580-43f5629c-e490-40b3-b62d-098e55d38fa8.png)

**Comment by zkqiang** [comment]
没用过这个，还是要你自己研究下

**Comment by 2w1nd** [comment]
好的。
