### ISSUE TITLE
请问这个主题有html静态文件那种版本吗

### ISSUE THREAD

**Issue by java-aodeng** [fluid-dev/hexo-theme-fluid#705]
#### 请确认
- [ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

**Comment by zkqiang** [comment]
没明白你什么意思，Hexo 本身生成的就是静态文件

**Comment by java-aodeng** [comment]
没事没事，我就是想不用hexo使用这个主题哎

**Comment by zkqiang** [comment]
本主题就是基于 Hexo 的，不能脱离 Hexo 使用
