### ISSUE TITLE
侧边栏展示当前分类下的文章功能 支持目录子项

### ISSUE THREAD

**Issue by M0cK1nG-b1Rd** [fluid-dev/hexo-theme-fluid#707]
#### 如是功能需求，请确定符合以下情况
- [ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [ ] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

版本：`1.9.0-beta.6`

开发大大好，似乎现在`category_bar`的配置项不能定义子项？

比如我的某篇文章的 Front-matter 是这样指定的
```
category_bar: ['Web']
categories:
  - Web
  - 靶场
  - HackTheBox
```
category_bar项只有配置成true或者['Web']的时候才生效，我想只显示子项如`靶场`和`HackTheBox`可以吗，我尝试过配置成`category_bar: ['HackTheBox']`，但没有效果，是我的配置问题还是目前还不支持这个特性呢

**Comment by zkqiang** [comment]
确实现在没覆盖这种情况，后续会再更新一次
