### ISSUE TITLE
支持便捷地设置遵从 Do Not Track

### ISSUE THREAD

**Issue by jiesou** [fluid-dev/hexo-theme-fluid#710]
#### 如是功能需求，请确定符合以下情况
- [ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

支持在主题配置中便捷地启用遵从 DNT 即 Do Not Track 或者 “不跟踪”
这可以让用户决定是否被百度统计等统计模块跟踪
<https://www.w3.org/TR/tracking-dnt>

#### 请描述您认为可行的解决方案

例如添加一个 web_analytics.follow_dnt 的配置来设置是否遵从 DNT
只需要将所有统计模块放在同一处 `<script>` 然后在加载统计模块前加一个判断，例如：

```JavaScript
let dnt = navigator.doNotTrack || window.doNotTrack || navigator.msDoNotTrack;
if (!dnt.startsWith('1') && !dnt.startsWith('yes') && !dnt.startsWith('on')) {
...
}
```

#### 考虑过的替代方案

虽然可以比较简单地通过自定义、注入之类的功能实现，但如果能直接添加一个配置就支持，那会让网站方支持 DNT 的门槛降低很多

**Comment by zkqiang** [comment]
感谢建议，dev已实现
