### ISSUE TITLE
图片描述可以关闭吗 我没有在用户手册中找到相关选项

### ISSUE THREAD

**Issue by howie-wu** [fluid-dev/hexo-theme-fluid#713]
![image](https://user-images.githubusercontent.com/98788152/164737210-e4bcc0ce-9c5d-4380-9b0a-2e8688adc1de.png)
出现了这样的问题

**Comment by zkqiang** [comment]
最新的 [1.9.0-beta](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.9.0-beta.6) 支持这个选项
