### ISSUE TITLE
highlightjs代码高亮无法使用”base16/xxx”的样式

### ISSUE THREAD

**Issue by Zongjy** [fluid-dev/hexo-theme-fluid#714]
#### 请确认
- [√] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [√] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

在设置highlightjs进行代码高亮时，想要使用base16子目录下的css样式，但是貌似css.ejs转义那里不对（只是猜测，我没有任何js基础），导致无法正常配置，代码块部分是白的（基础样式？）请问有什么解决办法吗，还是说我使用方式不对（汗）
这是_config.yml里的内容
```    
highlightjs:
      # 在链接中挑选 style 填入
      # Select a style in the link
      # See: https://highlightjs.org/static/demo/
      style: "base16/dark-violet"
```
谢谢帮助！

**Comment by zkqiang** [comment]
可以试试最新 [1.9.0-beta](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.9.0-beta.6)
