### ISSUE TITLE
comment: bool报错

### ISSUE THREAD

**Issue by lzhvahaha** [fluid-dev/hexo-theme-fluid#715]
#### 问题描述
某一个文章添加comment: bool或不添加任何语句，都打不开
只有添加comment: ’Valine'才能打开

**Comment by zkqiang** [comment]
`comment: bool` 指的是 `comment: true` 或者 `comment: false`

**Comment by lzhvahaha** [comment]
谢谢您谢谢您



在 2022-04-24 11:41:17，"张凯强" ***@***.***> 写道：

comment: bool 指的是 comment: true 或者 comment: false
