### ISSUE TITLE
leancloud国际版无法自定义server_url

### ISSUE THREAD

**Issue by InkyTea** [fluid-dev/hexo-theme-fluid#716]
![新建位图图像](https://user-images.githubusercontent.com/71004263/164971645-de9105af-1de7-4d7a-835d-d4294cb06e3b.png)

我希望国际版优先使用自己定义的服务器地址
因为DNS问题，部分用户无法访问国际版服务器地址
我想自己反向代理服务器地址

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/1d524d06af1571aca4a27b3f8efed5604cd24eaf/_config.yml#L259-L261

**Comment by InkyTea** [comment]
> server_url:

国际版会根据app_id自动构建server_url
但是我想使用自己定义的

**Comment by InkyTea** [comment]
> https://github.com/fluid-dev/hexo-theme-fluid/blob/1d524d06af1571aca4a27b3f8efed5604cd24eaf/_config.yml#L259-L261

国际版这个参数无效，会优先自己构建

**Comment by zkqiang** [comment]
之前国际版的 AppID 是 `-MdYXbMMI` 结尾，所以通过这个来判断了

现在不一样了吗？

**Comment by zkqiang** [comment]
是我的错，你可以先把那行代码改为：

```
var apiServer = serverUrl || `https://${appId.slice(0, 8).toLowerCase()}.api.lncldglobal.com`;
```
