### ISSUE TITLE
浏览器标签页位Hexo

### ISSUE THREAD

**Issue by RatedR9** [fluid-dev/hexo-theme-fluid#717]
已修改navbar
  
  blog_title: "Fluid"
但浏览器标签页标题仍为Hexo
![image](https://user-images.githubusercontent.com/62322670/164975126-ee28ad3a-b138-489a-9290-ec7e12bff50a.png)

**Comment by zkqiang** [comment]
https://hexo.io/zh-cn/docs/configuration#%E7%BD%91%E7%AB%99
