### ISSUE TITLE
highlightjs,prismjs均无法无法实现vue代码高亮

### ISSUE THREAD

**Issue by superBiuBiuMan** [fluid-dev/hexo-theme-fluid#722]
#### 请确认
- [ √] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [  √ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
谷歌浏览器,使用highlightjs,prismjs均无法无法实现vue代码高亮 ,typora可以正常高亮显示

![](https://dreamos.oss-cn-beijing.aliyuncs.com/gitblog/202205062026970.png)

**Comment by zkqiang** [comment]
高亮问题请到 highlightjs 或 prismjs 的 issues 区寻求帮助
