### ISSUE TITLE
支持 Waline 2.x

### ISSUE THREAD

**Issue by MSDNicrosoft** [fluid-dev/hexo-theme-fluid#723]
当前 Waline 已更新至 2.x 版本，与 1.x 相比，差异较大

建议根据官方的文档进行适配
https://waline.js.org

**Comment by jiesou** [comment]
```yml
static_prefix:
  waline: https://lib.baomitu.com/waline/latest/
```

这样设置静态资源就行了吧，没啥要单独适配的吧

**Comment by MSDNicrosoft** [comment]
> ```yaml
> static_prefix:
>   waline: https://lib.baomitu.com/waline/latest/
> ```
> 
> 这样设置静态资源就行了吧，没啥要单独适配的吧

有 API 的更改、弃用和 CSS 类的更名

**Comment by MSDNicrosoft** [comment]
@zkqiang Waline 更新到 2.x 后无法使用，控制台提示：
![image](https://user-images.githubusercontent.com/69967436/168306427-c13cb62f-0d2a-43b2-a430-954ebfecf944.png)

而且：
- Waline 在 2.x 提供了多种版本的客户端文件
- Waline 在 2.x 将 **W**aline.*.js 改成了 **w**aline.*.js

详见：
- <https://waline.js.org/guide/client/import.html#%E5%BC%95%E5%85%A5>
- <https://waline.js.org/migration/client.html>

**Comment by MSDNicrosoft** [comment]
在 `layout/_partials/comments/waline.ejs`[Line 13] 中将 `new Waline(options);` 改成 `new Waline.init(options);` 没有任何作用

**Comment by loststar** [comment]
同样遇到了这个问题，插个眼看没有解决方案

**Comment by lixiangang2** [comment]
将`new Waline(options);`改成`Waline.init(options);`，同时修改`waline.ejs`文件中对应部分的为`Fluid.utils.createCssLink('<%= url_join(theme.static_prefix.waline, 'waline.css') %>')
      Fluid.utils.createScript('<%= url_join(theme.static_prefix.waline, 'waline.js') %>', function() {`好像就可以了，今天试了试，可以实现功能。

**Comment by zkqiang** [comment]
dev 已更新

**Comment by MSDNicrosoft** [comment]
> dev 已更新

好的，感谢
