### ISSUE TITLE
主题对 Waline 最新样式适配错误

### ISSUE THREAD

**Issue by jiesou** [fluid-dev/hexo-theme-fluid#724]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

#### 问题描述

我使用主题自带的 Waline 评论时注意到当 Waline 主题色为彩色时，提交按钮上黑色的文字显得很不协调：

![Screenshot_2022-05-10-17-28-41-016-edit_com.mmbox.xbrowser.pro.jpg](https://user-images.githubusercontent.com/84175239/167597851-29614c47-9186-459b-8127-b086e2b7d2b2.jpg)

并且在 Waline 的示例上不是这样：

![Screenshot_2022-05-10-17-40-33-818-edit_com.mmbox.xbrowser.pro.jpg](https://user-images.githubusercontent.com/84175239/167599342-12d13fb4-10f6-430a-b5c9-666c6f610f92.jpg)

经过一番查找我找到了原因，在[此处](https://github.com/fluid-dev/hexo-theme-fluid/blob/develop/source/css/_pages/_post/comment.styl#L3-L4)，主题将 V/Waline 的 .vbtn color 全部设为了主题的 --text-color

虽然这能更方便地统一配色，但在某些情况下这看上去很糟糕

#### 考虑过的替代方案

我试着用自定义 CSS 来修改颜色

```css 
button.vbtn.primary{
  --text-color: #fff;
}
```

但这又会导致在评论提交时按钮的加载圈颜色异常

![Screenshot_2022-05-10-17-27-55-918-edit_com.mmbox.xbrowser.pro.jpg](https://user-images.githubusercontent.com/84175239/167600028-9d05acda-015e-4991-8342-b9cff498e62b.jpg)

正常情况下它应该是这样的

![Screenshot_2022-05-10-17-26-32-215-edit_com.mmbox.xbrowser.pro.jpg](https://user-images.githubusercontent.com/84175239/167600090-fd63aa25-e6a1-449a-a230-71c699479b85.jpg)

这应该是因为主题的 `!important`

#### 请描述您认为可行的解决方案

希望主题能提供一个配置项，设置是否让主题介入评论系统的样式

**Comment by zkqiang** [comment]
可以用更高优先级的 CSS !important 修改回去，后续我再修复下这个问题

**Comment by jiesou** [comment]
手动修改回去也会导致加载圈的颜色异常

**Comment by zkqiang** [comment]
那我后续再跟踪下这个问题，之前的 CSS 是针对 v1 的修改

**Comment by zkqiang** [comment]
dev 已更新
