### ISSUE TITLE
在 Edge 浏览器开启侧边标签页时，返回顶部按钮位置不当

### ISSUE THREAD

**Issue by KiyanYang** [fluid-dev/hexo-theme-fluid#730]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

使用 Edge 浏览器，开启侧边标签页，打开使用该主题的网页，可以看到 返回顶部 按钮的位置不当。

#### 复现步骤
该 Bug 复现步骤如下：
1. 打开 Edge 浏览器，并启用侧边标签栏。
2. 打开博客网页可以看到看到 返回顶部 按钮的位置不当。
3. 复现地址：[官网](https://hexo.fluid-dev.com/)。

#### 截图

<img width="960" alt="i1" src="https://user-images.githubusercontent.com/50903774/168428861-6e60aa55-a991-44d0-9f68-523ba6395bdd.png">
<img width="960" alt="i2" src="https://user-images.githubusercontent.com/50903774/168428865-9fe5d0c5-0d2a-4cc8-a5d4-6a31ea38e7be.png">

**Comment by arkerny** [comment]
我这儿在特定页面宽度下才会有这个问题，基本不影响使用，您是不是可以更改分辨率以及更换设备试试？
