### ISSUE TITLE
访问量数据问题

### ISSUE THREAD

**Issue by JackeyLea** [fluid-dev/hexo-theme-fluid#736]
Firefox更新到100之后，访问量数据变得异常了
![2022-05-16_23-00](https://user-images.githubusercontent.com/22772053/168623307-aeb982ec-1f86-45ba-91b7-396416a71e94.png)

但是chrome系没有问题

![2022-05-16_23-04](https://user-images.githubusercontent.com/22772053/168623996-d60b3c07-a3de-41dc-afba-43986436b3c2.png)

是主题需要适配还是浏览器问题

**Comment by zkqiang** [comment]
可以[注入](https://hexo.fluid-dev.com/docs/advance/#hexo-%E6%B3%A8%E5%85%A5%E4%BB%A3%E7%A0%81) `<meta name="referrer" content="no-referrer-when-downgrade">`

但也只能解决部分浏览器

归根结底还是 busuanzi 没有更新了，建议使用 leancloud
