### ISSUE TITLE
格式询问

### ISSUE THREAD

**Issue by felixchen0707** [fluid-dev/hexo-theme-fluid#737]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
![image](https://user-images.githubusercontent.com/99467198/168631856-db6a34f4-8c0b-4a41-a6ec-cd870589e67b.png)
hexo init之后在 theme文件夹下使用git clone 克隆主题，hexo s 预览后格式出现问题

**Comment by Away30** [comment]
我也是啊，出了什么问题

**Comment by felixchen0707** [comment]
你的错乱界面也和我一样吗？！！

**Comment by Away30** [comment]
是的，看起来好多人都遇到这个问题了

**Comment by felixchen0707** [comment]
今天修改config的时候突然就碰到了这个 已一直捣鼓到现在了 要是大家都有这个问题我就要睡了 困死了

**Comment by zkqiang** [comment]
@felixchen0707 @Away30 
是因为 jsdelivrCDN 无法访问导致，请参照 https://github.com/fluid-dev/hexo-theme-fluid/issues/656
