### ISSUE TITLE
小白有问题

### ISSUE THREAD

**Issue by felixchen0707** [fluid-dev/hexo-theme-fluid#738]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
小白发问：用户指南中插入数学公式第三部分pandoc下载的详细过程是什么谢谢谢谢谢

**Comment by zkqiang** [comment]
文档里已经给出 pandoc 官方文档的[链接](https://github.com/jgm/pandoc/blob/master/INSTALL.md)了，请根据里面的步骤进行安装，也可以在中文网站里搜索其他人的总结
