### ISSUE TITLE
直接输入网站域名打开后显示不安全

### ISSUE THREAD

**Issue by adrianmiao** [fluid-dev/hexo-theme-fluid#739]
大佬们，为什么我换了fluid后，直接输入域名会显示不安全啊，但是如果打上https://+域名就没事，我上一个主题没出现这个情况。求解。

**Comment by zkqiang** [comment]
这个跟主题没关系...

直接输入域名可能是你浏览器记录了你 http:// 的链接

可以设置“强制跳转https”

**Comment by adrianmiao** [comment]
好的，谢谢
