### ISSUE TITLE
关于项目转移 About project transfer

### ISSUE THREAD

**Issue by 0x2E** [fluid-dev/hexo-theme-fluid#74]
大家好，我是 Material-T 主题的发起人。Material-T 自 2018 年 10 月 15 日第一次 commit 以来，经过了长时间的优化与迭代，非常感谢大家这一年来的贡献与支持。

现在已有许多热情的开发者参与到项目中（特别致谢 @zkqiang），我想是时候将 Material-T 彻底交给社区了，于是我们发起了 [Fluid-dev 组织](https://github.com/fluid-dev) 并将 Material-T 转入其中，更名为 [hexo-theme-fluid](https://github.com/fluid-dev/hexo-theme-fluid)。以后关于主题、插件、文档等相关项目都会由 Fluid-dev 组织推动，对于更名和项目转移带来的不便我深感抱歉。
 
未来我们将继续为大家提供优质的项目，也欢迎热情、富有创造力的开发者加入我们 😄 

-----

Hello everyone, I am the initiator of the Material-T theme. Since the first commit of Material-T on October 15, 2018, after a long period of optimization and iteration, I am very grateful for your contribution and support over the past year.

There are already many enthusiastic developers involved in the project (especially thanks to @zkqiang), I think it is time to give Material-T to the community, so we launched the [Fluid-dev organization](https://github.com/fluid-dev) and transferred Material-T Into it, renamed to [hexo-theme-fluid](https://github.com/fluid-dev/hexo-theme-fluid). In the future, related topics, plug-ins, documentation and other related projects will be promoted by the Fluid-dev organization. I am sorry for the inconvenience caused by the change of name and project transfer.
 
In the future, we will continue to provide quality projects for everyone, and we welcome enthusiastic and creative developers to join us.  😄

**Comment by zkqiang** [comment]
如打算升级 v1.4.0，建议按如下操作：
1. 将 release 包解压后重命名为 fluid （使用 master 分支建议重新 clone）
2. 将博客根目录 _config.yml 配置修改 theme: fluid
3. 将原 Material-T 目录的 _config.yml 覆盖过来（可不修改内容)；或者参见「[关于配置 Config](https://github.com/fluid-dev/hexo-theme-fluid#%E5%85%B3%E4%BA%8E%E9%85%8D%E7%BD%AE-config)」中配置的新功能。

---

If you want to upgrade v1.4.0,  it is recommended to do:

1. Unzip [v1.4.0 release](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.4.0) and rename the directory to "`fluid`"
2. Find `_config.yml` of your blog root, then modify configuration: `theme: fluid`
3. Copy `_config.yml` of Material-T directory to replace the one of fluid (No need to modify the configurations)
