### ISSUE TITLE
CDN上静态资源访问不到

### ISSUE THREAD

**Issue by paulo-t** [fluid-dev/hexo-theme-fluid#740]
cdn上的静态资源访问不到，请问是这些资源过期了么
![image](https://user-images.githubusercontent.com/30173528/168946658-519bc1ae-1b5b-41aa-b90f-337548b30b18.png)

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/issues/656

**Comment by paulo-t** [comment]
问题已解决，谢谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fluid-dev/hexo-theme-fluid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 上午10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fluid-dev/hexo-theme-fluid] CDN上静态资源访问不到 (Issue #740)





 
#656
