### ISSUE TITLE
设置Mathjax渲染模式

### ISSUE THREAD

**Issue by YSXCC** [fluid-dev/hexo-theme-fluid#749]
当我升级了hexo和fluid版本后, Mathjax默认采用了CHTML渲染.

希望能够在配置文件中主动设置渲染模式.

**Comment by YSXCC** [comment]
暂时设置Mathjax默认渲染为 svg 的方法就是在 ..\hexo-theme-fluid\layout\_partials\plugins\math.js中修改'es5/tex-mml-chtml.js'为'es5/tex-svg.js'

**Comment by hewei2001** [comment]
我也遇到了同样的问题，我是修改为 `es5/tex-svg-full.js` 解决的

**Comment by ZermZhang** [comment]
_config.fluid.yml配置文件中，增加如下配置可以使Mathjax默认渲染方式为svg：
这里好像没有名为tex-mml-chtml.js的脚本[😂](https://emojipedia.org/face-with-tears-of-joy/)
```yml
static_prefix:
  mathjax: https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.1/
```

**Comment by YSXCC** [comment]
是 Mathjax 版本问题, 3.2.0版本会出现默认 CHTML 渲染, 切换至 3.2.1就没问题了. 感谢！
