### ISSUE TITLE
关于覆盖配置的一点点问题

### ISSUE THREAD

**Issue by huaxianyan** [fluid-dev/hexo-theme-fluid#75]
首先恭喜本项目又步入了一个新时代，下面说正题。

在看到新的 released 时我赶紧更新了一下，但是在尝试覆盖设置的时候发现了点问题，就是关于导航栏的配置文件。

为了使其中文化，我做了一些修改，配置如下：
```
navbar:
  blog_title:  # 导航栏左侧的标题，为空则按 hexo config.title 显示
  menu:
    主页: /
    归档: /archives/
#    Categories: /categories/
    标签: /tags/
    关于: /about/
```

但发现会和原来的配置共存，这样导航栏就会显示默认的英文以及覆盖过去的中文。目前的做法是修改了主题目录下的配置文件。

但是这块的覆盖逻辑，可能需要再思考一下如何实现。

**Comment by zkqiang** [comment]
正巧昨晚我也发现此问题，所以更新了 develop 代码，你可以把 [nav.ejs](https://github.com/fluid-dev/hexo-theme-fluid/blob/develop/layout/_partial/nav.ejs) 内容先复制到本地先使用

**Comment by huaxianyan** [comment]
@zkqiang 好的

**Comment by huaxianyan** [comment]
@zkqiang 另外 about 页面还是在主题文件夹内的，这块有没有考虑下做覆盖配置？虽然主题更新的时候可以跳过该文件夹，但是用 git 来更新的话本地与远程不同会比较麻烦

**Comment by zkqiang** [comment]
@huaxianyan 记录下来了，后续更新
