### ISSUE TITLE
版权自定义文本的保留

### ISSUE THREAD

**Issue by scarleast** [fluid-dev/hexo-theme-fluid#755]
#### 如是功能需求，请确定符合以下情况
1.87旧版本支持，1.90取消

#### 请描述该需求尝试解决的问题
我认可fluid主题的GPL协议，但博客内容是博主自己创作的，很多时候，不希望被随意转载（虽然版权声明很多时候并没有用，但还是希望采用如NC、ND的声明），被人到处转载真的很无语，所以希望能保持1.87版本版权文本的自定义。

#### 请描述您认为可行的解决方案
保留1.87旧版本，自定义版权文本的配置选项

#### 考虑过的替代方案
保持旧版本不升级

**Comment by zkqiang** [comment]
GPL是主题开源项目的协议，跟博客内容无关

博客协议的声明已经更新了样式，依然支持 NC ND 声明
https://github.com/fluid-dev/hexo-theme-fluid/blob/fffe6fd41f441072a6a4058e8aff9d15ccd1f6e3/_config.yml#L645-L652

**Comment by scarleast** [comment]
好的，感谢，看到release里面直接取消了copyright的content配置，以为只能跟随主题配置成BY-SA，支持其他声明也没问题了，感谢。
