### ISSUE TITLE
关于归档页与分类页增加图片的问题

### ISSUE THREAD

**Issue by destroyerngu** [fluid-dev/hexo-theme-fluid#759]
当我们写了大量的博客时，归档页和分类页全是一行一行的文字，我们渴望添加一下图片减少单调性。
归档页：
            希望可以按月或按年增加图片区分（加到左侧）
分类页：
           希望不同的分类也可以增加图片区分（加到左侧）

**Comment by destroyerngu** [comment]
衷心希望你们可以做好，你们的theme设计真的很好，很用心

**Comment by zkqiang** [comment]
暂时没有这个打算，可以自己修改
