### ISSUE TITLE
提一个bug

### ISSUE THREAD

**Issue by ZhouShisong** [fluid-dev/hexo-theme-fluid#76]
在手机浏览器上会出现网页已经加载完毕，浏览器的进度条已经显示100%然后隐藏了，但是网页上的精度条和loading的圆圈还在显示动画的bug。设备是iPhoneXS、iPhone8和iPhone6s，环境是Safari、Chrome和QQ浏览器都出现了这个bug，不是必现，是大概率出现这个bug。麻烦检查一下是什么原因哦

**Comment by 0x2E** [comment]
你好 @ZhouShisong 

下个版本移除了顶部进度条 ~~约等于修复bug了哈哈哈~~
