### ISSUE TITLE
valine报错未找到appID问题

### ISSUE THREAD

**Issue by QiQiWan** [fluid-dev/hexo-theme-fluid#760]
#### 请确认
- [ checked ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

主题配置文件正常的情况下，valine无法正常使用，主题配置文件如下图所示：
![image](https://user-images.githubusercontent.com/60660430/172301869-cf09b613-9660-4993-9e22-2d3f0ea6ac0a.png)

leancloud配置如下图所示：

![image](https://user-images.githubusercontent.com/60660430/172301960-13b3fffe-f172-4b98-9995-c16782068314.png)

浏览器打开报错如下图所示：

![image](https://user-images.githubusercontent.com/60660430/172302611-981fafa2-8b5c-4bbd-9e67-0bcd8c950f9b.png)

请问是否是CDN的原因，是否需要更新以调整CDN链接

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/8d79792853244585488908431b02dd6cd59d68b3/_config.yml#L284-L286
