### ISSUE TITLE
info 中的按钮不能正常显示

### ISSUE THREAD

**Issue by huaxianyan** [fluid-dev/hexo-theme-fluid#761]
https://www.neko7ina.com/5g-and-volte-on-pixel-5.html

info 中的按钮不能正常显示按钮样式了，1.9.0 之前的版本正常

![Snipaste_2022-06-07_17-01-33](https://user-images.githubusercontent.com/19589248/172341018-dd3aa515-30b7-4ac3-b598-8b55f93a0676.png)

**Comment by zkqiang** [comment]
1.9.0 按钮样式改为原生了，默认背景色是透明的，可以通过配置来修改：

https://github.com/fluid-dev/hexo-theme-fluid/blob/8d79792853244585488908431b02dd6cd59d68b3/_config.yml#L215-L218
