### ISSUE TITLE
LeanCloud 统计避免恶意篡改

### ISSUE THREAD

**Issue by AnzhiZhang** [fluid-dev/hexo-theme-fluid#763]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

## 问题描述

使用 LeanCloud 统计访问量，发现可以访问 API 实现恶意篡改访问量。

## 示例

```python
import requests
print(requests.put(
    'https://n7i9euyn.api.lncldglobal.com/1.1/classes/Counter/xxx',
    json={"time": 200},
    headers={
        'x-lc-id': 'xxx',
        'x-lc-key': 'xxx'
    }
).json())
```

URL 的参数在请求返回中：
![image](https://user-images.githubusercontent.com/37402126/172785481-b964ebd9-646f-4ba7-ab08-c6fce4110ff7.png)
ID 和 Key 在请求头中：
![image](https://user-images.githubusercontent.com/37402126/172785591-e95955e3-9eca-434e-98ed-28cb4db4a23c.png)

我已成功在我的博客和 [您的博客](https://zkqiang.cn/) 测试以上代码篡改访问量成功。

## 尝试的解决方案
- 官方文档的 [安全域名](https://zh-docs.leancloud.app/data_security.html#hash-49355226) 设置，没有效果

**Comment by zkqiang** [comment]
安全域名只对 JavaScript SDK 有效

后续计划通过类似于 [hexo-leancloud-counter-security](https://github.com/theme-next/hexo-leancloud-counter-security) 来解决这个问题

**Comment by zkqiang** [comment]
另外可以参考 https://leaferx.online/2018/02/11/lc-security/

去设置 `beforeUpdate` 参数校验，我的博客已经加上去了
