### ISSUE TITLE
使用 waline 评论无法配置 placeholder

### ISSUE THREAD

**Issue by AnzhiZhang** [fluid-dev/hexo-theme-fluid#764]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

评论框的默认文字 `欢迎评论` 无法修改。
![image](https://user-images.githubusercontent.com/37402126/172898630-9e040927-d7ab-4680-a7d6-d7c35a56c533.png)

在 [官方文档](https://waline.js.org/advanced/intro.html) 的评论中，该文字是修改了的。
![image](https://user-images.githubusercontent.com/37402126/172898183-8788773f-4699-42b6-b7ee-918e77009bd4.png)

根据 Fluid 可以根据 `requiredMeta` 调整 `（可选）`，猜测实际上 waline 提供了自定义文字的功能，故这个 Issue 应该发在这里。如果是通过强行修改实现，希望可以提供此功能。

**Comment by AnzhiZhang** [comment]
补充：看到回复时 placeholder 位置会变为 `@xxx`，合理猜测 waline 有自定义的功能
![image](https://user-images.githubusercontent.com/37402126/173178725-b8272441-a24e-48a6-92ad-c8b573c77cf7.png)

**Comment by zkqiang** [comment]
https://waline.js.org/guide/client/i18n.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80

v2改成 locale.placeholder 了，直接添加配置项即可

**Comment by AnzhiZhang** [comment]
已解决，谢谢！
