### ISSUE TITLE
使用encrypt插件进行加密时，输入密码后没有任何地方可以点击，回车也没用

### ISSUE THREAD

**Issue by Grace-1024** [fluid-dev/hexo-theme-fluid#768]
<img width="861" alt="image" src="https://user-images.githubusercontent.com/48310779/173012161-061652cb-f00e-4a4f-855c-c16e3312ec98.png">

**Comment by zkqiang** [comment]
dev 分支已更新

**Comment by Grace-1024** [comment]
thanks
