### ISSUE TITLE
waline 插件置顶评论交互按钮无效

### ISSUE THREAD

**Issue by AnzhiZhang** [fluid-dev/hexo-theme-fluid#771]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

已排除 waline 本身的问题，我在评论后台界面置顶了一条评论，是可以点击的，目前供复现确认使用，之后删除这条评论。
网址：https://comment.blog.zhanganzhi.com/

#### Bug 描述

置顶的评论删除、点赞、回复按钮无效

#### 复现步骤

也使用了无痕模式确认

https://blog.zhanganzhi.com/2022/06/b583a6838537

#### 截图
![image](https://user-images.githubusercontent.com/37402126/173178567-12b4219e-9ca5-46f9-923d-3fb664f4c704.png)
![image](https://user-images.githubusercontent.com/37402126/173178571-0698295d-11ea-4e98-9228-438eb315ef25.png)

**Comment by zkqiang** [comment]
dev已修复，点不到是因为被标题的样式挡住了
