### ISSUE TITLE
表格渲染不正常

### ISSUE THREAD

**Issue by Cahcn** [fluid-dev/hexo-theme-fluid#772]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

Markdown 文件位于非 `_posts` 目录，执行 `hexo g` ，表格渲染不正常。
尝试更换 NexT 和 Volantis 主题，未出现该问题。

#### 复现步骤
该 Bug 复现步骤如下：
1. 按照 [README](https://github.com/fluid-dev/hexo-theme-fluid/blob/master/README.md) 全新安装 Hexo 和主题，不修改主题任何配置

2. 将以下内容保存为 Markdown 文件
```Markdown
---
title: 表格测试
date: 2022-06-13 20:27:10
categories:
tags:
---
| 序号 | 频点   | 调制方式 | 视频编码 | 视频码率 |
| ---- | ------ | -------- | -------- | -------- |
| 1    | 506MHz | 64QAM    | MPEG-2   | 4Mbps    |
| 2    | 506MHz | 64QAM    | MPEG-2   | 4Mbps    |
| 3    | 506MHz | 64QAM    | MPEG-2   | 4Mbps    |
| 4    | 251MHz | 128QAM   | H.264    | 7.5Mbps  |
| 5    | 251MHz | 128QAM   | H.264    | 7Mbps    |
| 6    | 251MHz | 128QAM   | H.264    | 7Mbps    |
| 6    | 243MHz | 128QAM   | H.264    | 7Mbps    |
```

3. 将 Markdown 文件命名为 `demo.md` ，另存一份，命名为 `index.md`

4. 文件路径分别为 `\blog\source\_posts\demo.md` 和 `\blog\source\demo\index.md`

5. `hexo g` & `hexo s`

6. _posts 目录下文章表格渲染正常，demo 目录下文章表格渲染不正常，如下图所示

#### 截图
![Image 2](https://user-images.githubusercontent.com/28830841/173358180-d7101e5b-41da-4c28-804b-3fe731e9df0d.png)
![Image 3](https://user-images.githubusercontent.com/28830841/173358195-4d703fb0-69b4-4a5b-8cb2-ba828db47b6a.png)

**Comment by zkqiang** [comment]
请参考[文档](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A1%B5%E9%9D%A2)

正文默认没有 Markdown 样式，如果希望和文章相同的样式，可以加上：
```md
<div class="markdown-body">
正文
</div>
```
