### ISSUE TITLE
[Question] 有相关可以隐藏滚动条的设置么?

### ISSUE THREAD

**Issue by mritd** [fluid-dev/hexo-theme-fluid#773]
#### 请确认
- [ x ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ x ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

请问有可以自动隐藏浏览器右侧滚动条的设置么? 抱歉我暂时没有在 _config.yaml 里找到.

**Comment by zkqiang** [comment]
没有，通过自定义CSS
