### ISSUE TITLE
文章右侧的目录功能不能跳转

### ISSUE THREAD

**Issue by lewiserii** [fluid-dev/hexo-theme-fluid#775]
文章右侧的目录功能不能跳转到文章中对应的内容

而是跳转到页首  http://xxx.xxx/xxx.html#

锚点失效

**Comment by zywvvd** [comment]
我也是这个问题

**Comment by zywvvd** [comment]
> 文章右侧的目录功能不能跳转到文章中对应的内容
> 
> 而是跳转到页首 http://xxx.xxx/xxx.html#
> 
> 锚点失效

兄弟你问题解决了吗

**Comment by lewiserii** [comment]
> > 文章内容的目录功能不能跳转到文章中的目录
> > 改变跳转到页首http://xxx.xxx/xxx.html#
> > 航点失效
> 
> 兄弟你的问题解决了吗

没有解决

**Comment by zywvvd** [comment]
我的解决了，1.9+ 的主题目录没有问题，可能是升级后 npm 有些插件版本低了
我调整了 package 里的依赖包后问题解决了

- 升级了一些依赖版本
- 删除了 toc 插件

当前的 npm 依赖：
```
  "dependencies": {
    "12": "^1.0.2",
    "hexo": "^6.2.0",
    "hexo-baidu-url-submit": "0.0.6",
    "hexo-deployer-git": "^3.0.0",
    "hexo-filter-flowchart": "^1.0.4",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-searchdb": "^1.2.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-helper-live2d": "^3.1.1",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-markdown-it": "^5.0.0",
    "hexo-renderer-stylus": "^2.1.0",
    "hexo-server": "^3.0.0",
    "hexo-sliding-spoiler": "^1.2.1",
    "hexo-symbols-count-time": "^0.7.0",
    "hexo-tag-echarts": "^1.0.0",
    "live2d-widget-model-z16": "^1.0.5",
    "markdown-it-emoji": "^2.0.0",
    "markdown-it-task-lists": "^2.1.1",
    "mathjax": "^3.1.2",
    "picgo-plugin-web-uploader": "^1.1.1",
    "twemoji": "^13.1.0",
    "upgrade": "^1.1.0"
  },
```

建议你新建一个干净的 hexo 工程，加入干净的最新版 fluid
你会发现目录没有问题，再对照看看当前设置哪里需要调整

**Comment by lewiserii** [comment]
> 我的解决了，1.9+的主题目录没有问题，可能是升级后npm 的这些插件版本低了我调整包里的依赖包后问题解决了
> 
> * 升级了一些依赖版本
> * 删除了 toc 插件
> 
> 当前的 npm 依赖：
> 
> ```
>   "dependencies": {
>     "12": "^1.0.2",
>     "hexo": "^6.2.0",
>     "hexo-baidu-url-submit": "0.0.6",
>     "hexo-deployer-git": "^3.0.0",
>     "hexo-filter-flowchart": "^1.0.4",
>     "hexo-generator-archive": "^1.0.0",
>     "hexo-generator-category": "^1.0.0",
>     "hexo-generator-feed": "^2.2.0",
>     "hexo-generator-index-pin-top": "^0.2.2",
>     "hexo-generator-search": "^2.4.0",
>     "hexo-generator-searchdb": "^1.2.0",
>     "hexo-generator-tag": "^1.0.0",
>     "hexo-helper-live2d": "^3.1.1",
>     "hexo-renderer-ejs": "^2.0.0",
>     "hexo-renderer-markdown-it": "^5.0.0",
>     "hexo-renderer-stylus": "^2.1.0",
>     "hexo-server": "^3.0.0",
>     "hexo-sliding-spoiler": "^1.2.1",
>     "hexo-symbols-count-time": "^0.7.0",
>     "hexo-tag-echarts": "^1.0.0",
>     "live2d-widget-model-z16": "^1.0.5",
>     "markdown-it-emoji": "^2.0.0",
>     "markdown-it-task-lists": "^2.1.1",
>     "mathjax": "^3.1.2",
>     "picgo-plugin-web-uploader": "^1.1.1",
>     "twemoji": "^13.1.0",
>     "upgrade": "^1.1.0"
>   },
> ```
> 
> 建议你新建一个干净的 hexo 工程，加入干净的最新版流体 你发现没有目录问题，再看看当前组的哪里需要调整

感谢您的建议，我执行  npm uninstall hexo-toc 命令删除toc插件后完美解决问题
