### ISSUE TITLE
文档语言配置疑似错误

### ISSUE THREAD

**Issue by AnzhiZhang** [fluid-dev/hexo-theme-fluid#777]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

[语言配置](https://hexo.fluid-dev.com/docs/guide/#%E8%AF%AD%E8%A8%80%E9%85%8D%E7%BD%AE) 自定义语言的第一步要求创建 `languages` 文件夹，第二步要求在 `_languages` 文件夹内创建文件。

#### 截图
![image](https://user-images.githubusercontent.com/37402126/174426463-9c305870-cda5-4668-bbea-d2e214f7d8d2.png)

**Comment by zkqiang** [comment]
应均为 `languages`，已修改
