### ISSUE TITLE
现在是不支持背景音乐了吗

### ISSUE THREAD

**Issue by LolitaSian** [fluid-dev/hexo-theme-fluid#779]
原来用的是两年前的版本一直没升级，升级到最新版之后发现没有背景音乐功能了。在配置指南中没有找到

**Comment by zkqiang** [comment]
若干个版本之前已经移除

请参考 [这篇文章](https://hexo.fluid-dev.com/posts/hexo-injector/#aplayer-%E9%9F%B3%E4%B9%90%E6%92%AD%E6%94%BE%E5%99%A8) 自行添加
