### ISSUE TITLE
1.9 + 版本公式渲染错误

### ISSUE THREAD

**Issue by zywvvd** [fluid-dev/hexo-theme-fluid#783]
#### 问题描述
在升级 fluid 到1.9 + 版本后MathJax 公式在电脑的 谷歌浏览器不能正常显示，但是在 安卓手机上显示正常
![](https://101.43.39.125/HexoFiles/vvd_file_mt/202206241320494.jpg)

- 我看到了 v1.8.14 针对 MathJax 的提示
  按照提示成功执行了
```
npm uninstall hexo-renderer-kramed --save
npm install hexo-renderer-pandoc --save
```
  在系统安装了 [Pandoc](https://github.com/jgm/pandoc/blob/master/INSTALL.md)
![](https://101.43.39.125/HexoFiles/vvd_file_mt/202206241322643.jpg)

 但仍然出现了上述问题

参考文档 https://hexo.fluid-dev.com/docs/guide/#latex-%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F 
卸载了 npm uninstall hexo-renderer-marked --save

问题还是没有解决

- 我尝试将 fluid 退回 1.8.9 版本后没有出现上述问题，但是我需要 1.9 版本的 Waline2
- 不知道还有哪里没有调整
- 这是我的 package.json 是不是问题出在这里
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "5.4.0"
  },
  "dependencies": {
    "12": "^1.0.2",
    "hexo": "^5.4.0",
    "hexo-baidu-url-submit": "0.0.6",
    "hexo-deployer-git": "^3.0.0",
    "hexo-filter-flowchart": "^1.0.4",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-searchdb": "^1.2.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-helper-live2d": "^3.1.1",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-markdown-it": "^5.0.0",
    "hexo-renderer-pandoc": "^0.3.1",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-sliding-spoiler": "^1.2.1",
    "hexo-symbols-count-time": "^0.7.0",
    "hexo-tag-echarts": "^1.0.0",
    "hexo-toc": "^1.1.0",
    "live2d-widget-model-z16": "^1.0.5",
    "markdown-it-emoji": "^2.0.0",
    "markdown-it-task-lists": "^2.1.1",
    "mathjax": "^3.1.2",
    "picgo-plugin-web-uploader": "^1.1.1",
    "twemoji": "^13.1.0",
    "upgrade": "^1.1.0"
  },
  "devDependencies": {
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-sitemap": "^2.0.0"
  },
  "scripts": {
    "dev": "hexo server -p $PORT",
    "build": "hexo generate"
  }
}

```

我的 主页  www.zywvvd.com
访问这个页面 可以复现问题 https://www.zywvvd.com/notes/study/math/convex-func/convex-func/
感谢~

**Comment by zywvvd** [comment]
经过排查 我发现是公式 的懒加载 导致的问题，我在 math.ejs 文件中删掉
```
            loader : {
              ${ lazy ? 'load: \[\'ui/lazy\'\]' : '' }
            },
```
显示便正常了

如果想要屏蔽部分代码是否可以通过注入的方式 无侵入地修改

**Comment by Enderfga** [comment]
同样的问题 但是删除上面的代码没有成功解决；右键选择这个选项可以正常显示，但还是很不方便
![svg](https://user-images.githubusercontent.com/74981769/175761059-c576dfd1-e767-4a76-96bb-c3947bc5ba6b.png)

**Comment by zywvvd** [comment]
> 同样的问题 但是删除上面的代码没有成功解决；右键选择这个选项可以正常显示，但还是很不方便 ![svg](https://user-images.githubusercontent.com/74981769/175761059-c576dfd1-e767-4a76-96bb-c3947bc5ba6b.png)

手机访问正常吗，我觉得如果手机端显示也有问题的话是渲染导致的，不然不是公式渲染的问题
1.8.14 之前的版本我的问题没有出现了，不知道你是不是和我一样的情况

**Comment by Enderfga** [comment]
> 

目前我删除了你提到到math.ejs对应的部分，手机显示正常，pc端的效果也跟你上面图片一样

**Comment by Enderfga** [comment]
另外我想请问一下 要怎么回退版本呢 我不熟悉npm 不敢乱动

**Comment by zywvvd** [comment]
> 另外我想请问一下 要怎么回退版本呢 我不熟悉npm 不敢乱动

我也不会 npm 是 git checkout 直接改调整主题源码版本弄的

**Comment by zkqiang** [comment]
请参考 https://github.com/fluid-dev/hexo-theme-fluid/issues/749#issuecomment-1135296099 看是否能解决问题

**Comment by zywvvd** [comment]
我确实用的是 mathjax 3.2.1， 该问题关闭懒加载后解决了
通过删除代码的方式，不知道有没有优雅的注入方式实现
当前问题关闭了
