### ISSUE TITLE
更新1.9+版本之后图片公式等均显示异常

### ISSUE THREAD

**Issue by Enderfga** [fluid-dev/hexo-theme-fluid#784]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

![](https://user-images.githubusercontent.com/74981769/175761163-a083afd2-0f2a-4b82-b205-0e43cc2a8901.png)
<img width="601" alt="image" src="https://user-images.githubusercontent.com/74981769/175761174-0a338685-2953-4418-a430-22d73fc15eb2.png">
更新之后网页加载明显变慢，图片链接正常（用的coding做图床）也不能显示；
可以通过图上方法右键加载，公式也是；
不清楚问题原因，请问可以回退更新吗

**Comment by zkqiang** [comment]
图片加载问题是因为图片请求报 429，可以打开浏览器 console 看下，跟主题版本无关

mathjax 问题请参考 https://github.com/fluid-dev/hexo-theme-fluid/issues/749#issuecomment-1135296099

想回退版本可以通过  `npm i hexo-theme-fluid@1.x.x` 指定版本号
