### ISSUE TITLE
如何给slogan设置特殊字体?

### ISSUE THREAD

**Issue by pans0ul** [fluid-dev/hexo-theme-fluid#785]
#### 请确认
- [V] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [V] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
如何给slogan设置特殊字体?

**Comment by pans0ul** [comment]
例如,可以设置字体类型 字体大小 斜体和粗体等

**Comment by zkqiang** [comment]
直接写 html 带上样式即可

**Comment by pans0ul** [comment]
> 直接写 html 带上样式即可

是在hexo g　生产之后的index.html吗? 如果是这样,这种改法,再下次清理之后,又要重新修改...

**Comment by pans0ul** [comment]
@zkqiang

**Comment by zkqiang** [comment]
```yaml
slogan: <em>粗体文字</em>
```
