### ISSUE TITLE
css、js等资源本地化，防止因第三方网站挂掉影响博客正常运行（我遇到了）

### ISSUE THREAD

**Issue by dr34-m** [fluid-dev/hexo-theme-fluid#786]
#### 如是功能需求，请确定符合以下情况

可以自定义解决，但是如果可以官方解决，会更好

#### 请描述该需求尝试解决的问题

防止因第三方网站挂掉影响博客正常运行（样式会乱掉，可以看这里的截图[我的博客](https://blog.ctftools.com/2022/06/newpost-44/)）

#### 请描述您认为可行的解决方案

静态资源存储到本地（自行实现可以参见[我的博客](https://blog.ctftools.com/2022/06/newpost-44/)），最好能官方实现，把这些静态自愿存储在fluid源码中，如果用户需要，可以提供开关让用户自行决定使用cdn或者本地资源

#### 考虑过的替代方案

可靠的css/js的cdn（很难）

最后，希望大家的博客都能稳定运行一百年

**Comment by zkqiang** [comment]
预留这些配置项就是为了解决你这个问题的...
