### ISSUE TITLE
需求:主题能否增加相册功能

### ISSUE THREAD

**Issue by BigD-Debug** [fluid-dev/hexo-theme-fluid#791]
想要一个相册的页面，类似于图床的“探索”之类的东西，可惜本人对代码这方面一知半懂，想求助于作者大大看能否整一个相册界面……

**Comment by arkerny** [comment]
个人认为相册这个东西恐怕超出了博客的范畴？而且fluid的风格不大适合做瀑布流的页面吧……
对于这个可以参考其他项目，然后链接到博客里会比较好一点。

**Comment by arkerny** [comment]
感觉可以参考下这个改一改即可
![hacker-and-painter-front/dark-code-gallery-section](https://github.com/hacker-and-painter-front/dark-code-gallery-section)

**Comment by arkerny** [comment]
或者如果条件允许可以自己部署兰空图床
[lsky-pro](https://github.com/lsky-org/lsky-pro)
