### ISSUE TITLE
文章中左侧支持显示相同标签的文章

### ISSUE THREAD

**Issue by Macr0phag3** [fluid-dev/hexo-theme-fluid#792]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题
类似文章中支持显示相同分类的文章，希望支持一下显示相同标签的文章。

#### 请描述您认为可行的解决方案
多标签的情况下可以类比 toc 多层显示。
```
tag1
    post1
    post2
tag2
   post1
   post3
```

#### 考虑过的替代方案
自己魔改。但是主题直接内置要好一些。

**Comment by zkqiang** [comment]
没这个打算，标签和分类的用途不同
