### ISSUE TITLE
文章出现删除线无法去除

### ISSUE THREAD

**Issue by Aliceliese** [fluid-dev/hexo-theme-fluid#800]
- [ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法
在复制文章至Markdown编辑器时显示无问题，但是在部署后文章出现删除线
![1-1](https://user-images.githubusercontent.com/90699463/179629257-55949525-df11-4c14-9dd9-a36a657c3efe.png)

如图的情况

**Comment by zkqiang** [comment]
与你安装的 renderer 有关，与主题无关

**Comment by Aliceliese** [comment]
麻烦请教，我该怎么处理，安装其他版本还是更改呢
