### ISSUE TITLE
建议增加首屏图片 开启或关闭功能

### ISSUE THREAD

**Issue by Radio-zhang** [fluid-dev/hexo-theme-fluid#801]
#### 如是功能需求，请确定符合以下情况
- [√] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [√] 难以通过第三方插件实现

非专业程序员，不知道怎么关闭首屏图片显示，建议直接增加选择性，用户使用true 或false 自行决定是否开启首屏图片

**Comment by zkqiang** [comment]
通过 [注入](https://hexo.fluid-dev.com/docs/advance/#fluid-%E6%B3%A8%E5%85%A5%E4%BB%A3%E7%A0%81) 替换掉 <header> 即可，但是样式会很丑，需要自己调下
