### ISSUE TITLE
关于fluid主题各个页面内容边框宽度和页面背景的设置问题

### ISSUE THREAD

**Issue by Nuts-sugar** [fluid-dev/hexo-theme-fluid#804]
如题，我想重新设置一下页面内容边框的宽度，如下图所示：
![image](https://user-images.githubusercontent.com/69556522/180184534-87f480a6-63fc-47a5-a4db-16c3d6bf5dda.png)
还有关于页面背景的设置，我想弄一个图片的虚化效果当做背景，想问一下该如何设置：
![image](https://user-images.githubusercontent.com/69556522/180184896-73d1126d-b133-4244-b79b-03751d389ce2.png)
谢谢~

**Comment by zkqiang** [comment]
自定义 CSS

**Comment by Nuts-sugar** [comment]
> 自定义 CSS
请问具体该怎么设置呢？（本菜鸡不晓得怎么弄呜呜呜）

**Comment by zkqiang** [comment]
可以看下 bootstrap 栅格是怎么用的，跟着修改即可。

不过周围各种布局要跟着一起改，所以不是三言两语能说清楚的，只能自行探索的

**Comment by Nuts-sugar** [comment]
好嘞
