### ISSUE TITLE
优化web analytics（网页访问统计）代码的位置

### ISSUE THREAD

**Issue by pooneyy** [fluid-dev/hexo-theme-fluid#806]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

百度统计要求将JS代码添加到网站全部页面的`</head>`标签前。
![image](https://user-images.githubusercontent.com/85266337/180372186-c3b2464e-b5de-40a5-a981-adb9deb1c427.png)

#### 请描述您认为可行的解决方案

目前是将代码放在Body里，改为放在Head里即可
#### 考虑过的替代方案

也许你会说可以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现，但是自定义引入的代码也在Body里，而不是在Head里
或许可以手动加到Head里，但是那只能是权宜之计，因为每新增一次文章，就会重新生成一次页面。

**Comment by zkqiang** [comment]
请更新最新版本 

https://github.com/fluid-dev/hexo-theme-fluid/commit/9ffbbf1b2de974feb215ef9cd39b38f7c7223912#diff-23480ceaaa0ee6e39e92912242a51c06615f0027c2b3e8359f0d6ba95443d172R46
