### ISSUE TITLE
由KaTeX更改为mathjax后无法正常渲染

### ISSUE THREAD

**Issue by shmilyty** [fluid-dev/hexo-theme-fluid#807]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

以前用 KaTeX 可以正常渲染，今天换成了 mathjax 后就无法正常显示公式。

KateX 预览如下（部分 LaTeX 公式不支持）：
![image](https://user-images.githubusercontent.com/61276699/180373457-a6738ba7-0cf7-4e40-8c7e-0580543d93a9.png)
按照文档指示换成 mathjax 后，便无法正常显示公式：
![image](https://user-images.githubusercontent.com/61276699/180373684-5fb6ac18-edb4-40a6-8e78-95ff2d47ac9f.png)
重复了好几遍 `hexo clean` `hexo g -d` 都没有用，救救孩子（bushi

配置如下：
![image](https://user-images.githubusercontent.com/61276699/180373996-beab9ccd-8df2-4123-bbf7-4a71953dde26.png)
![image](https://user-images.githubusercontent.com/61276699/180374028-1b9b02c9-61d7-4c37-a24c-211ae31ff404.png)
![image](https://user-images.githubusercontent.com/61276699/180374048-daac23c5-2772-412b-bff9-32cbe39d05da.png)

已知不是浏览器缓存的问题，每次 deploy 前都 clean 过一遍。

**Comment by Away30** [comment]
我也是的，请问你解决了吗

**Comment by shmilyty** [comment]
> 我也是的，请问你解决了吗

我已经解决了，还是一些配置方面的错误，我发一下我当前的配置：
![image](https://user-images.githubusercontent.com/61276699/182146694-235987a8-44d7-41b9-8ba0-07df31ae76e4.png)

![image](https://user-images.githubusercontent.com/61276699/182147091-d1aec411-e365-4f73-9ea3-9c851f0dd5f7.png)

我后来把本地博文和几个 config 文件全部备份了一下，把hexo博客删掉重装了一遍，直接加 mathjax。一开始还是不行，后来我发现有个地方字母打错了（有点尴尬😅）不知道如果不重装会不会有没有删完整的错误。

**Comment by shmilyty** [comment]
然后帮以后用 mathjax 的踩个坑：

mathjax 正常情况下不支持换行（\\），需要用`\\\\`转义，但是好像 hexo 里实测无效。

正确的做法是使用 `\displaylines` 命令。

比如：

```
\displaylines{f(x)f_0^{-1}(x)\equiv1(\bmod x^{\lceil \frac k 2\rceil})\\
f(x)f^{-1}(x)\equiv1(\bmod x^{\lceil \frac k 2\rceil})\\
f_0^{-1}(x)-f^{-1}x\equiv0(\bmod x^{\lceil \frac k 2\rceil})}
```

特别的，在 `\begin{...}` 里可以正常使用，以 aligned （左对齐命令）为例：

```
\begin{align}
f(x)&=\sum_{i=0}^\infty F(i)x^i\\
&=\sum_{i=0}^\infty \bigg(\sum_{k=0}^{n-1}k^iA_k\bigg)x^i\\
&=\sum_{k=0}^{n-1}A_k\bigg(\sum_{i=0}^\infty k^ix^i\bigg)\\
&=\sum_{k=0}^{n-1}{A_k\over1-kx}
\end{align}
```
