### ISSUE TITLE
自定义CSS或JS出现自动添加代码的情况

### ISSUE THREAD

**Issue by Waynehfut** [fluid-dev/hexo-theme-fluid#808]
#### 请确认

- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
在自定义JS和CSS时出现自动添加下述代码的情况，更换主题后未出现，请问作者能否协助解决？
```js
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/hint.css/2.4.1/hint.min.css">
```
![image](https://user-images.githubusercontent.com/8127447/180598461-deb7b084-ec28-4969-9f6f-94c8f112449f.png)

**Comment by zkqiang** [comment]
没明白什么情况，发一下具体的配置项？

**Comment by Waynehfut** [comment]
> 

我也没明白发生了啥，换了一个实现方式，暂时规避了这个问题，谢谢
