### ISSUE TITLE
关于页中 mailto 出错

### ISSUE THREAD

**Issue by lyc8503** [fluid-dev/hexo-theme-fluid#809]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

关于页中设置如下:
```
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/lyc8503", tip: "GitHub" }
    - { class: "iconfont icon-rss", link: "https://blog.lyc8503.site/atom.xml", tip: "RSS" }
    - { class: "iconfont icon-mail", link: "mailto:admin@lyc8503.site", tip: "Mail" }
```
在关于页中点击图标后跳转到 https://blog.lyc8503.site/mailto:admin@lyc8503.site 而没有正确地发送邮件.

错误示例页面: https://blog.lyc8503.site/about/

**Comment by zkqiang** [comment]
你的网址我打不开

不过我复制你的配置尝试了是没问题的

**Comment by lyc8503** [comment]
> 你的网址我打不开
> 
> 不过我复制你的配置尝试了是没问题的
> 
> <img alt="image" width="361" src="https://user-images.githubusercontent.com/32983588/181141693-be7930b8-4fac-4d4d-ab12-9754e6fb5774.png">

我看看是不是插件或者版本的问题
