### ISSUE TITLE
请问如何在博客底部添加全站文字计数？

### ISSUE THREAD

**Issue by Wwwhisperr** [fluid-dev/hexo-theme-fluid#811]
#### 已确认
- [ true] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ true] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

我尝试过用网上的办法在文章底部添加统计全站字数的代码块，但是显示出来的字数只是首页的字数，请问有没有办法能统计到全站所有文章的字数呢？求大佬赐教

**Comment by jinghu-moon** [comment]
`footer.ejs` 文件添加下面这句代码，即可实现统计全站字数

```ejs
<span><%= wordtotal(site) %></span>
```

**Comment by KEKKJ123** [comment]
我参考大佬的[文章](https://blog.fengcl.com/2022/08/21/fluid-theme/#%E5%85%A8%E7%AB%99%E5%AD%97%E6%95%B0%E7%BB%9F%E8%AE%A1)和另一位大佬的[修改例子](https://s1mplecode.com/)整理了[一篇文章](https://kekkj123.github.io/posts/Structured/Fluid_Theme_Modify/#%E5%85%A8%E7%AB%99%E5%AD%97%E6%95%B0%E7%BB%9F%E8%AE%A1)，现在发在这里，希望能帮到更多的人。
