### ISSUE TITLE
如何调整文章的尺寸？

### ISSUE THREAD

**Issue by pooneyy** [fluid-dev/hexo-theme-fluid#816]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

![image](https://user-images.githubusercontent.com/85266337/183613129-ce294fc8-f0fe-4500-aa65-e6760bf01f48.png)
希望能够调整`<div id="board">`的尺寸，让它更宽些。

**Comment by zkqiang** [comment]
自定义 CSS

**Comment by pooneyy** [comment]
> 自定义 CSS

不知道在哪里改
