### ISSUE TITLE
无法使用 Valine 作为评论插件

### ISSUE THREAD

**Issue by amakerlife** [fluid-dev/hexo-theme-fluid#817]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

在已经配置好 AppID 和 AppKey 的情况下，仍然无法使用 Valine，暂不清楚是否为主题的问题。

1. 复现问题的步骤：如图所示

![](https://raw.githubusercontent.com/amakerlife/img/main/data/动画.gif)

2. 复现问题的网页地址：<https://www.amakerlife.ml> 中任意一篇文章

3. 操作系统：win11 22000.856；浏览器版本：Chrome 104.0.5112.81

**Comment by zkqiang** [comment]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/32983588/184568544-d5297d0a-5db1-4e8d-9476-49207fb077fe.png">

leancloud 接口失败，请检查 valine 的配置

不应该是主题问题，官网用的就是 Valine
https://hexo.fluid-dev.com/posts/hello-fluid/

**Comment by amakerlife** [comment]
> <img alt="image" width="549" src="https://user-images.githubusercontent.com/32983588/184568544-d5297d0a-5db1-4e8d-9476-49207fb077fe.png">
> 
> leancloud 接口失败，请检查 valine 的配置
> 
> 不应该是主题或插件问题，官网用的就是 Valine https://hexo.fluid-dev.com/posts/hello-fluid/

能帮忙看一下哪里配置错了吗

![](https://raw.githubusercontent.com/amakerlife/img/main/data/20220818203116.png)

**Comment by zkqiang** [comment]
https://github.com/xCss/Valine/issues/378

或者更新 Valine 版本试试

**Comment by amakerlife** [comment]
> [xCss/Valine#378](https://github.com/xCss/Valine/issues/378)
> 
> 或者更新 Valine 版本试试

已经调整了 serverURLs 并将 Valine 更新至1.5.1 版本，控制台报错如下：

![](https://raw.githubusercontent.com/amakerlife/img/main/data/20220819212630.png)

av-min.js 返回 302 状态

![](https://raw.githubusercontent.com/amakerlife/img/main/data/20220819212407.png)

serverURLs 配置如下：

![](https://raw.githubusercontent.com/amakerlife/img/main/data/20220819212851.png)

该[博客](https://blog.csdn.net/hubojing/article/details/121770387)的解决方法还差最后一步，但不知道如何修改 js 文件源？

**Comment by ZermZhang** [comment]
https://forum.leancloud.cn/t/2022-8/25408
你使用的leancloud是国际版么？8月1日起共享域名不提供大陆的服务了
