### ISSUE TITLE
请问文章下面的’许可协议‘怎么关闭不显示

### ISSUE THREAD

**Issue by hypo1986** [fluid-dev/hexo-theme-fluid#818]
请问文章下面的’许可协议‘怎么关闭不显示
找半天没找到设置的地方，希望大佬帮忙回复，感谢哈

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/ffb31fb6d3436be33d58072d3096bd93f803d070/_config.yml#L645-L648

**Comment by hypo1986** [comment]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/3656381/184570262-f679b65a-d0fd-44d8-93c7-a264f8600461.png">
好像不行呢 我设置了 false 和 true 这个 都一直显示

**Comment by hypo1986** [comment]
> https://github.com/fluid-dev/hexo-theme-fluid/blob/ffb31fb6d3436be33d58072d3096bd93f803d070/_config.yml#L645-L648
![image](https://user-images.githubusercontent.com/3656381/184570349-29b22f1e-0a14-4698-b609-8ef5de56d663.png)

好像不行呢 我设置了 false 和 true 这个 都一直显示

**Comment by zkqiang** [comment]
原来是指这里，目前不支持单独关闭，下个版本支持

**Comment by hypo1986** [comment]
> 原来是指这里，目前不支持单独关闭，下个版本支持

copyright:
    enable: true
    license: ''
可以这样设置 下面图标和链接就不显示了  但是 上面字还是会显示
