### ISSUE TITLE
使用主题色后怎么样才能保证切换主题不更改code配色

### ISSUE THREAD

**Issue by Jack-InGitHub** [fluid-dev/hexo-theme-fluid#819]
#### 请确认
- [ x ] 已确认 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ x ] 已确认 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

使用主题色后怎么样才能保证切换亮色暗色主题后, 不去不更改code配色, 亮色主题色挺好看, 暗色之后就一塌糊涂了

**Comment by zkqiang** [comment]
没办法，code配色也是代码style的一部分，可以自定义 CSS 覆盖

**Comment by Jack-InGitHub** [comment]
> 没办法，代码替代代码样式的一部分，可以自定义 CSS 覆盖

可以说说要怎么样操作吗, 我不太懂CSS, 或者在哪儿可以找到相关教程呢, 我似乎没有查找到类似问题的可供参考的

**Comment by Jack-InGitHub** [comment]
我只是想用亮色的code配色去覆盖掉暗色的code配色

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/ffb31fb6d3436be33d58072d3096bd93f803d070/_config.yml#L62-L74

可以单独指定暗色的style
