### ISSUE TITLE
网页顶部的banner图片存在bug

### ISSUE THREAD

**Issue by ZhouShisong** [fluid-dev/hexo-theme-fluid#82]
banner图片在iPhone和iPad的浏览器上无法正常显示，无法完整的显示图片，只能显示图片的极小一部分，还是模糊的。在Mac上显示是正常的，这个Bug出现在master分支上，tag1.4.0没有这个问题。

**Comment by zkqiang** [comment]
master 先不要用，这个 BUG 还待解决

**Comment by Nick-Hopps** [comment]
#88

**Comment by zkqiang** [comment]
master分支已解决
