### ISSUE TITLE
似乎有一些配置外的字体

### ISSUE THREAD

**Issue by Initial-heart-1** [fluid-dev/hexo-theme-fluid#820]
在对站点进行 Lighthouse 审计时，我注意到似乎加载了两个并非由我配置的字体，由两个 css 文件请求且均指向 alicdn：
![image](https://user-images.githubusercontent.com/63091661/185738733-117d14df-38eb-44f9-88c6-7d2f26a4b655.png)
![image](https://user-images.githubusercontent.com/63091661/185738744-c2b79a0d-a54d-48d9-853c-bf5b1c4ea327.png)
加起来的用时 166ms，对于本来就慢的 Github Pages 来说更是雪上加霜
我自己有字体策略所以想问这个有办法删掉/关闭吗

**Comment by zkqiang** [comment]
这个是 [iconfont](https://www.iconfont.cn/)，用于主题所有的图标

166ms 在 Github Pages 墙内龟速面前可以忽略不计了。。。

**Comment by Initial-heart-1** [comment]
> 这个是 [iconfont](https://www.iconfont.cn/)，用于主题所有的图标
> 
> 166ms 在 Github Pages 墙内龟速面前可以忽略不计了。。。

事实上我使用了腾讯云的境外 CDN，也就是说其实通过港澳台节点访问

现在就是 100ms 100ms 的抓

这部分耗时太长了，引人注目

不能合在一个字体文件里吗？或者给个配置开关，给用户自主配置

刚刚又测了一次，587 ms，其中超过三分之一的时间花费在了 TTFB (193 ms)

**Comment by zkqiang** [comment]
没有合在一起，是因为小的那个是主题依赖的，大的那个是可配置的：

https://github.com/fluid-dev/hexo-theme-fluid/blob/ffb31fb6d3436be33d58072d3096bd93f803d070/_config.yml#L314-L316

**Comment by Initial-heart-1** [comment]
> 没有合在一起，是因为小的那个是主题依赖的，大的那个是可配置的：
> 
> https://github.com/fluid-dev/hexo-theme-fluid/blob/ffb31fb6d3436be33d58072d3096bd93f803d070/_config.yml#L314-L316

了解了，就是依赖那个是写死动不了是吧

**Comment by zkqiang** [comment]
> 了解了，就是依赖那个是写死动不了是吧

是的，后续更新再考虑把它变为可配置

**Comment by Initial-heart-1** [comment]
好的



------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年8月21日(星期天) 晚上10:05
To: ***@***.***&gt;; 
Cc: "Initial ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [fluid-dev/hexo-theme-fluid] 似乎有一些配置外的字体 (Issue #820)





  
了解了，就是依赖那个是写死动不了是吧
  
是的，后续更新再考虑把它变为可配置
