### ISSUE TITLE
搭建博客中代码段出现错位和重复&&版权部分也出现问题

### ISSUE THREAD

**Issue by zhuba-Ahhh** [fluid-dev/hexo-theme-fluid#824]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
搭建博客中代码段出现错位和重复，求助应该修改哪些部分，操作是按照网上一些教程一步一步操作。

问题相关情况如图:
![image](https://user-images.githubusercontent.com/84793349/187064908-b049d1ac-cbf4-4265-a571-4a96ce1d382e.png)
![image](https://user-images.githubusercontent.com/84793349/187064915-ed691cca-99a9-4097-9f53-cec9512a55c8.png)

[具体可以点击访问查看](https://zhuba-ahhh-github-io.vercel.app/)

**Comment by mikusaa** [comment]
在hexo的`_config.yml`文件里改下`URL`的配置就好了
![image](https://user-images.githubusercontent.com/31799398/187066412-33d3ac78-9b0b-428b-8e06-35632a9d665c.png)

**Comment by zkqiang** [comment]
代码行号是 renderer 问题
