### ISSUE TITLE
代码块支持 Solidity 语法高亮

### ISSUE THREAD

**Issue by Confucian-e** [fluid-dev/hexo-theme-fluid#826]
#### Make sure
- [ ] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] No solution found in [documentations](https://hexo.fluid-dev.com/docs/en/)

#### Describe the question

您好，我是一名区块链开发者，代码块能否支持 Solidity 语法高亮，或者我自己如何配置

**Comment by zkqiang** [comment]
代码高亮是基于第三方插件，请关注他们的更新
