### ISSUE TITLE
fluid归档、分类、标签界面查看文章404错误

### ISSUE THREAD

**Issue by charlesix59** [fluid-dev/hexo-theme-fluid#827]
#### Bug 描述
- 通过归档、分类与标签进入文章时，会出现404 bug，原因是会将archieve/category/tags加入到文章链接中导致失败
- 我尝试npm安装与本地安装，均出现该问题（不知道是否与配置有关，经过查阅并未找到相关说明）
- 创建新文章的方法为 `hexo new <page_name>`
- 该bug已经被我个人修复，可以访问https://charlesix59.github.io/2022/09/04/fix-fluid-open-err-page-bug/查看相关的信息
- 由于查看预览网站时并未发现与我相同的问题，所以猜想并非是框架直接的问题，可能与安装方式或配置有关
- 我是第一次使用该框架，同时也是第一次使用hexo，所以能够保证hexo是纯净的，不会有其它插件污染
- 运行环境 
  - os：window10 x64 
  - IDE：WebStorm
  - node版本：14.15.4
  - hexo版本： 6.2.0

#### 复现步骤
该 Bug 复现步骤如下：
在归档或分类或标签点击任意文章

**Comment by zkqiang** [comment]
这个基本和主题无关，主题不会干涉生成链接

**Comment by charlesix59** [comment]
我最近查阅了hexo的文档，发现在他提供的函数中发现了for_url()是回到文章根目录，但是实际上在我的hexo中for_url()并没有得到正确的结果。可能是hexo新版本的bug，或者是我安装的bug
可以确定与主题无关，麻烦您了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月11日(星期天) 晚上9:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fluid-dev/hexo-theme-fluid] fluid归档、分类、标签界面查看文章404错误 (Issue #827)





 
这个基本和主题无关，主题不会干涉生成链接
