### ISSUE TITLE
文档推荐的渲染器渲染 KaTeX 公式时没有使用正确的字体

### ISSUE THREAD

**Issue by greyishsong** [fluid-dev/hexo-theme-fluid#828]
#### Make sure
- [x] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases).
- [x] It can be replicated through `hexo clean && hexo s` and cleared browser cache in the localhost.
- [x] Not affected by other Hexo plugins

#### Describe the bug

文档的 *配置指南 -> 文章页 -> LaTeX 数学公式* 一节中，建议使用 `@upupming/hexo-renderer-markdown-it-plus` 以渲染 KaTeX 公式。但输出结果中所有的公式字符 CSS `font-family` 属性都是 `KaTeX_Main` （包括正常情况下应当是 `KaTeX_Math` 的那些），导致应当显示为斜体的字符都是正体（如截图所示）。

平台信息如下：

```
OS: Ubuntu 22.04 jammy
Shell: bash
DE: KDE 5.92.0 / Plasma 5.24.4
Browser: Firefox 104.0.1
```

Node.js 版本为 `16.15.1` ，测试目录 `package.json` 中关于包版本的部分如下：

```json
{
  "hexo": {
    "version": "6.2.0"
  },
  "dependencies": {
    "@upupming/hexo-renderer-markdown-it-plus": "^2.0.2",
    "hexo": "^6.2.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-stylus": "^2.1.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-fluid": "^1.9.2",
    "hexo-theme-landscape": "^0.0.3"
  }
}
```

整个测试目录按照文档推荐的方式安装 Hexo 和 Fluid 主题，仅包含一个 Markdown 源文件：

```markdown
---
title: Test KaTeX
math: true
---

This is a minimal test of KaTeX inline and block formulas. $A\vec{x}=\vec{b}$

$$
e^{\mathrm{i}\theta}=\cos\theta+\mathrm{i}\sin\theta
$$
```

主题配置文件 `_config.fluid.yml` 仅包含如下内容：

```yaml
post:
  math:
    enable: true
    specific: false # 此处改为 true 并不影响结果
    engine: katex
```

在换用 `hexo-renderer-markdown-it` 渲染器配合 `@traptitech/markdown-it-katex` 插件渲染后，所有公式显示正常。很抱歉我并不了解前端技术，如果有您需要我进行任何其他测试，请回复 issue 或者邮件联系我，我会尽力而为。该问题在我使用 NeXT 主题时同样发生（并以相同方法解决），疑似源自 `@upupming/hexo-renderer-markdown-it-plus` 。如果更多的测试表明确实如此，我建议您修改主题的文档。

#### To Reproduce

在我的平台上，复现问题的过程为：

1. 新建一个文件夹 `test` ，执行 `hexo init test`
2. 进入 `test` 安装主题，按照上述说明修改配置
3. 卸载原有的渲染渲染器、安装 `@upupming/hexo-renderer-markdown-it-plus`
4. 创建一个包含公式的 Markdown 源文件
5. 执行 `hexo clean && hexo g` 生成渲染结果

生成过程中没有出现任何 `WARN` 或 `ERROR` 信息。若执行 `hexo s` 并从本地访问生成结果，在浏览器开发者工具中可以看到 `katex.min.css` 加载成功，但公式中所有字符的字体都是 `KaTeX_Main` 。此时可以手动修改字体为 `KaTeX_Math` ，被修改的部分字符会正确地显示斜体。

#### Screenshots
![Screenshot_20220906_224353](https://user-images.githubusercontent.com/49446254/188672460-e686b15e-5f8d-460f-bba5-156d865fce7f.png)

**Comment by zkqiang** [comment]
>在换用 hexo-renderer-markdown-it 渲染器配合 @traptitech/markdown-it-katex 插件渲染后，所有公式显示正常。

这个我没有成功实现，能否提供具体的方式？

**Comment by greyishsong** [comment]
> > 在换用 hexo-renderer-markdown-it 渲染器配合 @traptitech/markdown-it-katex 插件渲染后，所有公式显示正常。
> 
> 这个我没有成功实现，能否提供具体的方式？

1. 卸载原有的所有渲染器，`npm install hexo-renderer-markdown-it --save` 安装 `hexo-renderer-markdown-it`
2. 安装插件 `npm install @traptitech/markdown-it-katex --save`
3. 在站点配置文件 `_config.yml` 中添加 `hexo-renderer-markdown-it` 的配置：
    ```yaml
    markdown:
      plugins:
        - "@traptitech/markdown-it-katex"
    ```
4. 清除缓存重新生成

这是前述测试文件重新生成的结果：

![Screenshot_20220912_100953](https://user-images.githubusercontent.com/49446254/189561786-7141d2b3-7738-481d-9201-a6445b16b0f6.png)

**Comment by zkqiang** [comment]
感谢，已更新到文档

**Comment by greyishsong** [comment]
> 感谢，已更新到文档

抱歉在 issue 关闭后进行回复，但请注意更新后的文档有一处错误：*配置指南 -> 文章页 -> LaTeX 数学公式* 一节中，将 `hexo-renderer-markdown-it` 误写作了 `hexo-renderer-pandoc` ，截图如下。

![Screenshot_20220914_171205](https://user-images.githubusercontent.com/49446254/190113278-ba4ec88c-cc14-444f-b64f-0fe6747c1965.png)
