### ISSUE TITLE
如何添加readme.md文件，我在source里创建后，hexo g 会把他生成readme.html文件，我不知道如何解决！

### ISSUE THREAD

**Issue by gnlh** [fluid-dev/hexo-theme-fluid#829]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

**Comment by gnlh** [comment]
如何添加readme.md文件，我在source里创建后，hexo g 会把他生成readme.html文件，我不知道如何解决！

**Comment by zkqiang** [comment]
https://hexo.io/zh-cn/docs/configuration#%E5%8C%85%E6%8B%AC%E6%88%96%E4%B8%8D%E5%8C%85%E6%8B%AC%E7%9B%AE%E5%BD%95%E5%92%8C%E6%96%87%E4%BB%B6

通过 `exclude` 排除
