### ISSUE TITLE
文章内的引入的img图片会压缩,在哪里能调整大小

### ISSUE THREAD

**Issue by ZengTianTu** [fluid-dev/hexo-theme-fluid#83]
文章内的引入的img图片会压缩,在哪里能调整大小

**Comment by zkqiang** [comment]
把 [这一行](https://github.com/fluid-dev/hexo-theme-fluid/blob/358d94a548d4226062941cc40ab5b92e79f7f0d3/source/css/_pages/_post/post.styl#L8) 改成 100% 或者注释掉
