### ISSUE TITLE
github pages部署问题

### ISSUE THREAD

**Issue by RookieTerry** [fluid-dev/hexo-theme-fluid#831]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
之前的发送邮件问题，换了一个评论模块后解决了，但是把页面部署到`github pages`时显示不正常，过了几个小时依然如此。如图：
![image](https://user-images.githubusercontent.com/77920425/190178187-24dfa244-43d6-478b-9b81-e91e92b37992.png)
![image](https://user-images.githubusercontent.com/77920425/190178339-f1d263d4-c772-40cc-a531-f631d887da13.png)

**Comment by zkqiang** [comment]
请在浏览器 console 检查具体报错，没办法帮忙解决部署问题

**Comment by chergn** [comment]
那放gitee呗，GitHub还卡呢。不过gitee没有Discussion模块，评论不太好弄

**Comment by chergn** [comment]
那放gitee呗，GitHub还卡呢。不过gitee没有Discussion模块，评论不太好弄
