### ISSUE TITLE
设置语言的时候出现该错误，YAMLException: duplicated mapping key at line 103, column 1:     language: zh-CN

### ISSUE THREAD

**Issue by lnnau** [fluid-dev/hexo-theme-fluid#832]
#### 问题描述
设置语言的时候出现该错误，YAMLException: duplicated mapping key at line 103, column 1:     language: zh-CN

#### 解决方式
不要按照提供的方式增加一个键language，在_config.yml的11行已经有language这个参数设置了，所以直接在这个地方修改语言为zh-CN就可以了。

**Comment by zkqiang** [comment]
是哪里的文档写了“增加一个键language”吗？我没找到

**Comment by lnnau** [comment]
> 是哪里的文档写了“增加一个键language”吗？我没找到

在README.md文档的“3指定主题”，指定主题设置和设置语言设置在一起，如果直接找到theme键修改主题后再在下面添加language的话会和最上面的language冲突，因为没有指明这两个键的配置位置，可能会因为使用者在没有仔细查看配置文档的时候出错，希望可以在README.md文件中指出具体配置。

**Comment by zkqiang** [comment]
> 在README.md文档的“3指定主题”，指定主题设置和设置语言设置在一起，如果直接找到theme键修改主题后再在下面添加language的话会和最上面的language冲突，因为没有指明这两个键的配置位置，可能会因为使用者在没有仔细查看配置文档的时候出错，希望可以在README.md文件中指出具体配置。

这个步骤已经注明是“修改 Hexo 博客目录中的 _config.yml”，而且 theme 和 language 都是修改（theme 也是已经存在的键），所以应该是你误解了...  这个文档两年没改了，还第一次有人提这个问题

**Comment by lnnau** [comment]
确实是我误解了
