### ISSUE TITLE
咱就是说会有侧栏功能吗

### ISSUE THREAD

**Issue by HosesaWu** [fluid-dev/hexo-theme-fluid#833]
舍不得fluid的外观和交互，但也极度想要个侧栏功能😔

**Comment by zkqiang** [comment]
没明白你说的“侧栏”是什么功能

**Comment by HosesaWu** [comment]
好的，那可能是我看的不仔细了，我去看看左右栏怎么开

**Comment by HosesaWu** [comment]
又看了一圈文档，还是没看到怎么打开左右侧栏

**Comment by zkqiang** [comment]
如果你是指弹出式的侧栏，那确实没有，以后大概率也不会有

**Comment by HosesaWu** [comment]
就是正常侧栏，比如说有个侧栏显示blog的作者信息什么的，我不知道怎么配置这个，文档上没看到，并不用弹出/滑动

**Comment by HosesaWu** [comment]
我叙述的可能不太专业，请大佬不要介意～

**Comment by zkqiang** [comment]
> 就是正常侧栏，比如说有个侧栏显示blog的作者信息什么的，我不知道怎么配置这个，文档上没看到，并不用弹出/滑动

这个也是没有的，也没有相关计划

**Comment by HosesaWu** [comment]
好的，感谢您
