### ISSUE TITLE
每个页面自定slogan

### ISSUE THREAD

**Issue by YQL-Skorpion** [fluid-dev/hexo-theme-fluid#839]
请问有办法给每个页面都自定打字机打的文字吗？配置指南里只说了主页怎么改，直接在别的页下面写slogan: 也没用。多谢

**Comment by YQL-Skorpion** [comment]
Update: 找到了，archive/categories/etc.下面写subtitle就行

**Comment by yuyi-shenlu** [comment]
怎么写？
