### ISSUE TITLE
请求加入图片内嵌

### ISSUE THREAD

**Issue by shmilyty** [fluid-dev/hexo-theme-fluid#843]
#### 如是功能需求，请确定符合以下情况
- [ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [ ] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

在写博客的时候，有时候我会以图片的形式插入 qq 表情
![image](https://user-images.githubusercontent.com/61276699/192148790-3125265e-55ae-49fb-a268-b49390d4c619.png)
但是由于插入图片默认是换行居中的，所以会看上去会很怪异。

我不是很懂开发，因此没有自己实现的能力，但是我经过搜索，没有找到什么结果。尝试用 html 代码的形式插入图片，还是没有达到预期的效果。

**Comment by ZHDreamer** [comment]
![Snipaste_2022-11-06_09-59-43](https://user-images.githubusercontent.com/40716043/200150576-a119341a-5021-482f-8ac7-3c96115217de.png)
在博客中插入 badage 也会有这个问题

**Comment by zkqiang** [comment]
使用 HTML 可以解决，例如
`这是一个普通段落 <span><img width=32 src="/images/20190818011319.png-slim"></span>`

<img width="240" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/32983588/005139d0-e757-4375-a2bf-41c06a7eade5">

@shmilyty @ZHDreamer
