### ISSUE TITLE
适配自己的主题时import_css 函数不生效问题

### ISSUE THREAD

**Issue by appotry** [fluid-dev/hexo-theme-fluid#844]
首先感谢作者的主题，代码写的超简洁，完善

现在按照 Fluid 主题生成框架改造自己的 Matery 博客 

几乎是重写的的超大工作量

发现 import_css 辅助函数，倒是生成了内容，但是在 head 中获取不倒 

个人集成测试时发现， css.ejs 中的这段代码还没有获取到后面import_css 注入的内容，这段代码放到 script.ejs 中倒是可用

```ejs
<% for (var idx = 0; idx < css_snippets.length; idx++) { %>
  <%- css_snippets[idx] %>
  <% matery_log(css_snippets[idx]) %>
<% } %>
<% page.css_snippets = [] %>
```

各种调试，花费大量时间还没有解决这个问题， 目前想了个这种解决方法
import.ejs 中添加
```ejs
hexo.extend.helper.register('css_injects', function(link, point) {
  for (var idx = 0; idx < this.page.css_snippets.length; idx++) {
    hexo.extend.injector.register('head_begin', () => {
      return this.page.css_snippets[idx];
    }, 'post');
  } 
});
```

新增了一个 helper 函数 `css_injects()` 放入 script.ejs 中来调用

@zkqiang 问一下，css.ejs 中的那段代码为啥获取不到内容？ 渲染顺序问题？有没有解决方法

**Comment by zkqiang** [comment]
你提供的信息有限，我很难做出回答。这一块问题建议深入了解下 hexo renderer 的工作原理，可能会更容易找到答案

**Comment by appotry** [comment]
我的失误， 这段代码需要放到 markdown-plugins.ejs 引用之后才能生效
