### ISSUE TITLE
Will my own configuration in _config.yml be overrided after updating the fluid theme?

### ISSUE THREAD

**Issue by erjiaxiao** [fluid-dev/hexo-theme-fluid#845]
#### Make sure
- [ ] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] No solution found in [documentations](https://hexo.fluid-dev.com/docs/en/)

#### Describe the question

As mentioned in the title, if it will, how could I keep my own configuration while updating?

**Comment by zkqiang** [comment]
See [override-configuration](https://hexo.fluid-dev.com/docs/en/guide/#override-configuration)

**Comment by erjiaxiao** [comment]
Hello @zkqiang, sorry to disturb you, could I ask why we don't need to worry configuration override if we use npm to install and update fluid theme? Is there any mechanism which helps us keep custom configuration automatically?  
![2022-09-27 202315](https://user-images.githubusercontent.com/44388426/192525417-3c1eb1b1-e4a7-4f57-aecf-464a208f37d8.png)

**Comment by zkqiang** [comment]
@erjiaxiao   Because `_config.yml` file should be in the blog directory after installation via npm (if you follow the guide), updating the fluid will not override it

**Comment by erjiaxiao** [comment]
@zkqiang I see.. So that also means if I store my own custom_avatar.png in the folder blog_dir/themes/fluid/source/img. Then it will be overrided after updating via npm. Is it right?

**Comment by zkqiang** [comment]
@erjiaxiao No, npm install in `blog_dir/node_modules/hexo-theme-fluid`, not in the `blog_dir/themes/`, which is two install ways, and you don't need to do them both.

If you want to update via npm, actually you can delete `theme/fluid` and place `custom_avatar.png` in `blog_dir/source/`

**Comment by erjiaxiao** [comment]
@zkqiang I see.. Thanks for your patience. The whole process is more clear to me. Do you think it is necessary to open a PR to add these messages in the docs of fluid theme, making it more informative?

**Comment by zkqiang** [comment]
@erjiaxiao In fact, these messages already exists in the docs, of course some of the messages belongs to Hexo docs

**Comment by erjiaxiao** [comment]
@zkqiang My bad.. next time I'll look through it more carefully. Thanks for so many explanations!
