### ISSUE TITLE
How to add image to header?

### ISSUE THREAD

**Issue by dovankha** [fluid-dev/hexo-theme-fluid#850]
Hi everyone, 
My blog is like this: 
![my_blog](https://user-images.githubusercontent.com/63991630/194505789-6f9b5a6f-bb17-4dcd-bfba-2f24cc39b4bf.png)
But, hexo themes fluid is like that:
![Hexo_themes_fluid](https://user-images.githubusercontent.com/63991630/194504989-6af835d3-2ad5-4480-a0a0-398c851a7ac4.png)
So, I want my blog to be like hexo themes fluid.
Thank you.

**Comment by zkqiang** [comment]
https://hexo.fluid-dev.com/docs/en/guide/#index-image

**Comment by dovankha** [comment]
Thank you very much ❤
