### ISSUE TITLE
自定义page中的超链接字体和普通字体相同

### ISSUE THREAD

**Issue by zuqingwang** [fluid-dev/hexo-theme-fluid#852]
如题，新生成了一个page，但页面里面的超链接和普通的字体是同一颜色，无法分辨。有没有办法解决这个问题，比如page和post共用一个css？（本人小白，仅为未验证的个人想法
hexo和fluid版本均为最新。

**Comment by zkqiang** [comment]
https://hexo.fluid-dev.com/docs/guide/#%E5%88%9B%E5%BB%BA%E9%A1%B5%E9%9D%A2

>正文默认没有 Markdown 样式，如果希望和文章相同的样式，可以加上：
>```
><div class="markdown-body">
>正文
></div>
>```
