### ISSUE TITLE
当网站保存在二级目录下，如果出现404，会错误的延迟redirect回url根目录

### ISSUE THREAD

**Issue by LovelyQuantum** [fluid-dev/hexo-theme-fluid#853]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

本库中相关代码如图
![image](https://user-images.githubusercontent.com/44353226/196038289-a6364dd2-6836-4de4-b514-410668bd2860.png)
其中`redirect`函数指向了url的根目录，而非网站根目录（二级目录）

**Comment by zkqiang** [comment]
thx
