### ISSUE TITLE
站点统计功能

### ISSUE THREAD

**Issue by gujiniCY** [fluid-dev/hexo-theme-fluid#856]
#### 请确认
- [X] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [X] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

我使用的是`1.9.3` 的主题

![image](https://user-images.githubusercontent.com/27911820/197124160-6c9f6dd7-15a8-434b-ac8b-7f1359eeb799.png)

站点统计那里，添加了百度和Google的站点ID，但是页面上没有他们的js文件请求。

我的配置文件
![image](https://user-images.githubusercontent.com/27911820/197124559-65fd1340-4a05-4c56-b68a-10de773ba7de.png)

我查看到源码中使用的是`theme.web_analytics.baidu` 但是在[配置文件](https://github.com/fluid-dev/hexo-theme-fluid/blob/master/_config.yml)中，theme这一层级好像没有。

![image](https://user-images.githubusercontent.com/27911820/197124253-20614a15-3644-4433-a10e-864f9af59b2e.png)

请求正确的用法是什么？

**Comment by zkqiang** [comment]
`theme` 是整个配置的对象

你配置没问题，请检查网页元素和控制台来排查问题

**Comment by gujiniCY** [comment]
![image](https://user-images.githubusercontent.com/27911820/197436001-59d20857-eb50-4556-8c57-06aca15f7b0b.png)
![image](https://user-images.githubusercontent.com/27911820/197436011-bbf7a5eb-d367-475d-9d0c-2079994b2b2b.png)
网页元素也有出现js代码
![image](https://user-images.githubusercontent.com/27911820/197436097-4186695c-76ff-4a72-8ab8-ed9812ac2fe3.png)
请求里面没有

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/d5797b6395cb6e0b2302a082f52d069b0bee8d89/_config.yml#L245-L248

默认开启了 Do Not Track，如果浏览器也打开了就不会请求
