### ISSUE TITLE
[Feature Request] Math

### ISSUE THREAD

**Issue by Alan-Liang** [fluid-dev/hexo-theme-fluid#87]
I wonder if this theme could support math in posts, favourably by TeX, like:
```latex
The Pythagorean theorem is $a^2+b^2=c^2$ .
$$\int_{a_0}^{a_1}x+\frac{1}{x}\:\mathrm{d}x$$
```

**Comment by zkqiang** [comment]
Currently not supported, but it will be added later.

**Comment by Nick-Hopps** [comment]
You can try this plugin：[hexo-renderer-markdown-it-plus](https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus), it works well for me: [https://infiniture.cn/2019/09/30/n%E7%9A%84a%E6%AC%A1%E6%96%B9%E6%B1%82%E5%92%8C%E9%97%AE%E9%A2%98/](https://infiniture.cn/2019/09/30/n%E7%9A%84a%E6%AC%A1%E6%96%B9%E6%B1%82%E5%92%8C%E9%97%AE%E9%A2%98/)

**Comment by zkqiang** [comment]
[v1.6.0](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.6.0) supports this feature now
