### ISSUE TITLE
支持Google Analytics 4的数据追踪

### ISSUE THREAD

**Issue by Aye10032** [fluid-dev/hexo-theme-fluid#874]
谷歌原本的Universal Analytics将在明年7月停止支持，希望能更新适配新的追踪代码
考虑到迁移问题，在配置文件中加一个tag来让用户选择使用哪一种追踪代码也行

**Comment by Aye10032** [comment]
又看了下新文档发现有支持，我之前眼瞎了（

**Comment by crescenth** [comment]
请问在那里支持的，我没找到啊。我也眼瞎了

**Comment by crescenth** [comment]
> 又看了下新文档发现有支持，我之前眼瞎了（

请问在那里支持的，我没找到啊。我也眼瞎了
