### ISSUE TITLE
文章末尾导航栏的“上一篇”和“下一篇”是反的

### ISSUE THREAD

**Issue by xkww3n** [fluid-dev/hexo-theme-fluid#875]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述
每篇文章末尾的导航栏中，“上一篇”链接实际上指向下一篇文章，而“下一篇”链接则实际上指向上一篇文章。

#### 复现步骤
该 Bug 复现步骤如下：
1. 打开使用 Fluid 主题的 Hexo 网站
3. 进入最新一篇文章
4. 滑动到底部
5. 可以看到出现了本不应出现，且实际上指向上一篇文章的“下一篇”链接（宽屏下直接显示文章名）

Fluid 官方网站亦受此 Bug 影响：<https://hexo.fluid-dev.com/posts/coding-imagehost/>

#### 截图
![image](https://user-images.githubusercontent.com/30206355/201517438-3acfbec6-970f-49a3-860d-535a860df1f0.png)

![image](https://user-images.githubusercontent.com/30206355/201517449-847cabff-df42-4a0e-b4c8-1ae062d4ca1c.png)

**Comment by zkqiang** [comment]
这里的“下一篇”指的是首页列表顺序的下一篇
