### ISSUE TITLE
一些改进建议

### ISSUE THREAD

**Issue by Nick-Hopps** [fluid-dev/hexo-theme-fluid#88]
非常感谢作者，主题是我喜欢的风格😁

提出一些建议：

1. 文章页中标题和时间之间间隔太短，建议在文章日期的 \<p\> 标签上加一个 class = "mt-2"
2. 希望增加 katex、mermaid/flowchart 支持

**Comment by zkqiang** [comment]
感谢，十月还会有更多优化

**Comment by Nick-Hopps** [comment]
然后 banner 的 background-attachment: fixed 在 safari 下无效，需要做一下兼容性处理

**Comment by Nick-Hopps** [comment]
我在 main.js 里面加了这么一句:

```js
// 如果是 safari 则强制修改 image-attachment 为 scroll
if(/Safari/.test(navigator.userAgent) && !/Chrome/.test(navigator.userAgent)) {
    $(".full-bg-img").css("background-attachment", "scroll");
}
```

暂时想不到更好的办法了，safari 都不支持 background-attachment 为 fixed

**Comment by zkqiang** [comment]
master分支已解决
