### ISSUE TITLE
bug?: prismjs cdn 不再能访问导致语法高亮不可用

### ISSUE THREAD

**Issue by rxliuli** [fluid-dev/hexo-theme-fluid#881]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [ ] 已经排除是其他 Hexo 插件影响

#### Bug 描述

代码高亮炸了，很奇怪，进一步检查了一下发现是 prismjs 无法访问

#### 复现步骤
该 Bug 复现步骤如下：

1. 打开 http://localhost:4000/p/b0cb4560702945069f8c885bc5244ef8/
2. 打开控制台
3. 发现错误 `Uncaught SyntaxError: Unexpected token ':' (at prism-line-numbers.min.js:1:4)`

相关配置文件：https://github.com/rxliuli/blog/blob/master/_config.fluid.yml

#### 截图

![image](https://user-images.githubusercontent.com/24560368/204108557-b534f2b7-48ad-41dc-a1e2-439b54d2ea87.png)

**Comment by zkqiang** [comment]
最新版已更新版本号，也可自行替换

https://github.com/fluid-dev/hexo-theme-fluid/commit/e928cd556f11f4f43c2e10d8dc43adaab2f86dee
