### ISSUE TITLE
加密文章刷新丢失样式

### ISSUE THREAD

**Issue by Miseryset** [fluid-dev/hexo-theme-fluid#882]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

一个很奇怪的现象，使用 hexo-blog-encrypt 加密的文章，在首次输入密码之后，所有内容都能正常显示，但是刷新页面或者重新进入页面，不用再输密码，文章却丢失了目录，链接颜色等
手机端的via-4.4.6，iceraven-1.18.4，windows的firefox-107都会这样

**Comment by reatiny** [comment]
同样的问题 有时候需要多次刷新 样式才能恢复正常

**Comment by llingy** [comment]
原因是这段：
```javascript
  if (document.getElementById('hbePass')) {
    Fluid.utils.waitElementLoaded('hbe-prefix', function() {
      var hbePrefix = document.querySelector('hbe-prefix');
      hbePrefix.parentElement.classList.add('markdown-body');
      Fluid.utils.retry(function() {
        if (Fluid.boot && Fluid.boot.refresh) {
          Fluid.boot.refresh();
          return true;
        }
      }, 100, 10);
    })
  }
```
hexo-blog-encrypt 会保存密码，如果之前有正确的密码则会自动解密，这段脚本有属性 defer，会在页面加载完后才执行，所以如果之前输入过密码则会导致 id 为 hbePass 的密码输入框已经被删除，则不会重新进行所需的操作。并且由于解密操作是异步的，很可能没法在正常执行这些操作之前解密完成。最终导致如果输过密码则丢失样式。

临时解决方式：
在需要解密的文章末加入以下代码：
```html
<script>
var hbePrefix = document.querySelector('hbe-prefix');
hbePrefix.parentElement.classList.add('markdown-body');
Fluid.utils.retry(function(){
    if (Fluid.boot && Fluid.boot.refresh) {
    Fluid.boot.refresh();
    return true;
    }
}, 100, 10);
</script>
```

希望作者尽快修复。
