### ISSUE TITLE
无法在文章页面加载 waline

### ISSUE THREAD

**Issue by amakerlife** [fluid-dev/hexo-theme-fluid#887]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [ ] 已经排除是其他 Hexo 插件影响

#### Bug 描述

在文章页中，waline 无法正常工作，配置如下图。但奇怪的是，友链页却可以。

![](https://img.makerlife.tk/data/20221211220433.png)

waline 静态：<https://cdn.bootcdn.net/ajax/libs/waline/2.14.1/>

控制台无报错

浏览器：Chrome

#### 复现步骤
可在该文章中复现：<https://www.makerlife.tk/post/solution-AT1898/>

#### 截图

见上

**Comment by zkqiang** [comment]
尝试升级最新版本 https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.9.4

**Comment by amakerlife** [comment]
> 尝试升级最新版本 https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.9.4

已经升级至 v1.9.4，问题依然存在，waline 静态已换为主题内置。
