### ISSUE TITLE
关于页

### ISSUE THREAD

**Issue by fengqiao18** [fluid-dev/hexo-theme-fluid#889]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

我在使用时无法正常显示LaTeX，不论文章页和关于页，均无法使用。

两种渲染器都更换了，没有效果。本地和上传后一样。

**Comment by fengqiao18** [comment]
顺便问一句，怎么去掉自建html页外面的主题的框？？

**Comment by zkqiang** [comment]
关于页同自定义页面，不加载额外的插件，需要在 front-matter 里单独指定
