### ISSUE TITLE
怎么实现国际化？

### ISSUE THREAD

**Issue by novolife** [fluid-dev/hexo-theme-fluid#89]
我看到Hexo的文档说要在模板里使用<%= _p('index.video', 3) %>这样的辅助函数，我想把网站导航栏里的进行翻译，但是不知道怎么做。

**Comment by 0x2E** [comment]
像这样：
```yaml
navbar:
  menu:
    首页: /
    归档: /archives/
    分类: /categories/
    标签: /tags/
    关于: /about/
```

**Comment by novolife** [comment]
> 修改主题配置文件中导航部分，把键改为中文，像这样：
> 
> ```yaml
> navbar:
>   menu:
>     首页: /
>     归档: /archives/
>     分类: /categories/
>     标签: /tags/
>     关于: /about/
> ```

我想保留原英文，而不是单纯的改原字段

**Comment by novolife** [comment]
刚刚摸索了一下找到了：在/layout里有模板，把/_partial里的nav.ejs中循环生成的导航项中名字部分用辅助函数包裹起来，再在翻译文件里写出来。
