### ISSUE TITLE
无法在部分页面加载 Waline 评论

### ISSUE THREAD

**Issue by amakerlife** [fluid-dev/hexo-theme-fluid#893]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

在 #887 中已经提出了详细的复现过程，复现浏览器：Chrome/Edge 108.0。

疑似只在 chromium 内核浏览器中出现问题，暂未发现其他内核浏览器有此问题。服务端（waline.makerlife.tk）可以在任意浏览器中正常使用。

无法复现浏览器：Safari 13.1, Firefox 108.0。

waline 静态资源使用最新主题内置（v2.14.1）和 v2.13.0 均无法解决问题。

**Comment by amakerlife** [comment]
另外添加一句，经过测试，有时 Chrome 访问会一直在转圈加载

有时会显示出评论但无法进行任何操作

![](https://img.makerlife.tk/data/waline1.gif)

有时又是正常加载

**Comment by amakerlife** [comment]
再跟进一下，貌似其他浏览器也会出现类似问题

**Comment by fengqiao18** [comment]
同问

**Comment by zkqiang** [comment]
@amakerlife @fengqiao18  请确定是否为 https://github.com/walinejs/waline/issues/1318 类似问题

**Comment by amakerlife** [comment]
> @amakerlife @fengqiao18 请确定是否为 [walinejs/waline#1318](https://github.com/walinejs/waline/issues/1318) 类似问题

表现是的，但已绑定自定义域名并使用 leancloud 国际版作为数据库

**Comment by Tim-Saijun** [comment]
> > @amakerlife @fengqiao18 请确定是否为 [walinejs/waline#1318](https://github.com/walinejs/waline/issues/1318) 类似问题
> 
> 表现是的，但已绑定自定义域名并使用 leancloud 国际版作为数据库

同，waline托关于vercel且绑了域名，直接访问域名可以评论，基于leancloud的访问量统计也正常；但主题里waline评论模块丢失。

**Comment by amakerlife** [comment]
> > > @amakerlife @fengqiao18 请确定是否为 [walinejs/waline#1318](https://github.com/walinejs/waline/issues/1318) 类似问题
> > 
> > 
> > 表现是的，但已绑定自定义域名并使用 leancloud 国际版作为数据库
> 
> 同，waline托关于vercel且绑了域名，直接访问域名可以评论，基于leancloud的访问量统计也正常；但主题里waline评论模块丢失。

你的友链页评论可以用吗？我的友链页正常文章页就时好时坏🤣

**Comment by amakerlife** [comment]
还有一个问题，过长文章直接不显示评论区域。

https://www.makerlife.live/post/exgcd/

![](https://img.makerlife.tk/data/202301261509131.png)

**Comment by Moraxyc** [comment]
同，仅部分页面加载成功，页面之间无标志性不同，无法判断原因

console无任何报错，无法判断是否为浏览器问题

后端可正常返回数据，排除后端问题

全局代理仍无法加载，排除网络问题

怀疑是fluid渲染过程中破坏了waline的加载

**Comment by Moraxyc** [comment]
safari for iOS 16.3也可触发该问题
![677F80D1-E645-41FE-920E-7BD0799C7F41](https://user-images.githubusercontent.com/69713071/217407832-55bb2109-8306-4e2e-829f-1c0ae416722e.gif)

**Comment by appotry** [comment]
说一下个人猜测，基于像素坐标加载waline，然而，文章中的图片等元素高度，在加载的时候会影响整体的高度，导致最下面的waline绝对高度的坐标变化，

超出一定范围，就会导致移动到最下面的时候，依然达不到加载waline的坐标判断

**Comment by zkqiang** [comment]
@appotry 如果怀疑是此问题，可以将

https://github.com/fluid-dev/hexo-theme-fluid/blob/dd447d23dbf5db13c1d9ab68e54c2d167a06bc67/_config.yml#L297-L300

设为 `false` 试一下，这样评论会在页面初始就加载

**Comment by amakerlife** [comment]
> @appotry 如果怀疑是此问题，可以将
> 
> https://github.com/fluid-dev/hexo-theme-fluid/blob/dd447d23dbf5db13c1d9ab68e54c2d167a06bc67/_config.yml#L297-L300
> 
> 设为 `false` 试一下，这样评论会在页面初始就加载

但在[这种](https://blog.makerlife.top/post/solution-ABC286C/)没有图片的文章，不会触发元素高度的变化，仍然无法加载评论甚至不显示评论区，怀疑可能还有其他问题导致。

**Comment by zkqiang** [comment]
在 [v1.9.5](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.9.5) 尝试修复了一次，请各位测试下

@amakerlife @appotry @Moraxyc @Tim-Saijun @fengqiao18

**Comment by resetsix** [comment]
我遇到一个bug：在开发环境和部署的默认域名可以正常显示评论框。但是(博客中)通过自定义域名访问的话就一直loading(默认域名指Vercel和Cloudflare page部署项目后自带的访问域名，两者都试过)。

waline部署是在vercel的，也确保服务正常。

有佬知道自定义域名访问一直转圈的原因吗？

**Comment by amakerlife** [comment]
目前用主题 1.9.8 和 FireFox 130，配 waline2.15.8 没发现问题。

没试 #1090 但至少目前正式版就能用
