### ISSUE TITLE
使用 hexo-blog-encrypt 加密文章时，如果之前输入过密码，文章会失去样式。

### ISSUE THREAD

**Issue by llingy** [fluid-dev/hexo-theme-fluid#895]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [ ] 已经排除是其他 Hexo 插件影响

#### Bug 描述
文章丢失样式。
#### 复现步骤
使用 hexo-blog-encrypt 加密文章时，如果之前输入过密码，文章会失去样式。
原因是这段：
```javascript
  if (document.getElementById('hbePass')) {
    Fluid.utils.waitElementLoaded('hbe-prefix', function() {
      var hbePrefix = document.querySelector('hbe-prefix');
      hbePrefix.parentElement.classList.add('markdown-body');
      Fluid.utils.retry(function() {
        if (Fluid.boot && Fluid.boot.refresh) {
          Fluid.boot.refresh();
          return true;
        }
      }, 100, 10);
    })
  }
```
hexo-blog-encrypt 会保存密码，如果之前有正确的密码则会自动解密，这段脚本有属性 defer，会在页面加载完后才执行，所以如果之前输入过密码则会导致 id 为 hbePass 的密码输入框已经被删除，则不会重新进行所需的操作。并且由于解密操作是异步的，很可能没法在正常执行这些操作之前解密完成。最终导致如果输过密码则丢失样式。

```javascript
if (document.getElementById('hbePass') || document.querySelector('hbe-prefix')) {
    Fluid.utils.waitElementLoaded('hbe-prefix', function() {
        var hbePrefix = document.querySelector('hbe-prefix');
        hbePrefix.parentElement.classList.add('markdown-body');
        hbePrefix.parentElement.removeChild(hbePrefix);
        Fluid.utils.retry(function() {
            if (Fluid.boot && Fluid.boot.refresh) {
                Fluid.boot.refresh();
                return true;
            }
        }, 100, 10);
    })
}
```
如果改成这样能正确加载样式。
#### 截图

![image](https://user-images.githubusercontent.com/70438351/211187204-7e2b9b75-c867-4d07-a0f6-33954981d3cd.png)
这是二级标题，但并没有相应的样式。

**Comment by llingy** [comment]
经查找，应修改 `/layout/_partials/plugins/encrypt.ejs` 中的代码。

**Comment by zkqiang** [comment]
Fixed in [v1.9.5](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.9.5)
