### ISSUE TITLE
隐藏文章 tags 链接失效

### ISSUE THREAD

**Issue by LingkKang** [fluid-dev/hexo-theme-fluid#896]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

隐藏文章下的 tags 链接全都会失效。不论是仅这篇文章单有的 tag，还是其他文章也有的 tag，都会导向 404 页面。

在本地 `hexo s` 测试都没问题。仅在 deploy 后失效。

隐藏文章：[Use CSLinux with SSH - Lingkang's Blog](https://lingkkang.github.io/2022/11/28/better-way-to-cslinux/)

独有 Tag：[Tags - VS-Code](https://lingkkang.github.io/tags/VS-Code/)

共同 Tag：[Tags - SSH](https://lingkkang.github.io/tags/SSH/)

有共同 Tag 的文章：[Connect to Local Machine in Hyper-V with SSH - Lingkang's Blog](https://lingkkang.github.io/2022/12/31/ssh-hyper-v/)

#### 其他

Categories 都正常。

在本地 `hexo s --draft` 测试了一篇隐藏的 draft，共同 tag 能正确导到地址，独有的 tag 显示 `Error: Cannot GET /tags/xxx`，应该是正常的情况。

显得问题很奇怪。🤔

> 4. 如果本地页面正常，部署后有问题，请清除缓存或者耐心等待 CDN 刷新（可能持续数小时），这不属于主题问题

已经一个月多了，尝试 `npm update` 和 清除缓存都不起作用。

**Comment by wuhao21** [comment]
大概看了一下你生成html的tag， https://lingkkang.github.io/tags/ssh/ 就是可以的。感觉是有大小写不同步的问题，但是我本地无法复现。

试试确认一下tag的大小写再生成一下？

**Comment by LingkKang** [comment]
> 试试确认一下tag的大小写再生成一下？

@wuhao21 解决了！的确是大小写的关系。把 markdown 里所有 `SSH` tag 都换成小写就没问题了（不知道为啥都大写就不行）。

多谢！
