### ISSUE TITLE
在使用脚注时出现 [object Object] 字样

### ISSUE THREAD

**Issue by SupeRuier** [fluid-dev/hexo-theme-fluid#900]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

在使用脚注时出现 [object Object] 字样，如下图所示。

<img width="588" alt="image" src="https://user-images.githubusercontent.com/30451800/212023294-157ee34a-3b8f-447d-9aee-c4b49e92565b.png">

**Comment by zkqiang** [comment]
能否提供更多的信息来让我复现这个 BUG？

**Comment by SupeRuier** [comment]
我发现如果遵守配置指南在主题配置区加入
```
footnote:
  enable: true
  header: ''
```
则会出现此现象，显示 [object Object]。试了三个文件，都可以复现。

此外如果不加入这个设置，同样可以使用 footnote，且不会出现 [object Object]。

**Comment by zkqiang** [comment]
我没有复现出来，我猜测可能是你的其他插件干扰，或者 front-matter 里设置了 `footnote` 字段
