### ISSUE TITLE
为什么_config.fluid.yml覆盖无效

### ISSUE THREAD

**Issue by Tokisaki-Galaxy** [fluid-dev/hexo-theme-fluid#904]
想问一下为什么_config.fluid.yml覆盖无效。
采用fork方式，然后hexo也是直接提交到Github上，fluid是一个子模块的方式部署。
平时更新直接传到Github上hexo项目，然后vercel再部署。
但是本地hexo s试了一下，发现覆盖完全无效，hexo g --debug也不会按照覆盖的来。
困扰很久了，昨天到今天都一直没研究出来，想来问问大佬。

**Comment by Tokisaki-Galaxy** [comment]
因为不是`_config.fluid.yml`，是`_config.hexo-theme-fluid.yml`
浪费人生中24小时。。。

**Comment by zousheng2002** [comment]
我一生行善积德终于让我花了一个小时搜到了你的解答！
感谢！

**Comment by zenith191** [comment]
非常感谢！成功解决问题！

**Comment by zenith191** [comment]
非常感谢！成功解决问题！

**Comment by WeiWu-code** [comment]
牛逼，我看了半天，还好看到了你
