### ISSUE TITLE
如何自定义子分类页面的标题

### ISSUE THREAD

**Issue by GinMiraing** [fluid-dev/hexo-theme-fluid#905]
#### 请确认
- [ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
子分类页面默认的标题格式是：分类 - 分类名。如何自定义该页面的标题呢？

![](https://i0.hdslb.com/bfs/album/ca71407d35a7234a45ae5e7ae2e4fa82498a0376.png@.webp)

**Comment by Jface001** [comment]
在博客文件夹下 /source/categories/index.md , 修改这个文件试试

**Comment by zkqiang** [comment]
```yaml
category:
  title: xxxx
```

但是只能写死一个标题
