### ISSUE TITLE
博客正文代码块跟图片宽度不一致。

### ISSUE THREAD

**Issue by Jface001** [fluid-dev/hexo-theme-fluid#908]
#### 如是功能需求，请确定符合以下情况
- [ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [ ] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

如下图，我发现图片宽度跟正文以及代码块宽度不一致，希望能设置一致，看起来统一点。
我的博客地址：jingyuu.top
<img width="1832" alt="image" src="https://user-images.githubusercontent.com/21217483/216822207-b0eab331-e0f1-413d-b69b-164fe1d9571a.png">

#### 请描述您认为可行的解决方案

希望博客图片宽度能跟正文宽度一致。

**Comment by zkqiang** [comment]
你可以通过自定义CSS修改
