### ISSUE TITLE
求助：写文章时，插入图片怎么用相对地址？

### ISSUE THREAD

**Issue by bternity** [fluid-dev/hexo-theme-fluid#909]
如题，写文章时，插入图片怎么用相对地址？
此外，想知道怎么修改图片的显示大小。

**Comment by bternity** [comment]
在写markdown的时候用了相对地址，如<img src="文章名字/图片.jpg" >。。在typora里面图片显示正常，但是网页全没有加载出来。

> 如题，写文章时，插入图片怎么用相对地址？
> 此外，想知道怎么修改图片的显示大小。

**Comment by GarytheNoob** [comment]
### 插入图片
无论是hexo还是本主题，绝大多数地址都是以`{hexo根目录}/source/`为相对的根目录。如果你在文章里输入了
```markdown
文章内容

![](/myimg/postName1/pic1.jpg)

文章内容
```
则图片会对应`{hexo根目录}/source/myimg/postName1/pic1.jpg`。其中`myimg/postName1/pic1.jpg`之类的可以自己重命名。

### 调整大小
Markdown没有直接的调整大小语法，所以只能使用html对应的语法，如：
```html
<img src="{图片地址}" alt="{图片描述}">
```
对应
```markdown
![{图片描述}]({图片地址})
```
要规定大小：
```html
<img src="{图片地址}" alt="{图片描述}"  width="{宽}" height="{高}">>
```
单位：像素
即可。

**Comment by chen-huaneng** [comment]
我和你有一样的问题，我的解决方案应该是比较优雅的，可以参考一下：[链接](https://chen-huaneng.github.io/2023/12/02/2023-12-2-2023-12-03-how-to-write-blog/#%E5%8D%8F%E8%B0%83-hexo-%E5%92%8C-typora-%E6%8F%92%E5%85%A5%E5%9B%BE%E7%89%87%E7%9A%84%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5)
