### ISSUE TITLE
[BUG]Gitalk评论bug

### ISSUE THREAD

**Issue by yangqihang01** [fluid-dev/hexo-theme-fluid#91]
作者您好，
您的博客自带的gitalk模块
我启动，并且配置好了id等

然后随便点一篇文章，初始化issue
然后gitalk提示不能读取未定义的仓库
原文好像是can't read repository not' define

然后就加载不了评论系统
请问这个bug如何解决
（原来用过其他博客框架，都是正常的）

**Comment by 0x2E** [comment]
你好，`hexo g` 后检查一下页面 HTML 的 Gitalk 部分，看仓库名等配置是不是跟配置文件里的一样。

**Comment by lc5900** [comment]
这个是主题的脚本问题，把每页数量加了引号，被当做字符串，无法转为int。我将尝试提交PR修复。

**Comment by zkqiang** [comment]
感谢 @lc5900 的PR
