### ISSUE TITLE
复制代码块时, 希望在最后一行添加换行

### ISSUE THREAD

**Issue by DengWuLi** [fluid-dev/hexo-theme-fluid#910]
#### 如是功能需求，请确定符合以下情况
- [x] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [x] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

复制代码块时, 希望可以在最后一行添加换行
#### 请描述您认为可行的解决方案

因为我是萌新小白, 所以不知道此功能有什么解决方案, 同时在网上搜索也并没有发现此功能的解决方案.
#### 考虑过的替代方案

发现部分博主使用HUGO编辑的博客, 复制代码块可以在最后一行添加空行.

**Comment by zkqiang** [comment]
可以通过注入 JS 给每个代码块后面自动加换行。

但是我不是很理解为什么这样（虽然我知道代码规范里要求空行，但是和展示代码不是一回事）
