### ISSUE TITLE
`search.content` cannot be set to `false`

### ISSUE THREAD

**Issue by luyuhuang** [fluid-dev/hexo-theme-fluid#912]
#### Make sure
- [x] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases).
- [x] It can be replicated through `hexo clean && hexo s` and cleared browser cache in the localhost.
- [x] Not affected by other Hexo plugins

#### Describe the bug

https://github.com/fluid-dev/hexo-theme-fluid/blob/fcee8f417ed9af3f8a0a74ff704c9b8b582f7828/scripts/generators/local-search.js#L38

The value of the expression is always `true`  no matter what the value of `searchConfig.content` is.

**Comment by wuhao21** [comment]
I will claim this bug.
