### ISSUE TITLE
Set `image_caption` for each post

### ISSUE THREAD

**Issue by luyuhuang** [fluid-dev/hexo-theme-fluid#913]
#### Make sure
- [x] Difficult to implemented through [custom](https://hexo.fluid-dev.com/docs/en/guide/#custom-js-css-html).
- [x] Difficult to implemented through third-party plugins.

#### Is your feature request related to a problem? Please describe

I migrate my blog to hexo & fluid from jekyll, which doesn't support image caption, so images in my posts don't have meaningful captions (like `![/path/to/img.png](/path/to/img.png)`). I have to set `image_caption.enable` to false, but I want my new posts can use this feature. So it'll be nice if I can set `image_caption.enable` for each post.

#### Describe the solution you'd like

Maybe we can modify like this:

https://github.com/fluid-dev/hexo-theme-fluid/blob/fcee8f417ed9af3f8a0a74ff704c9b8b582f7828/scripts/helpers/export-config.js#L22

```js
let { config, theme, fluid_version, page } = this; 
const exportConfig = { 
  image_caption: page.image_caption || theme.post.image_caption,
  ...
}
```

https://github.com/fluid-dev/hexo-theme-fluid/blob/fcee8f417ed9af3f8a0a74ff704c9b8b582f7828/layout/_partials/markdown-plugins.ejs#L16-L18

```ejs
<% if ((page.image_caption || theme.post.image_caption).enable) { %>
  <% import_script('<script>Fluid.plugins.imageCaption();</script>') %>
<% } %>
```

**Comment by zkqiang** [comment]
You can batch replace `![/path/to/img.png](/path/to/img.png)` to `![](/path/to/img.png)`, image caption will not be displayed if `[]` is empty
