### ISSUE TITLE
无法渲染&emsp

### ISSUE THREAD

**Issue by system51** [fluid-dev/hexo-theme-fluid#919]
无法渲染缩进，版本应该是最近出的版本，才安装的。没找到在哪里查看版本。
![image](https://user-images.githubusercontent.com/26198108/222871672-250ee5dc-2e99-47dc-892a-f2773e5baa75.png)

**Comment by zkqiang** [comment]
摘要部分不会进行 HTML 转义，可以考虑手动指定摘要
