### ISSUE TITLE
hexo g报错

### ISSUE THREAD

**Issue by ZhouShisong** [fluid-dev/hexo-theme-fluid#92]
1、source/_data/fluid_config.yml中配置了about.md会在hexo g时报错
是这样配置的：md_path: /abount/about.md，在这个目录下也创建了相应的文件
必须设置成  md_path: ./pages/about.md  才不会报错
也就是说about.md无法迁移到主题文件外。

2、Safari浏览时，文章页面滚动，在右下角的向上返回顶部的按钮，有时候会变到最右侧屏幕中央

**Comment by ZhouShisong** [comment]
tag 1.5报错的

**Comment by 0x2E** [comment]
你好，md_path 跟其他静态资源路径不一样，是相对于主题根目录的。比如把 about.md 放在 `/source/about.md` 的话，路径就填 `../../source/about.md`
