### ISSUE TITLE
一份功能需求

### ISSUE THREAD

**Issue by Bayi-Cat** [fluid-dev/hexo-theme-fluid#922]
一个小建议：
有很多开发者都会使用yarn而并非npm，fluid是否也能兼容yarn呢？
期待开发团队的回复
**I love fluid!**

**Comment by zkqiang** [comment]
我没太理解你的需求，Fluid 不兼容 yarn 是存在哪个方面吗？理论上 Fluid 并不依赖是 npm 还是 yarn，只取决于 hexo 的依赖
