### ISSUE TITLE
关于fluid 1.9.4版本使用GPL3开源协议的个人看法

### ISSUE THREAD

**Issue by Bayi-Cat** [fluid-dev/hexo-theme-fluid#923]
**个人**认为，GPL的开源理念太极致了，建议可以更改为MIT或Apache License。当然使用GPL也没什么不好，这是你们的自由

**Comment by zkqiang** [comment]
Fluid 是从 v1.9.0 版本开始改为 GPL3，是因为那时发生了一些事情，让我们改变了开源的想法，打算保留对一些商用行为的限制。不过 v1.9.0 之前的版本依然属于 MIT 协议，不受这次修改的影响。

另外我个人对 GPL3 并不觉得“太极致”，开源并不代表允许别人随意利用代码，如果那样反而是伤害开源精神的。
