### ISSUE TITLE
MathJax渲染的公式，上下标字体太大，公式渲染不好看

### ISSUE THREAD

**Issue by aizpy** [fluid-dev/hexo-theme-fluid#926]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

MathJax渲染的公式，上下标字体太大，公式渲染不好看。测试过在Chrome和Edge浏览器上都有这个问题。
_config.fluid.yml上的相关配置：
math: 
  enable: true
  specific: true
  engine: mathjax

#### 复现步骤
该 Bug 复现步骤如下：
1. 使用 mathjax 渲染数学公式
2. 键入如下公式：
$$
p(z) = \frac{1}{\sigma \sqrt{2\pi}}e^{-\frac{(z - \mu)^2}{2\sigma^2}}
$$
e指数上的平方字体太大，导致看起来所有字都粘在一起。

#### 截图

![image](https://user-images.githubusercontent.com/127382813/225340440-24743000-961a-4727-af48-c5fc40b2f454.png)

**Comment by Lixuannan** [comment]
用 pandoc 可以解决问题，但是会导致部分 latex 渲染错误，我也不知道为什么，可以去看一下 [https://github.com/fluid-dev/hexo-theme-fluid/issues/932](https://github.com/fluid-dev/hexo-theme-fluid/issues/932)
