### ISSUE TITLE
网站访问统计无法使用

### ISSUE THREAD

**Issue by YluHuu** [fluid-dev/hexo-theme-fluid#931]
#### 请确认
- [ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

我根据官方文档设置了相关的配置来统计网站访问量，但是在博客中无法显示，以下是我的配置等信息。
![pv](https://user-images.githubusercontent.com/95006157/228791872-eda3dc68-0c53-4a01-82a2-42b7f233f80b.png)
![pv1](https://user-images.githubusercontent.com/95006157/228791901-a7067b23-3a09-4f16-a348-cfb28f4593e9.png)
![无](https://user-images.githubusercontent.com/95006157/228791920-0adbf5ab-b09a-49b4-a41a-3f4cfb087296.png)

**Comment by zkqiang** [comment]
<img width="205" alt="image" src="https://user-images.githubusercontent.com/32983588/232291115-3bff41cb-abf9-4bf4-bdae-9b7c0c1011e3.png">

true
