### ISSUE TITLE
请问如何将自己的网站收录到搜索引擎？

### ISSUE THREAD

**Issue by c-167** [fluid-dev/hexo-theme-fluid#932]
在进行必应SEO收录申请时，想问一下该怎么操作？
![image](https://user-images.githubusercontent.com/82827359/229160308-cb1d9430-3591-4a16-aacb-523e7e328e96.png)

**Comment by zkqiang** [comment]
通过 [注入代码](https://hexo.fluid-dev.com/docs/advance/#fluid-%E6%B3%A8%E5%85%A5%E4%BB%A3%E7%A0%81) 功能，可以无侵入添加
