### ISSUE TITLE
https://hexo.fluid-dev.com/ 域名， 国内移动基本是无法访问的

### ISSUE THREAD

**Issue by appotry** [fluid-dev/hexo-theme-fluid#935]
## 问题

https://www.itdog.cn/http/

可以这里测试查看，

## 解决方法

上一个cdn，或者dns分线路解析

**Comment by zkqiang** [comment]
用的是香港阿里CDN，预算有限，如果被屏蔽了暂时也没啥好办法。。

**Comment by appotry** [comment]
用cloudflare啊，速度过得去
