### ISSUE TITLE
提供搜索的文件可否支持自定义配置？

### ISSUE THREAD

**Issue by huaxianyan** [fluid-dev/hexo-theme-fluid#94]
这块是否可以像其他静态资源一样支持自定义配置？

随着文章增多这个文件会越来越大，搜索的时候 Loading 半天也挺影响体验的。

**Comment by 0x2E** [comment]
配置文件里有个 search.path 指定 js 读取的数据文件路径。

可以在 `hexo g` 之后把 public 目录下生成的数据文件移到 CDN 上，配置文件里对应着修改路径即可。

**Comment by huaxianyan** [comment]
@0x2E 抱歉，没注意研究配置文件项，感谢帮助

**Comment by huaxianyan** [comment]
@0x2E 我尝试了一下，但是发现那个 path 好像默认是读本地的。

我把该项改成 ``https://pic.neko7ina.com:7777/public/local-search.xml`` 后，运行 ``hexo g`` 时会报错，有这么一条
```bash
Error: ENOENT: no such file or directory, mkdir 'C:\Neko7ina\Syncthing\Desktop\Hexo\Hexo\public\https:'
```

**Comment by 0x2E** [comment]
@huaxianyan 抱歉，是我的问题。search.path 没有区分开 hexo 渲染地址和 js 引用地址，下个版本会优化。

临时解决方法： https://github.com/fluid-dev/hexo-theme-fluid/blob/master/layout/_partial/footer.ejs#L83 改为如下
```js
 // var path = "<%- theme.search.path || '/local-search.xml' %>";
 var path = "https://pic.neko7ina.com:7777/public/local-search.xml";
```

**Comment by zkqiang** [comment]
我将 search.path 设置为绝对路径可以使用

**Comment by zkqiang** [comment]
Fixed https://github.com/fluid-dev/hexo-theme-fluid/commit/5e28c1646fea7af24902ace688ba9fce8b7f33aa
