### ISSUE TITLE
package.json文件的main参数填写文件本身是什么意思？

### ISSUE THREAD

**Issue by wdkGitHub** [fluid-dev/hexo-theme-fluid#940]
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/12813051/235300237-bb88d48a-ede3-4a30-92d6-58f70f0e6af5.png">

不太明白 main=package.json 什么意思，有人能解答一下疑问吗？

**Comment by zkqiang** [comment]
可以参考 https://docs.npmjs.com/cli/v9/configuring-npm/package-json#main

因为本项目没有真正的 `entry point`，所以就指定到这里了

**Comment by wdkGitHub** [comment]
谢谢
