### ISSUE TITLE
文章在首页显示不出来本地路径的图片，只能显示默认的图片，是图片路径不对还是有可能图片格式不对

### ISSUE THREAD

**Issue by dayangss** [fluid-dev/hexo-theme-fluid#942]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

**Comment by zkqiang** [comment]
应该是配置没生效，可以用 `hexo s --debug` 看一下输出的配置，没生效就再检查下哪里搞错了
