### ISSUE TITLE
尝试访问about页面时404

### ISSUE THREAD

**Issue by hhm1** [fluid-dev/hexo-theme-fluid#946]
#### 请确认
- [ √] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ √] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [ √] 已经排除是其他 Hexo 插件影响

#### Bug 描述

尝试访问about页面时404，尝试搜索Issues，虽然有相同的Issues，但都无法解决，尝试不动配置文件安装，也没解决
浏览器:Google Chrome
命令行:
```
INFO  Validating config
INFO  Start processing
INFO
------------------------------------------------
|                                              |
|     ________  __            _        __      |
|    |_   __  |[  |          (_)      |  ]     |
|      | |_ \_| | | __   _   __   .--.| |      |
|      |  _|    | |[  | | | [  |/ /'`\' |      |
|     _| |_     | | | \_/ |, | || \__/  |      |
|    |_____|   [___]'.__.'_/[___]'.__.;__]     |
|                                              |
|       Thank you for using Fluid theme !      |
|   Docs: https://hexo.fluid-dev.com/docs/en/  |
|                                              |
------------------------------------------------

WARN  [Fluid] It is recommended that you use override configuration: https://hexo.fluid-dev.com/docs/en/guide/#override-configuration
INFO  Hexo is running at http://localhost:4000/ . Press Ctrl+C to stop.
```

#### 复现步骤
该 Bug 复现步骤如下：
1. `hexo init test`
2. `cd test`
3. `git clone https://github.com/fluid-dev/hexo-theme-fluid.git themes/fluid`
4. `hexo server`
5. 打开[http://localhost:4000/about](http://localhost:4000/about)
6. Cannot GET /about/

#### 截图

![屏幕截图 2023-05-12 120529](https://github.com/fluid-dev/hexo-theme-fluid/assets/117976694/ff814db2-16e1-4d8b-bada-8e78190baa44)

**Comment by riveovo** [comment]
想问下你最后是怎么解决的呢？我也碰到这个问题了

**Comment by hhm1** [comment]
> 想问下你最后是怎么解决的呢？我也碰到这个问题了

没仔细看[文档](https://github.com/fluid-dev/hexo-theme-fluid#4-%E5%88%9B%E5%BB%BA%E5%85%B3%E4%BA%8E%E9%A1%B5)
