### ISSUE TITLE
请问如何加入禁f12和右键等功能？

### ISSUE THREAD

**Issue by dishao123** [fluid-dev/hexo-theme-fluid#948]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

你好，我想在博客中加入禁用f12控制台和右健检查，应该怎么做？我知道有注入器功能，但是不知道应该注入到哪里，所以来请教一下

**Comment by liJie-wk** [comment]
主题配置里的custom_js可以引入js文件
