### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Y-vagrant** [fluid-dev/hexo-theme-fluid#95]
## 一些建议:
- 发现md文件写标题的时候不管是二级标题还是三级标题都会自已在下面加上分割线这个就很难受,希望作者大大把它改成可选是否关闭的那种
[img](https://y-vagrant.github.io/tmp/-e179604ea853918.jpg) 
---
- 希望作者对图片加载进行优化,背景图有时一卡一卡的加载,有时又进界面一两秒后才开始加载
---
-  希望加入主页文章置顶功能
[img](https://y-vagrant.github.io/tmp/-4611cf9bbe550c6f.jpg) 
---
- 希望加入点击文章内图片自动放大查看功能
---

**辛苦作者大大了,望作者采纳**

**Comment by 0x2E** [comment]
你好，感谢建议~

关于第一个问题，这是沿用了 GitHub 的风格，每个尺寸的标题都会带有浅浅的下边框。

其他问题会在后续版本得到解决。

**Comment by Y-vagrant** [comment]
好的 谢谢作者大大采纳 最后两条建议参考下 我觉得有必要加入他们

**Comment by Godbn** [comment]
作者可以增加文章背景图随机获得吗？

**Comment by zkqiang** [comment]
@Y-vagrant master 分支已更新图片访达，有空可以体验以下

**Comment by zkqiang** [comment]
@Godbn 随机背景图后续会考虑，不过优先级会比较低

**Comment by zkqiang** [comment]
[v1.6.0](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.6.0) supports this features now
