### ISSUE TITLE
代码块中的代码被识别为脚注。

### ISSUE THREAD

**Issue by juxin-niu** [fluid-dev/hexo-theme-fluid#951]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

当我在Code block中插入类似``[^1]``，``[^2]``的内容时，这些内容会被错误地解析为脚注。

#### 复现步骤

例如，如果我在页面的**一个代码块中**加入下面的内容，那么上面的``[^1]``就会被错误地解析为脚注，但是下面的内容不受影响。

```plaintext
... [^1] ... [^2] ...

## Reference:

[^1]: ...
[^2]: ...
```

#### 截图

![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/88332544/6ff5d524-b80a-4a31-ad67-410355495f4f)

![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/88332544/e18a2c0f-dd80-4677-a6f0-bcaeb79438c4)

**Comment by Bluemangoo** [comment]
这是 Hexo markdown render 的事情，你要到那边发issue。
