### ISSUE TITLE
进入文章详情页面后，文章左上角位置当鼠标hover时会有img/fluid.png蓝色字样

### ISSUE THREAD

**Issue by rzh0504** [fluid-dev/hexo-theme-fluid#953]
#### 请确认
- [√] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [√] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [√] 已经排除是其他 Hexo 插件影响

#### 复现步骤
该 Bug 复现步骤如下：
1. 在 文章详情 页面左上角位置
2. 鼠标hovear
3. 会出现 img/fluid.png蓝色字样

#### 截图

![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/93367900/c17187ec-71ec-48c5-9ceb-a14d8842919f)

**Comment by zkqiang** [comment]
应该是你的样式没加载完整，再检查下自己的问题吧
