### ISSUE TITLE
hexo g时提示找不到highlightjs的style

### ISSUE THREAD

**Issue by AsanCai** [fluid-dev/hexo-theme-fluid#955]
在[这里](https://highlightjs.org/static/demo/)试了很多个其他的style，都没有成功

![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/24317027/5f469a39-00fd-43b2-aacd-cdffa2c62f95)

**Comment by zkqiang** [comment]
检查下 hljs 的版本

**Comment by AsanCai** [comment]
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/24317027/269a7a35-d456-4ccc-ae3c-76cb78e96c4a)
hljs应该是最新的版本，fluid默认接入的版本是？

**Comment by zkqiang** [comment]
默认取 `node_modules/highlight.js/styles/${cssName}.css`

**Comment by AmenLi** [comment]
遇到一样问题，根据楼上的说法，查找文件夹，发现没有这个模块。
需要先安装一下`npm install highlight.js`
然后如果用base16的样式，要这么填 `"base16/dracula"`
就没有再报错
