### ISSUE TITLE
Banner头图应在CSS加载之后加载

### ISSUE THREAD

**Issue by zhai0122** [fluid-dev/hexo-theme-fluid#959]
#### 如是功能需求，请确定符合以下情况
- [√] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [√] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

我当前使用的是随机图片api，所以每次刷新界面都会重新加载图片，但是发现暗黑页面样式总是在Banner头图加载完之后才加载。如果遇到大图片或者网络连接不稳定的话，样式也会加载很慢很难看。

#### 请描述您认为可行的解决方案

使用JavaScript动态将背景图片添加到banner元素中，由于不懂下面是chatgpt3.5给的答案
HTML代码：

```
<div id="banner" class="banner" parallax=true></div>
```

CSS代码：

```
#banner {
  background-repeat: no-repeat;
  background-position: center center;
  background-size: cover;
}
```

JavaScript代码：

```
window.onload = function() {
  var banner = document.getElementById('banner');
  banner.style.backgroundImage = "url('api')";
}
```

#### 考虑过的替代方案

每次手动修改，但是成本太高，我觉得其他人可能或多或少遇到这样的问题。

**Comment by zkqiang** [comment]
那应该是你请求随机图片api，导致阻塞了加载进程，修改成异步请求即可
