### ISSUE TITLE
Fluid 交流微信群

### ISSUE THREAD

**Issue by zkqiang** [fluid-dev/hexo-theme-fluid#96]
如果在 Fluid 使用中遇到障碍，在查询[「使用指南」](https://fluid-dev.github.io/hexo-fluid-docs/)无果后，可以在群内提出，其他 Bug 、建议、功能需求等最好仍使用 issue 提出。

<p align="center">
  <img alt="Fluid Logo" src="http://static.zkqiang.cn/images/20191206211444.jpeg-slim" width="300">
</p>

**进群方式：扫上方二维码，回复「fluid」拉进群**

**Comment by Awacky** [comment]
我在使用主题过程中出现了这些错误  hexo generate之后 [

![E8DNGI%YG911_{OFBP 843X](https://user-images.githubusercontent.com/24476942/67445557-ebbe4a80-f63f-11e9-8403-27f10e0bef67.png)

**Comment by zkqiang** [comment]
@Awacky 这是你 config 配置报错，可能是你没有按 Yaml 格式填写

**Comment by Awacky** [comment]
你好  就是我的这个awacky.github.io无法访问。和我绑定的www.awacky.com结果都一样，本地4000的结果都出来了。
这是在地址栏中  输入  www.awacky.com 和 awacky.github.io一样的效果。
localhost:4000的效果是这样的。


| |
陈恒
|
|
awacky@163.com
|
签名由网易邮箱大师定制
在2019年10月24日 09:39，张凯强<notifications@github.com> 写道：

@Awacky 这是你 config 配置报错，可能是你没有按 Yaml 格式填写

**Comment by zkqiang** [comment]
@Awacky 你给我网站，我是看不出什么问题的... 可以加微信群慢慢说

**Comment by Awacky** [comment]
这个页面上找不到微信群？

**Comment by Awacky** [comment]
二维码已经过期了。。。 -

**Comment by zkqiang** [comment]
@Awacky 更新了

**Comment by waaaang** [comment]
你好，我在4000端口访问是正常的，但是hexo d 之后里面配置的图片全部不能显示，请问是我网络的问题吗？还是我哪边没有配置好？

**Comment by zkqiang** [comment]
@waaaang 这个原因很多...  进群详聊吧，我换了新的二维码

**Comment by huangxjgit** [comment]
二维码加载不出来

**Comment by Himitsu98** [comment]
您好，二维码已过期，请更新

**Comment by Himitsu98** [comment]
您好，二维码已过期，请更新

**Comment by zkqiang** [comment]
@Himitsu98 已更新

**Comment by 1219960964** [comment]
二维码已经过期了

**Comment by zkqiang** [comment]
@1219960964 已更新

**Comment by Charlo-O** [comment]
二维码过期啦

**Comment by zkqiang** [comment]
@Charlo-O 已更新

**Comment by Zeyyyyyyyy** [comment]
hexo s 可以正常访问  但是hexo d  部署到Github  访问不了   www.zeyyyy.com

**Comment by zkqiang** [comment]
@Zeyyyyyyyy 没设置CNAME，建议再看看 github 的文档

**Comment by Reasonnnn** [comment]
about.md内容是空白的，没法编辑？

**Comment by zkqiang** [comment]
@Reasonnnn 
空白的就是给你编辑的
具体见 [使用指南](https://fluid-dev.github.io/hexo-fluid-docs/guide/#%E7%BC%96%E8%BE%91%E5%85%B3%E4%BA%8E%E5%86%85%E5%AE%B9)

**Comment by Tony-is-here** [comment]
感觉页面宽度优点窄, 不太看得懂 styl 文件, 不知道从哪里客制化. 
如果方便的话, 可以把页面宽度加到 config 里面么, 或者在 post.styl 里面加上注释.

**Comment by zkqiang** [comment]
@Tony-is-here 可使用最新版本 [自定义CSS](https://hexo.fluid-dev.com/docs/guide/#%E8%87%AA%E5%AE%9A%E4%B9%89-js-css-html) 功能修改任何样式

**Comment by ShootingWang** [comment]
你好，想请教一下关于“**首页隐藏文章**”功能的问题。目前的fluid版本的**“hide”功能**，会使得文章在首页、标签页、分类页都不出现。想要修改成“文章在首页不出现，但是在标签页、分类页出现”，但是到处搜索也找不到相应的修改方法，找到的是别的hexo主题的修改方法，在fluid中并不适用。
请问现在有这样的功能（文章在首页不出现，但是在标签页、分类页出现）吗？

**Comment by zkqiang** [comment]
> 你好，想请教一下关于“**首页隐藏文章**”功能的问题。目前的fluid版本的**“hide”功能**，会使得文章在首页、标签页、分类页都不出现。想要修改成“文章在首页不出现，但是在标签页、分类页出现”，但是到处搜索也找不到相应的修改方法，找到的是别的hexo主题的修改方法，在fluid中并不适用。
> 请问现在有这样的功能（文章在首页不出现，但是在标签页、分类页出现）吗？

@ShootingWang 没有，这个需求比较奇怪，正常隐藏肯定是无法找到踪迹才是隐藏，如果需求可以自己实现，不过在 Hexo 的逻辑里实现不太方便

**Comment by BOSS-xu** [comment]
二维码在哪呢？

**Comment by zkqiang** [comment]
> 二维码在哪呢？

@BOSS-xu 一楼有，你是不是被墙了图片显示不出来

**Comment by ivikon** [comment]
您好打扰了，我是今天第一次下载安装使用这个主题，我想请问一下，最新版本 1.8.0 是不是有个 bug，页头的导航栏在页面向下滚动的时候是不会自动从透明变成非透明有颜色的状态，只有在页面滚动结束之后才会变成非透明有颜色的状态，而这个问题我在上一个版本 1.7.5 中并没有遇到。请问是您修改了导航栏的这个设计还是说这是我某些地方修改使用不当导致的？

**Comment by zkqiang** [comment]
@ivikon 
可以看：https://hexo.fluid-dev.com/  
这个博客是与仓库代码同步的，如果你的前端效果与这个不一样，建议检查下自己代码的完整性，另外dev分支对一些滚动事件做了优化，也可以试一下

**Comment by ivikon** [comment]
> @ivikon
> 可以看：https://hexo.fluid-dev.com/
> 这个博客是与仓库代码同步的，如果你的前端效果与这个不一样，建议检查下自己代码的完整性，另外dev分支对一些滚动事件做了优化，也可以试一下
> 
> 后续有问题进群说吧

谢谢，解决了，我切换到了 dev 分支。
另外，我扫描了上面的二维码，但并没有给我通过好友申请。

**Comment by dihui-dpx** [comment]
更换个人空间地址后，主题文件里的所有文件都上传不到码云了，有没有知道怎么解决的
