### ISSUE TITLE
Error: Cannot find module 'css' 

### ISSUE THREAD

**Issue by jfuyun** [fluid-dev/hexo-theme-fluid#961]
<img width="1166" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/135296923/ff3274eb-244a-4e0b-b6f4-7755c696402a">

**Comment by SharwOrange** [comment]
我也有这个问题
[#592](https://github.com/fluid-dev/hexo-theme-fluid/issues/952#issuecomment-1562767661)
我参考这个问题修复了
只需要
`npm install css --save`

**Comment by sshelll** [comment]
> 我也有这个问题 [#592](https://github.com/fluid-dev/hexo-theme-fluid/issues/952#issuecomment-1562767661) 我参考这个问题修复了 只需要 `npm install css --save`

thanks！

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/issues/952

**Comment by zkqiang** [comment]
Fixed in [v1.9.5](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.9.5)
