### ISSUE TITLE
页面底部展示PV、UV统计数不显示

### ISSUE THREAD

**Issue by baijiangLai** [fluid-dev/hexo-theme-fluid#962]
# 展示网站的 PV、UV 统计数
  # Display website PV and UV statistics
  statistics:
    enable: true
    source: "leancloud"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"
    
    
    这是我的_config.yml的内容

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/dd447d23dbf5db13c1d9ab68e54c2d167a06bc67/_config.yml#L282-L295

要同时填这里
