### ISSUE TITLE
作者你好，貌似你的1.9.5版本在设置Auto时仍不跟随系统浅色模式，你的Demo也是如此

### ISSUE THREAD

**Issue by Songyon** [fluid-dev/hexo-theme-fluid#967]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述
作者你好，貌似你的1.9.5版本在设置Auto时仍不跟随系统浅色模式，你的Demo也是如此

#### 复现步骤
该 Bug 复现步骤如下：
打开https://hexo.fluid-dev.com

#### 截图

https://urlscan.io/liveshot/?width=500&height=1080&url=https://hexo.fluid-dev.com/

**Comment by zkqiang** [comment]
dev分支已修复

**Comment by Songyon** [comment]
> dev分支已修复

感谢！
