### ISSUE TITLE
使用valine+Server酱实现评论微信通知

### ISSUE THREAD

**Issue by baijiangLai** [fluid-dev/hexo-theme-fluid#968]
valine:
  appId: xxx
  appKey: xxx
  path: window.location.pathname
  placeholder: 留个言呗
  avatar: 'retro'
  meta: ['nick', 'mail', 'link']
  requiredFields: []
  pageSize: 10
  lang: 'zh-CN'
  highlight: false
  recordIP: true
  serverURLs: 'https://sctapi.ftqq.com/xxx.send'
  emojiCDN:
  emojiMaps:
  enableQQ: false
  
  在appId和appKey都使用的leanCloud配置的里面的，serverURLs使用的是Server酱提供的，这样配置了之后测试了一下，发送评论消息没有实现微信通知

**Comment by yangyhua** [comment]
这需要额外的js支持，不是hexo自带功能，网上有教程可以自己看下
