### ISSUE TITLE
一点细节的建议

### ISSUE THREAD

**Issue by huaxianyan** [fluid-dev/hexo-theme-fluid#97]
第一是关于 lazyload 的载入占位图，那个载入动画和整体风格有点出入太大，可否考虑更换一下，另外有没有指定的可能性？

第二我看到了配置文件里面的统计，但是没有 Google 的，这个可否考虑添加？或者指定一个文件让用户在 head 里插入一些自定义的代码？

仅供参考

**Comment by zkqiang** [comment]
[develop分支](https://github.com/fluid-dev/hexo-theme-fluid/blob/f484dc4030b0a1735e29661ccec34b66ae3ad54e/layout/_partial/analytics.ejs) 添加了谷歌统计

**Comment by zkqiang** [comment]
[v1.6.0](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.6.0) 已支持
