### ISSUE TITLE
关于页的标题无法自定义

### ISSUE THREAD

**Issue by zonglin-tian** [fluid-dev/hexo-theme-fluid#971]
我下载的最新 Fluid 主题, 并按官方教程建立了 about 页, 同时修改了对应 about 文件的标题, 但是部署到网站时, 始终不对 (从本地看也不对)
# config.fluid.yml
![config](https://github.com/fluid-dev/hexo-theme-fluid/assets/122209807/d8299ef6-4312-4a96-9e31-1d4240c97fa1)
# about/index.md
![source_code](https://github.com/fluid-dev/hexo-theme-fluid/assets/122209807/d233fa2c-52a1-4664-9ab7-fe3392cee564)
# 部署结果
![render](https://github.com/fluid-dev/hexo-theme-fluid/assets/122209807/d4d90819-ba04-4404-be2c-bf5f07690df5)

请问是什么原因?

**Comment by Cidream** [comment]
要到Cidream-blog\themes\fluid\languages中修改zh-CN.yml中的about
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/132119004/34fca36a-3f53-4f94-916f-a400b25a54fa)
比如我的就改成了作者

**Comment by zonglin-tian** [comment]
有效, 非常感谢!

**Comment by Cidream** [comment]
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/132119004/0438c11d-a996-4fda-bc22-aca9b2c09361)
这样也行 ，

**Comment by zonglin-tian** [comment]
谢谢, 对的, 这个应该是最快的

在你这个基础上, 我又看了下官网那个手册, 原理同一开始你给我的解决方案, 可以将 ".\themes\fluid\languages\zh-CN.yml" 下的文件复制到 ".\source\_data\languages\zh-CN.yml", 然后进行修改

这样就可以尽量不去改 themes 下的文件
