### ISSUE TITLE
关于waline无法使用

### ISSUE THREAD

**Issue by Riveer01** [fluid-dev/hexo-theme-fluid#972]
我在waline的服务器地址是可以正常使用的, 但是在博客中无法评论, 虽然waline被渲染出来了, 但评论会报错
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/75653615/ee3a4a06-df57-47ed-a7ca-4bf96df95ee3)

![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/75653615/4f0293d0-562e-43a3-8727-78ef7fbff13c)

**Comment by zkqiang** [comment]
<img width="686" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/32983588/794973a4-1961-485e-aa6b-cb3c5032e6f9">

我看你的评论是正常的，请再检查下你本地的情况

**Comment by Riveer01** [comment]
@zkqiang 感谢你的回复，我后来发现是serverURL值配置错误，waline官方文档说这个值是点击`visit`后弹出的网址，这是错误的，正确的应该是是`visit`旁边的`Domains`的值。
