### ISSUE TITLE
多URL随机背景图请教

### ISSUE THREAD

**Issue by QLozin** [fluid-dev/hexo-theme-fluid#973]
#### 请确认
- [X] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [X] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法
- [X] 在ISSUE中没有找到解决办法
#### 问题描述
翻阅了文档和ISSUE，发现好像没什么人提随机图片。
就是说，背景图、文章封面、文章背景图是否支持多图片地址(url)或API？
在一些主题中允许使用类似
```
banner_img:
    - https://pic1.example.com
    - https://pic2.eaxmple.com
```
的方式自动选择(分配)一个链接作为图片显示。
我稍微尝试了一下是失败的。暂时没有找到相关内容。

如果有这个功能的话就可以直接从图池里自动补全文章封面和背景图，不需要每次写文章的时候都手动设置了喵。
首页背景图也可以从图池抽取的话也不错。

感谢你的指导喵。

**Comment by zkqiang** [comment]
因为没有此功能，可以自己实现
