### ISSUE TITLE
优化功能：目录

### ISSUE THREAD

**Issue by Cidream** [fluid-dev/hexo-theme-fluid#979]
# ♥在自定义页面中增加目录
🎇主题本身支持目录功能，但新建的page不支持目录，我增加了一个模板ejs，在自定义的文章中调用它，但我不会写ejs，所以我不知如何写ejs使自定义页面中增加目录。请求解答。

**Comment by zkqiang** [comment]
如果你需要和文章相同的功能作为自定义页面，应该在 post 里创建，然后把 post 隐藏再使用

**Comment by Cidream** [comment]
但怎么隐藏个别文章的那个标题下方的元信息

**Comment by zkqiang** [comment]
> 但怎么隐藏个别文章的那个标题下方的元信息

那只能用一些奇怪的办法，比如在自定义页面引入目录的 js，或者在 post 里用 css 隐藏元信息
