### ISSUE TITLE
在自定义标签页 代码块显示不正常

### ISSUE THREAD

**Issue by Cidream** [fluid-dev/hexo-theme-fluid#980]
# 问题
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/132119004/1faf790b-f8b6-4ef6-8425-f7e64f24bf03)
在自定义标签页 代码块显示不正常
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/132119004/dd11ea6d-a931-4454-8cd9-ae93bddde0f6)
# 我有替代解决办法 ，但最好修正。
# 解决方法如下
## 1.增加type为code(可自己命名
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/132119004/4a4205c9-8635-4207-8a30-fb872266da0b)
## 2.增加文件code.ejs（目录如下）
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/132119004/6af96aef-e204-4e7e-b6b8-6477f117a1db)
## 2.写入文件code.ejs代码
```
<%
page.layout = "code"
page.title = theme.code.title || __('code.title')
page.title = theme.code.title || __('code.title')
page.subtitle = theme.code.subtitle || __('code.subtitle')
page.banner_img = page.banner_img || theme.code.banner_img
page.banner_img_height = page.banner_img_height || theme.about.banner_img_height
page.banner_mask_alpha = page.banner_mask_alpha || theme.about.banner_mask_alpha
%>

<article class="code-content page-content mt-5">
  <div class="markdown-body">
    <%- page.content %>
  </div>

  <% if(page.comments) { %>
  <% } %>
</article>

<%- partial('_partials/markdown-plugins') %>
```
# 保存即可！

**Comment by Cidream** [comment]
# 我有替代解决办法 ，但最好修正。

**Comment by zkqiang** [comment]
<img width="591" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/32983588/480c2717-a64c-4754-8d6c-eb24419ea766">
