### ISSUE TITLE
有沒有辦法在Home/Archives中隱藏post，但在Categories/Tags中顯示post呢？

### ISSUE THREAD

**Issue by AaronLin1229** [fluid-dev/hexo-theme-fluid#983]
#### 问题描述
我嘗試使用Front-Matter裡面將hide設置為true，但這樣在Home/Archives/Categories/Tags皆會被隱藏，請問有方法能夠Home/Archives中隱藏post，但在Categories/Tags中顯示post嗎？

**Comment by zkqiang** [comment]
最新版本已经增加了：
> 文章归档功能，在 FrontMatter 里添加 archive: true 可开启，该文章将不在首页列出，但依然能在归档、分类等页面看到
