### ISSUE TITLE
Questions about fluid's official documentation

### ISSUE THREAD

**Issue by waahah** [fluid-dev/hexo-theme-fluid#984]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

可以在*config.fluid.yml*配置文件的`custom_head`项中自定义添加**多行** `<head>` 标签中的 元数据 内容吗，像这样
```yml
custom_head: 
  - '<meta name="sogou_site_verification" content="xxxx"/>'
  - '<meta name="shenma-site-verification" content="xxxx">'
  - '<script type="text/javascript">[];window.CRISP_WEBSITE_ID="xxxxx";' 
 ```
#### 关于这块官方文档并没有讲清楚欸

**Comment by zkqiang** [comment]
直接写在一个字符串里就行了
