### ISSUE TITLE
控制台中输出的主题信息包含已失效的 `git.io` 短链接

### ISSUE THREAD

**Issue by yzl3014** [fluid-dev/hexo-theme-fluid#987]
当访客访问网站时，主题会向控制台中将会输出以下文本：
```text
------------------------------------------------
|                                              |
|     ________  __            _        __      |
|    |_   __  |[  |          (_)      |  ]     |
|      | |_ \_| | | __   _   __   .--.| |      |
|      |  _|    | |[  | | | [  |/ /'`\' |      |
|     _| |_     | | | \_/ |, | || \__/  |      |
|    |_____|   [___]'.__.'_/[___]'.__.;__]     |
|                                              |
|           Powered by Hexo x Fluid            |
|         GitHub: https://git.io/JqpVD         |
|                                              |
------------------------------------------------
```
但是，其中给出的Github仓库链接包含了`git.io`这个早已失效的短连接。
这是Github发布的通知： https://github.blog/changelog/2022-04-25-git-io-deprecation/ ，下面是部分内容的翻译：

>2022年1月，我们宣布[git.io 正在变成只读](https://github.blog/changelog/2022-01-11-git-io-no-longer-accepts-new-urls/)。正如1月份通知的那样，我们分享了不再使用该服务的计划。出于当前 git.io 基础设施重定向链接的安全性考虑，我们决定加快时间进度。我们将**在2022年4月29日从 git.io 移除所有现有的链接重定向**。
开发人员应该立即使用比 git.io 服务功能更强大的 URL 缩短服务。

虽然几乎没有人会去主动看一个普通网站的控制台，但是还是希望更改一下这个链接，毕竟它已经完全无法访问了。

**Comment by zkqiang** [comment]
这个公告我理解的是，之前的还能重定向，只是不能新增了


>In order to preserve the integrity of these historical documents, we have decided to archive the current git.io links in a new read-only service that will allow us to serve redirects for those links longer term.
>...
>GitHub support will not be able to update or edit redirection records served by the git.io archive service.

并且我访问依然是可以重定向的，如果是永久有效我觉得没有更换的必要

**Comment by yzl3014** [comment]
确实并非通知所写的那样“移除所有现有的链接重定向”，访问会正常跳转。不过在境内，域名已经无法访问了。
![](https://github.com/fluid-dev/hexo-theme-fluid/assets/79385954/f37d655d-6055-4b89-96df-621ce824b4b7)

**Comment by zkqiang** [comment]
[v1.9.7](https://github.com/fluid-dev/hexo-theme-fluid/releases/tag/v1.9.7) 已修复
