### ISSUE TITLE
永远加载不完的进度条

### ISSUE THREAD

**Issue by Enderfga** [fluid-dev/hexo-theme-fluid#994]
#### 请确认
- [√] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [√] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [√] 已经排除是其他 Hexo 插件影响

#### 复现步骤
该 Bug 复现步骤如下：
打开enderfga.cn
进度条开始加载，但一直不能结束

#### 截图

![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/74981769/63ed0182-80e6-4230-b880-b1fae7a594a9)

**Comment by Enderfga** [comment]
过了几个月我还是没有解决 不太清楚原因 我这边打开任意页面还是有这个问题 
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/74981769/73007b1c-d189-4614-b1e5-fc9f0d0c298d)

**Comment by f88083** [comment]
> 过了几个月我还是没有解决 不太清楚原因 我这边打开任意页面还是有这个问题 ![image](https://user-images.githubusercontent.com/74981769/285244703-73007b1c-d189-4614-b1e5-fc9f0d0c298d.png)

我自己的網站也沒有這個問題，你更新過hexo和fluid嗎?或是有換瀏覽器開過嗎?

**Comment by Enderfga** [comment]
> > 过了几个月我还是没有解决 不太清楚原因 我这边打开任意页面还是有这个问题 ![image](https://user-images.githubusercontent.com/74981769/285244703-73007b1c-d189-4614-b1e5-fc9f0d0c298d.png)
> 
> 我自己的網站也沒有這個問題，你更新過hexo和fluid嗎?或是有換瀏覽器開過嗎?

我尝试了chrome和edge都是这样  我看这个项目4个月没有更新了 那我用的hexo fluid应该也是最新的

**Comment by f88083** [comment]
> > > 过了几个月我还是没有解决 不太清楚原因 我这边打开任意页面还是有这个问题 ![image](https://user-images.githubusercontent.com/74981769/285244703-73007b1c-d189-4614-b1e5-fc9f0d0c298d.png)
> > 
> > 
> > 我自己的網站也沒有這個問題，你更新過hexo和fluid嗎?或是有換瀏覽器開過嗎?
> 
> 我尝试了chrome和edge都是这样 我看这个项目4个月没有更新了 那我用的hexo fluid应该也是最新的

那真是怪了，不過hexo三周前有更新，但應該不影響，我自己用的是最新的fluid和hexo最新版7.0.0

**Comment by Enderfga** [comment]
> > > > 过了几个月我还是没有解决 不太清楚原因 我这边打开任意页面还是有这个问题 ![image](https://user-images.githubusercontent.com/74981769/285244703-73007b1c-d189-4614-b1e5-fc9f0d0c298d.png)
> > > 
> > > 
> > > 我自己的網站也沒有這個問題，你更新過hexo和fluid嗎?或是有換瀏覽器開過嗎?
> > 
> > 
> > 我尝试了chrome和edge都是这样 我看这个项目4个月没有更新了 那我用的hexo fluid应该也是最新的
> 
> 那真是怪了，不過hexo三周前有更新，但應該不影響，我自己用的是最新的fluid和hexo最新版7.0.0

总之还是谢谢您

**Comment by f88083** [comment]
這些有在你的`_config.fluid.yml`嗎?
或是可以看看[這裡](https://github.com/rstacruz/nprogress)這是fluid用來顯示進度條的插件

```yml
  # 加载进度条
  # Progress bar when loading
  progressbar:
    enable: true
    height_px: 3
    color: "#29d"
    # See: https://github.com/rstacruz/nprogress
    options: { showSpinner: false, trickleSpeed: 100 }
```

祝好運

**Comment by Enderfga** [comment]
> 這些有在你的`_config.fluid.yml`嗎? 或是可以看看[這裡](https://github.com/rstacruz/nprogress)這是fluid用來顯示進度條的插件
> 
> ```yaml
>   # 加载进度条
>   # Progress bar when loading
>   progressbar:
>     enable: true
>     height_px: 3
>     color: "#29d"
>     # See: https://github.com/rstacruz/nprogress
>     options: { showSpinner: false, trickleSpeed: 100 }
> ```
> 
> 祝好運

改false就没有这个问题了 太谢谢了 强迫症舒服多了哈哈哈

**Comment by llleixx** [comment]
我也出现了这样的问题。

你的网站是放在 cloudflare 上的吗？
