### ISSUE TITLE
请求添加自定义鼠标指针样式功能

### ISSUE THREAD

**Issue by Yikang666** [fluid-dev/hexo-theme-fluid#996]
# 麻烦添加一下，辛苦了☕☕☕

#### 请描述该需求尝试解决的问题
添加自定义鼠标指针时，custom.css会与main.css的代码冲突，更改主题文件后会不好维护。

#### 请描述您认为可行的解决方案
添加自定义鼠标指针样式功能能够解决问题（在主题配置中单独留出填写指针样式文件的位置）。

#### 考虑过的替代方案
如果更改主题源文件，也能解决该问题。

**Comment by zkqiang** [comment]
暂时不考虑加入更多自定义样式的功能
