### ISSUE TITLE
网页标签图标不显示

### ISSUE THREAD

**Issue by DY-d** [fluid-dev/hexo-theme-fluid#998]
网页标签设置完之后，本地测试只在首页显示，当部署到github pages上时，绑定完自己的域名之后，就直接所有页面都不显示了。这是为什么？

**Comment by suiyideali** [comment]
我本地部署正常，部署到github pages上时，所有页面空白

**Comment by DY-d** [comment]
> 我本地部署正常，部署到github pages上时，所有页面空白

我的页面是正常的，但是所有页面的页签图标都没了
