### ISSUE TITLE
博客about页面中的引用无法正常显示

### ISSUE THREAD

**Issue by AI-Kyo-er** [fluid-dev/hexo-theme-fluid#999]
网址为：https://sieni-blog.com/about/

<img width="599" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/78187360/a3bef960-ab63-44d0-bf90-5b5f38830a96">
<img width="297" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/78187360/340a5928-aaf8-4472-a44b-d70a5797ec3a">

**Comment by AI-Kyo-er** [comment]
代码块等等好像也无法正常显示在about中

**Comment by LAGQWQ** [comment]
Fluid的Page页用不渲染Markdown，你可以用下面的标签使其渲染

```
<div class="markdown-body">
正文
</div>
```

**Comment by LAGQWQ** [comment]
还有 这不是bug 把你那傻逼标签去了

**Comment by AI-Kyo-er** [comment]
感谢回复，大有裨益，我已关闭之，该问题分类确有不妥，你来直接delete掉吧

------- Original Message -------
在 2023年10月4日 星期三 下午 11:24，SNES ***@***.***> 寫道：
